// build.js - build the self-hosted Simse compiler with cl.exe.
//
//   bun build.js [options] [<output.exe>]
//
// Simse is written in Simse: the compiler is the `.kt` sources under `cppsrc`, and
// the only hand-written C++ is the runtime's headers (`cppsrc/rtl/*.hpp`) and the
// published bootstrap. Every operation a program reaches - the runtime primitives, the
// platform's file I/O, the clocks - is generated into the program's own translation unit
// from `cppsrc/rtl/_res.md` (`impl_specs/generators.md`). So this script is a two-step build:
//
//   1. transpile `cppsrc` into one C++ file, with a Simse compiler (`--root` /
//      `--out`). The compiler it uses is `./simse.exe` when it exists, and otherwise
//      the published `cppsrc/simse_bootstrap.cpp` compiled on the spot - which is
//      what makes a fresh checkout buildable with a C++ compiler alone.
//   2. compile that one file into `simse.exe`.
//
// `cppsrc/simse_bootstrap.cpp` is the *published* copy of the amalgamation: it is
// checked in, it is regenerated by this script, and it must stay a fixed point (the
// compiler it builds transpiles `cppsrc` back into the same bytes - `bun
// tools/bootstrap.js` checks exactly that).
//
// Options:
//   --cpp <file>      compile this C++ file instead of regenerating (implies --no-gen)
//   --exe <file>      executable name/path (default: simse.exe)
//   --out <file>      generated C++ name/path (default: simse_out.cpp;
//                     `--out cppsrc/simse_bootstrap.cpp` refreshes the published
//                     bootstrap)
//   --root <dir>      source root to transpile, relative to the repo (default: cppsrc)
//   --compiler <exe>  the Simse compiler to transpile with (default: ./simse.exe,
//                     else the bootstrap compiled for this build)
//   --no-gen          skip transpiling; compile the existing/--cpp file
//   --profile         transpile with --profile: the emitted program carries the
//                     instrumented profiler and prints its table at the end of main
//                     (impl_specs/profiling.md)
//   --release         release build: /O2 /Ob3 /DNDEBUG, with whole-program
//                     optimization (/GL, whose link-time codegen is LTCG) unless
//                     --no-lto says otherwise
//   --debug           debug build (the default)
//   --no-lto          skip the release build's /GL: a quicker build, a slightly slower
//                     compiler
//   --pdb             keep debug info in a release build (/Zi /DEBUG; the .pdb lands
//                     in the build folder), for a profiler or a debugger
//   --arch <arch>     vcvarsall target architecture (default: the host's)
//   --define <m[=v]>  add a preprocessor define to the compile (repeatable), e.g.
//                     --define SIMSE_NO_PACK4. It reaches the one translation unit a
//                     program is, headers and generated code together, so the RTL's
//                     layout choices can never disagree with the compiler's.
//   -h, --help        show this help
//
// Objects and intermediate files go to `build/<debug|release>/`. The generated file
// includes "cppsrc/rtl/simse.hpp", so the repository root is on the include path.

import { $ } from "bun";
import { existsSync, mkdirSync, readdirSync, statSync } from "node:fs";
import * as path from "node:path";

import {
  developerEnv,
  fail as failTool,
  hostArch,
  normalizeArch,
  REPO,
  runCl,
  whichCl,
} from "./tools/msvc.mjs";

const fail = (message) => failTool("build", message);
const BOOTSTRAP = path.join("cppsrc", "simse_bootstrap.cpp");

function usage() {
  console.log(`usage: bun build.js [options] [<output.exe>]

  --cpp <file>      compile this C++ file instead of regenerating (implies --no-gen)
  --exe <file>      executable name/path (default: simse.exe)
  --out <file>      generated C++ name/path (default: simse_out.cpp;
                    --out cppsrc/simse_bootstrap.cpp refreshes the published bootstrap)
  --root <dir>      source root to transpile, relative to the repo (default: cppsrc)
  --compiler <exe>  the Simse compiler to transpile with (default: ./simse.exe,
                    else the bootstrap compiled for this build)
  --no-gen          skip transpiling; compile the existing/--cpp file
  --profile         transpile with --profile (impl_specs/profiling.md)
  --release         release build: /O2 /Ob3 /DNDEBUG, with whole-program
                    optimization (/GL, whose link-time codegen is LTCG) unless
                    --no-lto says otherwise
  --debug           debug build (the default)
  --no-lto          skip the release build's /GL: a quicker build, a slightly slower
                    compiler
  --pdb             keep debug info in a release build (/Zi /DEBUG; the .pdb lands
                    in the build folder), for a profiler or a debugger
  --arch <arch>     vcvarsall target architecture (default: the host's)
  --define <m[=v]>  add a preprocessor define to the compile (repeatable)
  -h, --help        show this help`);
}

function parseArgs(argv) {
  const opts = {
    root: "cppsrc",
    out: "simse_out.cpp",
    exe: "simse.exe",
    gen: true,
    profile: false,
    release: false,
    debug: false,
    lto: true,
    pdb: false,
    arch: null,
    compiler: null,
    defines: [],
  };
  const value = (i) => {
    if (i + 1 >= argv.length) fail(`missing value for ${argv[i]}`);
    return argv[i + 1];
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    switch (arg) {
      case "--cpp": opts.cpp = value(i); opts.gen = false; i++; break;
      case "--exe": opts.exe = value(i); i++; break;
      case "--out": opts.out = value(i); i++; break;
      case "--root": opts.root = value(i); i++; break;
      case "--compiler": opts.compiler = value(i); i++; break;
      case "--no-gen": opts.gen = false; break;
      case "--profile": opts.profile = true; break;
      case "--release": opts.release = true; break;
      case "--debug": opts.release = false; opts.debug = true; break;
      case "--lto": opts.lto = true; break;
      case "--no-lto": opts.lto = false; break;
      case "--pdb": opts.pdb = true; break;
      case "--arch": opts.arch = value(i); i++; break;
      case "--define": opts.defines.push(value(i)); i++; break;
      case "-h": case "--help": opts.help = true; break;
      default:
        if (arg.startsWith("-")) fail(`unknown option '${arg}' (try --help)`);
        opts.exe = arg;
    }
  }
  return opts;
}

// cl.exe's arguments for one configuration. `--release` and `--pdb` are separate on
// purpose: `--release --pdb` is the pair a profiler wants (optimized code, full symbols),
// which is what the deleted MSBuild profiling project used to provide.
//
// A release build links with whole-program optimization by default: the compiler is one
// 46k-line translation unit, so the cross-function inlining LTCG buys is exactly the
// shape it can use. `/GL` alone is the whole request - `cl` ignores a bare `/LTCG`
// (D9002) because the link-time codegen is implied by linking `/GL` objects, which is
// also why the link prints "Generating code". `--no-lto` is there for a quick build:
// LTCG dominates a release build's time, and what it buys is run time.
function compileFlags(opts) {
  const flags = opts.release ? ["/MD", "/O2", "/Ob3", "/DNDEBUG"] : ["/MDd", "/Od"];
  if (opts.pdb || !opts.release) flags.push("/Zi");
  if (opts.pdb) flags.push("/DEBUG");
  if (opts.release && opts.lto) flags.push("/GL");
  return flags;
}

// Whether `compiler` is older than the prelude sources. The prelude is a *directory
// read at run time* (`cppsrc/rtl/*.kt`), so an older compiler sees a new declaration it
// may not know how to emit - a trap worth a warning, never a failure: the build below
// is what fixes it.
function preludeNewerThan(compiler) {
  if (!existsSync(compiler)) return false;
  const stamp = statSync(compiler).mtimeMs;
  const prelude = path.join(REPO, "cppsrc", "rtl");
  for (const entry of readdirSync(prelude)) {
    if (entry.endsWith(".kt") && statSync(path.join(prelude, entry)).mtimeMs > stamp) return true;
  }
  return false;
}

async function main() {
  const opts = parseArgs(process.argv.slice(2));
  if (opts.help) {
    usage();
    return;
  }
  const cwd = process.cwd();
  const mode = opts.release ? "release" : "debug";
  const work = path.join(REPO, "build", mode);
  const objDir = path.join(work, "obj");
  mkdirSync(objDir, { recursive: true });

  const outCpp = path.resolve(cwd, opts.out);
  const exe = path.resolve(cwd, opts.exe);
  const flags = compileFlags(opts);
  const defines = opts.defines.map((define) => `/D${define}`);

  const arch = normalizeArch(opts.arch || hostArch());
  const env = developerEnv(arch, "build");
  const cl = whichCl(env);
  if (!cl) fail(`cl.exe not found on the Visual Studio PATH (arch ${arch})`);
  console.log(`build: ${mode} build for ${arch}`);
  console.log(`build: cl.exe ${cl}`);

  // --- step 1: transpile the compiler source tree ----------------------------
  if (opts.gen) {
    let compiler = opts.compiler ? path.resolve(cwd, opts.compiler) : path.join(REPO, "simse.exe");
    if (!existsSync(compiler)) {
      // No working compiler yet: compile the published bootstrap. It is a complete
      // compiler, so this is the whole "from a C++ compiler alone" path.
      const bootstrap = path.join(REPO, BOOTSTRAP);
      if (!existsSync(bootstrap)) fail(`missing ${BOOTSTRAP} (and no ./simse.exe)`);
      compiler = path.join(work, "simse_boot.exe");
      mkdirSync(path.join(work, "bootobj"), { recursive: true });
      console.log(`build: no ./simse.exe; compiling the published bootstrap`);
      console.log(`build:            ${BOOTSTRAP} -> ${path.relative(REPO, compiler)}`);
      const boot = runCl(env, [
        cl, "/nologo", "/std:c++20", "/EHsc", "/W3", ...flags,
        ...defines, `/I${REPO}`,
        `/Fo${path.join(work, "bootobj")}${path.sep}`, `/Fe${compiler}`,
        `/Fd${path.join(work, "bootobj")}${path.sep}boot.pdb`,
        BOOTSTRAP,
      ]);
      if (boot !== 0) fail("compiling the bootstrap failed");
    }
    // Run from the repository root: the compiler's default prelude is the relative
    // path `cppsrc/rtl`, and the source-map comments in the output use the paths it
    // was given.
    if (!opts.compiler && preludeNewerThan(compiler)) {
      console.warn(`build: warning: ${path.basename(compiler)} is older than cppsrc/rtl, ` +
          "so it may not know every declaration the prelude has; this build replaces it");
    }
    console.log(`build: transpiling ${opts.root} -> ${outCpp}`);
    console.log(`build:            with ${path.relative(REPO, compiler)}`);
    const transpileArgs = [compiler, "--root", opts.root, "-o", outCpp];
    if (opts.profile) transpileArgs.push("--profile");
    const result = await $`${transpileArgs}`.cwd(REPO).nothrow();
    if (result.exitCode !== 0) fail(`transpiling failed (exit ${result.exitCode})`);
  }

  const cpp = opts.cpp ? path.resolve(cwd, opts.cpp) : outCpp;
  if (!existsSync(cpp)) fail(`C++ source not found: ${cpp} (pass --cpp or drop --no-gen)`);

  // --- step 2: compile the amalgamation --------------------------------------
  console.log(`build: compiling ${path.relative(REPO, cpp)}`);
  console.log(`build:            -> ${exe}`);
  const args = [
    cl, "/nologo", "/std:c++20", "/EHsc", "/W3", ...flags,
    ...defines, `/I${REPO}`,
    `/Fo${objDir}${path.sep}`, `/Fe${exe}`,
    `/Fd${path.join(objDir, "build.pdb")}`,
    cpp,
  ];
  const compile = runCl(env, args);
  if (compile !== 0) fail("cl.exe failed");
  console.log(`build: wrote ${exe}`);
}

main();
