// Generated by the Simse compiler. Do not edit.
#include "cppsrc/rtl/simse.hpp"
#include <type_traits>

// The string-literal pool's decoder (impl_specs/rtl-abi.md, "String literals: one
// table"): the emitter writes one pool of bytes plus two run-length encoded index
// series - where each entry starts and how long it is - and this expands them into the
// `StrView` per entry, once, before `main` runs. It was cppsrc/rtl/strtable.hpp.
//
// Six things are deliberate in the shape the emitter writes:
//
//  - **Both series are stored as "what to subtract from the previous value"**, with an
//    implicit 0 before the first entry: `value[i] = value[i-1] - series[i]`. The
//    literals are ordered longest first, so a length series descends slowly and a
//    *difference* of it is a small number - mostly 0 between the many literals of equal
//    length (85% of them on the compiler's own table).
//  - **Each series is run-length encoded**: its length first, then alternating blocks of
//    non-repeating values (a count, then that many values) and of runs (a count, then
//    that many `times, value` pairs), until the length is filled. The element type is a
//    template parameter because the emitter picks the width: `Int16` when every number
//    fits, `Int` otherwise.
//  - The pool is the literal texts themselves, adjacent, so the C++ compiler decodes
//    every escape and the emitter's decoding only has to agree about *how many bytes* an
//    escape costs. The emitted `static_assert` on the pool's `sizeof` is the check.
//  - The series are expanded into *stack* arrays in the initializer and dropped when it
//    returns: no heap, and the encoded statics are all the program carries.
//  - An entry is a 12-byte `StrView`, not the 32-byte owning `Str` the table used to
//    hold, and start-up allocates nothing for the literals.
//  - The pool is `const char` (a string literal, read-only) while `StrView` holds the
//    language's mutable `Char*`; the constness is cast away here, in the one place the
//    pool is touched, and nothing writes through it.

template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count);

#include <chrono>

// Time natives (the Simse surface is the prelude file cppsrc/rtl/rtl.kt). All three are
// monotonic clocks - never going backwards - since an arbitrary fixed point:
// `simse_nowMillis` for logging, and the finer `simse_nowMicros` / `simse_nowNanos` for
// the instrumented profiler (`cppsrc/profiling`, and the emitted `profileApp.measure(...)`
// of a `--profile` build; `--profile-nanos` picks the nanosecond clock). It was
// cppsrc/rtl/timeops.hpp, and its definitions were the last
// thing left in cppsrc/rtl/native.cpp - they are this section's now, so the clock is
// emitted into the program like any other prelude body and there is nothing to link.
// `emit: always`
// because the profiler's runtime is emitted by the *compiler* rather than named by
// the program: a `--profile` build needs these declarations whether or not the program
// ever asks for the time.
Int64 simse_nowMillis();
Int64 simse_nowMicros();
Int64 simse_nowNanos();

// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 59;
static const char __sm_stringPool[] =
    "a message that does not fit in the inline buffer" "hello world" "Type.Named" "DataClass" "no points" "null raw" "only-one" "positive" "bad int" "Module" "[|::|]" "absent" "column" "Field" "green" "hello" "isVar" "other" "simse" "world" "|,|,|" "Tile" "Type" "head" "item" "kind" "leaf" "line" "many" "name" "nope" "true" "zero" "2.5" "Int" "box" "one" "red" "two" "zzz" "| |" "17" "24" "42" "='" "\n" "||" " " "'" "+" "1" "2" "3" "a" "b" "n" "x" "y" "" 
;
static const Int16 __sm_stringStarts[] = {59,3,0,-48,37,1,2,1,2,0,1,3,2,0,2,1,3,0,1,1,1,7,0,1,1,1,11,0,1,1,1,7,0,1,1,1,3,0,3,1,-1,1,1,10,0};
static const Int16 __sm_stringLens[] = {59,2,-48,37,1,2,1,2,0,1,3,2,0,2,1,3,0,1,1,1,7,0,1,1,1,11,0,1,1,1,7,0,1,1,1,3,0,3,1,-1,1,1,10,0,1,1};
static_assert(sizeof(__sm_stringPool) - 1 == 276, "the string pool and its length index disagree");
static StrView __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

// `spanOf(items)`: a span over a list's elements, generated (`cppsrc/rtl/_res.md`).
template <class T>
Span<T> simse_spanOf(List<T>* items);

// What a view's byte operations still need from C++ (specs/built-in-types.md, "Views").
// The byte work itself - `find`/`indexOf`, `startsWith`/`startsWithPtr`, `substr`/`toString`
// - is Simse now, in cppsrc/rtl/StrView.kt over the span and the intrinsics
// (cppsrc/rtl/intrinsics.kt). What remains here is the `Span` member passthroughs, which
// cannot be Simse without shadowing the member they call, and `spanOfStr`, whose two
// overloads are picked by C++ overload resolution at the desugar's site (Parser.kt's
// `parseWhen`) rather than by a declaration - so a declaration reaches this section, and a
// program that calls one pays for this text (`sourcegen/ResGen.kt`).
//
// `StrView` *is* a `Span<Char>`, so `self.len`, `self[i]` and `self.slice(...)` below are
// the span's own members (cppsrc/rtl/span.hpp) - and `at` is *not* an operation of its
// own: the span's member serves it (cppsrc/rtl/StrView.kt), as `atPtr` is the
// language's (cppsrc/rtl/Span.kt).
Int simse_strView_size(StrView self);
Bool simse_strView_isEmpty(StrView self);
StrView simse_strView_slice(StrView self, Int start);
StrView simse_strView_slice(StrView self, Int start, Int count);
Char simse_strView_charAt(StrView self, Int index);
StrView simse_spanOfStr(Str* text);
StrView simse_spanOfStr(StrView view);

#include <cstdint>
#include <type_traits>

// The List/Array/Str primitives behind the prelude (impl_specs/native-interop.md), moved
// out of cppsrc/rtl/listops.hpp. Index and range errors are unchecked, matching the
// language's no-exceptions policy: `removeAt`/`removeRange` with an out-of-range index is
// undefined behavior (specs/language-decisions.md).

// Appends `value` to the end of `self`. The value is a non-deduced context so a literal
// argument (e.g. a `const char[]`) converts to the element type instead of making `T`
// ambiguous.
template <class T>
void simse_list_append(List<T>& self, const std::type_identity_t<T>& value);

// The list literal's fallback (cppsrc/rtl/rtl.kt): the compiler turns
// `listOf<Str>("a", "b")` into the construction itself, so this runs only for a position
// with no destination slot.
template <class T>
List<T> simse_listOf(const List<T>* values);

template <class T>
void simse_list_removeAt(List<T>& self, Int index);
template <class T>
void simse_list_removeRange(List<T>& self, Int start, Int end);
template <class T>
Int simse_array_count(const Array<T>& self);
template <class T>
Array<T> simse_list_toArray(const List<T>& self);
template <class T>
List<T> simse_array_toList(const Array<T>& self);
template <class T>
Array<T> simse_arrayEmpty();

void simse_str_append(Str& self, Char value);
void simse_str_appendStr(Str& self, const Str& value);
void simse_str_appendStrPtr(Str& self, const Str* value);
void simse_str_reserve(Str& self, Int count);
Str simse_int_toString(Int self);

#include <algorithm>
#include <type_traits>
#include <utility>

// The Dictionary operations and the extra List helpers behind the prelude
// (impl_specs/native-interop.md), moved out of cppsrc/rtl/dictops.hpp. The key/value
// parameters are non-deduced (`std::type_identity_t`) so that a literal argument (e.g. a
// `const char[]` key or an integer value) converts to the element type instead of making
// the template argument ambiguous.
//
// Errors are unchecked, matching the dictionary's own semantics and the language's
// no-exceptions policy: `get`/`has` on a missing key behave as documented, while `remove`
// of an absent key is a no-op.

// `dictionaryOf<K, V>()`: the empty-dictionary construction.
template <class K, class V>
Dictionary<K, V> simse_dictionaryOf();

// `d.getPtr(key)`: the value's place in the dictionary, or `null` when the key is
// absent - the read that copies nothing (`get` copies the value out, `has` is this with
// the pointer tested). The place is the dictionary's own storage, so it is valid until
// the next `insert`/`remove`/`clear` on that dictionary.
template <class K, class V>
V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.get(key)`: the value for `key`, or an empty `Opt` when absent.
template <class K, class V>
Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.has(key)`: whether `key` is present.
template <class K, class V>
Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.insert(key, value)`: insert or replace.
template <class K, class V>
void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                       const std::type_identity_t<V>& value);

// `d.remove(key)`: erase when present (a no-op otherwise).
template <class K, class V>
void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.size()`: the number of entries.
template <class K, class V>
Int simse_dict_size(const Dictionary<K, V>& self);

// `d.keys()`: the keys in the dictionary's iteration order (unspecified; sort for a
// deterministic order).
template <class K, class V>
List<K> simse_dict_keys(const Dictionary<K, V>& self);

// `d.values()`: the values in the dictionary's iteration order (unspecified).
template <class K, class V>
List<V> simse_dict_values(const Dictionary<K, V>& self);

// `d.clear()`: remove every entry.
template <class K, class V>
void simse_dict_clear(Dictionary<K, V>& self);

// `items.contains(value)`: linear membership test (`operator==` on elements).
template <class T>
Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value);

// `items.sort(less)`: in-place sort using the `(*T, *T) -> Bool` comparator. The comparator
// comes from a Simse lambda (a C++ lambda or Func), so it is a template parameter rather
// than a fixed type; it takes its two elements by pointer, so each is read where `std::sort`
// holds it instead of being copied into the comparison.
template <class T, class F>
void simse_list_sort(List<T>& self, F less);

#include <bit>
#include <cstring>

// The primitives a concatenation is *expanded* into (impl_specs/linear-il.md, "Concat").
// There is no `cat` function and no per-part `append`: the emitter computes every part's
// *exact* length, performs one `resize`, and then writes each part straight into the slot it
// owns while one `char*` advances by that part's length. So a chain of n parts touches the
// allocator once, computes each part once and copies each part once - the shape Java 9's
// `StringConcatFactory` has, with the C++ compiler seeing the straight-line form instead of a
// variadic call.
//
// No program names these: the emitter writes the symbols itself, the way it writes
// `simse_addressOf`. What each kind of part costs:
//   * a text part (a `Str`, or a literal whose length the lowering already knows) is a
//     `std::memcpy` - a constant size is one register or vector store, a runtime `Str` size
//     one call;
//   * an integer (`Int8`/`Int16`/`Int32`/`Int64`, `Int`) is *counted* by the bit scan below
//     (`std::bit_width` plus one power-of-ten comparison, never a division loop) and *written*
//     by `simse_strAddInt` - two digits per step out of a table, right to left inside the slot
//     that was made for it, so the digits are never built into a second buffer;
//   * a `Char` is one byte;
//   * a `Bool` is a `StrView` over a two-entry table ("true"/"false"): it has no digits to
//     render and is not a hot path, so it goes through the text path.
// A float is deliberately *absent*: its length is only known by formatting it, so the lowering
// keeps the `toString()` call (one `Str`, made ahead of time) and the part *is* that `Str` -
// one conversion, not one for the length and another for the write.
Int simse_strCountDigits(Int64 value);
void simse_strAddInt(char* target, Int64 value, Int count);
StrView simse_strBoolView(Bool value);

#include <charconv>
#include <cstddef>
#include <system_error>

// The string, character, numeric-conversion and min/max operations behind the prelude
// (impl_specs/native-interop.md, specs/built-in-types.md), moved out of
// cppsrc/rtl/strops.hpp.
//
// `Str` is the inline `SmString` (smstring.hpp): every size, length and index here is the
// language's `Int` (`int32_t`), including `Str::npos`, which is `-1`. Index/range errors
// are unchecked where the underlying operation is unchecked; the `Opt`-returning
// conversions never throw.

// `Str.charAt(index)`: the byte at `index` (unchecked; no bounds test).
Char simse_str_charAt(const Str& self, Int index);

// `Str.trim()` strips leading and trailing whitespace (space, tab, newline, CR).
Str simse_str_trim(const Str& self);

// `Str.split(separator)` splits on every occurrence. An empty separator returns the whole
// string as a single element. Two overloads: a separator string and a separator byte.
List<Str> simse_str_split(const Str& self, const Str& separator);
List<Str> simse_str_split(const Str& self, Char separator);

// ASCII/byte case folding (the string type is a byte string).
Str simse_str_toUpper(const Str& self);
Str simse_str_toLower(const Str& self);

// `Str.find(sub)` returns the first index of `sub`, or -1 when absent (the language's
// spelling of C++ `npos`).
Int simse_str_find(const Str& self, const Str& sub);

// `Str.lastIndexOf(sub)` returns the last index of `sub`, or -1 when absent.
Int simse_str_lastIndexOf(const Str& self, const Str& sub);

// `Str.substr(start, len)` clamps `start` to [0, size]; `len` may run past the end.
Str simse_str_substr(const Str& self, Int start, Int len);

Bool simse_str_startsWith(const Str& self, const Str& prefix);
Bool simse_str_endsWith(const Str& self, const Str& suffix);

// `Str.replace(from, to)` replaces every occurrence of `from` with `to`.
Str simse_str_replace(const Str& self, const Str& from, const Str& to);

// `Str.toInt()`/`Str.toFloat()` parse the whole string; failure (or a non-empty trailing
// remainder) yields `Opt.none()`. No exceptions: `std::from_chars` reports errors through
// its return value.
Opt<Int> simse_str_toInt(const Str& self);
Opt<Float64> simse_str_toFloat(const Str& self);

// `Char` is a signed 8-bit integer; the checks are byte-range tests so they do not depend
// on the C locale. Space, tab, newline and carriage return count as space; form feed and
// vertical tab do not.
Bool simse_char_isDigit(Char self);
Bool simse_char_isAlpha(Char self);
Bool simse_char_isAlphaOrDigit(Char self);
Bool simse_char_isSpace(Char self);

// Numeric conversions. `Char` is an 8-bit integer, so it stringifies as a number.
template <class T>
Str simse_num_toString(const T& self);
Str simse_char_toString(Char self);
Str simse_bool_toString(Bool self);

#include <cstdio>

// `print` / `println` in C, not C++ streams. The language's formatting is its own (`fmtStr`), and
// a value is one `fwrite`/`fputs`, so a program that prints never pulls in <iostream> - and with
// it the standard streams' static construction and the locale facets that drag in. One overload
// per built-in `println` accepts, so a call spells the same whatever it prints; `bool` prints
// `true`/`false`, which is what the `std::boolalpha` the emitter used to write gave.
inline void simse_write(const Str& value, FILE* out) {
    std::fwrite(value.data(), 1, (std::size_t) value.size(), out);
}

inline void simse_write(StrView value, FILE* out) {
    std::fwrite(value.ptr, 1, (std::size_t) value.len, out);
}

inline void simse_write(bool value, FILE* out) {
    std::fputs(value ? "true" : "false", out);
}

inline void simse_write(char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(signed char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(unsigned char value, FILE* out) {
    std::fputc((int) value, out);
}

inline void simse_write(short value, FILE* out) {
    std::fprintf(out, "%d", (int) value);
}

inline void simse_write(int value, FILE* out) {
    std::fprintf(out, "%d", value);
}

inline void simse_write(long value, FILE* out) {
    std::fprintf(out, "%ld", value);
}

inline void simse_write(long long value, FILE* out) {
    std::fprintf(out, "%lld", value);
}

inline void simse_write(float value, FILE* out) {
    std::fprintf(out, "%g", (double) value);
}

inline void simse_write(double value, FILE* out) {
    std::fprintf(out, "%g", value);
}

template <class T>
inline void simse_print(const T& value, FILE* out) {
    simse_write(value, out);
}

template <class T>
inline void simse_println(const T& value, FILE* out) {
    simse_write(value, out);
    std::fputc('\n', out);
}

struct ns1_Counter;
template <class A, class B>
struct ns1_Pair;
struct ns1_CounterHello;
struct ns1_Box;
struct ns1_Cell;
struct ns1_Grid;
struct ns1_CounterReceiverShapes;
struct ns1_Holder;
struct ns1_Shell;
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Counter {
    Int value;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
template <class A, class B>
struct ns1_Pair {
    A first;
    B second;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_CounterHello {
    Int value;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
using ns1_Mapper = Func<Int(Int)>;
// stress/objects/src/main.kt
using ns1_Predicate = Func<Bool(Int)>;
// stress/objects/src/main.kt
enum class ns1_Color { Red, Green = 4, Blue };
inline ns1_Color ns1_simse_Color_fromInt(Int value) { return (ns1_Color) value; }
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Box {
    Int value;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Cell {
    Int value;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Grid {
    ns1_Cell cell;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_CounterReceiverShapes {
    Int n;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Holder {
    ns1_CounterReceiverShapes counter;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Shell {
    Str text;
};
SIMSE_PACK_POP
// stress/objects/src/main.kt
enum class ns1_Shape { Circle, Square = 4 };
inline ns1_Shape ns1_simse_Shape_fromInt(Int value) { return (ns1_Shape) value; }

Bool startsWith(StrView* self, Str text);
Int find(StrView* self, Str sub);
Str substr(StrView* self, Int from, Int count);
Str toString(StrView* self);
Str fmtStr(StrView fmt, List<Str>* items);
Bool isEmpty(Str* self);
template <class T>
T min(T a, T b);
template <class T>
T max(T a, T b);
Int ns1_bump(ns1_Counter* self);
Int ns1_read(Ref<ns1_Counter> box);
Int ns1_bumpThrough(Ref<ns1_Counter> box);
Int ns1_partCountedReference();
template <class T>
T ns1_identity(T value);
Int ns1_partGenerics();
Int ns1_bump(ns1_CounterHello* self);
Int ns1_partHello();
Int ns1_apply(ns1_Mapper f, Int value);
Int ns1_countIf(List<Int>* items, ns1_Predicate predicate);
ns1_Mapper ns1_makeAdder();
Int ns1_partLambdas();
Str ns1_label(ns1_Color c);
Str ns1_describe(Int n);
Ref<ns1_Box> ns1_maybeRef(Bool flag);
ns1_Box* ns1_maybePointer(Ref<ns1_Box> box, Bool flag);
Int ns1_partLanguageTour();
Opt<Int> ns1_half(Int n);
Res<Str> ns1_labelOptionalResult(Int n);
Res<Int> ns1_longError();
Res<Int> ns1_echo(Res<Int> r);
Int ns1_partOptionalResult();
void ns1_bump(Int* value);
void ns1_bumpCell(ns1_Cell* cell);
Int ns1_partPointerPlace();
void ns1_bump(ns1_CounterReceiverShapes* self);
void ns1_add(ns1_CounterReceiverShapes* self, Int delta);
Int ns1_twice(ns1_CounterReceiverShapes* self);
ns1_CounterReceiverShapes* ns1_self(ns1_CounterReceiverShapes* self);
void ns1_bumpTwice(ns1_CounterReceiverShapes* counter);
Int ns1_partReceiverShapes();
Str ns1_mirror(Str* a, Ref<Str> b);
Str ns1_parcel(Str after, List<Str>* items);
Int ns1_partRtlSimse();
Bool ns1_isEmpty(ns1_Shell* self);
Str ns1_describeShapes(Str* self);
Int ns1_area(Int height);
Int ns1_partShapes();
Attribute ns1_attr(Str name, Str value);
List<Attribute> ns1_attrs3(Attribute a, Attribute b, Attribute c);
List<Attribute> ns1_attrs4(Attribute a, Attribute b, Attribute c, Attribute d);
Array<XmlNode> ns1_noChildren();
Array<XmlNode> ns1_oneChild(XmlNode child);
Str ns1_escapeText(Str text);
Str ns1_indentation(Int depth);
Str ns1_dumpNode(XmlNode node, Int depth);
Int ns1_partXmlTree();

Bool startsWith(StrView* self, Str text) {
    Str* _sm_base1;
    Int count, _sm_expr1;
    Bool _sm_expr2;
    Char* _sm_expr4;
    count = text.size();
    _sm_expr1 = simse_strView_size((*self));
    _sm_expr2 = count > _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    _sm_expr2 = count <= 0;
    if (_sm_expr2) goto L3;
    goto L4;
    L3:;
    return true;
    L4:;
    _sm_base1 = &text;
    _sm_expr4 = simse_str_data(_sm_base1);
    _sm_expr1 = simse_mem_compare(self->ptr, 0, _sm_expr4, 0, count);
    _sm_expr2 = _sm_expr1 == 0;
    return _sm_expr2;
}
Int find(StrView* self, Str sub) {
    Str* _sm_base1;
    Int needle, len, _sm_expr3, i;
    Bool _sm_expr1;
    Char* _sm_expr6;
    needle = sub.size();
    _sm_expr1 = needle == 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return 0;
    L2:;
    len = simse_strView_size((*self));
    _sm_expr1 = needle > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    _sm_expr3 = -1;
    return _sm_expr3;
    L4:;
    i = 0;
    L5:;
    _sm_expr3 = i + needle;
    _sm_expr1 = _sm_expr3 <= len;
    if (!(_sm_expr1)) goto L6;
    _sm_base1 = &sub;
    _sm_expr6 = simse_str_data(_sm_base1);
    _sm_expr3 = simse_mem_compare(self->ptr, i, _sm_expr6, 0, needle);
    _sm_expr1 = _sm_expr3 == 0;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    return i;
    L8:;
    i = i + 1;
    goto L5;
    L6:;
    _sm_expr3 = -1;
    return _sm_expr3;
}
Str substr(StrView* self, Int from, Int count) {
    Int len, begin, end, _sm_expr6;
    Bool _sm_expr1;
    len = simse_strView_size((*self));
    begin = from;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr1 = begin > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = len;
    L4:;
    end = begin + count;
    _sm_expr1 = count < 0;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    end = begin;
    L6:;
    _sm_expr1 = end > len;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    end = len;
    L8:;
    Str out;
    _sm_expr1 = end > begin;
    if (_sm_expr1) goto L9;
    goto L10;
    L9:;
    _sm_expr6 = end - begin;
    simse_str_setBytes(out, self->ptr, begin, _sm_expr6);
    L10:;
    return out;
}
Str toString(StrView* self) {
    Int _sm_expr1;
    Str _sm_expr2;
    _sm_expr1 = simse_strView_size((*self));
    _sm_expr2 = substr(self, 0, _sm_expr1);
    return _sm_expr2;
}
Str fmtStr(StrView fmt, List<Str>* items) {
    Str _sm_base2, out;
    Bool _sm_expr1;
    Int points, i, _sm_expr2, _sm_expr8, used;
    Char _sm_expr4, ch;
    _sm_expr1 = items == nullptr;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return fmt;
    L2:;
    points = 0;
    i = 0;
    L3:;
    _sm_expr2 = simse_strView_size(fmt);
    _sm_expr1 = i < _sm_expr2;
    if (!(_sm_expr1)) goto L4;
    _sm_expr4 = simse_strView_charAt(fmt, i);
    _sm_expr1 = _sm_expr4 == '|';
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    points = points + 1;
    L6:;
    i = i + 1;
    goto L3;
    L4:;
    _sm_expr2 = items->size();
    _sm_expr1 = points != _sm_expr2;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    return fmt;
    L8:;
    out = __sm_stringTable[58];
    _sm_expr8 = simse_strView_size(fmt);
    simse_str_reserve(out, _sm_expr8);
    used = 0;
    i = 0;
    L9:;
    _sm_expr2 = simse_strView_size(fmt);
    _sm_expr1 = i < _sm_expr2;
    if (!(_sm_expr1)) goto L10;
    ch = simse_strView_charAt(fmt, i);
    _sm_expr1 = ch == '|';
    if (_sm_expr1) goto L11;
    goto L12;
    L11:;
    _sm_base2 = (*items)[used];
    simse_str_appendStr(out, _sm_base2);
    used = used + 1;
    goto L13;
    L12:;
    simse_str_append(out, ch);
    L13:;
    i = i + 1;
    goto L9;
    L10:;
    return out;
}
Bool isEmpty(Str* self) {
    Int _sm_expr1;
    Bool _sm_expr2;
    _sm_expr1 = self->size();
    _sm_expr2 = _sm_expr1 == 0;
    return _sm_expr2;
}
template <class T>
T min(T a, T b) {
    Bool _sm_expr1;
    _sm_expr1 = a < b;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return a;
    L2:;
    return b;
}
template <class T>
T max(T a, T b) {
    Bool _sm_expr1;
    _sm_expr1 = a > b;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return a;
    L2:;
    return b;
}
// stress/objects/src/main.kt
Int ns1_bump(ns1_Counter* self) {
    Int _sm_base1, _sm_expr1, _sm_expr2;
    _sm_expr1 = self->value;
    _sm_base1 = _sm_expr1 + 1;
    self->value = _sm_base1;
    _sm_expr2 = self->value;
    return _sm_expr2;
}
// stress/objects/src/main.kt
Int ns1_read(Ref<ns1_Counter> box) {
    Int _sm_expr1;
    _sm_expr1 = box->value;
    return _sm_expr1;
}
// stress/objects/src/main.kt
Int ns1_bumpThrough(Ref<ns1_Counter> box) {
    Ref<ns1_Counter> again;
    Int _sm_expr1;
    again = box;
    _sm_expr1 = ns1_bump((again).get());
    return _sm_expr1;
}
// stress/objects/src/main.kt
Int ns1_partCountedReference() {
    Int _sm_base1, _sm_base2, _sm_base3, _sm_expr1, bumped, _sm_expr2;
    ns1_Counter plain;
    Ref<ns1_Counter> first;
    plain = ns1_Counter{10};
    first = makeRef<std::remove_cvref_t<decltype((plain))>>(plain);
    _sm_expr1 = ns1_read(first);
    simse_println((_sm_expr1), stdout);
    bumped = ns1_bump((first).get());
    simse_println((bumped), stdout);
    _sm_base1 = plain.value;
    simse_println((_sm_base1), stdout);
    _sm_base2 = first->value;
    simse_println((_sm_base2), stdout);
    _sm_expr2 = ns1_bumpThrough(first);
    simse_println((_sm_expr2), stdout);
    _sm_base3 = first->value;
    simse_println((_sm_base3), stdout);
    return 0;
}
// stress/objects/src/main.kt
template <class T>
T ns1_identity(T value) {
    return value;
}
// stress/objects/src/main.kt
Int ns1_partGenerics() {
    Int _sm_base1, _sm_base2, _sm_expr1, _sm_expr2;
    List<Int> numbers;
    ns1_Pair<Int, Bool> a;
    ns1_Pair<Str, Int> b;
    numbers = List<Int>();
    a = ns1_Pair<Int, Bool>{1, true};
    b = ns1_Pair<Str, Int>{__sm_stringTable[38], 2};
    _sm_expr1 = ns1_identity<Int>(7);
    simse_println((_sm_expr1), stdout);
    _sm_base1 = a.first;
    simse_println((_sm_base1), stdout);
    _sm_base2 = b.second;
    simse_println((_sm_base2), stdout);
    _sm_expr2 = numbers.size();
    simse_println((_sm_expr2), stdout);
    return 0;
}
// stress/objects/src/main.kt
Int ns1_bump(ns1_CounterHello* self) {
    Int _sm_expr1, _sm_expr2;
    _sm_expr1 = self->value;
    _sm_expr2 = _sm_expr1 + 1;
    return _sm_expr2;
}
// stress/objects/src/main.kt
Int ns1_partHello() {
    Int i, total, _sm_expr3;
    Bool _sm_expr1;
    ns1_CounterHello c;
    i = 0;
    total = 0;
    L1:;
    _sm_expr1 = i < 5;
    if (!(_sm_expr1)) goto L2;
    total = total + i;
    i = i + 1;
    goto L1;
    L2:;
    c = ns1_CounterHello{10};
    _sm_expr1 = total > 5;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    simse_println((total), stdout);
    goto L5;
    L4:;
    _sm_expr3 = ns1_bump(simse_addressOf(c));
    simse_println((_sm_expr3), stdout);
    L5:;
    simse_println((true), stdout);
    return 0;
}
// stress/objects/src/main.kt
Int ns1_apply(ns1_Mapper f, Int value) {
    Int _sm_expr1;
    _sm_expr1 = f(value);
    return _sm_expr1;
}
// stress/objects/src/main.kt
Int ns1_countIf(List<Int>* items, ns1_Predicate predicate) {
    Int _sm_base1, count;
    Span<Int> c;
    Bool _sm_expr1, _sm_expr2;
    count = 0;
    c = simse_spanOf(items);
    L1:;
    _sm_expr1 = c.isEmpty();
    _sm_expr2 = !_sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_base1 = c[0];
    _sm_expr1 = predicate(_sm_base1);
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    count = count + 1;
    L4:;
    c = c.slice(1);
    goto L1;
    L2:;
    return count;
}
// stress/objects/src/main.kt
ns1_Mapper ns1_makeAdder() {
struct ns1_makeAdder_closure1 {
    Int factor;
    auto operator()(Int v) {
        Int _sm_base1, _sm_expr1;
        _sm_base1 = this->factor;
        _sm_expr1 = v + _sm_base1;
        return _sm_expr1;
    }
};

    ns1_makeAdder_closure1 _sm_base1;
    Int factor;
    factor = 10;
    _sm_base1 = ns1_makeAdder_closure1{factor};
    return _sm_base1;
}
// stress/objects/src/main.kt
Int ns1_partLambdas() {
struct ns1_partLambdas_closure1 {
    auto operator()(Int v) {
        Int _sm_expr1;
        _sm_expr1 = v * 2;
        return _sm_expr1;
    }
};

struct ns1_partLambdas_closure2 {
    auto operator()(Int v) {
        Int _sm_expr1;
        _sm_expr1 = v + 1;
        return _sm_expr1;
    }
};

struct ns1_partLambdas_closure3 {
    auto operator()(Int v) {
        Int _sm_expr1;
        Bool _sm_expr2;
        _sm_expr1 = v % 2;
        _sm_expr2 = _sm_expr1 == 0;
        return _sm_expr2;
    }
};

struct ns1_partLambdas_closure4 {
    auto operator()(Int v) {
        Bool _sm_expr1;
        _sm_expr1 = v > 2;
        return _sm_expr1;
    }
};

struct ns1_partLambdas_closure5 {
    auto operator()(Int v) {
        Bool _sm_expr1;
        Int _sm_expr2;
        _sm_expr1 = v > 0;
        if (_sm_expr1) goto L1;
        goto L2;
        L1:;
        _sm_expr2 = v * 100;
        return _sm_expr2;
        L2:;
        return 0;
    }
};

    ns1_partLambdas_closure2 _sm_base1;
    List<Int>* _sm_base2, * _sm_base3;
    ns1_partLambdas_closure4 _sm_base4;
    ns1_Mapper doubler, add10, big;
    Int _sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr5, _sm_expr6, _sm_expr7;
    List<Int> items;
    ns1_Predicate isEven;
    doubler = ns1_partLambdas_closure1{};
    _sm_expr1 = doubler(21);
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = ns1_apply(doubler, 5);
    simse_println((_sm_expr2), stdout);
    _sm_base1 = ns1_partLambdas_closure2{};
    _sm_expr3 = ns1_apply(_sm_base1, 41);
    simse_println((_sm_expr3), stdout);
    add10 = ns1_makeAdder();
    _sm_expr4 = add10(5);
    simse_println((_sm_expr4), stdout);
    items = List<Int>();
    simse_list_append(items, 1);
    simse_list_append(items, 2);
    simse_list_append(items, 3);
    simse_list_append(items, 4);
    isEven = ns1_partLambdas_closure3{};
    _sm_base2 = &items;
    _sm_expr5 = ns1_countIf(_sm_base2, isEven);
    simse_println((_sm_expr5), stdout);
    _sm_base3 = &items;
    _sm_base4 = ns1_partLambdas_closure4{};
    _sm_expr6 = ns1_countIf(_sm_base3, _sm_base4);
    simse_println((_sm_expr6), stdout);
    big = ns1_partLambdas_closure5{};
    _sm_expr7 = big(3);
    simse_println((_sm_expr7), stdout);
    return 0;
}
// stress/objects/src/main.kt
Str ns1_label(ns1_Color c) {
    ns1_Color _sm_expr1;
    Bool _sm_expr2;
    _sm_expr1 = ns1_Color::Red;
    _sm_expr2 = c == _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[37];
    L2:;
    _sm_expr1 = ns1_Color::Green;
    _sm_expr2 = c == _sm_expr1;
    if (_sm_expr2) goto L4;
    goto L5;
    L4:;
    return __sm_stringTable[14];
    L5:;
    return __sm_stringTable[17];
}
// stress/objects/src/main.kt
Str ns1_describe(Int n) {
    Bool _sm_expr1;
    _sm_expr1 = n == 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[32];
    L2:;
    _sm_expr1 = n == 1;
    if (_sm_expr1) goto L4;
    goto L5;
    L4:;
    return __sm_stringTable[36];
    L5:;
    return __sm_stringTable[28];
}
// stress/objects/src/main.kt
Ref<ns1_Box> ns1_maybeRef(Bool flag) {
    Ref<ns1_Box> _sm_expr1;
    if (flag) goto L1;
    goto L2;
    L1:;
    _sm_expr1 = makeRef<ns1_Box>(7);
    return _sm_expr1;
    L2:;
    return nullptr;
}
// stress/objects/src/main.kt
ns1_Box* ns1_maybePointer(Ref<ns1_Box> box, Bool flag) {
    ns1_Box* _sm_expr1;
    if (flag) goto L1;
    goto L2;
    L1:;
    _sm_expr1 = (box).get();
    return _sm_expr1;
    L2:;
    return nullptr;
}
// stress/objects/src/main.kt
Int ns1_partLanguageTour() {
    ns1_Color _sm_base1, _sm_base2, _sm_base3, _sm_base4, parsed, _sm_expr8;
    Int _sm_base6, _sm_base9, _sm_expr6, _sm_expr9, _sm_expr14, _sm_expr15, _sm_expr21;
    Str _sm_base11, _sm_base12, _sm_base13, _sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr5,
        _sm_expr7, text, _sm_expr16, _sm_expr19, _sm_expr30, _sm_expr31, _sm_expr32;
    Char _sm_base14, _sm_base15, letter;
    Float64 _sm_base16, _sm_expr25;
    Ref<ns1_Box> present, absent, boxed;
    Bool _sm_expr10, _sm_expr17, _sm_expr18, _sm_expr23, _sm_expr26, _sm_expr27, _sm_expr28, _sm_expr29;
    ns1_Box* rawPresent, * rawAbsent;
    Opt<Int> number, badNumber;
    Opt<Float64> fraction;
    Int8 small;
    _sm_base1 = ns1_Color::Red;
    _sm_expr1 = ns1_label(_sm_base1);
    simse_println((_sm_expr1), stdout);
    _sm_base2 = ns1_Color::Green;
    _sm_expr2 = ns1_label(_sm_base2);
    simse_println((_sm_expr2), stdout);
    _sm_base3 = ns1_Color::Blue;
    _sm_expr3 = ns1_label(_sm_base3);
    simse_println((_sm_expr3), stdout);
    _sm_expr4 = ns1_describe(0);
    simse_println((_sm_expr4), stdout);
    _sm_expr5 = ns1_describe(5);
    simse_println((_sm_expr5), stdout);
    _sm_base4 = ns1_Color::Green;
    _sm_expr6 = static_cast<Int>(_sm_base4);
    simse_println((_sm_expr6), stdout);
    parsed = ns1_simse_Color_fromInt(4);
    _sm_expr7 = ns1_label(parsed);
    simse_println((_sm_expr7), stdout);
    _sm_expr8 = ns1_simse_Color_fromInt(5);
    _sm_expr9 = static_cast<Int>(_sm_expr8);
    simse_println((_sm_expr9), stdout);
    present = ns1_maybeRef(true);
    _sm_expr10 = present != nullptr;
    if (_sm_expr10) goto L1;
    goto L2;
    L1:;
    _sm_base6 = present->value;
    simse_println((_sm_base6), stdout);
    L2:;
    absent = ns1_maybeRef(false);
    _sm_expr10 = absent == nullptr;
    if (_sm_expr10) goto L3;
    goto L4;
    L3:;
    simse_println((__sm_stringTable[11]), stdout);
    L4:;
    boxed = makeRef<ns1_Box>(3);
    rawPresent = ns1_maybePointer(boxed, true);
    _sm_expr10 = rawPresent != nullptr;
    if (_sm_expr10) goto L5;
    goto L6;
    L5:;
    _sm_base9 = rawPresent->value;
    simse_println((_sm_base9), stdout);
    L6:;
    rawAbsent = ns1_maybePointer(boxed, false);
    _sm_expr10 = rawAbsent == nullptr;
    if (_sm_expr10) goto L7;
    goto L8;
    L7:;
    simse_println((__sm_stringTable[5]), stdout);
    L8:;
    text = __sm_stringTable[1];
    _sm_expr14 = simse_str_find(text, __sm_stringTable[19]);
    simse_println((_sm_expr14), stdout);
    _sm_expr15 = simse_str_find(text, __sm_stringTable[39]);
    simse_println((_sm_expr15), stdout);
    _sm_expr16 = simse_str_substr(text, 0, 5);
    simse_println((_sm_expr16), stdout);
    _sm_expr17 = simse_str_startsWith(text, __sm_stringTable[15]);
    simse_println((_sm_expr17), stdout);
    _sm_expr18 = simse_str_endsWith(text, __sm_stringTable[19]);
    simse_println((_sm_expr18), stdout);
    _sm_expr19 = simse_str_replace(text, __sm_stringTable[19], __sm_stringTable[18]);
    simse_println((_sm_expr19), stdout);
    _sm_base11 = __sm_stringTable[43];
    number = simse_str_toInt(_sm_base11);
    _sm_expr10 = number.hasValue();
    if (_sm_expr10) goto L9;
    goto L10;
    L9:;
    _sm_expr21 = number.value();
    simse_println((_sm_expr21), stdout);
    L10:;
    _sm_base12 = __sm_stringTable[30];
    badNumber = simse_str_toInt(_sm_base12);
    _sm_expr10 = badNumber.hasValue();
    _sm_expr23 = !_sm_expr10;
    if (_sm_expr23) goto L11;
    goto L12;
    L11:;
    simse_println((__sm_stringTable[8]), stdout);
    L12:;
    _sm_base13 = __sm_stringTable[33];
    fraction = simse_str_toFloat(_sm_base13);
    _sm_expr10 = fraction.hasValue();
    if (_sm_expr10) goto L13;
    goto L14;
    L13:;
    _sm_expr25 = fraction.value();
    simse_println((_sm_expr25), stdout);
    L14:;
    letter = 'a';
    _sm_expr26 = simse_char_isAlpha(letter);
    simse_println((_sm_expr26), stdout);
    _sm_expr27 = simse_char_isDigit(letter);
    simse_println((_sm_expr27), stdout);
    _sm_base14 = '7';
    _sm_expr28 = simse_char_isDigit(_sm_base14);
    simse_println((_sm_expr28), stdout);
    _sm_base15 = ' ';
    _sm_expr29 = simse_char_isSpace(_sm_base15);
    simse_println((_sm_expr29), stdout);
    small = 5;
    _sm_expr30 = simse_num_toString(small);
    simse_println((_sm_expr30), stdout);
    _sm_expr31 = __sm_stringTable[31];
    simse_println((_sm_expr31), stdout);
    _sm_base16 = 2.5;
    _sm_expr32 = simse_num_toString(_sm_base16);
    simse_println((_sm_expr32), stdout);
    auto _sm_expr33 = min(3, 9);
    simse_println((_sm_expr33), stdout);
    auto _sm_expr34 = max(3, 9);
    simse_println((_sm_expr34), stdout);
    return 0;
}
// stress/objects/src/main.kt
Opt<Int> ns1_half(Int n) {
    Int _sm_expr1, _sm_expr4;
    Bool _sm_expr2;
    Opt<Int> _sm_expr3;
    _sm_expr1 = n % 2;
    _sm_expr2 = _sm_expr1 != 0;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    _sm_expr3 = Opt<Int>::none();
    return _sm_expr3;
    L2:;
    _sm_expr4 = n / 2;
    _sm_expr3 = Opt<Int>::some(_sm_expr4);
    return _sm_expr3;
}
// stress/objects/src/main.kt
Res<Str> ns1_labelOptionalResult(Int n) {
    Bool _sm_expr1;
    Res<Str> _sm_expr2;
    _sm_expr1 = n < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    _sm_expr2 = Res<Str>::err(__sm_stringTable[58]);
    return _sm_expr2;
    L2:;
    _sm_expr2 = Res<Str>::ok(__sm_stringTable[7]);
    return _sm_expr2;
}
// stress/objects/src/main.kt
Res<Int> ns1_longError() {
    Res<Int> _sm_expr1;
    _sm_expr1 = Res<Int>::err(__sm_stringTable[0]);
    return _sm_expr1;
}
// stress/objects/src/main.kt
Res<Int> ns1_echo(Res<Int> r) {
    Str _sm_base1;
    Int _sm_base2;
    Res<Int> copy, _sm_expr3;
    Bool _sm_expr1, _sm_expr2;
    copy = r;
    _sm_expr1 = copy.isOk();
    _sm_expr2 = !_sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    _sm_base1 = copy.Error;
    _sm_expr3 = Res<Int>::err(_sm_base1);
    return _sm_expr3;
    L2:;
    _sm_base2 = copy.Value;
    _sm_expr3 = Res<Int>::ok(_sm_base2);
    return _sm_expr3;
}
// stress/objects/src/main.kt
Int ns1_partOptionalResult() {
    Str* _sm_base1;
    Str _sm_base2, _sm_base5, _sm_expr5, _sm_expr8;
    Opt<Int>* _sm_base3, * _sm_base4;
    Opt<Int> empty, found, _sm_expr13, _sm_expr14;
    Bool _sm_expr1, _sm_expr3, _sm_expr7, _sm_expr10, _sm_expr12, _sm_expr16, _sm_expr17;
    Int _sm_expr2, _sm_expr4, _sm_expr6, _sm_expr9, _sm_expr11, _sm_expr15, _sm_expr20;
    Opt<Str> text, copy;
    Res<Str> bad, good;
    List<Opt<Int>> counts;
    Res<Int> failed, again, _sm_expr18, _sm_expr19;
    empty = Opt<Int>();
    _sm_expr1 = empty.hasValue();
    simse_println((_sm_expr1), stdout);
    found = ns1_half(8);
    _sm_expr2 = found.value();
    simse_println((_sm_expr2), stdout);
    found = ns1_half(9);
    _sm_expr3 = found.hasValue();
    simse_println((_sm_expr3), stdout);
    found = Opt<Int>::some(3);
    _sm_expr4 = found.value();
    simse_println((_sm_expr4), stdout);
    text = Opt<Str>::some(__sm_stringTable[15]);
    copy = text;
    _sm_expr5 = copy.value();
    _sm_expr6 = _sm_expr5.size();
    simse_println((_sm_expr6), stdout);
    text = Opt<Str>::none();
    _sm_expr7 = text.hasValue();
    simse_println((_sm_expr7), stdout);
    _sm_expr8 = copy.value();
    simse_println((_sm_expr8), stdout);
    _sm_expr9 = -1;
    bad = ns1_labelOptionalResult(_sm_expr9);
    _sm_expr10 = bad.isOk();
    simse_println((_sm_expr10), stdout);
    _sm_base1 = simse_addressOf(bad.Error);
    _sm_expr11 = _sm_base1->size();
    simse_println((_sm_expr11), stdout);
    good = ns1_labelOptionalResult(7);
    _sm_expr12 = good.isOk();
    simse_println((_sm_expr12), stdout);
    _sm_base2 = good.Value;
    simse_println((_sm_base2), stdout);
    counts = List<Opt<Int>>();
    _sm_expr13 = ns1_half(4);
    simse_list_append(counts, _sm_expr13);
    _sm_expr14 = ns1_half(5);
    simse_list_append(counts, _sm_expr14);
    _sm_base3 = simse_addressOf(counts[0]);
    _sm_expr15 = _sm_base3->value();
    simse_println((_sm_expr15), stdout);
    _sm_base4 = simse_addressOf(counts[1]);
    _sm_expr16 = _sm_base4->hasValue();
    simse_println((_sm_expr16), stdout);
    failed = ns1_longError();
    _sm_expr17 = failed.isOk();
    simse_println((_sm_expr17), stdout);
    again = ns1_echo(failed);
    _sm_base5 = again.Error;
    simse_println((_sm_base5), stdout);
    _sm_expr18 = Res<Int>::ok(9);
    _sm_expr19 = ns1_echo(_sm_expr18);
    _sm_expr20 = _sm_expr19.Value;
    simse_println((_sm_expr20), stdout);
    return 0;
}
// stress/objects/src/main.kt
void ns1_bump(Int* value) {
    Int _sm_base1, _sm_expr1;
    _sm_expr1 = *value;
    _sm_base1 = _sm_expr1 + 1;
    *value = _sm_base1;
}
// stress/objects/src/main.kt
void ns1_bumpCell(ns1_Cell* cell) {
    Int _sm_base1, _sm_expr1;
    _sm_expr1 = cell->value;
    _sm_base1 = _sm_expr1 + 1;
    cell->value = _sm_base1;
}
// stress/objects/src/main.kt
Int ns1_partPointerPlace() {
    Int* _sm_base1, * _sm_base4, * _sm_base8, * _sm_base10, * _sm_base11, * _sm_base13, * _sm_base15;
    ns1_Cell* _sm_base2, * _sm_base3, * _sm_base5, * _sm_base6, * _sm_base7, * _sm_base9, * _sm_base12,
        * _sm_base14;
    Int local;
    Str _sm_expr1, _sm_expr4, _sm_expr6, _sm_expr7, _sm_expr8;
    ns1_Cell _sm_expr2, _sm_expr3, _sm_expr5;
    List<ns1_Cell> cells;
    ns1_Grid grid;
    local = 1;
    _sm_base1 = &local;
    ns1_bump(_sm_base1);
    _sm_expr1 = simse_int_toString(local);
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = ns1_Cell{1};
    _sm_expr3 = ns1_Cell{2};
    cells = List<ns1_Cell>{_sm_expr2, _sm_expr3};
    _sm_base3 = simse_addressOf(cells[0]);
    _sm_base2 = _sm_base3;
    ns1_bumpCell(_sm_base2);
    _sm_base5 = simse_addressOf(cells[0]);
    _sm_base4 = simse_addressOf(_sm_base5->value);
    _sm_expr4 = simse_int_toString((*_sm_base4));
    simse_println((_sm_expr4), stdout);
    _sm_expr5 = ns1_Cell{5};
    grid = ns1_Grid{_sm_expr5};
    _sm_base7 = simse_addressOf(grid.cell);
    _sm_base6 = _sm_base7;
    ns1_bumpCell(_sm_base6);
    _sm_base9 = simse_addressOf(grid.cell);
    _sm_base8 = simse_addressOf(_sm_base9->value);
    _sm_expr6 = simse_int_toString((*_sm_base8));
    simse_println((_sm_expr6), stdout);
    _sm_base12 = simse_addressOf(cells[1]);
    _sm_base11 = simse_addressOf(_sm_base12->value);
    _sm_base10 = _sm_base11;
    ns1_bump(_sm_base10);
    _sm_base14 = simse_addressOf(cells[1]);
    _sm_base13 = simse_addressOf(_sm_base14->value);
    _sm_expr7 = simse_int_toString((*_sm_base13));
    simse_println((_sm_expr7), stdout);
    _sm_base15 = &local;
    ns1_bump(_sm_base15);
    _sm_expr8 = simse_int_toString(local);
    simse_println((_sm_expr8), stdout);
    return 0;
}
// stress/objects/src/main.kt
void ns1_bump(ns1_CounterReceiverShapes* self) {
    ns1_add(self, 1);
}
// stress/objects/src/main.kt
void ns1_add(ns1_CounterReceiverShapes* self, Int delta) {
    Int _sm_base1, _sm_expr1;
    _sm_expr1 = self->n;
    _sm_base1 = _sm_expr1 + delta;
    self->n = _sm_base1;
}
// stress/objects/src/main.kt
Int ns1_twice(ns1_CounterReceiverShapes* self) {
    Int _sm_expr1;
    ns1_bump(self);
    ns1_bump(self);
    _sm_expr1 = self->n;
    return _sm_expr1;
}
// stress/objects/src/main.kt
ns1_CounterReceiverShapes* ns1_self(ns1_CounterReceiverShapes* self) {
    ns1_CounterReceiverShapes* _sm_expr1;
    _sm_expr1 = self;
    return _sm_expr1;
}
// stress/objects/src/main.kt
void ns1_bumpTwice(ns1_CounterReceiverShapes* counter) {
    ns1_bump(counter);
    ns1_bump(counter);
}
// stress/objects/src/main.kt
Int ns1_partReceiverShapes() {
    Int* _sm_base1, * _sm_base3, * _sm_base6;
    ns1_CounterReceiverShapes* _sm_base2, * _sm_base4, * _sm_base5, * through;
    ns1_CounterReceiverShapes counter, _sm_expr4;
    Int _sm_expr1;
    Str _sm_expr2, _sm_expr3, _sm_expr5, _sm_expr6;
    ns1_Holder holder;
    counter = ns1_CounterReceiverShapes{0};
    _sm_expr1 = ns1_twice(simse_addressOf(counter));
    _sm_expr2 = simse_int_toString(_sm_expr1);
    simse_println((_sm_expr2), stdout);
    through = ns1_self(simse_addressOf(counter));
    ns1_add(through, 3);
    _sm_base1 = simse_addressOf(counter.n);
    _sm_expr3 = simse_int_toString((*_sm_base1));
    simse_println((_sm_expr3), stdout);
    _sm_expr4 = ns1_CounterReceiverShapes{10};
    holder = ns1_Holder{_sm_expr4};
    _sm_base2 = simse_addressOf(holder.counter);
    ns1_bump(_sm_base2);
    _sm_base4 = simse_addressOf(holder.counter);
    _sm_base3 = simse_addressOf(_sm_base4->n);
    _sm_expr5 = simse_int_toString((*_sm_base3));
    simse_println((_sm_expr5), stdout);
    _sm_base5 = &counter;
    ns1_bumpTwice(_sm_base5);
    _sm_base6 = simse_addressOf(counter.n);
    _sm_expr6 = simse_int_toString((*_sm_base6));
    simse_println((_sm_expr6), stdout);
    return 0;
}
// stress/objects/src/main.kt
Str ns1_mirror(Str* a, Ref<Str> b) {
    char* __sm_catP;
    Str _sm_base2, _sm_base3, _sm_expr1;
    _sm_base2 = *(a);
    _sm_base3 = *(b);
    _sm_expr1.resize(4 + _sm_base2.size() + _sm_base3.size());
    __sm_catP = _sm_expr1.data();
    *__sm_catP = (char) ('[');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, _sm_base2.data(), _sm_base2.size());
    __sm_catP = __sm_catP + _sm_base2.size();
    std::memcpy(__sm_catP, "::", 2);
    __sm_catP = __sm_catP + 2;
    std::memcpy(__sm_catP, _sm_base3.data(), _sm_base3.size());
    __sm_catP = __sm_catP + _sm_base3.size();
    *__sm_catP = (char) (']');
    return _sm_expr1;
}
// stress/objects/src/main.kt
Str ns1_parcel(Str after, List<Str>* items) {
    char* __sm_catP;
    Str out, _sm_expr3, _sm_expr4;
    Int i, _sm_expr1;
    Bool _sm_expr2;
    out = after;
    i = 0;
    L1:;
    _sm_expr1 = items->size();
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr3.resize(1 + out.size());
    __sm_catP = _sm_expr3.data();
    std::memcpy(__sm_catP, out.data(), out.size());
    __sm_catP = __sm_catP + out.size();
    *__sm_catP = (char) ('+');
    _sm_expr4 = (*items)[i];
    out.resize(_sm_expr3.size() + _sm_expr4.size());
    __sm_catP = out.data();
    std::memcpy(__sm_catP, _sm_expr3.data(), _sm_expr3.size());
    __sm_catP = __sm_catP + _sm_expr3.size();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    i = i + 1;
    goto L1;
    L2:;
    return out;
}
// stress/objects/src/main.kt
Int ns1_partRtlSimse() {
    char* __sm_catP;
    List<Str> _sm_base7, _sm_base9, _sm_base16, parts;
    List<Str>* _sm_base8, * _sm_base10, * _sm_base19;
    Str _sm_base11, _sm_base12, _sm_base13, _sm_base14, _sm_base15, _sm_base17, _sm_base18, _sm_expr1,
        _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr6, _sm_expr7, _sm_expr8, _sm_expr9, _sm_expr10, _sm_expr11,
        text, borrowed, _sm_expr17, _sm_expr19, _sm_expr20;
    Int least, most, _sm_expr18;
    Float64 _sm_expr5;
    Bool _sm_expr12, _sm_expr13, _sm_expr14, _sm_expr16;
    ns1_Shell _sm_expr15;
    Str* ptr;
    Ref<Str> boxed;
    least = min(3, 2);
    most = max(3, 2);
    _sm_expr1 = simse_int_toString(least);
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = simse_int_toString(most);
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = min<Str>(__sm_stringTable[54], __sm_stringTable[53]);
    simse_println((_sm_expr3), stdout);
    _sm_expr4 = max<Str>(__sm_stringTable[54], __sm_stringTable[53]);
    simse_println((_sm_expr4), stdout);
    _sm_expr5 = min<Float64>(2.5, 1.5);
    _sm_expr6 = simse_num_toString(_sm_expr5);
    simse_println((_sm_expr6), stdout);
    _sm_expr7.resize(6);
    __sm_catP = _sm_expr7.data();
    *__sm_catP = (char) ('[');
    __sm_catP = __sm_catP + 1;
    *__sm_catP = (char) ('a');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, "::", 2);
    __sm_catP = __sm_catP + 2;
    *__sm_catP = (char) ('b');
    __sm_catP = __sm_catP + 1;
    *__sm_catP = (char) (']');
    simse_println((_sm_expr7), stdout);
    _sm_expr8.resize(5);
    __sm_catP = _sm_expr8.data();
    *__sm_catP = (char) ('1');
    __sm_catP = __sm_catP + 1;
    *__sm_catP = (char) (',');
    __sm_catP = __sm_catP + 1;
    *__sm_catP = (char) ('2');
    __sm_catP = __sm_catP + 1;
    *__sm_catP = (char) (',');
    __sm_catP = __sm_catP + 1;
    *__sm_catP = (char) ('3');
    simse_println((_sm_expr8), stdout);
    _sm_expr9.resize(2);
    __sm_catP = _sm_expr9.data();
    *__sm_catP = (char) ('x');
    __sm_catP = __sm_catP + 1;
    *__sm_catP = (char) ('y');
    simse_println((_sm_expr9), stdout);
    _sm_base7 = List<Str>{__sm_stringTable[56]};
    _sm_base8 = &_sm_base7;
    _sm_expr10 = fmtStr(__sm_stringTable[4], _sm_base8);
    simse_println((_sm_expr10), stdout);
    _sm_base9 = List<Str>{__sm_stringTable[6]};
    _sm_base10 = &_sm_base9;
    _sm_expr11 = fmtStr(__sm_stringTable[40], _sm_base10);
    simse_println((_sm_expr11), stdout);
    _sm_base11 = __sm_stringTable[53];
    _sm_expr12 = isEmpty(simse_addressOf(_sm_base11));
    simse_println((_sm_expr12), stdout);
    _sm_base12 = __sm_stringTable[58];
    _sm_expr13 = isEmpty(simse_addressOf(_sm_base12));
    simse_println((_sm_expr13), stdout);
    text = __sm_stringTable[54];
    _sm_expr14 = isEmpty(simse_addressOf(text));
    simse_println((_sm_expr14), stdout);
    _sm_expr15 = ns1_Shell{__sm_stringTable[58]};
    _sm_expr16 = ns1_isEmpty(simse_addressOf(_sm_expr15));
    simse_println((_sm_expr16), stdout);
    borrowed = __sm_stringTable[24];
    ptr = &borrowed;
    boxed = makeRef<std::remove_cvref_t<decltype((borrowed))>>(borrowed);
    _sm_expr17 = ns1_mirror(ptr, boxed);
    simse_println((_sm_expr17), stdout);
    _sm_base13 = *(ptr);
    _sm_base14 = *(boxed);
    parts = List<Str>{_sm_base13, _sm_base14, __sm_stringTable[26]};
    _sm_expr18 = parts.size();
    _sm_expr19 = simse_int_toString(_sm_expr18);
    simse_println((_sm_expr19), stdout);
    _sm_base15 = parts[0];
    simse_println((_sm_base15), stdout);
    _sm_base17 = *(ptr);
    _sm_base18 = *(boxed);
    _sm_base16 = List<Str>{_sm_base17, _sm_base18, __sm_stringTable[26]};
    _sm_base19 = &_sm_base16;
    _sm_expr20 = ns1_parcel(__sm_stringTable[23], _sm_base19);
    simse_println((_sm_expr20), stdout);
    return 0;
}
// stress/objects/src/main.kt
Bool ns1_isEmpty(ns1_Shell* self) {
    Str* _sm_base1;
    Bool _sm_expr1;
    _sm_base1 = simse_addressOf(self->text);
    _sm_expr1 = isEmpty(_sm_base1);
    return _sm_expr1;
}
// stress/objects/src/main.kt
Str ns1_describeShapes(Str* self) {
    return (*self);
}
// stress/objects/src/main.kt
Int ns1_area(Int height) {
    Int _sm_expr1;
    _sm_expr1 = 3 * height;
    return _sm_expr1;
}
// stress/objects/src/main.kt
Int ns1_partShapes() {
    Str name, _sm_expr1;
    Int _sm_expr2;
    ns1_Shape _sm_expr3, _sm_expr4;
    Bool _sm_expr5;
    name = __sm_stringTable[35];
    _sm_expr1 = ns1_describeShapes(simse_addressOf(name));
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = ns1_area(4);
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = ns1_Shape::Circle;
    _sm_expr4 = ns1_Shape::Circle;
    _sm_expr5 = _sm_expr3 == _sm_expr4;
    simse_println((_sm_expr5), stdout);
    simse_println(('a'), stdout);
    return 0;
}
// stress/objects/src/main.kt
Attribute ns1_attr(Str name, Str value) {
    Attribute _sm_expr1;
    _sm_expr1 = Attribute(name, value);
    return _sm_expr1;
}
// stress/objects/src/main.kt
List<Attribute> ns1_attrs3(Attribute a, Attribute b, Attribute c) {
    List<Attribute> list;
    list = List<Attribute>();
    simse_list_append(list, a);
    simse_list_append(list, b);
    simse_list_append(list, c);
    return list;
}
// stress/objects/src/main.kt
List<Attribute> ns1_attrs4(Attribute a, Attribute b, Attribute c, Attribute d) {
    List<Attribute> list;
    list = List<Attribute>();
    simse_list_append(list, a);
    simse_list_append(list, b);
    simse_list_append(list, c);
    simse_list_append(list, d);
    return list;
}
// stress/objects/src/main.kt
Array<XmlNode> ns1_noChildren() {
    Array<XmlNode> _sm_expr1;
    _sm_expr1 = Array<XmlNode>();
    return _sm_expr1;
}
// stress/objects/src/main.kt
Array<XmlNode> ns1_oneChild(XmlNode child) {
    List<XmlNode> children;
    Array<XmlNode> _sm_expr1;
    children = List<XmlNode>();
    simse_list_append(children, child);
    _sm_expr1 = simse_list_toArray(children);
    return _sm_expr1;
}
// stress/objects/src/main.kt
Str ns1_escapeText(Str text) {
    Str out;
    Int i, _sm_expr1;
    Bool _sm_expr2;
    Char ch;
    out = Str();
    i = 0;
    L1:;
    _sm_expr1 = text.size();
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    ch = text[i];
    _sm_expr2 = ch == '\\';
    if (_sm_expr2) goto L3;
    goto L4;
    L3:;
    simse_str_append(out, '\\');
    simse_str_append(out, '\\');
    goto L17;
    L4:;
    _sm_expr2 = ch == '\n';
    if (_sm_expr2) goto L6;
    goto L7;
    L6:;
    simse_str_append(out, '\\');
    simse_str_append(out, 'n');
    goto L17;
    L7:;
    _sm_expr2 = ch == '\r';
    if (_sm_expr2) goto L9;
    goto L10;
    L9:;
    simse_str_append(out, '\\');
    simse_str_append(out, 'r');
    goto L17;
    L10:;
    _sm_expr2 = ch == '\t';
    if (_sm_expr2) goto L12;
    goto L13;
    L12:;
    simse_str_append(out, '\\');
    simse_str_append(out, 't');
    goto L17;
    L13:;
    _sm_expr2 = ch == '\'';
    if (_sm_expr2) goto L15;
    goto L16;
    L15:;
    simse_str_append(out, '\\');
    simse_str_append(out, '\'');
    goto L17;
    L16:;
    simse_str_append(out, ch);
    L17:;
    i = i + 1;
    goto L1;
    L2:;
    return out;
}
// stress/objects/src/main.kt
Str ns1_indentation(Int depth) {
    Str out;
    Int i, _sm_expr1;
    Bool _sm_expr2;
    out = Str();
    i = 0;
    L1:;
    _sm_expr1 = depth * 2;
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    simse_str_append(out, ' ');
    i = i + 1;
    goto L1;
    L2:;
    return out;
}
// stress/objects/src/main.kt
Str ns1_dumpNode(XmlNode node, Int depth) {
    char* __sm_catP;
    Int __sm_catAt;
    List<Attribute>* _sm_base1, * _sm_base2;
    Str _sm_base3, _sm_expr1, _sm_expr2, out, _sm_expr8, _sm_expr9;
    XmlNode _sm_base4;
    Int i, _sm_expr3, j, _sm_expr13;
    Bool _sm_expr4;
    Attribute attribute;
    Array<XmlNode> children;
    _sm_expr1 = ns1_indentation(depth);
    _sm_expr2 = node.name;
    out.resize(_sm_expr1.size() + _sm_expr2.size());
    __sm_catP = out.data();
    std::memcpy(__sm_catP, _sm_expr1.data(), _sm_expr1.size());
    __sm_catP = __sm_catP + _sm_expr1.size();
    std::memcpy(__sm_catP, _sm_expr2.data(), _sm_expr2.size());
    i = 0;
    L1:;
    _sm_base1 = simse_addressOf(node.attributes);
    _sm_expr3 = _sm_base1->size();
    _sm_expr4 = i < _sm_expr3;
    if (!(_sm_expr4)) goto L2;
    _sm_base2 = simse_addressOf(node.attributes);
    attribute = (*_sm_base2)[i];
    _sm_expr1.resize(1 + out.size());
    __sm_catP = _sm_expr1.data();
    std::memcpy(__sm_catP, out.data(), out.size());
    __sm_catP = __sm_catP + out.size();
    *__sm_catP = (char) (' ');
    _sm_expr2 = attribute.name;
    _sm_expr8.resize(2 + _sm_expr1.size() + _sm_expr2.size());
    __sm_catP = _sm_expr8.data();
    std::memcpy(__sm_catP, _sm_expr1.data(), _sm_expr1.size());
    __sm_catP = __sm_catP + _sm_expr1.size();
    std::memcpy(__sm_catP, _sm_expr2.data(), _sm_expr2.size());
    __sm_catP = __sm_catP + _sm_expr2.size();
    std::memcpy(__sm_catP, "='", 2);
    _sm_base3 = attribute.value;
    _sm_expr9 = ns1_escapeText(_sm_base3);
    out.resize(1 + _sm_expr8.size() + _sm_expr9.size());
    __sm_catP = out.data();
    std::memcpy(__sm_catP, _sm_expr8.data(), _sm_expr8.size());
    __sm_catP = __sm_catP + _sm_expr8.size();
    std::memcpy(__sm_catP, _sm_expr9.data(), _sm_expr9.size());
    __sm_catP = __sm_catP + _sm_expr9.size();
    *__sm_catP = (char) ('\'');
    i = i + 1;
    goto L1;
    L2:;
    __sm_catAt = out.size();
    out.resize(__sm_catAt + 1);
    __sm_catP = out.data() + __sm_catAt;
    *__sm_catP = (char) ('\n');
    children = node.Children;
    j = 0;
    L3:;
    _sm_expr3 = simse_array_count(children);
    _sm_expr4 = j < _sm_expr3;
    if (!(_sm_expr4)) goto L4;
    _sm_expr13 = depth + 1;
    _sm_base4 = children[j];
    _sm_expr1 = ns1_dumpNode(_sm_base4, _sm_expr13);
    __sm_catAt = out.size();
    out.resize(__sm_catAt + _sm_expr1.size());
    __sm_catP = out.data() + __sm_catAt;
    std::memcpy(__sm_catP, _sm_expr1.data(), _sm_expr1.size());
    j = j + 1;
    goto L3;
    L4:;
    return out;
}
// stress/objects/src/main.kt
Int ns1_partXmlTree() {
    Attribute _sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr7, _sm_expr8, _sm_expr9, _sm_expr10,
        _sm_expr13, _sm_expr14, _sm_expr15, _sm_expr16, _sm_expr19, _sm_expr20, _sm_expr21;
    List<Attribute> _sm_expr5, _sm_expr11, _sm_expr17, _sm_expr22;
    Array<XmlNode> _sm_expr6, _sm_expr12, _sm_expr18, _sm_expr23;
    XmlNode typeNode, fieldNode, dataClassNode, moduleNode;
    Str _sm_expr24;
    _sm_expr1 = ns1_attr(__sm_stringTable[25], __sm_stringTable[2]);
    _sm_expr2 = ns1_attr(__sm_stringTable[27], __sm_stringTable[50]);
    _sm_expr3 = ns1_attr(__sm_stringTable[12], __sm_stringTable[42]);
    _sm_expr4 = ns1_attr(__sm_stringTable[29], __sm_stringTable[34]);
    _sm_expr5 = ns1_attrs4(_sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4);
    _sm_expr6 = ns1_noChildren();
    typeNode = XmlNode(__sm_stringTable[22], _sm_expr5, _sm_expr6);
    _sm_expr7 = ns1_attr(__sm_stringTable[29], __sm_stringTable[55]);
    _sm_expr8 = ns1_attr(__sm_stringTable[16], __sm_stringTable[31]);
    _sm_expr9 = ns1_attr(__sm_stringTable[27], __sm_stringTable[50]);
    _sm_expr10 = ns1_attr(__sm_stringTable[12], __sm_stringTable[41]);
    _sm_expr11 = ns1_attrs4(_sm_expr7, _sm_expr8, _sm_expr9, _sm_expr10);
    _sm_expr12 = ns1_oneChild(typeNode);
    fieldNode = XmlNode(__sm_stringTable[13], _sm_expr11, _sm_expr12);
    _sm_expr13 = ns1_attr(__sm_stringTable[25], __sm_stringTable[3]);
    _sm_expr14 = ns1_attr(__sm_stringTable[27], __sm_stringTable[50]);
    _sm_expr15 = ns1_attr(__sm_stringTable[12], __sm_stringTable[50]);
    _sm_expr16 = ns1_attr(__sm_stringTable[29], __sm_stringTable[21]);
    _sm_expr17 = ns1_attrs4(_sm_expr13, _sm_expr14, _sm_expr15, _sm_expr16);
    _sm_expr18 = ns1_oneChild(fieldNode);
    dataClassNode = XmlNode(__sm_stringTable[3], _sm_expr17, _sm_expr18);
    _sm_expr19 = ns1_attr(__sm_stringTable[25], __sm_stringTable[9]);
    _sm_expr20 = ns1_attr(__sm_stringTable[27], __sm_stringTable[50]);
    _sm_expr21 = ns1_attr(__sm_stringTable[12], __sm_stringTable[50]);
    _sm_expr22 = ns1_attrs3(_sm_expr19, _sm_expr20, _sm_expr21);
    _sm_expr23 = ns1_oneChild(dataClassNode);
    moduleNode = XmlNode(__sm_stringTable[9], _sm_expr22, _sm_expr23);
    _sm_expr24 = ns1_dumpNode(moduleNode, 0);
    simse_print((_sm_expr24), stdout);
    return 0;
}
// stress/objects/src/main.kt
int main() {
    ns1_partCountedReference();
    ns1_partGenerics();
    ns1_partHello();
    ns1_partLambdas();
    ns1_partLanguageTour();
    ns1_partOptionalResult();
    ns1_partPointerPlace();
    ns1_partReceiverShapes();
    ns1_partRtlSimse();
    ns1_partShapes();
    ns1_partXmlTree();
    return 0;
}

// `spanOf(items)`: a span over a list's elements. It borrows the list - the list has
// to outlive the span - and does not copy it (`&items` would box a copy instead).
template <class T>
inline Span<T> simse_spanOf(List<T>* items) {
    return Span<T>(items->data(), items->size());
}

inline Int simse_strView_size(StrView self) {
    return self.len;
}

inline Bool simse_strView_isEmpty(StrView self) {
    return self.len <= 0;
}

// `view.slice(start)`: from `start` to the end (C# `Slice(int)`).
inline StrView simse_strView_slice(StrView self, Int start) {
    return self.slice(start);
}

// `view.slice(start, count)`: `count` bytes from `start` (C# `Slice(int, int)`).
inline StrView simse_strView_slice(StrView self, Int start, Int count) {
    return self.slice(start, count);
}

inline Char simse_strView_charAt(StrView self, Int index) {
    return self[index];
}

// `spanOfStr(text)`: a view over a string's bytes. It borrows the string - the string
// has to outlive the view - and does not copy it (`&text` would box a copy instead).
// `Str` is a `char` buffer on the C++ side and the language's `Char` is a signed byte,
// hence the cast.
inline StrView simse_spanOfStr(Str* text) {
    return StrView(reinterpret_cast<Char*>(text->data()), text->size());
}

// `spanOfStr(view)`: a `StrView` already is a view, so this overload is the identity. It is
// what lets the `when`-over-strings desugar (`Parser.kt`'s `parseWhen`) extract the subject
// with `spanOfStr` without knowing whether it is a `Str` or a `StrView` - the C++ overload
// resolution picks the borrowed view or the identity, and the tests compare against it.
inline StrView simse_spanOfStr(StrView view) {
    return view;
}

template <class T>
inline void simse_list_append(List<T>& self, const std::type_identity_t<T>& value) {
    self.push_back(value);
}

template <class T>
inline List<T> simse_listOf(const List<T>* values) {
    return *values;
}

// Removes the single element at `index`.
template <class T>
inline void simse_list_removeAt(List<T>& self, Int index) {
    self.erase(self.begin() + index);
}

// Removes the half-open range [start, end).
template <class T>
inline void simse_list_removeRange(List<T>& self, Int start, Int end) {
    self.erase(self.begin() + start, self.begin() + end);
}

// `Array<T>.count()`: the element count stored at the front of the block.
template <class T>
inline Int simse_array_count(const Array<T>& self) {
    return self.count();
}

// `List<T>.toArray()` (specs/built-in-types.md): copies the elements into one count-first
// block. Element copies are value copies, like every other copy in the language.
template <class T>
inline Array<T> simse_list_toArray(const List<T>& self) {
    const Int count = self.size();
    if (count <= 0) {
        return Array<T>();
    }
    Array<T> result(count);
    for (Int i = 0; i < count; i++) {
        result[i] = self[i];
    }
    return result;
}

// `Array<T>.toList()`: the growable copy, which is how an element is added to an array.
template <class T>
inline List<T> simse_array_toList(const Array<T>& self) {
    List<T> result;
    const Int count = self.count();
    result.reserve(count);
    for (Int i = 0; i < count; i++) {
        result.push_back(self[i]);
    }
    return result;
}

// `arrayEmpty<T>()`: the shared, zero-length array of `T` (no allocation).
template <class T>
inline Array<T> simse_arrayEmpty() {
    return Array<T>();
}

// `Str.append(ch)`: `Str` has no single-character append, so this is `push_back`.
inline void simse_str_append(Str& self, Char value) {
    self.push_back(static_cast<char>(value));
}

// `Str.appendStr(text)`: appends in place, so an emitter accumulates output without
// `out = out + text` rebuilding the whole buffer on every line (which is quadratic).
inline void simse_str_appendStr(Str& self, const Str& value) {
    self.append(value);
}

// `Str.appendStrPtr(text)`: the same append for a text the caller only *borrows*, so
// nothing is copied on the way.
inline void simse_str_appendStrPtr(Str& self, const Str* value) {
    if (value != nullptr) self.append(*value);
}

// `Str.reserve(count)`: grows the buffer once, so a run of appends writes the text once
// instead of copying the accumulated prefix at every growth step. A *hint*, not a length.
inline void simse_str_reserve(Str& self, Int count) {
    self.reserve((Str::size_type) count);
}

// `Int.toString()`: the scalar-to-inline-string conversion (specs/memory-model.md).
inline Str simse_int_toString(Int self) {
    return std::to_string(self);
}

// `dictionaryOf<K, V>()`: `Dictionary<K, V>` is a value type, so this default-constructs
// one.
template <class K, class V>
inline Dictionary<K, V> simse_dictionaryOf() {
    return Dictionary<K, V>();
}

template <class K, class V>
inline V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return self.valuePtr(key);
}

template <class K, class V>
inline Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    const V* found = simse_dict_getPtr(self, key);
    if (found == nullptr) return Opt<V>::none();
    return Opt<V>::some(*found);
}

template <class K, class V>
inline Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return simse_dict_getPtr(self, key) != nullptr;
}

template <class K, class V>
inline void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                              const std::type_identity_t<V>& value) {
    self.insert_or_assign(key, value);
}

template <class K, class V>
inline void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    self.erase(key);
}

template <class K, class V>
inline Int simse_dict_size(const Dictionary<K, V>& self) {
    return (Int) self.size();
}

template <class K, class V>
inline List<K> simse_dict_keys(const Dictionary<K, V>& self) {
    List<K> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.first);
    return out;
}

template <class K, class V>
inline List<V> simse_dict_values(const Dictionary<K, V>& self) {
    List<V> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.second);
    return out;
}

template <class K, class V>
inline void simse_dict_clear(Dictionary<K, V>& self) {
    self.clear();
}

template <class T>
inline Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value) {
    for (const T& item : self) {
        if (item == value) return true;
    }
    return false;
}

template <class T, class F>
inline void simse_list_sort(List<T>& self, F less) {
    std::sort(self.begin(), self.end(), [&less](const T& a, const T& b) {
        return less(const_cast<T*>(&a), const_cast<T*>(&b));
    });
}

// The powers of ten the bit scan settles its guess against.
static const unsigned long long smStrDigitPow10[20] = {
    1ull, 10ull, 100ull, 1000ull, 10000ull, 100000ull, 1000000ull, 10000000ull,
    100000000ull, 1000000000ull, 10000000000ull, 100000000000ull, 1000000000000ull,
    10000000000000ull, 100000000000000ull, 1000000000000000ull, 10000000000000000ull,
    100000000000000000ull, 1000000000000000000ull, 10000000000000000000ull
};

// The digit count, exact for every width (a narrower integer widens to `Int64` with the same
// digits). `std::bit_width(magnitude)` is the position of the highest set bit plus one - one
// `clz`/`bsr` - and `1233 / 4096 = 0.3010...` is log10(2), so the product is
// floor(log10(magnitude)) or one off; the comparison against that power of ten settles which.
// The early return is the one case the scan cannot answer (`0`), and the sign is a separate
// term, counted on the widened value so `-INT64_MIN` never overflows.
inline Int simse_strCountDigits(Int64 value) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (magnitude < 10ull) {
        return value < 0 ? 2 : 1;
    }
    Int bits = (Int) std::bit_width(magnitude);
    Int guess = (Int) (((unsigned int) bits * 1233u) >> 12);
    Int digits = guess + (magnitude >= smStrDigitPow10[guess] ? 1 : 0);
    return digits + (value < 0 ? 1 : 0);
}

// Two digits per step: the table holds "00".."99", so the inner loop never divides by ten.
struct SmStrDigitPairTable {
    char text[200];
    constexpr SmStrDigitPairTable() : text() {
        for (Int i = 0; i < 100; i = i + 1) {
            text[i * 2] = (char) ('0' + i / 10);
            text[i * 2 + 1] = (char) ('0' + i % 10);
        }
    }
};

static constexpr SmStrDigitPairTable smStrDigitPairs{};

// The digits of `value`, written straight into the `count` bytes `target` already owns and
// walking *back* through them (the least-significant pair first), so no second buffer and no
// second pass is needed. `count` must be exact - `simse_strCountDigits`'s answer, sign
// included - because the slots of the parts around this one depend on it.
inline void simse_strAddInt(char* target, Int64 value, Int count) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (value < 0) {
        target[0] = '-';
        count = count - 1;
        target = target + 1;
    }
    while (count >= 2) {
        unsigned int pair = (unsigned int) (magnitude % 100ull);
        magnitude /= 100ull;
        count = count - 2;
        target[count] = smStrDigitPairs.text[pair * 2];
        target[count + 1] = smStrDigitPairs.text[pair * 2 + 1];
    }
    if (count == 1) {
        target[0] = (char) ('0' + (Int) magnitude);
    }
}

// The two texts a bool can be, as a `StrView` over a two-entry table - the string-table shape,
// so a bool part is just another text part (a `memcpy` of a runtime length) and needs no digits
// of its own. Cold enough that the two loads the compiler folds it to do not matter.
inline StrView simse_strBoolView(Bool value) {
    static Char texts[2][6] = {"true", "false"};
    static Int lens[2] = {4, 5};
    Int at = value ? 0 : 1;
    return StrView(texts[at], lens[at]);
}

// `Str.isEmpty()` is the prelude's own body (cppsrc/rtl/rtl.kt), not a resource: `size()`
// is the built-in it needs. This one is the shared space test the `Char` predicate below
// uses too.
inline Bool simse_str_isSpaceByte(Char ch) {
    return ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r';
}

inline Char simse_str_charAt(const Str& self, Int index) {
    return (Char) self[index];
}

inline Str simse_str_trim(const Str& self) {
    Int begin = 0;
    Int end = self.size();
    while (begin < end && simse_str_isSpaceByte((Char) self[begin])) begin++;
    while (end > begin && simse_str_isSpaceByte((Char) self[end - 1])) end--;
    return self.substr(begin, end - begin);
}

inline List<Str> simse_str_split(const Str& self, const Str& separator) {
    List<Str> parts;
    if (separator.empty()) {
        parts.push_back(self);
        return parts;
    }
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + separator.size();
    }
    return parts;
}

// How many bytes of `self` are `ch`: what the byte-separator split reserves up front.
inline Int simse_count_char_in_str(const Str* self, char ch) {
    Int count = 0;
    const char* data = self->data();
    Int len = self->size();
    for (Int i = 0; i < len; i++) {
        if (data[i] == ch) {
            count++;
        }
    }
    return count;
}

inline List<Str> simse_str_split(const Str& self, Char separator) {
    List<Str> parts;
    parts.reserve(simse_count_char_in_str(&self, separator));
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + 1;
    }
    return parts;
}

inline Str simse_str_toUpper(const Str& self) {
    Str result = self;
    for (char& ch : result) {
        if (ch >= 'a' && ch <= 'z') ch = (char) (ch - 'a' + 'A');
    }
    return result;
}

inline Str simse_str_toLower(const Str& self) {
    Str result = self;
    for (char& ch : result) {
        if (ch >= 'A' && ch <= 'Z') ch = (char) (ch - 'A' + 'a');
    }
    return result;
}

inline Int simse_str_find(const Str& self, const Str& sub) {
    Int found = self.find(sub);
    return found == Str::npos ? -1 : found;
}

inline Int simse_str_lastIndexOf(const Str& self, const Str& sub) {
    Int found = self.rfind(sub);
    return found == Str::npos ? -1 : found;
}

inline Str simse_str_substr(const Str& self, Int start, Int len) {
    if (start < 0) start = 0;
    if (start > self.size()) start = self.size();
    Str result = self.substr(start);
    if (len >= 0 && len < result.size()) result.resize(len);
    return result;
}

inline Bool simse_str_startsWith(const Str& self, const Str& prefix) {
    return prefix.size() <= self.size() && self.compare(0, prefix.size(), prefix) == 0;
}

inline Bool simse_str_endsWith(const Str& self, const Str& suffix) {
    return suffix.size() <= self.size()
           && self.compare(self.size() - suffix.size(), suffix.size(), suffix) == 0;
}

inline Str simse_str_replace(const Str& self, const Str& from, const Str& to) {
    if (from.empty()) return self;
    Str result;
    Int pos = 0;
    while (true) {
        Int found = self.find(from, pos);
        if (found == Str::npos) {
            result.append(self, pos, Str::npos);
            break;
        }
        result.append(self, pos, found - pos);
        result += to;
        pos = found + from.size();
    }
    return result;
}

inline Opt<Int> simse_str_toInt(const Str& self) {
    if (self.empty()) return Opt<Int>::none();
    Int value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Int>::none();
    return Opt<Int>::some(value);
}

inline Opt<Float64> simse_str_toFloat(const Str& self) {
    if (self.empty()) return Opt<Float64>::none();
    Float64 value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Float64>::none();
    return Opt<Float64>::some(value);
}

inline Bool simse_char_isDigit(Char self) {
    return self >= '0' && self <= '9';
}

inline Bool simse_char_isAlpha(Char self) {
    return (self >= 'a' && self <= 'z') || (self >= 'A' && self <= 'Z');
}

inline Bool simse_char_isAlphaOrDigit(Char self) {
    return simse_char_isAlpha(self) || simse_char_isDigit(self);
}

inline Bool simse_char_isSpace(Char self) {
    return simse_str_isSpaceByte(self);
}

template <class T>
inline Str simse_num_toString(const T& self) {
    return std::to_string(self);
}

inline Str simse_char_toString(Char self) {
    return std::to_string((int) self);
}

inline Str simse_bool_toString(Bool self) {
    return self ? "true" : "false";
}

// Expands one run-length encoded series into `out`, which holds `count` values.
template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; // stream[0] is the series' own length
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

// Fills `table` from the pool and the two expanded series: an offset increment and a
// byte count per entry, both rebuilt by subtracting the stored value from the one before.
inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  // this entry's offset increment, rebuilt from the start series
    Int length = 0; // this entry's byte count, rebuilt from the length series
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = StrView(bytes + at, length);
    }
}

// The three monotonic clocks. `steady_clock` is the one clock the standard library
// promises cannot go backwards, which is what makes a duration between two readings
// meaningful (`impl_specs/profiling.md`).
Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

Int64 simse_nowNanos() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
}

// The `simse_write` overloads and the two printers are all inline in the forward block: nothing
// here.
