// Generated by the Simse compiler. Do not edit.
#include "cppsrc/rtl/simse.hpp"
#include <type_traits>

// The string-literal pool's decoder (impl_specs/rtl-abi.md, "String literals: one
// table"): the emitter writes one pool of bytes plus two run-length encoded index
// series - where each entry starts and how long it is - and this expands them into the
// `StrView` per entry, once, before `main` runs. It was cppsrc/rtl/strtable.hpp.
//
// Six things are deliberate in the shape the emitter writes:
//
//  - **Both series are stored as "what to subtract from the previous value"**, with an
//    implicit 0 before the first entry: `value[i] = value[i-1] - series[i]`. The
//    literals are ordered longest first, so a length series descends slowly and a
//    *difference* of it is a small number - mostly 0 between the many literals of equal
//    length (85% of them on the compiler's own table).
//  - **Each series is run-length encoded**: its length first, then alternating blocks of
//    non-repeating values (a count, then that many values) and of runs (a count, then
//    that many `times, value` pairs), until the length is filled. The element type is a
//    template parameter because the emitter picks the width: `Int16` when every number
//    fits, `Int` otherwise.
//  - The pool is the literal texts themselves, adjacent, so the C++ compiler decodes
//    every escape and the emitter's decoding only has to agree about *how many bytes* an
//    escape costs. The emitted `static_assert` on the pool's `sizeof` is the check.
//  - The series are expanded into *stack* arrays in the initializer and dropped when it
//    returns: no heap, and the encoded statics are all the program carries.
//  - An entry is a 12-byte `StrView`, not the 32-byte owning `Str` the table used to
//    hold, and start-up allocates nothing for the literals.
//  - The pool is `const char` (a string literal, read-only) while `StrView` holds the
//    language's mutable `Char*`; the constness is cast away here, in the one place the
//    pool is touched, and nothing writes through it.

template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count);

#include <chrono>

// Time natives (the Simse surface is the prelude file cppsrc/rtl/rtl.kt). All three are
// monotonic clocks - never going backwards - since an arbitrary fixed point:
// `simse_nowMillis` for logging, and the finer `simse_nowMicros` / `simse_nowNanos` for
// the instrumented profiler (`cppsrc/profiling`, and the emitted `profileApp.measure(...)`
// of a `--profile` build; `--profile-nanos` picks the nanosecond clock). It was
// cppsrc/rtl/timeops.hpp, and its definitions were the last
// thing left in cppsrc/rtl/native.cpp - they are this section's now, so the clock is
// emitted into the program like any other prelude body and there is nothing to link.
// `emit: always`
// because the profiler's runtime is emitted by the *compiler* rather than named by
// the program: a `--profile` build needs these declarations whether or not the program
// ever asks for the time.
Int64 simse_nowMillis();
Int64 simse_nowMicros();
Int64 simse_nowNanos();

// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 22;
static const char __sm_stringPool[] =
    "name:value" "static" "alpha" "three" "beta" "name" "hey" "one" "two" "val" "var" "]=" " " ":" "=" "[" "a" "b" "c" "k" "z" "" 
;
static const Int16 __sm_stringStarts[] = {22,8,0,-10,4,1,0,1,0,1,3,4,0,2,1,8,0};
static const Int16 __sm_stringLens[] = {22,7,-10,4,1,0,1,0,1,3,4,0,2,1,8,0,1,1};
static_assert(sizeof(__sm_stringPool) - 1 == 60, "the string pool and its length index disagree");
static StrView __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

// `spanOf(items)`: a span over a list's elements, generated (`cppsrc/rtl/_res.md`).
template <class T>
Span<T> simse_spanOf(List<T>* items);

// What a view's byte operations still need from C++ (specs/built-in-types.md, "Views").
// The byte work itself - `find`/`indexOf`, `startsWith`/`startsWithPtr`, `substr`/`toString`
// - is Simse now, in cppsrc/rtl/StrView.kt over the span and the intrinsics
// (cppsrc/rtl/intrinsics.kt). What remains here is the `Span` member passthroughs, which
// cannot be Simse without shadowing the member they call, and `spanOfStr`, whose two
// overloads are picked by C++ overload resolution at the desugar's site (Parser.kt's
// `parseWhen`) rather than by a declaration - so a declaration reaches this section, and a
// program that calls one pays for this text (`sourcegen/ResGen.kt`).
//
// `StrView` *is* a `Span<Char>`, so `self.len`, `self[i]` and `self.slice(...)` below are
// the span's own members (cppsrc/rtl/span.hpp) - and `at` is *not* an operation of its
// own: the span's member serves it (cppsrc/rtl/StrView.kt), as `atPtr` is the
// language's (cppsrc/rtl/Span.kt).
Int simse_strView_size(StrView self);
Bool simse_strView_isEmpty(StrView self);
StrView simse_strView_slice(StrView self, Int start);
StrView simse_strView_slice(StrView self, Int start, Int count);
Char simse_strView_charAt(StrView self, Int index);
StrView simse_spanOfStr(Str* text);
StrView simse_spanOfStr(StrView view);

#include <cstdint>
#include <type_traits>

// The List/Array/Str primitives behind the prelude (impl_specs/native-interop.md), moved
// out of cppsrc/rtl/listops.hpp. Index and range errors are unchecked, matching the
// language's no-exceptions policy: `removeAt`/`removeRange` with an out-of-range index is
// undefined behavior (specs/language-decisions.md).

// Appends `value` to the end of `self`. The value is a non-deduced context so a literal
// argument (e.g. a `const char[]`) converts to the element type instead of making `T`
// ambiguous.
template <class T>
void simse_list_append(List<T>& self, const std::type_identity_t<T>& value);

// The list literal's fallback (cppsrc/rtl/rtl.kt): the compiler turns
// `listOf<Str>("a", "b")` into the construction itself, so this runs only for a position
// with no destination slot.
template <class T>
List<T> simse_listOf(const List<T>* values);

template <class T>
void simse_list_removeAt(List<T>& self, Int index);
template <class T>
void simse_list_removeRange(List<T>& self, Int start, Int end);
template <class T>
Int simse_array_count(const Array<T>& self);
template <class T>
Array<T> simse_list_toArray(const List<T>& self);
template <class T>
List<T> simse_array_toList(const Array<T>& self);
template <class T>
Array<T> simse_arrayEmpty();

void simse_str_append(Str& self, Char value);
void simse_str_appendStr(Str& self, const Str& value);
void simse_str_appendStrPtr(Str& self, const Str* value);
void simse_str_reserve(Str& self, Int count);
Str simse_int_toString(Int self);

#include <algorithm>
#include <type_traits>
#include <utility>

// The Dictionary operations and the extra List helpers behind the prelude
// (impl_specs/native-interop.md), moved out of cppsrc/rtl/dictops.hpp. The key/value
// parameters are non-deduced (`std::type_identity_t`) so that a literal argument (e.g. a
// `const char[]` key or an integer value) converts to the element type instead of making
// the template argument ambiguous.
//
// Errors are unchecked, matching the dictionary's own semantics and the language's
// no-exceptions policy: `get`/`has` on a missing key behave as documented, while `remove`
// of an absent key is a no-op.

// `dictionaryOf<K, V>()`: the empty-dictionary construction.
template <class K, class V>
Dictionary<K, V> simse_dictionaryOf();

// `d.getPtr(key)`: the value's place in the dictionary, or `null` when the key is
// absent - the read that copies nothing (`get` copies the value out, `has` is this with
// the pointer tested). The place is the dictionary's own storage, so it is valid until
// the next `insert`/`remove`/`clear` on that dictionary.
template <class K, class V>
V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.get(key)`: the value for `key`, or an empty `Opt` when absent.
template <class K, class V>
Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.has(key)`: whether `key` is present.
template <class K, class V>
Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.insert(key, value)`: insert or replace.
template <class K, class V>
void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                       const std::type_identity_t<V>& value);

// `d.remove(key)`: erase when present (a no-op otherwise).
template <class K, class V>
void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.size()`: the number of entries.
template <class K, class V>
Int simse_dict_size(const Dictionary<K, V>& self);

// `d.keys()`: the keys in the dictionary's iteration order (unspecified; sort for a
// deterministic order).
template <class K, class V>
List<K> simse_dict_keys(const Dictionary<K, V>& self);

// `d.values()`: the values in the dictionary's iteration order (unspecified).
template <class K, class V>
List<V> simse_dict_values(const Dictionary<K, V>& self);

// `d.clear()`: remove every entry.
template <class K, class V>
void simse_dict_clear(Dictionary<K, V>& self);

// `items.contains(value)`: linear membership test (`operator==` on elements).
template <class T>
Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value);

// `items.sort(less)`: in-place sort using the `(*T, *T) -> Bool` comparator. The comparator
// comes from a Simse lambda (a C++ lambda or Func), so it is a template parameter rather
// than a fixed type; it takes its two elements by pointer, so each is read where `std::sort`
// holds it instead of being copied into the comparison.
template <class T, class F>
void simse_list_sort(List<T>& self, F less);

// `lenOf(x)`: one read-only length operation, declared `data` in the prelude
// (cppsrc/rtl/rtl.kt) so that a repeated call on an unchanged value is one call
// (cppsrc/linear/ReusePure.kt) and a borrow proof may call it (cppsrc/parser/BorrowParams.kt).
// `Str` and `List` are heavy values, so the receiver is taken by reference - a by-value
// parameter would copy one per call. The containers whose count a declaration already spells
// (`Array.count`, `Dictionary.size`, `StrView.size`) keep those declarations; this is the
// operation for the two the language cannot otherwise spell.
Int simse_lenOf(const Str& self);
template <class T, int N>
Int simse_lenOf(const SmallVector<T, N>& self);

#include <bit>
#include <cstring>

// The primitives a concatenation is *expanded* into (impl_specs/linear-il.md, "Concat").
// There is no `cat` function and no per-part `append`: the emitter computes every part's
// *exact* length, performs one `resize`, and then writes each part straight into the slot it
// owns while one `char*` advances by that part's length. So a chain of n parts touches the
// allocator once, computes each part once and copies each part once - the shape Java 9's
// `StringConcatFactory` has, with the C++ compiler seeing the straight-line form instead of a
// variadic call.
//
// No program names these: the emitter writes the symbols itself, the way it writes
// `simse_addressOf`. What each kind of part costs:
//   * a text part (a `Str`, or a literal whose length the lowering already knows) is a
//     `std::memcpy` - a constant size is one register or vector store, a runtime `Str` size
//     one call;
//   * an integer (`Int8`/`Int16`/`Int32`/`Int64`, `Int`) is *counted* by the bit scan below
//     (`std::bit_width` plus one power-of-ten comparison, never a division loop) and *written*
//     by `simse_strAddInt` - two digits per step out of a table, right to left inside the slot
//     that was made for it, so the digits are never built into a second buffer;
//   * a `Char` is one byte;
//   * a `Bool` is a `StrView` over a two-entry table ("true"/"false"): it has no digits to
//     render and is not a hot path, so it goes through the text path.
// A float is deliberately *absent*: its length is only known by formatting it, so the lowering
// keeps the `toString()` call (one `Str`, made ahead of time) and the part *is* that `Str` -
// one conversion, not one for the length and another for the write.
Int simse_strCountDigits(Int64 value);
void simse_strAddInt(char* target, Int64 value, Int count);
StrView simse_strBoolView(Bool value);

#include <charconv>
#include <cstddef>
#include <system_error>

// The string, character, numeric-conversion and min/max operations behind the prelude
// (impl_specs/native-interop.md, specs/built-in-types.md), moved out of
// cppsrc/rtl/strops.hpp.
//
// `Str` is the inline `SmString` (smstring.hpp): every size, length and index here is the
// language's `Int` (`int32_t`), including `Str::npos`, which is `-1`. Index/range errors
// are unchecked where the underlying operation is unchecked; the `Opt`-returning
// conversions never throw.
//
// What is only a byte loop is Simse now (cppsrc/rtl/rtl.kt: `trim`, `substr`,
// `startsWith`/`endsWith`, case folding and the `Char` predicates); what stays is what
// reaches `SmString` internals (`charAt`, `find`, `lastIndexOf`, `split`, `replace`) or the
// standard library (`std::from_chars`, `std::to_string`).

// `Str.charAt(index)`: the byte at `index` (unchecked; no bounds test).
Char simse_str_charAt(const Str& self, Int index);

// `Str.split(separator)` splits on every occurrence. An empty separator returns the whole
// string as a single element. Two overloads: a separator string and a separator byte.
List<Str> simse_str_split(const Str& self, const Str& separator);
List<Str> simse_str_split(const Str& self, Char separator);

// `Str.find(sub)` returns the first index of `sub`, or -1 when absent (the language's
// spelling of C++ `npos`).
Int simse_str_find(const Str& self, const Str& sub);

// `Str.lastIndexOf(sub)` returns the last index of `sub`, or -1 when absent.
Int simse_str_lastIndexOf(const Str& self, const Str& sub);

// `Str.replace(from, to)` replaces every occurrence of `from` with `to`.
Str simse_str_replace(const Str& self, const Str& from, const Str& to);

// `Str.toInt()`/`Str.toFloat()` parse the whole string; failure (or a non-empty trailing
// remainder) yields `Opt.none()`. No exceptions: `std::from_chars` reports errors through
// its return value.
Opt<Int> simse_str_toInt(const Str& self);
Opt<Float64> simse_str_toFloat(const Str& self);

// `Str.initByValue(value)`: the `initByValue` convention for `Str` (cppsrc/rtl/rtl.kt),
// setting the receiver in place. The empty form is a Simse method (an empty body).
void simse_str_initByValue(Str& self, const Str& value);

// `Char` is a signed 8-bit integer; the checks are byte-range tests so they do not depend
// on the C locale. Space, tab, newline and carriage return count as space; form feed and
// vertical tab do not. They stay here because a body would emit a `Char* self` receiver (a
// `Char` is a scalar) while the call sites and the `CharPredicate` function values need the
// byte by value.
Bool simse_char_isDigit(Char self);
Bool simse_char_isAlpha(Char self);
Bool simse_char_isAlphaOrDigit(Char self);
Bool simse_char_isSpace(Char self);

// Numeric conversions. `Char` is an 8-bit integer, so it stringifies as a number.
template <class T>
Str simse_num_toString(const T& self);
Str simse_char_toString(Char self);
Str simse_bool_toString(Bool self);

#include <cstdio>

// `print` / `println` in C, not C++ streams. The language's formatting is its own (`fmtStr`), and
// a value is one `fwrite`/`fputs`, so a program that prints never pulls in <iostream> - and with
// it the standard streams' static construction and the locale facets that drag in. One overload
// per built-in `println` accepts, so a call spells the same whatever it prints; `bool` prints
// `true`/`false`, which is what the `std::boolalpha` the emitter used to write gave.
inline void simse_write(const Str& value, FILE* out) {
    std::fwrite(value.data(), 1, (std::size_t) value.size(), out);
}

inline void simse_write(StrView value, FILE* out) {
    std::fwrite(value.ptr, 1, (std::size_t) value.len, out);
}

inline void simse_write(bool value, FILE* out) {
    std::fputs(value ? "true" : "false", out);
}

inline void simse_write(char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(signed char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(unsigned char value, FILE* out) {
    std::fputc((int) value, out);
}

inline void simse_write(short value, FILE* out) {
    std::fprintf(out, "%d", (int) value);
}

inline void simse_write(int value, FILE* out) {
    std::fprintf(out, "%d", value);
}

inline void simse_write(long value, FILE* out) {
    std::fprintf(out, "%ld", value);
}

inline void simse_write(long long value, FILE* out) {
    std::fprintf(out, "%lld", value);
}

inline void simse_write(float value, FILE* out) {
    std::fprintf(out, "%g", (double) value);
}

inline void simse_write(double value, FILE* out) {
    std::fprintf(out, "%g", value);
}

template <class T>
inline void simse_print(const T& value, FILE* out) {
    simse_write(value, out);
}

template <class T>
inline void simse_println(const T& value, FILE* out) {
    simse_write(value, out);
    std::fputc('\n', out);
}

struct ns1_Point;
struct ns1_Cell;
// stress/collections/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Point {
    Int x;
    Int y;
};
SIMSE_PACK_POP
// stress/collections/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Cell {
    Int value;
};
SIMSE_PACK_POP
// stress/collections/src/main.kt
using ns1_Taker = Func<void(Int)>;

template <class T>
T* atPtr(Span<T>* self, Int index);
Bool startsWith(StrView* self, Str text);
Int find(StrView* self, Str sub);
Str substr(StrView* self, Int from, Int count);
Str toString(StrView* self);
template <class T>
struct List_iter_yieldable {
    Int branch{};
    T current{};
    List<T>* _sm_self{};
    Int i{};
    Int len{};
    Bool advance() {
        Bool _sm_base1, _sm_base3, _sm_expr1;
        Int _sm_base2, _sm_base4, _sm_base5, _sm_base7, _sm_base8, _sm_base10, _sm_base11, _sm_base12;
        List<T>* _sm_base6, * _sm_base9;
        T _sm_expr2;
        _sm_base2 = this->branch;
        _sm_base1 = _sm_base2 == -1;
        if (_sm_base1) goto L2;
        _sm_base4 = this->branch;
        _sm_base3 = _sm_base4 == 1;
        if (_sm_base3) goto LY1;
        this->i = 0;
        _sm_base6 = this->_sm_self;
        _sm_base5 = simse_lenOf((*_sm_base6));
        this->len = _sm_base5;
        L1:;
        _sm_base7 = this->i;
        _sm_base8 = this->len;
        _sm_expr1 = _sm_base7 < _sm_base8;
        if (!(_sm_expr1)) goto L2;
        _sm_base9 = this->_sm_self;
        _sm_base10 = this->i;
        _sm_expr2 = (*_sm_base9)[_sm_base10];
        this->current = _sm_expr2;
        this->branch = 1;
        return true;
        LY1:;
        _sm_base12 = this->i;
        _sm_base11 = _sm_base12 + 1;
        this->i = _sm_base11;
        goto L1;
        L2:;
        this->branch = -1;
        return false;
    }
};

template <class T>
List_iter_yieldable<T> iter(List<T>* self);
template <class T>
struct Array_iter_yieldable {
    Int branch{};
    T current{};
    Array<T>* _sm_self{};
    Int i{};
    Int len{};
    Bool advance() {
        Bool _sm_base1, _sm_base3, _sm_expr1;
        Int _sm_base2, _sm_base4, _sm_base5, _sm_base7, _sm_base8, _sm_base10, _sm_base11, _sm_base12;
        Array<T>* _sm_base6, * _sm_base9;
        T _sm_expr2;
        _sm_base2 = this->branch;
        _sm_base1 = _sm_base2 == -1;
        if (_sm_base1) goto L2;
        _sm_base4 = this->branch;
        _sm_base3 = _sm_base4 == 1;
        if (_sm_base3) goto LY1;
        this->i = 0;
        _sm_base6 = this->_sm_self;
        _sm_base5 = simse_array_count((*_sm_base6));
        this->len = _sm_base5;
        L1:;
        _sm_base7 = this->i;
        _sm_base8 = this->len;
        _sm_expr1 = _sm_base7 < _sm_base8;
        if (!(_sm_expr1)) goto L2;
        _sm_base9 = this->_sm_self;
        _sm_base10 = this->i;
        _sm_expr2 = (*_sm_base9)[_sm_base10];
        this->current = _sm_expr2;
        this->branch = 1;
        return true;
        LY1:;
        _sm_base12 = this->i;
        _sm_base11 = _sm_base12 + 1;
        this->i = _sm_base11;
        goto L1;
        L2:;
        this->branch = -1;
        return false;
    }
};

template <class T>
Array_iter_yieldable<T> iter(Array<T>* self);
template <class T>
struct Span_iter_yieldable {
    Int branch{};
    T current{};
    Span<T>* _sm_self{};
    Int i{};
    Int len{};
    Bool advance() {
        Bool _sm_base1, _sm_base3, _sm_expr1;
        Int _sm_base2, _sm_base4, _sm_base5, _sm_base7, _sm_base8, _sm_base10, _sm_base11, _sm_base12;
        Span<T>* _sm_base6, * _sm_base9;
        T _sm_expr2;
        _sm_base2 = this->branch;
        _sm_base1 = _sm_base2 == -1;
        if (_sm_base1) goto L2;
        _sm_base4 = this->branch;
        _sm_base3 = _sm_base4 == 1;
        if (_sm_base3) goto LY1;
        this->i = 0;
        _sm_base6 = this->_sm_self;
        _sm_base5 = _sm_base6->size();
        this->len = _sm_base5;
        L1:;
        _sm_base7 = this->i;
        _sm_base8 = this->len;
        _sm_expr1 = _sm_base7 < _sm_base8;
        if (!(_sm_expr1)) goto L2;
        _sm_base9 = this->_sm_self;
        _sm_base10 = this->i;
        _sm_expr2 = (*_sm_base9)[_sm_base10];
        this->current = _sm_expr2;
        this->branch = 1;
        return true;
        LY1:;
        _sm_base12 = this->i;
        _sm_base11 = _sm_base12 + 1;
        this->i = _sm_base11;
        goto L1;
        L2:;
        this->branch = -1;
        return false;
    }
};

template <class T>
Span_iter_yieldable<T> iter(Span<T>* self);
template <class T>
struct List_iterPtr_yieldable {
    Int branch{};
    T* current{};
    List<T>* _sm_self{};
    Int i{};
    Int len{};
    Bool advance() {
        Bool _sm_base1, _sm_base3, _sm_expr1;
        Int _sm_base2, _sm_base4, _sm_base5, _sm_base7, _sm_base8, _sm_base11, _sm_base12, _sm_base13;
        List<T>* _sm_base6, * _sm_base10;
        T* _sm_base9, * _sm_expr2;
        _sm_base2 = this->branch;
        _sm_base1 = _sm_base2 == -1;
        if (_sm_base1) goto L2;
        _sm_base4 = this->branch;
        _sm_base3 = _sm_base4 == 1;
        if (_sm_base3) goto LY1;
        this->i = 0;
        _sm_base6 = this->_sm_self;
        _sm_base5 = simse_lenOf((*_sm_base6));
        this->len = _sm_base5;
        L1:;
        _sm_base7 = this->i;
        _sm_base8 = this->len;
        _sm_expr1 = _sm_base7 < _sm_base8;
        if (!(_sm_expr1)) goto L2;
        _sm_base10 = this->_sm_self;
        _sm_base11 = this->i;
        _sm_base9 = simse_addressOf((*_sm_base10)[_sm_base11]);
        _sm_expr2 = _sm_base9;
        this->current = _sm_expr2;
        this->branch = 1;
        return true;
        LY1:;
        _sm_base13 = this->i;
        _sm_base12 = _sm_base13 + 1;
        this->i = _sm_base12;
        goto L1;
        L2:;
        this->branch = -1;
        return false;
    }
};

template <class T>
List_iterPtr_yieldable<T> iterPtr(List<T>* self);
template <class T>
struct Array_iterPtr_yieldable {
    Int branch{};
    T* current{};
    Array<T>* _sm_self{};
    Int i{};
    Int len{};
    Bool advance() {
        Bool _sm_base1, _sm_base3, _sm_expr1;
        Int _sm_base2, _sm_base4, _sm_base5, _sm_base7, _sm_base8, _sm_base11, _sm_base12, _sm_base13;
        Array<T>* _sm_base6, * _sm_base10;
        T* _sm_base9, * _sm_expr2;
        _sm_base2 = this->branch;
        _sm_base1 = _sm_base2 == -1;
        if (_sm_base1) goto L2;
        _sm_base4 = this->branch;
        _sm_base3 = _sm_base4 == 1;
        if (_sm_base3) goto LY1;
        this->i = 0;
        _sm_base6 = this->_sm_self;
        _sm_base5 = simse_array_count((*_sm_base6));
        this->len = _sm_base5;
        L1:;
        _sm_base7 = this->i;
        _sm_base8 = this->len;
        _sm_expr1 = _sm_base7 < _sm_base8;
        if (!(_sm_expr1)) goto L2;
        _sm_base10 = this->_sm_self;
        _sm_base11 = this->i;
        _sm_base9 = simse_addressOf((*_sm_base10)[_sm_base11]);
        _sm_expr2 = _sm_base9;
        this->current = _sm_expr2;
        this->branch = 1;
        return true;
        LY1:;
        _sm_base13 = this->i;
        _sm_base12 = _sm_base13 + 1;
        this->i = _sm_base12;
        goto L1;
        L2:;
        this->branch = -1;
        return false;
    }
};

template <class T>
Array_iterPtr_yieldable<T> iterPtr(Array<T>* self);
template <class T>
struct Span_iterPtr_yieldable {
    Int branch{};
    T* current{};
    Span<T>* _sm_self{};
    Int i{};
    Int len{};
    Bool advance() {
        Bool _sm_base1, _sm_base3, _sm_expr1;
        Int _sm_base2, _sm_base4, _sm_base5, _sm_base7, _sm_base8, _sm_base11, _sm_base12, _sm_base13;
        Span<T>* _sm_base6, * _sm_base10;
        T* _sm_base9, * _sm_expr2;
        _sm_base2 = this->branch;
        _sm_base1 = _sm_base2 == -1;
        if (_sm_base1) goto L2;
        _sm_base4 = this->branch;
        _sm_base3 = _sm_base4 == 1;
        if (_sm_base3) goto LY1;
        this->i = 0;
        _sm_base6 = this->_sm_self;
        _sm_base5 = _sm_base6->size();
        this->len = _sm_base5;
        L1:;
        _sm_base7 = this->i;
        _sm_base8 = this->len;
        _sm_expr1 = _sm_base7 < _sm_base8;
        if (!(_sm_expr1)) goto L2;
        _sm_base10 = this->_sm_self;
        _sm_base11 = this->i;
        _sm_base9 = simse_addressOf((*_sm_base10)[_sm_base11]);
        _sm_expr2 = _sm_base9;
        this->current = _sm_expr2;
        this->branch = 1;
        return true;
        LY1:;
        _sm_base13 = this->i;
        _sm_base12 = _sm_base13 + 1;
        this->i = _sm_base12;
        goto L1;
        L2:;
        this->branch = -1;
        return false;
    }
};

template <class T>
Span_iterPtr_yieldable<T> iterPtr(Span<T>* self);
Bool compareLessThan(Str* left, Str* right);
Str substr(Str* self, Int start, Int len);
Bool startsWith(Str* self, Str prefix);
Bool isEmpty(Str* self);
List<Str> ns1_texts();
Int ns1_partArrayLayout();
Int ns1_partBulkList();
Int ns1_partContainers();
Int ns1_partDictionary();
Int ns1_arraySum(List<Int>* items);
Int ns1_spanSum(List<Int>* items);
Int ns1_partForArray();
Int ns1_total(List<Int>* items);
Int ns1_partForContainer();
Int ns1_bump(List<ns1_Cell>* cells);
void ns1_report(List<ns1_Cell>* cells);
Int ns1_arrayBump(List<ns1_Cell>* items);
Int ns1_spanSumPointer(List<Int>* items);
Int ns1_partForPointer();
// stress/collections/src/main.kt
struct ns1_List_everyNth_yieldable {
    Int branch{};
    Int current{};
    List<Int>* _sm_self{};
    Int step{};
    Int i{};
    Bool advance() {
        Bool _sm_base1, _sm_base3, _sm_expr2;
        Int _sm_base2, _sm_base4, _sm_base6, _sm_base8, _sm_base9, _sm_base10, _sm_base11, _sm_expr1;
        List<Int>* _sm_base5, * _sm_base7;
        _sm_base2 = this->branch;
        _sm_base1 = _sm_base2 == -1;
        if (_sm_base1) goto L2;
        _sm_base4 = this->branch;
        _sm_base3 = _sm_base4 == 1;
        if (_sm_base3) goto LY1;
        this->i = 0;
        L1:;
        _sm_base5 = this->_sm_self;
        _sm_expr1 = simse_lenOf((*_sm_base5));
        _sm_base6 = this->i;
        _sm_expr2 = _sm_base6 < _sm_expr1;
        if (!(_sm_expr2)) goto L2;
        _sm_base7 = this->_sm_self;
        _sm_base8 = this->i;
        _sm_expr1 = (*_sm_base7)[_sm_base8];
        this->current = _sm_expr1;
        this->branch = 1;
        return true;
        LY1:;
        _sm_base10 = this->i;
        _sm_base11 = this->step;
        _sm_base9 = _sm_base10 + _sm_base11;
        this->i = _sm_base9;
        goto L1;
        L2:;
        this->branch = -1;
        return false;
    }
};

ns1_List_everyNth_yieldable ns1_everyNth(List<Int>* self, Int step);
Int ns1_partLambdaFor();
Int ns1_addAll(List<Int>* values);
Int ns1_sumValues(List<Int> values);
Int ns1_countBoxed(Ref<List<Int>> values);
Str ns1_format(Str shape, List<Str>* items);
Int ns1_count(List<Str>* values);
Int ns1_partPackArgs();
Int ns1_sum(List<Int>* items);
Int ns1_tailSum(List<Int>* items);
Int ns1_middleSum(List<Int>* items);
Str ns1_afterColon(Str text);
void ns1_bumpSpan(Span<Int> span);
Char* ns1_headByte(Str* text);
Int ns1_partSpan();

template <class T>
T* atPtr(Span<T>* self, Int index) {
    T* _sm_base1, * _sm_expr1;
    _sm_base1 = simse_addressOf((*self)[index]);
    _sm_expr1 = _sm_base1;
    return _sm_expr1;
}
Bool startsWith(StrView* self, Str text) {
    Int count, _sm_expr1, i;
    Bool _sm_expr2, _sm_expr6;
    Char _sm_expr5;
    count = simse_lenOf(text);
    _sm_expr1 = simse_strView_size((*self));
    _sm_expr2 = count > _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    i = 0;
    L3:;
    _sm_expr2 = i < count;
    if (!(_sm_expr2)) goto L4;
    {
        auto _sm_expr4 = self->ptr[i];
        _sm_expr5 = simse_str_charAt(text, i);
        _sm_expr6 = _sm_expr4 != _sm_expr5;
        if (_sm_expr6) goto L5;
        goto L6;
        L5:;
        return false;
        L6:;
        i = i + 1;
        goto L3;
    }
    L4:;
    return true;
}
Int find(StrView* self, Str sub) {
    Int needle, len, _sm_expr3, i, j, _sm_expr7;
    Bool _sm_expr1, _sm_expr10;
    Char _sm_expr9;
    needle = simse_lenOf(sub);
    _sm_expr1 = needle == 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return 0;
    L2:;
    len = simse_strView_size((*self));
    _sm_expr1 = needle > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    _sm_expr3 = -1;
    return _sm_expr3;
    L4:;
    i = 0;
    L5:;
    _sm_expr3 = i + needle;
    _sm_expr1 = _sm_expr3 <= len;
    if (!(_sm_expr1)) goto L6;
    j = 0;
    L7:;
    _sm_expr1 = j < needle;
    if (_sm_expr1) goto L10;
    goto L8;
    L10:;
    _sm_expr7 = i + j;
    {
        auto _sm_expr8 = self->ptr[_sm_expr7];
        _sm_expr9 = simse_str_charAt(sub, j);
        _sm_expr10 = _sm_expr8 == _sm_expr9;
        if (_sm_expr10) goto L9;
        goto L8;
        L9:;
        j = j + 1;
        goto L7;
    }
    L8:;
    _sm_expr1 = j == needle;
    if (_sm_expr1) goto L11;
    goto L12;
    L11:;
    return i;
    L12:;
    i = i + 1;
    goto L5;
    L6:;
    _sm_expr3 = -1;
    return _sm_expr3;
}
Str substr(StrView* self, Int from, Int count) {
    Int len, begin, end, _sm_expr6;
    Bool _sm_expr1;
    len = simse_strView_size((*self));
    begin = from;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr1 = begin > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = len;
    L4:;
    end = begin + count;
    _sm_expr1 = count < 0;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    end = begin;
    L6:;
    _sm_expr1 = end > len;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    end = len;
    L8:;
    Str out;
    _sm_expr1 = end > begin;
    if (_sm_expr1) goto L9;
    goto L10;
    L9:;
    _sm_expr6 = end - begin;
    simse_str_setBytes(out, self->ptr, begin, _sm_expr6);
    L10:;
    return out;
}
Str toString(StrView* self) {
    Int _sm_expr1;
    Str _sm_expr2;
    _sm_expr1 = simse_strView_size((*self));
    _sm_expr2 = substr(self, 0, _sm_expr1);
    return _sm_expr2;
}
template <class T>
List_iter_yieldable<T> iter(List<T>* self) {
    List_iter_yieldable<T> machine{};
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
template <class T>
Array_iter_yieldable<T> iter(Array<T>* self) {
    Array_iter_yieldable<T> machine{};
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
template <class T>
Span_iter_yieldable<T> iter(Span<T>* self) {
    Span_iter_yieldable<T> machine{};
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
template <class T>
List_iterPtr_yieldable<T> iterPtr(List<T>* self) {
    List_iterPtr_yieldable<T> machine{};
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
template <class T>
Array_iterPtr_yieldable<T> iterPtr(Array<T>* self) {
    Array_iterPtr_yieldable<T> machine{};
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
template <class T>
Span_iterPtr_yieldable<T> iterPtr(Span<T>* self) {
    Span_iterPtr_yieldable<T> machine{};
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
Bool compareLessThan(Str* left, Str* right) {
    StrView _sm_expr1, _sm_expr2;
    Bool _sm_expr3;
    _sm_expr1 = simse_spanOfStr(left);
    _sm_expr2 = simse_spanOfStr(right);
    _sm_expr3 = _sm_expr1 < _sm_expr2;
    return _sm_expr3;
}
Str substr(Str* self, Int start, Int len) {
    Str* _sm_base1;
    Int begin, _sm_expr2, count;
    Bool _sm_expr1;
    Char* _sm_expr8;
    begin = start;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr2 = simse_lenOf((*self));
    _sm_expr1 = begin > _sm_expr2;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = simse_lenOf((*self));
    L4:;
    _sm_expr2 = simse_lenOf((*self));
    count = _sm_expr2 - begin;
    _sm_expr1 = len >= 0;
    if (_sm_expr1) goto L7;
    goto L6;
    L7:;
    _sm_expr1 = len < count;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    count = len;
    L6:;
    Str out;
    _sm_expr1 = count > 0;
    if (_sm_expr1) goto L8;
    goto L9;
    L8:;
    _sm_base1 = self;
    _sm_expr8 = simse_str_data(_sm_base1);
    simse_str_setBytes(out, _sm_expr8, begin, count);
    L9:;
    return out;
}
Bool startsWith(Str* self, Str prefix) {
    Int count, _sm_expr1, i;
    Bool _sm_expr2;
    Char _sm_expr4, _sm_expr5;
    count = simse_lenOf(prefix);
    _sm_expr1 = simse_lenOf((*self));
    _sm_expr2 = count > _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    i = 0;
    L3:;
    _sm_expr2 = i < count;
    if (!(_sm_expr2)) goto L4;
    _sm_expr4 = simse_str_charAt((*self), i);
    _sm_expr5 = simse_str_charAt(prefix, i);
    _sm_expr2 = _sm_expr4 != _sm_expr5;
    if (_sm_expr2) goto L5;
    goto L6;
    L5:;
    return false;
    L6:;
    i = i + 1;
    goto L3;
    L4:;
    return true;
}
Bool isEmpty(Str* self) {
    Int _sm_expr1;
    Bool _sm_expr2;
    _sm_expr1 = simse_lenOf((*self));
    _sm_expr2 = _sm_expr1 == 0;
    return _sm_expr2;
}
// stress/collections/src/main.kt
List<Str> ns1_texts() {
    List<Str> texts;
    texts = List<Str>();
    simse_list_append(texts, __sm_stringTable[2]);
    simse_list_append(texts, __sm_stringTable[4]);
    return texts;
}
// stress/collections/src/main.kt
Int ns1_partArrayLayout() {
    Int _sm_base1, _sm_base2, _sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr5, _sm_expr6,
        _sm_expr7, _sm_expr8, _sm_expr9, _sm_expr12, _sm_expr13, _sm_expr14, _sm_expr15, _sm_expr17;
    ns1_Point* _sm_base3, * _sm_base4;
    Str _sm_base5;
    List<Int> values, nothing, growable;
    Array<Int> arr, alias, empty, emptyAgain, grown;
    List<ns1_Point> points;
    ns1_Point _sm_expr10, _sm_expr11;
    Array<ns1_Point> pointArray;
    List<Str> _sm_expr16;
    Array<Str> names;
    values = List<Int>();
    simse_list_append(values, 10);
    simse_list_append(values, 20);
    simse_list_append(values, 30);
    arr = simse_list_toArray(values);
    _sm_expr1 = simse_array_count(arr);
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = arr[0];
    _sm_expr3 = arr[1];
    _sm_expr4 = _sm_expr2 + _sm_expr3;
    _sm_expr5 = arr[2];
    _sm_expr6 = _sm_expr4 + _sm_expr5;
    simse_println((_sm_expr6), stdout);
    alias = arr;
    alias[1] = 99;
    _sm_base1 = arr[1];
    simse_println((_sm_base1), stdout);
    empty = simse_arrayEmpty<Int>();
    _sm_expr7 = simse_array_count(empty);
    simse_println((_sm_expr7), stdout);
    nothing = List<Int>();
    emptyAgain = simse_list_toArray(nothing);
    _sm_expr8 = simse_array_count(emptyAgain);
    simse_println((_sm_expr8), stdout);
    growable = simse_array_toList(arr);
    simse_list_append(growable, 40);
    grown = simse_list_toArray(growable);
    _sm_expr9 = simse_array_count(grown);
    simse_println((_sm_expr9), stdout);
    _sm_base2 = grown[3];
    simse_println((_sm_base2), stdout);
    points = List<ns1_Point>();
    _sm_expr10 = ns1_Point{1, 2};
    simse_list_append(points, _sm_expr10);
    _sm_expr11 = ns1_Point{3, 4};
    simse_list_append(points, _sm_expr11);
    pointArray = simse_list_toArray(points);
    _sm_expr12 = simse_array_count(pointArray);
    simse_println((_sm_expr12), stdout);
    _sm_base3 = simse_addressOf(pointArray[0]);
    _sm_expr13 = _sm_base3->x;
    _sm_base4 = simse_addressOf(pointArray[1]);
    _sm_expr14 = _sm_base4->y;
    _sm_expr15 = _sm_expr13 + _sm_expr14;
    simse_println((_sm_expr15), stdout);
    _sm_expr16 = ns1_texts();
    names = simse_list_toArray(_sm_expr16);
    _sm_expr17 = simse_array_count(names);
    simse_println((_sm_expr17), stdout);
    _sm_base5 = names[1];
    simse_println((_sm_base5), stdout);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_partBulkList() {
    Int _sm_base1, _sm_base2, i, _sm_expr2, _sm_expr3, total, _sm_expr4;
    List<Int> values;
    Bool _sm_expr1;
    values = List<Int>();
    i = 0;
    L1:;
    _sm_expr1 = i < 10000;
    if (!(_sm_expr1)) goto L2;
    _sm_expr2 = i % 97;
    simse_list_append(values, _sm_expr2);
    i = i + 1;
    goto L1;
    L2:;
    _sm_expr3 = simse_lenOf(values);
    simse_println((_sm_expr3), stdout);
    total = 0;
    i = 0;
    L3:;
    _sm_expr4 = simse_lenOf(values);
    _sm_expr1 = i < _sm_expr4;
    if (!(_sm_expr1)) goto L4;
    _sm_expr4 = values[i];
    total = total + _sm_expr4;
    i = i + 1;
    goto L3;
    L4:;
    simse_println((total), stdout);
    _sm_base1 = values[0];
    simse_println((_sm_base1), stdout);
    _sm_base2 = values[9999];
    simse_println((_sm_base2), stdout);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_partContainers() {
    Int _sm_base1, _sm_expr1, _sm_expr2, _sm_expr3;
    List<Int> xs;
    xs = List<Int>();
    simse_list_append(xs, 10);
    simse_list_append(xs, 20);
    simse_list_append(xs, 30);
    _sm_expr1 = simse_lenOf(xs);
    simse_println((_sm_expr1), stdout);
    simse_list_removeAt(xs, 1);
    _sm_expr2 = simse_lenOf(xs);
    simse_println((_sm_expr2), stdout);
    _sm_base1 = xs[1];
    simse_println((_sm_base1), stdout);
    simse_list_removeRange(xs, 0, 1);
    _sm_expr3 = simse_lenOf(xs);
    simse_println((_sm_expr3), stdout);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_partDictionary() {
struct ns1_partDictionary_closure1 {
    auto operator()(Int* left, Int* right) {
        Int _sm_base1, _sm_base2;
        Bool _sm_expr1;
        _sm_base1 = *(left);
        _sm_base2 = *(right);
        _sm_expr1 = _sm_base1 < _sm_base2;
        return _sm_expr1;
    }
};

    Int _sm_base2, _sm_base7, _sm_expr1, _sm_expr3, _sm_expr7, i, _sm_expr10, j, _sm_expr16, _sm_expr17;
    Str _sm_base5;
    ns1_partDictionary_closure1 _sm_base6;
    Dictionary<Str, Int> counts;
    Opt<Int> _sm_expr2, _sm_expr6;
    Bool _sm_expr4, _sm_expr5, _sm_expr9, _sm_expr12, _sm_expr13;
    Int* present, * _sm_expr8;
    List<Str> names;
    List<Int> values;
    counts = simse_dictionaryOf<Str, Int>();
    simse_dict_insert(counts, __sm_stringTable[17], 2);
    simse_dict_insert(counts, __sm_stringTable[16], 1);
    simse_dict_insert(counts, __sm_stringTable[18], 3);
    simse_dict_insert(counts, __sm_stringTable[17], 20);
    _sm_expr1 = simse_dict_size(counts);
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = simse_dict_get(counts, __sm_stringTable[16]);
    _sm_expr3 = _sm_expr2.value();
    simse_println((_sm_expr3), stdout);
    _sm_expr4 = simse_dict_has(counts, __sm_stringTable[20]);
    simse_println((_sm_expr4), stdout);
    present = simse_dict_getPtr(counts, __sm_stringTable[17]);
    _sm_expr5 = present != nullptr;
    if (_sm_expr5) goto L1;
    goto L2;
    L1:;
    *present = 21;
    _sm_base2 = *present;
    simse_println((_sm_base2), stdout);
    L2:;
    _sm_expr6 = simse_dict_get(counts, __sm_stringTable[17]);
    _sm_expr7 = _sm_expr6.value();
    simse_println((_sm_expr7), stdout);
    _sm_expr8 = simse_dict_getPtr(counts, __sm_stringTable[20]);
    _sm_expr9 = _sm_expr8 == nullptr;
    simse_println((_sm_expr9), stdout);
    names = simse_dict_keys(counts);
    simse_list_sort(names, compareLessThan);
    i = 0;
    L3:;
    _sm_expr10 = simse_lenOf(names);
    _sm_expr5 = i < _sm_expr10;
    if (!(_sm_expr5)) goto L4;
    _sm_base5 = names[i];
    simse_println((_sm_base5), stdout);
    i = i + 1;
    goto L3;
    L4:;
    _sm_expr12 = simse_list_contains(names, __sm_stringTable[18]);
    simse_println((_sm_expr12), stdout);
    _sm_expr13 = simse_list_contains(names, __sm_stringTable[20]);
    simse_println((_sm_expr13), stdout);
    values = simse_dict_values(counts);
    _sm_base6 = ns1_partDictionary_closure1{};
    simse_list_sort(values, _sm_base6);
    j = 0;
    L5:;
    _sm_expr10 = simse_lenOf(values);
    _sm_expr5 = j < _sm_expr10;
    if (!(_sm_expr5)) goto L6;
    _sm_base7 = values[j];
    simse_println((_sm_base7), stdout);
    j = j + 1;
    goto L5;
    L6:;
    simse_dict_remove(counts, __sm_stringTable[16]);
    _sm_expr16 = simse_dict_size(counts);
    simse_println((_sm_expr16), stdout);
    simse_dict_clear(counts);
    _sm_expr17 = simse_dict_size(counts);
    simse_println((_sm_expr17), stdout);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_arraySum(List<Int>* items) {
    Array<Int> arr;
    Int sum, value;
    Array_iter_yieldable<Int> _sm_for1;
    Bool _sm_expr1;
    arr = simse_list_toArray((*items));
    sum = 0;
    _sm_for1 = iter(simse_addressOf(arr));
    L1:;
    _sm_expr1 = _sm_for1.advance();
    if (!(_sm_expr1)) goto L2;
    value = _sm_for1.current;
    sum = sum + value;
    goto L1;
    L2:;
    return sum;
}
// stress/collections/src/main.kt
Int ns1_spanSum(List<Int>* items) {
    Span<Int> span;
    Int sum, value;
    Span_iter_yieldable<Int> _sm_for2;
    Bool _sm_expr1;
    span = simse_spanOf(items);
    sum = 0;
    _sm_for2 = iter(simse_addressOf(span));
    L1:;
    _sm_expr1 = _sm_for2.advance();
    if (!(_sm_expr1)) goto L2;
    value = _sm_for2.current;
    sum = sum + value;
    goto L1;
    L2:;
    return sum;
}
// stress/collections/src/main.kt
Int ns1_partForArray() {
    char* __sm_catP;
    Int __sm_catC0;
    List<Int>* _sm_base1, * _sm_base2;
    List<Int> numbers;
    Array<Int> _sm_expr1, _sm_expr4;
    Array_iter_yieldable<Int> _sm_for3, _sm_for4;
    Bool _sm_expr2;
    Int value, _sm_index4, _sm_value_2, index, _sm_expr12, _sm_expr14;
    Str _sm_expr3, _sm_expr9, _sm_expr11, _sm_expr13, _sm_expr15;
    numbers = List<Int>();
    simse_list_append(numbers, 3);
    simse_list_append(numbers, 4);
    simse_list_append(numbers, 99);
    simse_list_append(numbers, 5);
    _sm_expr1 = simse_list_toArray(numbers);
    _sm_for3 = iter(simse_addressOf(_sm_expr1));
    L1:;
    _sm_expr2 = _sm_for3.advance();
    if (!(_sm_expr2)) goto L2;
    value = _sm_for3.current;
    _sm_expr3 = simse_int_toString(value);
    simse_println((_sm_expr3), stdout);
    goto L1;
    L2:;
    _sm_expr4 = simse_list_toArray(numbers);
    _sm_for4 = iter(simse_addressOf(_sm_expr4));
    _sm_index4 = -1;
    L3:;
    _sm_expr2 = _sm_for4.advance();
    if (!(_sm_expr2)) goto L4;
    _sm_index4 = _sm_index4 + 1;
    _sm_value_2 = _sm_for4.current;
    index = _sm_index4;
    _sm_expr2 = index == 1;
    if (_sm_expr2) goto L3;
    _sm_expr2 = _sm_value_2 == 99;
    if (_sm_expr2) goto L4;
    __sm_catC0 = simse_strCountDigits(index);
    _sm_expr9.resize(1 + __sm_catC0);
    __sm_catP = _sm_expr9.data();
    simse_strAddInt(__sm_catP, index, __sm_catC0);
    __sm_catP = __sm_catP + __sm_catC0;
    *__sm_catP = (char) ('=');
    __sm_catC0 = simse_strCountDigits(_sm_value_2);
    _sm_expr11.resize(_sm_expr9.size() + __sm_catC0);
    __sm_catP = _sm_expr11.data();
    std::memcpy(__sm_catP, _sm_expr9.data(), _sm_expr9.size());
    __sm_catP = __sm_catP + _sm_expr9.size();
    simse_strAddInt(__sm_catP, _sm_value_2, __sm_catC0);
    simse_println((_sm_expr11), stdout);
    goto L3;
    L4:;
    _sm_base1 = &numbers;
    _sm_expr12 = ns1_arraySum(_sm_base1);
    _sm_expr13 = simse_int_toString(_sm_expr12);
    simse_println((_sm_expr13), stdout);
    _sm_base2 = &numbers;
    _sm_expr14 = ns1_spanSum(_sm_base2);
    _sm_expr15 = simse_int_toString(_sm_expr14);
    simse_println((_sm_expr15), stdout);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_total(List<Int>* items) {
    Int sum, value;
    List_iter_yieldable<Int> _sm_for5;
    Bool _sm_expr1;
    sum = 0;
    _sm_for5 = iter(items);
    L1:;
    _sm_expr1 = _sm_for5.advance();
    if (!(_sm_expr1)) goto L2;
    value = _sm_for5.current;
    sum = sum + value;
    goto L1;
    L2:;
    return sum;
}
// stress/collections/src/main.kt
Int ns1_partForContainer() {
    char* __sm_catP;
    List<Int>* _sm_base1;
    List<Int> numbers;
    List_iter_yieldable<Int> _sm_for6, _sm_for8;
    Bool _sm_expr1;
    Int value, _sm_index7, index, _sm_index8, _sm_value_2, _sm_index_2, _sm_expr14;
    Str _sm_expr2, word, _sm_expr4, _sm_expr5, _sm_expr6, _sm_expr13, _sm_expr15;
    List<Str> words;
    List_iter_yieldable<Str> _sm_for7;
    numbers = List<Int>();
    simse_list_append(numbers, 10);
    simse_list_append(numbers, 20);
    simse_list_append(numbers, 30);
    _sm_for6 = iter(simse_addressOf(numbers));
    L1:;
    _sm_expr1 = _sm_for6.advance();
    if (!(_sm_expr1)) goto L2;
    value = _sm_for6.current;
    _sm_expr2 = simse_int_toString(value);
    simse_println((_sm_expr2), stdout);
    goto L1;
    L2:;
    words = List<Str>();
    simse_list_append(words, __sm_stringTable[7]);
    simse_list_append(words, __sm_stringTable[8]);
    simse_list_append(words, __sm_stringTable[3]);
    _sm_for7 = iter(simse_addressOf(words));
    _sm_index7 = -1;
    L3:;
    _sm_expr1 = _sm_for7.advance();
    if (!(_sm_expr1)) goto L4;
    _sm_index7 = _sm_index7 + 1;
    word = _sm_for7.current;
    index = _sm_index7;
    _sm_expr4 = simse_int_toString(index);
    _sm_expr5.resize(1 + _sm_expr4.size());
    __sm_catP = _sm_expr5.data();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    __sm_catP = __sm_catP + _sm_expr4.size();
    *__sm_catP = (char) (':');
    _sm_expr6.resize(_sm_expr5.size() + word.size());
    __sm_catP = _sm_expr6.data();
    std::memcpy(__sm_catP, _sm_expr5.data(), _sm_expr5.size());
    __sm_catP = __sm_catP + _sm_expr5.size();
    std::memcpy(__sm_catP, word.data(), word.size());
    simse_println((_sm_expr6), stdout);
    goto L3;
    L4:;
    _sm_for8 = iter(simse_addressOf(numbers));
    _sm_index8 = -1;
    L5:;
    _sm_expr1 = _sm_for8.advance();
    if (!(_sm_expr1)) goto L6;
    _sm_index8 = _sm_index8 + 1;
    _sm_value_2 = _sm_for8.current;
    _sm_index_2 = _sm_index8;
    _sm_expr1 = _sm_index_2 == 1;
    if (_sm_expr1) goto L5;
    _sm_expr1 = _sm_value_2 > 25;
    if (_sm_expr1) goto L6;
    word = simse_int_toString(_sm_index_2);
    _sm_expr4.resize(1 + word.size());
    __sm_catP = _sm_expr4.data();
    std::memcpy(__sm_catP, word.data(), word.size());
    __sm_catP = __sm_catP + word.size();
    *__sm_catP = (char) ('=');
    _sm_expr5 = simse_int_toString(_sm_value_2);
    _sm_expr13.resize(_sm_expr4.size() + _sm_expr5.size());
    __sm_catP = _sm_expr13.data();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    __sm_catP = __sm_catP + _sm_expr4.size();
    std::memcpy(__sm_catP, _sm_expr5.data(), _sm_expr5.size());
    simse_println((_sm_expr13), stdout);
    goto L5;
    L6:;
    _sm_base1 = &numbers;
    _sm_expr14 = ns1_total(_sm_base1);
    _sm_expr15 = simse_int_toString(_sm_expr14);
    simse_println((_sm_expr15), stdout);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_bump(List<ns1_Cell>* cells) {
    Int _sm_base1, total, _sm_expr2, _sm_expr3;
    List_iterPtr_yieldable<ns1_Cell> _sm_for9;
    Bool _sm_expr1;
    ns1_Cell* cell;
    total = 0;
    _sm_for9 = iterPtr(cells);
    L1:;
    _sm_expr1 = _sm_for9.advance();
    if (!(_sm_expr1)) goto L2;
    cell = _sm_for9.current;
    _sm_expr2 = cell->value;
    _sm_base1 = _sm_expr2 + 1;
    cell->value = _sm_base1;
    _sm_expr3 = cell->value;
    total = total + _sm_expr3;
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
void ns1_report(List<ns1_Cell>* cells) {
    char* __sm_catP;
    Int __sm_catC0;
    Int* _sm_base1;
    List_iterPtr_yieldable<ns1_Cell> _sm_for10;
    Int _sm_index10, i;
    Bool _sm_expr1;
    ns1_Cell* cell;
    Str _sm_expr3, _sm_expr5;
    _sm_for10 = iterPtr(cells);
    _sm_index10 = -1;
    L1:;
    _sm_expr1 = _sm_for10.advance();
    if (!(_sm_expr1)) goto L2;
    _sm_index10 = _sm_index10 + 1;
    cell = _sm_for10.current;
    i = _sm_index10;
    __sm_catC0 = simse_strCountDigits(i);
    _sm_expr3.resize(1 + __sm_catC0);
    __sm_catP = _sm_expr3.data();
    simse_strAddInt(__sm_catP, i, __sm_catC0);
    __sm_catP = __sm_catP + __sm_catC0;
    *__sm_catP = (char) (':');
    _sm_base1 = simse_addressOf(cell->value);
    __sm_catC0 = simse_strCountDigits((*_sm_base1));
    _sm_expr5.resize(_sm_expr3.size() + __sm_catC0);
    __sm_catP = _sm_expr5.data();
    std::memcpy(__sm_catP, _sm_expr3.data(), _sm_expr3.size());
    __sm_catP = __sm_catP + _sm_expr3.size();
    simse_strAddInt(__sm_catP, (*_sm_base1), __sm_catC0);
    simse_println((_sm_expr5), stdout);
    goto L1;
    L2:;
}
// stress/collections/src/main.kt
Int ns1_arrayBump(List<ns1_Cell>* items) {
    Int _sm_base1, total, _sm_expr2, _sm_expr3;
    Array<ns1_Cell> cells;
    Array_iterPtr_yieldable<ns1_Cell> _sm_for11;
    Bool _sm_expr1;
    ns1_Cell* cell;
    cells = simse_list_toArray((*items));
    total = 0;
    _sm_for11 = iterPtr(simse_addressOf(cells));
    L1:;
    _sm_expr1 = _sm_for11.advance();
    if (!(_sm_expr1)) goto L2;
    cell = _sm_for11.current;
    _sm_expr2 = cell->value;
    _sm_base1 = _sm_expr2 * 2;
    cell->value = _sm_base1;
    _sm_expr3 = cell->value;
    total = total + _sm_expr3;
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
Int ns1_spanSumPointer(List<Int>* items) {
    Span<Int> span;
    Int total, _sm_expr2;
    Span_iterPtr_yieldable<Int> _sm_for12;
    Bool _sm_expr1;
    Int* value;
    span = simse_spanOf(items);
    total = 0;
    _sm_for12 = iterPtr(simse_addressOf(span));
    L1:;
    _sm_expr1 = _sm_for12.advance();
    if (!(_sm_expr1)) goto L2;
    value = _sm_for12.current;
    _sm_expr2 = *value;
    total = total + _sm_expr2;
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
Int ns1_partForPointer() {
    List<ns1_Cell>* _sm_base1, * _sm_base2, * _sm_base5;
    Int* _sm_base3;
    ns1_Cell* _sm_base4;
    List<Int>* _sm_base8;
    List<ns1_Cell> cells;
    ns1_Cell _sm_expr1, _sm_expr2, _sm_expr3;
    Int _sm_expr4, _sm_expr7, _sm_expr10;
    Str _sm_expr5, _sm_expr6, _sm_expr8, _sm_expr9, _sm_expr11;
    List<Int> numbers;
    cells = List<ns1_Cell>();
    _sm_expr1 = ns1_Cell{1};
    simse_list_append(cells, _sm_expr1);
    _sm_expr2 = ns1_Cell{2};
    simse_list_append(cells, _sm_expr2);
    _sm_expr3 = ns1_Cell{3};
    simse_list_append(cells, _sm_expr3);
    _sm_base1 = &cells;
    _sm_expr4 = ns1_bump(_sm_base1);
    _sm_expr5 = simse_int_toString(_sm_expr4);
    simse_println((_sm_expr5), stdout);
    _sm_base2 = &cells;
    ns1_report(_sm_base2);
    _sm_base4 = simse_addressOf(cells[0]);
    _sm_base3 = simse_addressOf(_sm_base4->value);
    _sm_expr6 = simse_int_toString((*_sm_base3));
    simse_println((_sm_expr6), stdout);
    _sm_base5 = &cells;
    _sm_expr7 = ns1_arrayBump(_sm_base5);
    _sm_expr8 = simse_int_toString(_sm_expr7);
    simse_println((_sm_expr8), stdout);
    _sm_expr9 = simse_int_toString((*_sm_base3));
    simse_println((_sm_expr9), stdout);
    numbers = List<Int>();
    simse_list_append(numbers, 4);
    simse_list_append(numbers, 7);
    simse_list_append(numbers, 9);
    _sm_base8 = &numbers;
    _sm_expr10 = ns1_spanSumPointer(_sm_base8);
    _sm_expr11 = simse_int_toString(_sm_expr10);
    simse_println((_sm_expr11), stdout);
    return 0;
}
// stress/collections/src/main.kt
ns1_List_everyNth_yieldable ns1_everyNth(List<Int>* self, Int step) {
    ns1_List_everyNth_yieldable machine{};
    machine.step = step;
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
// stress/collections/src/main.kt
Int ns1_partLambdaFor() {
struct ns1_partLambdaFor_closure1 {
    List<Int> items;
    auto operator()(Int n) {
        List<Int> _sm_base1;
        Int total, value, _sm_expr2;
        List_iter_yieldable<Int> _sm_for13;
        Bool _sm_expr1;
        Str _sm_expr3;
        total = 0;
        _sm_base1 = this->items;
        _sm_for13 = iter(simse_addressOf(_sm_base1));
        L1:;
        _sm_expr1 = _sm_for13.advance();
        if (!(_sm_expr1)) goto L2;
        value = _sm_for13.current;
        total = total + value;
        goto L1;
        L2:;
        _sm_expr2 = total + n;
        _sm_expr3 = simse_int_toString(_sm_expr2);
        simse_println((_sm_expr3), stdout);
    }
};

struct ns1_partLambdaFor_closure2 {
    List<Int> items;
    auto operator()(Int n) {
        List<Int> _sm_base1;
        ns1_List_everyNth_yieldable _sm_expr1, _sm_for14;
        Bool _sm_expr2;
        Int value, _sm_expr3;
        Str _sm_expr4;
        _sm_base1 = this->items;
        _sm_expr1 = ns1_everyNth(simse_addressOf(_sm_base1), 2);
        _sm_for14 = _sm_expr1;
        L1:;
        _sm_expr2 = _sm_for14.advance();
        if (!(_sm_expr2)) goto L2;
        value = _sm_for14.current;
        _sm_expr3 = value + n;
        _sm_expr4 = simse_int_toString(_sm_expr3);
        simse_println((_sm_expr4), stdout);
        goto L1;
        L2:;
    }
};

struct ns1_partLambdaFor_closure3 {
    List<Int> items;
    auto operator()(Int n) {
        char* __sm_catP;
        Int __sm_catC0;
        List<Int> _sm_base1;
        ns1_List_everyNth_yieldable _sm_expr1, _sm_for15;
        Int _sm_index15, value, index, _sm_expr3;
        Bool _sm_expr2;
        Str _sm_expr5, _sm_expr7;
        _sm_base1 = this->items;
        _sm_expr1 = ns1_everyNth(simse_addressOf(_sm_base1), 2);
        _sm_for15 = _sm_expr1;
        _sm_index15 = -1;
        L1:;
        _sm_expr2 = _sm_for15.advance();
        if (!(_sm_expr2)) goto L2;
        _sm_index15 = _sm_index15 + 1;
        value = _sm_for15.current;
        index = _sm_index15;
        _sm_expr3 = index + n;
        __sm_catC0 = simse_strCountDigits(_sm_expr3);
        _sm_expr5.resize(1 + __sm_catC0);
        __sm_catP = _sm_expr5.data();
        simse_strAddInt(__sm_catP, _sm_expr3, __sm_catC0);
        __sm_catP = __sm_catP + __sm_catC0;
        *__sm_catP = (char) (':');
        __sm_catC0 = simse_strCountDigits(value);
        _sm_expr7.resize(_sm_expr5.size() + __sm_catC0);
        __sm_catP = _sm_expr7.data();
        std::memcpy(__sm_catP, _sm_expr5.data(), _sm_expr5.size());
        __sm_catP = __sm_catP + _sm_expr5.size();
        simse_strAddInt(__sm_catP, value, __sm_catC0);
        simse_println((_sm_expr7), stdout);
        goto L1;
        L2:;
    }
};

    List<Int> items;
    ns1_Taker sumWith, eachNth, indexed;
    items = List<Int>();
    simse_list_append(items, 10);
    simse_list_append(items, 20);
    simse_list_append(items, 30);
    sumWith = ns1_partLambdaFor_closure1{items};
    sumWith(1);
    eachNth = ns1_partLambdaFor_closure2{items};
    eachNth(1);
    indexed = ns1_partLambdaFor_closure3{items};
    indexed(7);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_addAll(List<Int>* values) {
    Int total, _sm_expr2;
    List_iterPtr_yieldable<Int> _sm_for16;
    Bool _sm_expr1;
    Int* value;
    total = 0;
    _sm_for16 = iterPtr(values);
    L1:;
    _sm_expr1 = _sm_for16.advance();
    if (!(_sm_expr1)) goto L2;
    value = _sm_for16.current;
    _sm_expr2 = *value;
    total = total + _sm_expr2;
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
Int ns1_sumValues(List<Int> values) {
    Int total, i, _sm_expr1;
    Bool _sm_expr2;
    total = 0;
    i = 0;
    L1:;
    _sm_expr1 = simse_lenOf(values);
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr1 = values[i];
    total = total + _sm_expr1;
    i = i + 1;
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
Int ns1_countBoxed(Ref<List<Int>> values) {
    Int _sm_expr1;
    _sm_expr1 = simse_lenOf((*values));
    return _sm_expr1;
}
// stress/collections/src/main.kt
Str ns1_format(Str shape, List<Str>* items) {
    char* __sm_catP;
    Int __sm_catC0;
    Str out, _sm_expr4, _sm_expr7, _sm_expr8;
    Int i, _sm_expr1;
    Bool _sm_expr2;
    out = __sm_stringTable[21];
    i = 0;
    L1:;
    _sm_expr1 = simse_lenOf((*items));
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr4.resize(1 + out.size() + shape.size());
    __sm_catP = _sm_expr4.data();
    std::memcpy(__sm_catP, out.data(), out.size());
    __sm_catP = __sm_catP + out.size();
    std::memcpy(__sm_catP, shape.data(), shape.size());
    __sm_catP = __sm_catP + shape.size();
    *__sm_catP = (char) ('[');
    __sm_catC0 = simse_strCountDigits(i);
    _sm_expr7.resize(2 + _sm_expr4.size() + __sm_catC0);
    __sm_catP = _sm_expr7.data();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    __sm_catP = __sm_catP + _sm_expr4.size();
    simse_strAddInt(__sm_catP, i, __sm_catC0);
    __sm_catP = __sm_catP + __sm_catC0;
    std::memcpy(__sm_catP, "]=", 2);
    _sm_expr8 = (*items)[i];
    out.resize(1 + _sm_expr7.size() + _sm_expr8.size());
    __sm_catP = out.data();
    std::memcpy(__sm_catP, _sm_expr7.data(), _sm_expr7.size());
    __sm_catP = __sm_catP + _sm_expr7.size();
    std::memcpy(__sm_catP, _sm_expr8.data(), _sm_expr8.size());
    __sm_catP = __sm_catP + _sm_expr8.size();
    *__sm_catP = (char) (' ');
    i = i + 1;
    goto L1;
    L2:;
    return out;
}
// stress/collections/src/main.kt
Int ns1_count(List<Str>* values) {
    Int _sm_expr1;
    _sm_expr1 = simse_lenOf((*values));
    return _sm_expr1;
}
// stress/collections/src/main.kt
Int ns1_partPackArgs() {
    List<Int> _sm_base1, _sm_base3, _sm_base5, _sm_base9, _sm_base11, numbers, primes, zeros;
    List<Int>* _sm_base2, * _sm_base4, * _sm_base6, * _sm_base7, * _sm_base8, * _sm_base10, * _sm_base18,
        * _sm_base19;
    Ref<List<Int>> _sm_base12;
    Str _sm_base13, _sm_expr2, _sm_expr4, _sm_expr6, _sm_expr8, _sm_expr10, _sm_expr12, _sm_expr14,
        _sm_expr16, _sm_expr18, _sm_expr20, _sm_expr22, _sm_expr26, _sm_expr28, _sm_expr30;
    List<Str>* _sm_base14, * _sm_base16, * _sm_base17;
    List<Str> _sm_base15, keywords, _sm_expr23;
    Int _sm_expr1, _sm_expr3, _sm_expr5, _sm_expr7, _sm_expr9, _sm_expr11, _sm_expr13, _sm_expr15,
        _sm_expr17, _sm_expr19, _sm_expr21, _sm_expr24, _sm_expr25, _sm_expr27, _sm_expr29;
    List<Bool> falses;
    _sm_base1 = List<Int>{1, 2, 3};
    _sm_base2 = &_sm_base1;
    _sm_expr1 = ns1_addAll(_sm_base2);
    _sm_expr2 = simse_int_toString(_sm_expr1);
    simse_println((_sm_expr2), stdout);
    _sm_base3 = List<Int>{10};
    _sm_base4 = &_sm_base3;
    _sm_expr3 = ns1_addAll(_sm_base4);
    _sm_expr4 = simse_int_toString(_sm_expr3);
    simse_println((_sm_expr4), stdout);
    _sm_base5 = List<Int>{};
    _sm_base6 = &_sm_base5;
    _sm_expr5 = ns1_addAll(_sm_base6);
    _sm_expr6 = simse_int_toString(_sm_expr5);
    simse_println((_sm_expr6), stdout);
    numbers = List<Int>{4, 5};
    _sm_base7 = &numbers;
    _sm_expr7 = ns1_addAll(_sm_base7);
    _sm_expr8 = simse_int_toString(_sm_expr7);
    simse_println((_sm_expr8), stdout);
    _sm_base8 = &numbers;
    _sm_expr9 = ns1_addAll(_sm_base8);
    _sm_expr10 = simse_int_toString(_sm_expr9);
    simse_println((_sm_expr10), stdout);
    _sm_base9 = List<Int>{6, 7, 8};
    _sm_expr11 = ns1_sumValues(_sm_base9);
    _sm_expr12 = simse_int_toString(_sm_expr11);
    simse_println((_sm_expr12), stdout);
    _sm_expr13 = ns1_sumValues(numbers);
    _sm_expr14 = simse_int_toString(_sm_expr13);
    simse_println((_sm_expr14), stdout);
    _sm_base10 = &numbers;
    _sm_base11 = *(_sm_base10);
    _sm_expr15 = ns1_sumValues(_sm_base11);
    _sm_expr16 = simse_int_toString(_sm_expr15);
    simse_println((_sm_expr16), stdout);
    _sm_base12 = makeRef<std::remove_cvref_t<decltype((numbers))>>(numbers);
    _sm_expr17 = ns1_countBoxed(_sm_base12);
    _sm_expr18 = simse_int_toString(_sm_expr17);
    simse_println((_sm_expr18), stdout);
    keywords = List<Str>{__sm_stringTable[1], __sm_stringTable[10], __sm_stringTable[9]};
    _sm_expr19 = simse_lenOf(keywords);
    _sm_expr20 = simse_int_toString(_sm_expr19);
    simse_println((_sm_expr20), stdout);
    _sm_base13 = keywords[2];
    simse_println((_sm_base13), stdout);
    _sm_base14 = &keywords;
    _sm_expr21 = ns1_count(_sm_base14);
    simse_println((_sm_expr21), stdout);
    _sm_base15 = List<Str>{__sm_stringTable[16], __sm_stringTable[17]};
    _sm_base16 = &_sm_base15;
    _sm_expr22 = ns1_format(__sm_stringTable[19], _sm_base16);
    simse_println((_sm_expr22), stdout);
    _sm_expr23 = List<Str>{};
    _sm_base17 = &_sm_expr23;
    _sm_expr24 = ns1_count(_sm_base17);
    simse_println((_sm_expr24), stdout);
    primes = List<Int>{2, 3, 5, 7};
    _sm_base18 = &primes;
    _sm_expr25 = ns1_addAll(_sm_base18);
    _sm_expr26 = simse_int_toString(_sm_expr25);
    simse_println((_sm_expr26), stdout);
    zeros = List<Int>(3);
    _sm_base19 = &zeros;
    _sm_expr27 = ns1_addAll(_sm_base19);
    _sm_expr28 = simse_int_toString(_sm_expr27);
    simse_println((_sm_expr28), stdout);
    falses = List<Bool>(4, false);
    _sm_expr29 = simse_lenOf(falses);
    _sm_expr30 = simse_int_toString(_sm_expr29);
    simse_println((_sm_expr30), stdout);
    return 0;
}
// stress/collections/src/main.kt
Int ns1_sum(List<Int>* items) {
    Int total, _sm_expr3;
    Span<Int> span;
    Bool _sm_expr1, _sm_expr2;
    total = 0;
    span = simse_spanOf(items);
    L1:;
    _sm_expr1 = span.isEmpty();
    _sm_expr2 = !_sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr3 = span[0];
    total = total + _sm_expr3;
    span = span.slice(1);
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
Int ns1_tailSum(List<Int>* items) {
    Span<Int> full, tail;
    Int total, _sm_expr3;
    Bool _sm_expr1, _sm_expr2;
    full = simse_spanOf(items);
    tail = full.slice(2);
    total = 0;
    L1:;
    _sm_expr1 = tail.isEmpty();
    _sm_expr2 = !_sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr3 = tail.at(0);
    total = total + _sm_expr3;
    tail = tail.slice(1);
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
Int ns1_middleSum(List<Int>* items) {
    Span<Int> full, middle;
    Int total, i, _sm_expr1;
    Bool _sm_expr2;
    full = simse_spanOf(items);
    middle = full.slice(1, 2);
    total = 0;
    i = 0;
    L1:;
    _sm_expr1 = middle.size();
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr1 = middle[i];
    total = total + _sm_expr1;
    i = i + 1;
    goto L1;
    L2:;
    return total;
}
// stress/collections/src/main.kt
Str ns1_afterColon(Str text) {
    Str* _sm_base1;
    StrView bytes, _sm_expr6;
    Int at, _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr5;
    Bool _sm_expr1;
    Str _sm_expr7;
    _sm_base1 = &text;
    bytes = simse_spanOfStr(_sm_base1);
    at = find(simse_addressOf(bytes), __sm_stringTable[13]);
    _sm_expr1 = at < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[21];
    L2:;
    _sm_expr2 = at + 1;
    _sm_expr3 = simse_strView_size(bytes);
    _sm_expr4 = _sm_expr3 - at;
    _sm_expr5 = _sm_expr4 - 1;
    _sm_expr6 = simse_strView_slice(bytes, _sm_expr2, _sm_expr5);
    _sm_expr7 = toString(simse_addressOf(_sm_expr6));
    return _sm_expr7;
}
// stress/collections/src/main.kt
void ns1_bumpSpan(Span<Int> span) {
    Int index;
    Int* slot;
    index = 1;
    slot = atPtr(simse_addressOf(span), index);
    auto _sm_expr1 = slot[0];
    slot[0] = _sm_expr1 + 100;
}
// stress/collections/src/main.kt
Char* ns1_headByte(Str* text) {
    StrView _sm_expr1;
    Char* _sm_expr2;
    _sm_expr1 = simse_spanOfStr(text);
    _sm_expr2 = atPtr(simse_addressOf(_sm_expr1), 0);
    return _sm_expr2;
}
// stress/collections/src/main.kt
Int ns1_partSpan() {
    List<Int>* _sm_base1, * _sm_base2, * _sm_base3, * _sm_base4;
    Str* _sm_base5, * _sm_base7;
    Int _sm_base6, _sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4;
    List<Int> items;
    Span<Int> all;
    Str text, _sm_expr5, _sm_expr8, word;
    StrView _sm_expr6;
    Bool _sm_expr7;
    Char* _sm_expr9;
    items = List<Int>();
    simse_list_append(items, 4);
    simse_list_append(items, 7);
    simse_list_append(items, 9);
    _sm_base1 = &items;
    _sm_expr1 = ns1_sum(_sm_base1);
    simse_println((_sm_expr1), stdout);
    _sm_base2 = &items;
    _sm_expr2 = ns1_tailSum(_sm_base2);
    simse_println((_sm_expr2), stdout);
    _sm_base3 = &items;
    _sm_expr3 = ns1_middleSum(_sm_base3);
    simse_println((_sm_expr3), stdout);
    _sm_base4 = &items;
    all = simse_spanOf(_sm_base4);
    _sm_expr4 = all.size();
    simse_println((_sm_expr4), stdout);
    text = __sm_stringTable[0];
    _sm_expr5 = ns1_afterColon(text);
    simse_println((_sm_expr5), stdout);
    _sm_base5 = &text;
    _sm_expr6 = simse_spanOfStr(_sm_base5);
    _sm_expr7 = startsWith(simse_addressOf(_sm_expr6), __sm_stringTable[5]);
    simse_println((_sm_expr7), stdout);
    _sm_expr8 = substr(simse_addressOf(text), 0, 4);
    simse_println((_sm_expr8), stdout);
    ns1_bumpSpan(all);
    _sm_base6 = items[1];
    simse_println((_sm_base6), stdout);
    word = __sm_stringTable[6];
    _sm_base7 = &word;
    _sm_expr9 = ns1_headByte(_sm_base7);
    auto _sm_expr10 = _sm_expr9[0];
    simse_println((_sm_expr10), stdout);
    return 0;
}
// stress/collections/src/main.kt
int main() {
    ns1_partArrayLayout();
    ns1_partBulkList();
    ns1_partContainers();
    ns1_partDictionary();
    ns1_partForArray();
    ns1_partForContainer();
    ns1_partForPointer();
    ns1_partLambdaFor();
    ns1_partPackArgs();
    ns1_partSpan();
    return 0;
}

// `spanOf(items)`: a span over a list's elements. It borrows the list - the list has
// to outlive the span - and does not copy it (`&items` would box a copy instead).
template <class T>
inline Span<T> simse_spanOf(List<T>* items) {
    return Span<T>(items->data(), items->size());
}

inline Int simse_strView_size(StrView self) {
    return self.len;
}

inline Bool simse_strView_isEmpty(StrView self) {
    return self.len <= 0;
}

// `view.slice(start)`: from `start` to the end (C# `Slice(int)`).
inline StrView simse_strView_slice(StrView self, Int start) {
    return self.slice(start);
}

// `view.slice(start, count)`: `count` bytes from `start` (C# `Slice(int, int)`).
inline StrView simse_strView_slice(StrView self, Int start, Int count) {
    return self.slice(start, count);
}

inline Char simse_strView_charAt(StrView self, Int index) {
    return self[index];
}

// `spanOfStr(text)`: a view over a string's bytes. It borrows the string - the string
// has to outlive the view - and does not copy it (`&text` would box a copy instead).
// `Str` is a `char` buffer on the C++ side and the language's `Char` is a signed byte,
// hence the cast.
inline StrView simse_spanOfStr(Str* text) {
    return StrView(reinterpret_cast<Char*>(text->data()), text->size());
}

// `spanOfStr(view)`: a `StrView` already is a view, so this overload is the identity. It is
// what lets the `when`-over-strings desugar (`Parser.kt`'s `parseWhen`) extract the subject
// with `spanOfStr` without knowing whether it is a `Str` or a `StrView` - the C++ overload
// resolution picks the borrowed view or the identity, and the tests compare against it.
inline StrView simse_spanOfStr(StrView view) {
    return view;
}

template <class T>
inline void simse_list_append(List<T>& self, const std::type_identity_t<T>& value) {
    self.push_back(value);
}

template <class T>
inline List<T> simse_listOf(const List<T>* values) {
    return *values;
}

// Removes the single element at `index`.
template <class T>
inline void simse_list_removeAt(List<T>& self, Int index) {
    self.erase(self.begin() + index);
}

// Removes the half-open range [start, end).
template <class T>
inline void simse_list_removeRange(List<T>& self, Int start, Int end) {
    self.erase(self.begin() + start, self.begin() + end);
}

// `Array<T>.count()`: the element count stored at the front of the block.
template <class T>
inline Int simse_array_count(const Array<T>& self) {
    return self.count();
}

// `List<T>.toArray()` (specs/built-in-types.md): copies the elements into one count-first
// block. Element copies are value copies, like every other copy in the language.
template <class T>
inline Array<T> simse_list_toArray(const List<T>& self) {
    const Int count = self.size();
    if (count <= 0) {
        return Array<T>();
    }
    Array<T> result(count);
    for (Int i = 0; i < count; i++) {
        result[i] = self[i];
    }
    return result;
}

// `Array<T>.toList()`: the growable copy, which is how an element is added to an array.
template <class T>
inline List<T> simse_array_toList(const Array<T>& self) {
    List<T> result;
    const Int count = self.count();
    result.reserve(count);
    for (Int i = 0; i < count; i++) {
        result.push_back(self[i]);
    }
    return result;
}

// `arrayEmpty<T>()`: the shared, zero-length array of `T` (no allocation).
template <class T>
inline Array<T> simse_arrayEmpty() {
    return Array<T>();
}

// `Str.append(ch)`: `Str` has no single-character append, so this is `push_back`.
inline void simse_str_append(Str& self, Char value) {
    self.push_back(static_cast<char>(value));
}

// `Str.appendStr(text)`: appends in place, so an emitter accumulates output without
// `out = out + text` rebuilding the whole buffer on every line (which is quadratic).
inline void simse_str_appendStr(Str& self, const Str& value) {
    self.append(value);
}

// `Str.appendStrPtr(text)`: the same append for a text the caller only *borrows*, so
// nothing is copied on the way.
inline void simse_str_appendStrPtr(Str& self, const Str* value) {
    if (value != nullptr) self.append(*value);
}

// `Str.reserve(count)`: grows the buffer once, so a run of appends writes the text once
// instead of copying the accumulated prefix at every growth step. A *hint*, not a length.
inline void simse_str_reserve(Str& self, Int count) {
    self.reserve((Str::size_type) count);
}

// `Int.toString()`: the scalar-to-inline-string conversion (specs/memory-model.md).
inline Str simse_int_toString(Int self) {
    return std::to_string(self);
}

// `dictionaryOf<K, V>()`: `Dictionary<K, V>` is a value type, so this default-constructs
// one.
template <class K, class V>
inline Dictionary<K, V> simse_dictionaryOf() {
    return Dictionary<K, V>();
}

template <class K, class V>
inline V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return self.valuePtr(key);
}

template <class K, class V>
inline Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    const V* found = simse_dict_getPtr(self, key);
    if (found == nullptr) return Opt<V>::none();
    return Opt<V>::some(*found);
}

template <class K, class V>
inline Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return simse_dict_getPtr(self, key) != nullptr;
}

template <class K, class V>
inline void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                              const std::type_identity_t<V>& value) {
    self.insert_or_assign(key, value);
}

template <class K, class V>
inline void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    self.erase(key);
}

template <class K, class V>
inline Int simse_dict_size(const Dictionary<K, V>& self) {
    return (Int) self.size();
}

template <class K, class V>
inline List<K> simse_dict_keys(const Dictionary<K, V>& self) {
    List<K> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.first);
    return out;
}

template <class K, class V>
inline List<V> simse_dict_values(const Dictionary<K, V>& self) {
    List<V> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.second);
    return out;
}

template <class K, class V>
inline void simse_dict_clear(Dictionary<K, V>& self) {
    self.clear();
}

template <class T>
inline Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value) {
    for (const T& item : self) {
        if (item == value) return true;
    }
    return false;
}

template <class T, class F>
inline void simse_list_sort(List<T>& self, F less) {
    std::sort(self.begin(), self.end(), [&less](const T& a, const T& b) {
        return less(const_cast<T*>(&a), const_cast<T*>(&b));
    });
}

inline Int simse_lenOf(const Str& self) {
    return self.size();
}

// `List<T>` is `SmallVector<T, 4>` (cppsrc/rtl/containers.hpp), so one overload serves every
// element type and inline capacity.
template <class T, int N>
inline Int simse_lenOf(const SmallVector<T, N>& self) {
    return self.size();
}

// The powers of ten the bit scan settles its guess against.
static const unsigned long long smStrDigitPow10[20] = {
    1ull, 10ull, 100ull, 1000ull, 10000ull, 100000ull, 1000000ull, 10000000ull,
    100000000ull, 1000000000ull, 10000000000ull, 100000000000ull, 1000000000000ull,
    10000000000000ull, 100000000000000ull, 1000000000000000ull, 10000000000000000ull,
    100000000000000000ull, 1000000000000000000ull, 10000000000000000000ull
};

// The digit count, exact for every width (a narrower integer widens to `Int64` with the same
// digits). `std::bit_width(magnitude)` is the position of the highest set bit plus one - one
// `clz`/`bsr` - and `1233 / 4096 = 0.3010...` is log10(2), so the product is
// floor(log10(magnitude)) or one off; the comparison against that power of ten settles which.
// The early return is the one case the scan cannot answer (`0`), and the sign is a separate
// term, counted on the widened value so `-INT64_MIN` never overflows.
inline Int simse_strCountDigits(Int64 value) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (magnitude < 10ull) {
        return value < 0 ? 2 : 1;
    }
    Int bits = (Int) std::bit_width(magnitude);
    Int guess = (Int) (((unsigned int) bits * 1233u) >> 12);
    Int digits = guess + (magnitude >= smStrDigitPow10[guess] ? 1 : 0);
    return digits + (value < 0 ? 1 : 0);
}

// Two digits per step: the table holds "00".."99", so the inner loop never divides by ten.
struct SmStrDigitPairTable {
    char text[200];
    constexpr SmStrDigitPairTable() : text() {
        for (Int i = 0; i < 100; i = i + 1) {
            text[i * 2] = (char) ('0' + i / 10);
            text[i * 2 + 1] = (char) ('0' + i % 10);
        }
    }
};

static constexpr SmStrDigitPairTable smStrDigitPairs{};

// The digits of `value`, written straight into the `count` bytes `target` already owns and
// walking *back* through them (the least-significant pair first), so no second buffer and no
// second pass is needed. `count` must be exact - `simse_strCountDigits`'s answer, sign
// included - because the slots of the parts around this one depend on it.
inline void simse_strAddInt(char* target, Int64 value, Int count) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (value < 0) {
        target[0] = '-';
        count = count - 1;
        target = target + 1;
    }
    while (count >= 2) {
        unsigned int pair = (unsigned int) (magnitude % 100ull);
        magnitude /= 100ull;
        count = count - 2;
        target[count] = smStrDigitPairs.text[pair * 2];
        target[count + 1] = smStrDigitPairs.text[pair * 2 + 1];
    }
    if (count == 1) {
        target[0] = (char) ('0' + (Int) magnitude);
    }
}

// The two texts a bool can be, as a `StrView` over a two-entry table - the string-table shape,
// so a bool part is just another text part (a `memcpy` of a runtime length) and needs no digits
// of its own. Cold enough that the two loads the compiler folds it to do not matter.
inline StrView simse_strBoolView(Bool value) {
    static Char texts[2][6] = {"true", "false"};
    static Int lens[2] = {4, 5};
    Int at = value ? 0 : 1;
    return StrView(texts[at], lens[at]);
}

inline Char simse_str_charAt(const Str& self, Int index) {
    return (Char) self[index];
}

inline List<Str> simse_str_split(const Str& self, const Str& separator) {
    List<Str> parts;
    if (separator.empty()) {
        parts.push_back(self);
        return parts;
    }
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + separator.size();
    }
    return parts;
}

// How many bytes of `self` are `ch`: what the byte-separator split reserves up front.
inline Int simse_count_char_in_str(const Str* self, char ch) {
    Int count = 0;
    const char* data = self->data();
    Int len = self->size();
    for (Int i = 0; i < len; i++) {
        if (data[i] == ch) {
            count++;
        }
    }
    return count;
}

inline List<Str> simse_str_split(const Str& self, Char separator) {
    List<Str> parts;
    parts.reserve(simse_count_char_in_str(&self, separator));
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + 1;
    }
    return parts;
}

inline Int simse_str_find(const Str& self, const Str& sub) {
    Int found = self.find(sub);
    return found == Str::npos ? -1 : found;
}

inline Int simse_str_lastIndexOf(const Str& self, const Str& sub) {
    Int found = self.rfind(sub);
    return found == Str::npos ? -1 : found;
}

inline Str simse_str_replace(const Str& self, const Str& from, const Str& to) {
    if (from.empty()) return self;
    Str result;
    Int pos = 0;
    while (true) {
        Int found = self.find(from, pos);
        if (found == Str::npos) {
            result.append(self, pos, Str::npos);
            break;
        }
        result.append(self, pos, found - pos);
        result += to;
        pos = found + from.size();
    }
    return result;
}

inline Opt<Int> simse_str_toInt(const Str& self) {
    if (self.empty()) return Opt<Int>::none();
    Int value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Int>::none();
    return Opt<Int>::some(value);
}

inline Opt<Float64> simse_str_toFloat(const Str& self) {
    if (self.empty()) return Opt<Float64>::none();
    Float64 value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Float64>::none();
    return Opt<Float64>::some(value);
}

inline void simse_str_initByValue(Str& self, const Str& value) {
    self = value;
}

// The shared space test, used by `simse_char_isSpace` (and, in Simse, by `Str.trim`).
inline Bool simse_str_isSpaceByte(Char ch) {
    return ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r';
}

inline Bool simse_char_isDigit(Char self) {
    return self >= '0' && self <= '9';
}

inline Bool simse_char_isAlpha(Char self) {
    return (self >= 'a' && self <= 'z') || (self >= 'A' && self <= 'Z');
}

inline Bool simse_char_isAlphaOrDigit(Char self) {
    return simse_char_isAlpha(self) || simse_char_isDigit(self);
}

inline Bool simse_char_isSpace(Char self) {
    return simse_str_isSpaceByte(self);
}

template <class T>
inline Str simse_num_toString(const T& self) {
    return std::to_string(self);
}

inline Str simse_char_toString(Char self) {
    return std::to_string((int) self);
}

inline Str simse_bool_toString(Bool self) {
    return self ? "true" : "false";
}

// Expands one run-length encoded series into `out`, which holds `count` values.
template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; // stream[0] is the series' own length
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

// Fills `table` from the pool and the two expanded series: an offset increment and a
// byte count per entry, both rebuilt by subtracting the stored value from the one before.
inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  // this entry's offset increment, rebuilt from the start series
    Int length = 0; // this entry's byte count, rebuilt from the length series
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = StrView(bytes + at, length);
    }
}

// The three monotonic clocks. `steady_clock` is the one clock the standard library
// promises cannot go backwards, which is what makes a duration between two readings
// meaningful (`impl_specs/profiling.md`).
Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

Int64 simse_nowNanos() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
}

// The `simse_write` overloads and the two printers are all inline in the forward block: nothing
// here.
