// Generated by the Simse compiler. Do not edit.
#include "cppsrc/rtl/simse.hpp"
#include <iostream>
#include <type_traits>

// The string-literal pool's decoder (impl_specs/rtl-abi.md, "String literals: one
// table"): the emitter writes one pool of bytes plus two run-length encoded index
// series - where each entry starts and how long it is - and this expands them into the
// `StrView` per entry, once, before `main` runs. It was cppsrc/rtl/strtable.hpp.
//
// Six things are deliberate in the shape the emitter writes:
//
//  - **Both series are stored as "what to subtract from the previous value"**, with an
//    implicit 0 before the first entry: `value[i] = value[i-1] - series[i]`. The
//    literals are ordered longest first, so a length series descends slowly and a
//    *difference* of it is a small number - mostly 0 between the many literals of equal
//    length (85% of them on the compiler's own table).
//  - **Each series is run-length encoded**: its length first, then alternating blocks of
//    non-repeating values (a count, then that many values) and of runs (a count, then
//    that many `times, value` pairs), until the length is filled. The element type is a
//    template parameter because the emitter picks the width: `Int16` when every number
//    fits, `Int` otherwise.
//  - The pool is the literal texts themselves, adjacent, so the C++ compiler decodes
//    every escape and the emitter's decoding only has to agree about *how many bytes* an
//    escape costs. The emitted `static_assert` on the pool's `sizeof` is the check.
//  - The series are expanded into *stack* arrays in the initializer and dropped when it
//    returns: no heap, and the encoded statics are all the program carries.
//  - An entry is a 12-byte `StrView`, not the 32-byte owning `Str` the table used to
//    hold, and start-up allocates nothing for the literals.
//  - The pool is `const char` (a string literal, read-only) while `StrView` holds the
//    language's mutable `Char*`; the constness is cast away here, in the one place the
//    pool is touched, and nothing writes through it.

template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count);

#include <chrono>

// Time natives (the Simse surface is the prelude file cppsrc/rtl/rtl.kt). Both are
// monotonic clocks - never going backwards - since an arbitrary fixed point:
// `simse_nowMillis` for logging, the finer `simse_nowMicros` for the instrumented
// profiler (`cppsrc/profiling`, and the emitted `profileApp.measure(...)` of a
// `--profile` build). It was cppsrc/rtl/timeops.hpp, and its definitions were the last
// thing left in cppsrc/rtl/native.cpp - they are this section's now, so the clock is
// emitted into the program like any other prelude body and there is nothing to link.
// `emit: always`
// because the profiler's runtime is emitted by the *compiler* rather than named by
// the program: a `--profile` build needs these two declarations whether or not the program
// ever asks for the time.
Int64 simse_nowMillis();
Int64 simse_nowMicros();

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <system_error>

// The platform's filesystem/IO operations (impl_specs/native-interop.md). They were
// cppsrc/rtl/native.cpp - the repository's one hand-written translation unit beside the
// published bootstrap - so building a program meant compiling *and linking* a second file,
// and a build that left it out failed in the linker rather than in the compiler. The bodies
// are this section's now: a program that reaches one of these symbols has the prototype and
// the definition emitted into its own translation unit, which is what makes
// `cppsrc/simse_bootstrap.cpp` buildable on its own.
//
// `emit: always`, for the reason `timeops` is: a *program* may name any of these symbols
// with a declaration of its own - `native("simse_native_readFile") fun readFile(...)`, which
// is `native-interop.md`'s example and `stress/native-read-file`'s - and then no `res`
// declaration reaches this section for it to be found by (`sourcegen/ResGen.kt`). The
// platform's C++ is the runtime's FFI, so like a linked runtime it is there for every
// program; what a program pays for it is about 4 KB of text, the same code the linker used
// to place whether or not the program called it.
//
// The Simse surface is the prelude file cppsrc/rtl/fs.kt, plus `readFile` in
// cppsrc/common/common.kt (a normal module of the compiler). The prototypes used to live in
// cppsrc/rtl/fs.hpp and cppsrc/rtl/filestream.hpp, which is why those headers are gone - a
// section carries its own declaration half in `forward`.

Str simse_native_readFile(const Str& path);
List<Str> simse_listFiles(const Str& dir, const Str& ext);
List<Str> simse_listFilesDirect(const Str& dir, const Str& ext);
Bool simse_writeFile(const Str& path, const Str& content);
Str simse_pathCanonical(const Str& path);
Bool simse_pathIsDirectory(const Str& path);
Bool simse_pathExists(const Str& path);
void simse_eprintln(const Str& text);
FileStream* simse_fileStream_open(const Str& path);

struct ns1_Counter;
// stress/counted-reference/src/main.kt:13
SIMSE_PACK_PUSH
struct ns1_Counter {
    Int value;
};
SIMSE_PACK_POP
ns1_Counter ns1__make_Counter(Int value) {
    return ns1_Counter{value};
}

Int ns1_bump(ns1_Counter* self);
Int ns1_read(Ref<ns1_Counter> box);
Int ns1_bumpThrough(Ref<ns1_Counter> box);

// stress/counted-reference/src/main.kt:14
Int ns1_bump(ns1_Counter* self) {
    Int _sm_base1;
    Int _sm_expr1;
    Int _sm_expr2;
    _sm_expr1 = self->value;
    _sm_base1 = _sm_expr1 + 1;
    self->value = _sm_base1;
    _sm_expr2 = self->value;
    return _sm_expr2;
}
// stress/counted-reference/src/main.kt:20
Int ns1_read(Ref<ns1_Counter> box) {
    Int _sm_expr1;
    _sm_expr1 = box->value;
    return _sm_expr1;
}
// stress/counted-reference/src/main.kt:26
Int ns1_bumpThrough(Ref<ns1_Counter> box) {
    Ref<ns1_Counter> again;
    Int _sm_expr1;
    again = box;
    _sm_expr1 = ns1_bump((again).get());
    return _sm_expr1;
}
// stress/counted-reference/src/main.kt:31
int main() {
    Int _sm_base1;
    Int _sm_base2;
    Int _sm_base3;
    ns1_Counter plain;
    Ref<ns1_Counter> first;
    Int _sm_expr1;
    Int bumped;
    Int _sm_expr2;
    plain = ns1__make_Counter(10);
    first = makeRef<std::remove_cvref_t<decltype((plain))>>(plain);
    _sm_expr1 = ns1_read(first);
    std::cout << std::boolalpha << (_sm_expr1) << std::endl;
    bumped = ns1_bump((first).get());
    std::cout << std::boolalpha << (bumped) << std::endl;
    _sm_base1 = plain.value;
    std::cout << std::boolalpha << (_sm_base1) << std::endl;
    _sm_base2 = first->value;
    std::cout << std::boolalpha << (_sm_base2) << std::endl;
    _sm_expr2 = ns1_bumpThrough(first);
    std::cout << std::boolalpha << (_sm_expr2) << std::endl;
    _sm_base3 = first->value;
    std::cout << std::boolalpha << (_sm_base3) << std::endl;
    return 0;
}

// Expands one run-length encoded series into `out`, which holds `count` values.
template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; // stream[0] is the series' own length
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

// Fills `table` from the pool and the two expanded series: an offset increment and a
// byte count per entry, both rebuilt by subtracting the stored value from the one before.
inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  // this entry's offset increment, rebuilt from the start series
    Int length = 0; // this entry's byte count, rebuilt from the length series
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = StrView(bytes + at, length);
    }
}

// The two monotonic clocks. `steady_clock` is the one clock the standard library
// promises cannot go backwards, which is what makes a duration between two readings
// meaningful (`impl_specs/profiling.md`).
Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

// The whole file as bytes; empty when it cannot be read.
Str simse_native_readFile(const Str& path) {
    Str result;
    FILE* file = fopen(path.c_str(), "rb");
    if (file == nullptr) return result;
    fseek(file, 0, SEEK_END);
    const int fileSize = ftell(file);
    fseek(file, 0, SEEK_SET);
    result.resize(fileSize);
    fread(result.data(), 1, fileSize, file);
    fclose(file);
    return result;
}

// Every `ext`-suffixed file under `dir`, recursively, sorted; empty when `dir` is not a
// directory. The one place the "generic separators" rule is applied, so a scanned path
// matches the same path given explicitly (e.g. `--root cppsrc` vs an explicit input
// file): this and the compiler's own dedup key both read these strings.
List<Str> simse_listFiles(const Str& dir, const Str& ext) {
    List<Str> matchingFiles;

    // The standard filesystem API works in std::string; the language works in Str
    // (`simse_toStdString` is a no-op copy when Str is std::string).
    const std::string dirText = simse_toStdString(dir);
    const std::string wantedExt = simse_toStdString(ext);

    if (!std::filesystem::exists(dirText) || !std::filesystem::is_directory(dirText)) {
        return matchingFiles;
    }
    for (const auto& entry: std::filesystem::recursive_directory_iterator(dirText)) {
        if (entry.is_regular_file() && entry.path().extension() == wantedExt) {
            matchingFiles.push_back(simse_fromStdString(entry.path().generic_string()));
        }
    }
    std::sort(matchingFiles.begin(), matchingFiles.end());
    return matchingFiles;
}

// The non-recursive form, for `import a.b.c` directory resolution.
List<Str> simse_listFilesDirect(const Str& dir, const Str& ext) {
    List<Str> files;
    std::error_code ec;
    if (!std::filesystem::is_directory(simse_toStdString(dir), ec)) {
        return files;
    }
    for (const auto& entry: std::filesystem::directory_iterator(simse_toStdString(dir), ec)) {
        if (entry.is_regular_file() && entry.path().extension() == simse_toStdString(ext)) {
            files.push_back(simse_fromStdString(entry.path().generic_string()));
        }
    }
    std::sort(files.begin(), files.end());
    return files;
}

Bool simse_writeFile(const Str& path, const Str& content) {
    FILE* out = fopen(path.c_str(), "wb");
    if (out == nullptr) {
        return false;
    }
    fwrite(content.data(), 1, content.length(), out);
    fclose(out);
    return true;
}

Str simse_pathCanonical(const Str& path) {
    std::error_code ec;
    std::filesystem::path canonical = std::filesystem::weakly_canonical(
            std::filesystem::path(simse_toStdString(path)), ec);
    return ec ? path : simse_fromStdString(canonical.string());
}

Bool simse_pathIsDirectory(const Str& path) {
    std::error_code ec;
    return std::filesystem::is_directory(simse_toStdString(path), ec);
}

Bool simse_pathExists(const Str& path) {
    std::error_code ec;
    return std::filesystem::exists(simse_toStdString(path), ec);
}

void simse_eprintln(const Str& text) {
    fprintf(stderr, "%s\n", text.c_str());
}

// The stream's own operations (`readLine`, `readLineInto`, `readLineView`, `fileSize`,
// `close`) are the `filestream` section below: the emitter calls a handle's methods as
// members, and the struct that declares them is cppsrc/rtl/filestream.hpp. Only the
// constructor-like `open` lives here, as a free function.
FileStream* simse_fileStream_open(const Str& path) {
    auto* stream = new FileStream();
    stream->file.open(simse_toStdString(path), std::ios::binary);
    if (!stream->file.is_open()) {
        delete stream;
        return nullptr;
    }
    stream->chunk.resize(256 * 1024);
    std::error_code ec;
    const std::uintmax_t size = std::filesystem::file_size(simse_toStdString(path), ec);
    stream->size = ec ? 0 : (Int64) size;
    return stream;
}
