// Generated by the Simse compiler. Do not edit.
#include "src/rtl/simse.hpp"
#include <type_traits>


template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, Span<Char>* table, Int count);

#include <chrono>

Int64 simse_nowMillis();
Int64 simse_nowMicros();
Int64 simse_nowNanos();

template <class T>
struct Span;
struct ns1_Cell;
// src/rtl
SIMSE_PACK_PUSH
template <class T>
struct Span {
    T* ptr;
    Int len;
};
SIMSE_PACK_POP
// stress/ref-promote/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Cell {
    Int value;
};
SIMSE_PACK_POP

#include <cstdint>
#include <type_traits>


template <class T>
void simse_list_append(List<T>& self, const std::type_identity_t<T>& value);

template <class T>
List<T> simse_listOf(const List<T>* values);

template <class T>
void simse_list_removeAt(List<T>& self, Int index);
template <class T>
void simse_list_removeRange(List<T>& self, Int start, Int end);
template <class T>
Int simse_array_count(const Array<T>& self);
template <class T>
Array<T> simse_list_toArray(const List<T>& self);
template <class T>
List<T> simse_array_toList(const Array<T>& self);
template <class T>
Array<T> simse_arrayEmpty();

void simse_str_append(Str& self, Char value);
void simse_str_appendStr(Str& self, const Str& value);
void simse_str_appendStrPtr(Str& self, const Str* value);
void simse_str_reserve(Str& self, Int count);
Str simse_int_toString(Int self);

#include <cstdio>

inline void simse_write(const Str& value, FILE* out) {
    std::fwrite(value.data(), 1, (std::size_t) value.size(), out);
}

inline void simse_write(Span<Char> value, FILE* out) {
    std::fwrite(value.ptr, 1, (std::size_t) value.len, out);
}

inline void simse_write(bool value, FILE* out) {
    std::fputs(value ? "true" : "false", out);
}

inline void simse_write(char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(signed char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(unsigned char value, FILE* out) {
    std::fputc((int) value, out);
}

inline void simse_write(short value, FILE* out) {
    std::fprintf(out, "%d", (int) value);
}

inline void simse_write(int value, FILE* out) {
    std::fprintf(out, "%d", value);
}

inline void simse_write(long value, FILE* out) {
    std::fprintf(out, "%ld", value);
}

inline void simse_write(long long value, FILE* out) {
    std::fprintf(out, "%lld", value);
}

inline void simse_write(float value, FILE* out) {
    std::fprintf(out, "%g", (double) value);
}

inline void simse_write(double value, FILE* out) {
    std::fprintf(out, "%g", value);
}

template <class T>
inline void simse_print(const T& value, FILE* out) {
    simse_write(value, out);
}

template <class T>
inline void simse_println(const T& value, FILE* out) {
    simse_write(value, out);
    std::fputc('\n', out);
}

void ns1_add(ns1_Cell* self, Int n);
Int ns1_bump();
Ref<ns1_Cell> ns1_make();
Int ns1_point();

// stress/ref-promote/src/main.kt
void ns1_add(ns1_Cell* self, Int n) {
    Int _sm_base1, _sm_expr1;
    _sm_expr1 = self->value;
    _sm_base1 = _sm_expr1 + n;
    self->value = _sm_base1;
}
// stress/ref-promote/src/main.kt
Int ns1_bump() {
    Int _sm_base1, _sm_expr1, _sm_expr2;
    ns1_Cell _sm_stk0;
    ns1_Cell* c;
    _sm_stk0 = ns1_Cell{7};
    c = &_sm_stk0;
    _sm_expr1 = c->value;
    _sm_base1 = _sm_expr1 + 1;
    c->value = _sm_base1;
    _sm_expr2 = c->value;
    return _sm_expr2;
}
// stress/ref-promote/src/main.kt
Ref<ns1_Cell> ns1_make() {
    Int v;
    Ref<ns1_Cell> c;
    v = 10;
    c = makeRef<ns1_Cell>(v);
    return c;
}
// stress/ref-promote/src/main.kt
Int ns1_point() {
    Int _sm_base1, _sm_expr1, _sm_expr2;
    ns1_Cell _sm_stk0;
    ns1_Cell* c, * p;
    _sm_stk0 = ns1_Cell{3};
    c = &_sm_stk0;
    p = c;
    _sm_expr1 = p->value;
    _sm_base1 = _sm_expr1 + 1;
    p->value = _sm_base1;
    _sm_expr2 = c->value;
    return _sm_expr2;
}
// stress/ref-promote/src/main.kt
int main() {
    Int _sm_base1, _sm_base2, _sm_base3, _sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr5,
        _sm_expr6;
    List<Int> _sm_base4;
    Ref<ns1_Cell> p;
    ns1_Cell _sm_stk3;
    ns1_Cell* c;
    List<Int>* xs;
    _sm_expr1 = ns1_bump();
    simse_println((_sm_expr1), stdout);
    p = ns1_make();
    _sm_expr2 = p->value;
    _sm_base1 = _sm_expr2 + 5;
    p->value = _sm_base1;
    _sm_base2 = p->value;
    simse_println((_sm_base2), stdout);
    _sm_stk3 = ns1_Cell{1};
    c = &_sm_stk3;
    ns1_add(c, 4);
    _sm_base3 = c->value;
    simse_println((_sm_base3), stdout);
    _sm_base4 = List<Int>();
    xs = &_sm_base4;
    simse_list_append((*xs), 3);
    simse_list_append((*xs), 4);
    _sm_expr3 = (*xs)[0];
    _sm_expr4 = (*xs)[1];
    _sm_expr5 = _sm_expr3 + _sm_expr4;
    simse_println((_sm_expr5), stdout);
    _sm_expr6 = ns1_point();
    simse_println((_sm_expr6), stdout);
    return 0;
}

template <class T>
inline void simse_list_append(List<T>& self, const std::type_identity_t<T>& value) {
    self.push_back(value);
}

template <class T>
inline List<T> simse_listOf(const List<T>* values) {
    return *values;
}

template <class T>
inline void simse_list_removeAt(List<T>& self, Int index) {
    self.erase(self.begin() + index);
}

template <class T>
inline void simse_list_removeRange(List<T>& self, Int start, Int end) {
    self.erase(self.begin() + start, self.begin() + end);
}

template <class T>
inline Int simse_array_count(const Array<T>& self) {
    return self.count();
}

template <class T>
inline Array<T> simse_list_toArray(const List<T>& self) {
    const Int count = self.size();
    if (count <= 0) {
        return Array<T>();
    }
    Array<T> result(count);
    for (Int i = 0; i < count; i++) {
        result[i] = self[i];
    }
    return result;
}

template <class T>
inline List<T> simse_array_toList(const Array<T>& self) {
    List<T> result;
    const Int count = self.count();
    result.reserve(count);
    for (Int i = 0; i < count; i++) {
        result.push_back(self[i]);
    }
    return result;
}

template <class T>
inline Array<T> simse_arrayEmpty() {
    return Array<T>();
}

inline void simse_str_append(Str& self, Char value) {
    self.push_back(static_cast<char>(value));
}

inline void simse_str_appendStr(Str& self, const Str& value) {
    self.append(value);
}

inline void simse_str_appendStrPtr(Str& self, const Str* value) {
    if (value != nullptr) self.append(*value);
}

inline void simse_str_reserve(Str& self, Int count) {
    self.reserve((Str::size_type) count);
}

inline Str simse_int_toString(Int self) {
    return std::to_string(self);
}

template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; 
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, Span<Char>* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  
    Int length = 0; 
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = Span<Char>{bytes + at, length};
    }
}

Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

Int64 simse_nowNanos() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
}

inline SmString::SmString(const Span<Char>& view)
    : SmString(reinterpret_cast<const char*>(view.ptr), view.len) {
}
