// Generated by the Simse compiler. Do not edit.
#include "cppsrc/rtl/simse.hpp"
#include <iostream>
#include <type_traits>

// stress/smgen-cpp/src/main.kt:9
Str simse_str_trim(const Str& text);
// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 1;
static const char __sm_stringPool[] =
    "  padded  " 
;
static const Int16 __sm_stringStarts[] = {1,1,0};
static const Int16 __sm_stringLens[] = {1,1,-10};
static_assert(sizeof(__sm_stringPool) - 1 == 10, "the string pool and its length index disagree");
static StrView __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

// stress/smgen-cpp/src/main.kt:11
int main() {
    Str _sm_expr1;
    _sm_expr1 = simse_str_trim(__sm_stringTable[0]);
    std::cout << std::boolalpha << (_sm_expr1) << std::endl;
    return 0;
}
