// Generated by the Simse compiler. Do not edit.
#include "src/rtl/simse.hpp"
#include <type_traits>


template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, Span<Char>* table, Int count);

#include <chrono>

Int64 simse_nowMillis();
Int64 simse_nowMicros();
Int64 simse_nowNanos();

template <class T>
struct Span;
template <class T>
struct Opt;
template <class T>
struct Res;
struct ns1_Point;
struct ns1_Label;
struct ns1_Shape;
// src/rtl
SIMSE_PACK_PUSH
template <class T>
struct Span {
    T* ptr;
    Int len;
};
SIMSE_PACK_POP
// src/rtl
enum class SmOptTypes { None, Value };
inline SmOptTypes simse_SmOptTypes_fromInt(Int value) { return (SmOptTypes) value; }
// src/rtl
SIMSE_PACK_PUSH
template <Bool SmManaged, class T> struct SmOptStorage;
template <class T> struct SmOptStorage<false, T> {
    SmOptTypes _type = SmOptTypes::None;
    union {
        T Value;
    };
    SmOptStorage() {}
    void setValue(T value) {
        _type = SmOptTypes::Value;
        Value = std::move(value);
    }
    void setNone() {
        _type = SmOptTypes::None;
    }
};
template <class T> struct SmOptStorage<true, T> {
    SmOptTypes _type = SmOptTypes::None;
    union {
        T Value;
    };
    SmOptStorage() {}
    SmOptStorage(const SmOptStorage& other) { this->copyFrom(other); }
    SmOptStorage(SmOptStorage&& other) noexcept { this->moveFrom(other); }
    ~SmOptStorage() { this->destroyActive(); }
    SmOptStorage& operator=(const SmOptStorage& other) {
        if (this != &other) {
            this->destroyActive();
            this->copyFrom(other);
        }
        return *this;
    }
    SmOptStorage& operator=(SmOptStorage&& other) noexcept {
        if (this != &other) {
            this->destroyActive();
            this->moveFrom(other);
        }
        return *this;
    }
    void destroyActive() {
        switch (this->_type) {
            case SmOptTypes::Value: simse_destroy(this->Value); break;
            default: break;
        }
        this->_type = SmOptTypes::None;
    }
    void copyFrom(const SmOptStorage& other) {
        switch (other._type) {
            case SmOptTypes::Value: ::new ((void *) &this->Value) T(other.Value); this->_type = SmOptTypes::Value; break;
            default: break;
        }
    }
    void moveFrom(SmOptStorage& other) {
        switch (other._type) {
            case SmOptTypes::Value: ::new ((void *) &this->Value) T(std::move(other.Value)); this->_type = SmOptTypes::Value; break;
            default: break;
        }
    }
    void setValue(T value) {
        if (_type == SmOptTypes::Value) {
            Value = std::move(value);
            return;
        }
        this->destroyActive();
        _type = SmOptTypes::Value;
        ::new ((void *) &Value) T(std::move(value));
    }
    void setNone() {
        this->destroyActive();
    }
};
template <class T>
struct Opt : SmOptStorage<SmUnionManaged<T>, T> {
};
SIMSE_PACK_POP
template <class T>
inline Bool operator==(const Opt<T>& self, SmOptTypes tag) { return self._type == tag; }
template <class T>
inline Bool operator==(const Opt<T>* self, SmOptTypes tag) { return self->_type == tag; }
template <class T>
inline Bool operator!=(const Opt<T>& self, SmOptTypes tag) { return self._type != tag; }
template <class T>
inline Bool operator!=(const Opt<T>* self, SmOptTypes tag) { return self->_type != tag; }
template <class T>
inline SmOptTypes getTypeOf(Opt<T>* self) {
    return self->_type;
}
template <class T>
inline Bool isOfType(Opt<T>* self, SmOptTypes typeToCheck) {
    return self->_type == typeToCheck;
}
template <class T>
inline void setNone(Opt<T>* self) {
    self->setNone();
}
template <class T>
inline void initByValue(Opt<T>* self) {
    self->setNone();
}
template <class T>
inline void setValue(Opt<T>* self, T value) {
    self->setValue(std::move(value));
}
template <class T>
inline T* getValue(Opt<T>* self) {
    if (self->_type == SmOptTypes::Value) {
        return &self->Value;
    }
    return nullptr;
}
template <class T>
inline void initByValue(Opt<T>* self, T value) {
    self->setValue(std::move(value));
}
// src/rtl
enum class SmResTypes { None, Value, Error };
inline SmResTypes simse_SmResTypes_fromInt(Int value) { return (SmResTypes) value; }
// src/rtl
SIMSE_PACK_PUSH
template <Bool SmManaged, class T> struct SmResStorage;
template <class T> struct SmResStorage<false, T> {
    SmResTypes _type = SmResTypes::None;
    union {
        T Value;
        Str Error;
    };
    SmResStorage() {}
    void setValue(T value) {
        _type = SmResTypes::Value;
        Value = std::move(value);
    }
    void setError(Str value) {
        _type = SmResTypes::Error;
        Error = std::move(value);
    }
    void setNone() {
        _type = SmResTypes::None;
    }
};
template <class T> struct SmResStorage<true, T> {
    SmResTypes _type = SmResTypes::None;
    union {
        T Value;
        Str Error;
    };
    SmResStorage() {}
    SmResStorage(const SmResStorage& other) { this->copyFrom(other); }
    SmResStorage(SmResStorage&& other) noexcept { this->moveFrom(other); }
    ~SmResStorage() { this->destroyActive(); }
    SmResStorage& operator=(const SmResStorage& other) {
        if (this != &other) {
            this->destroyActive();
            this->copyFrom(other);
        }
        return *this;
    }
    SmResStorage& operator=(SmResStorage&& other) noexcept {
        if (this != &other) {
            this->destroyActive();
            this->moveFrom(other);
        }
        return *this;
    }
    void destroyActive() {
        switch (this->_type) {
            case SmResTypes::Value: simse_destroy(this->Value); break;
            case SmResTypes::Error: simse_destroy(this->Error); break;
            default: break;
        }
        this->_type = SmResTypes::None;
    }
    void copyFrom(const SmResStorage& other) {
        switch (other._type) {
            case SmResTypes::Value: ::new ((void *) &this->Value) T(other.Value); this->_type = SmResTypes::Value; break;
            case SmResTypes::Error: ::new ((void *) &this->Error) Str(other.Error); this->_type = SmResTypes::Error; break;
            default: break;
        }
    }
    void moveFrom(SmResStorage& other) {
        switch (other._type) {
            case SmResTypes::Value: ::new ((void *) &this->Value) T(std::move(other.Value)); this->_type = SmResTypes::Value; break;
            case SmResTypes::Error: ::new ((void *) &this->Error) Str(std::move(other.Error)); this->_type = SmResTypes::Error; break;
            default: break;
        }
    }
    void setValue(T value) {
        if (_type == SmResTypes::Value) {
            Value = std::move(value);
            return;
        }
        this->destroyActive();
        _type = SmResTypes::Value;
        ::new ((void *) &Value) T(std::move(value));
    }
    void setError(Str value) {
        if (_type == SmResTypes::Error) {
            Error = std::move(value);
            return;
        }
        this->destroyActive();
        _type = SmResTypes::Error;
        ::new ((void *) &Error) Str(std::move(value));
    }
    void setNone() {
        this->destroyActive();
    }
};
template <class T>
struct Res : SmResStorage<SmUnionManaged<T, Str>, T> {
};
SIMSE_PACK_POP
template <class T>
inline Bool operator==(const Res<T>& self, SmResTypes tag) { return self._type == tag; }
template <class T>
inline Bool operator==(const Res<T>* self, SmResTypes tag) { return self->_type == tag; }
template <class T>
inline Bool operator!=(const Res<T>& self, SmResTypes tag) { return self._type != tag; }
template <class T>
inline Bool operator!=(const Res<T>* self, SmResTypes tag) { return self->_type != tag; }
template <class T>
inline SmResTypes getTypeOf(Res<T>* self) {
    return self->_type;
}
template <class T>
inline Bool isOfType(Res<T>* self, SmResTypes typeToCheck) {
    return self->_type == typeToCheck;
}
template <class T>
inline void setNone(Res<T>* self) {
    self->setNone();
}
template <class T>
inline void initByValue(Res<T>* self) {
    self->setNone();
}
template <class T>
inline void setValue(Res<T>* self, T value) {
    self->setValue(std::move(value));
}
template <class T>
inline T* getValue(Res<T>* self) {
    if (self->_type == SmResTypes::Value) {
        return &self->Value;
    }
    return nullptr;
}
template <class T>
inline void initByValue(Res<T>* self, T value) {
    self->setValue(std::move(value));
}
template <class T>
inline void setError(Res<T>* self, Str value) {
    self->setError(std::move(value));
}
template <class T>
inline Str* getError(Res<T>* self) {
    if (self->_type == SmResTypes::Error) {
        return &self->Error;
    }
    return nullptr;
}
template <class T>
requires (!std::is_same_v<Str, T>)
inline void initByValue(Res<T>* self, Str value) {
    self->setError(std::move(value));
}
// stress/json/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Point {
    Int x;
    Int y;
};
SIMSE_PACK_POP
// stress/json/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Label {
    Str text;
    Bool flagged;
};
SIMSE_PACK_POP
// stress/json/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Shape {
    Str name;
    ns1_Point corner;
    ns1_Label tag;
};
SIMSE_PACK_POP

// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 13;
static const char __sm_stringPool[] =
    "a\"b\\c" "flagged" "corner" "false" "plain" "name" "text" "true" "box" "tag" "x" "y" "{" 
;
static const Int16 __sm_stringStarts[] = {13,3,0,-5,-2,1,2,1,2,0,1,1,2,0,4,1,0,2,0};
static const Int16 __sm_stringLens[] = {13,2,-5,-2,1,2,1,2,0,1,1,2,0,3,1,0,2,1,2,0};
static_assert(sizeof(__sm_stringPool) - 1 == 49, "the string pool and its length index disagree");
static Span<Char> __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

#include <cstdint>
#include <type_traits>


template <class T>
void simse_list_append(List<T>& self, const std::type_identity_t<T>& value);

template <class T>
List<T> simse_listOf(const List<T>* values);

template <class T>
void simse_list_removeAt(List<T>& self, Int index);
template <class T>
void simse_list_removeRange(List<T>& self, Int start, Int end);
template <class T>
Int simse_array_count(const Array<T>& self);
template <class T>
Array<T> simse_list_toArray(const List<T>& self);
template <class T>
List<T> simse_array_toList(const Array<T>& self);
template <class T>
Array<T> simse_arrayEmpty();

void simse_str_append(Str& self, Char value);
void simse_str_appendStr(Str& self, const Str& value);
void simse_str_appendStrPtr(Str& self, const Str* value);
void simse_str_reserve(Str& self, Int count);
Str simse_int_toString(Int self);

Int simse_lenOf(const Str& self);
template <class T, int N>
Int simse_lenOf(const SmallVector<T, N>& self);

#include <cerrno>
#include <charconv>
#include <cstddef>
#include <cstdlib>
#include <system_error>


Char simse_str_charAt(const Str& self, Int index);

List<Str> simse_str_split(const Str& self, const Str& separator);
List<Str> simse_str_split(const Str& self, Char separator);

Int simse_str_find(const Str& self, const Str& sub);

Int simse_str_lastIndexOf(const Str& self, const Str& sub);

Str simse_str_replace(const Str& self, const Str& from, const Str& to);

Opt<Int> simse_str_toInt(const Str& self);
Opt<Float64> simse_str_toFloat(const Str& self);

void simse_str_initByValue(Str& self, const Str& value);

template <class T>
Str simse_num_toString(const T& self);
Str simse_char_toString(Char self);
Str simse_bool_toString(Bool self);

#include <algorithm>
#include <type_traits>
#include <utility>


template <class K, class V>
Dictionary<K, V> simse_dictionaryOf();

template <class K, class V>
V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                       const std::type_identity_t<V>& value);

template <class K, class V>
void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
Int simse_dict_size(const Dictionary<K, V>& self);

template <class K, class V>
List<K> simse_dict_keys(const Dictionary<K, V>& self);

template <class K, class V>
List<V> simse_dict_values(const Dictionary<K, V>& self);

template <class K, class V>
void simse_dict_clear(Dictionary<K, V>& self);

template <class T>
Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value);

template <class T, class F>
void simse_list_sort(List<T>& self, F less);

#include <cstdio>

inline void simse_write(const Str& value, FILE* out) {
    std::fwrite(value.data(), 1, (std::size_t) value.size(), out);
}

inline void simse_write(Span<Char> value, FILE* out) {
    std::fwrite(value.ptr, 1, (std::size_t) value.len, out);
}

inline void simse_write(bool value, FILE* out) {
    std::fputs(value ? "true" : "false", out);
}

inline void simse_write(char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(signed char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(unsigned char value, FILE* out) {
    std::fputc((int) value, out);
}

inline void simse_write(short value, FILE* out) {
    std::fprintf(out, "%d", (int) value);
}

inline void simse_write(int value, FILE* out) {
    std::fprintf(out, "%d", value);
}

inline void simse_write(long value, FILE* out) {
    std::fprintf(out, "%ld", value);
}

inline void simse_write(long long value, FILE* out) {
    std::fprintf(out, "%lld", value);
}

inline void simse_write(float value, FILE* out) {
    std::fprintf(out, "%g", (double) value);
}

inline void simse_write(double value, FILE* out) {
    std::fprintf(out, "%g", value);
}

template <class T>
inline void simse_print(const T& value, FILE* out) {
    simse_write(value, out);
}

template <class T>
inline void simse_println(const T& value, FILE* out) {
    simse_write(value, out);
    std::fputc('\n', out);
}

template <class T>
Int size(Span<T>* self);
template <class T>
T at(Span<T>* self, Int index);
Char charAt(Span<Char>* self, Int index);
Str substr(Span<Char>* self, Int from, Int count);
Str toString(Span<Char>* self);
Int compareTo(Span<Char>* self, Span<Char> other);
Bool equals(Span<Char>* self, Span<Char> other);
Str plus(Span<Char>* self, Span<Char> other);
template <class T>
Bool simse_optHasValue(Opt<T>* self);
template <class T>
T simse_optValue(Opt<T>* self);
template <class T>
Bool simse_resHasValue(Res<T>* self);
template <class T>
T simse_resValue(Res<T>* self);
template <class T>
Str simse_resError(Res<T>* self);
template <class T>
Opt<T> simse_optSome(T value);
template <class T>
Opt<T> simse_optNone();
template <class T>
Res<T> simse_resOk(T value);
template <class T>
Res<T> simse_resErr(Str message);
void initByValue(Str* self);
Str substr(Str* self, Int start, Int len);
Str jsonQuoted(Str value);
Str toJson(ns1_Point* self);
Str toJson(Int* self);
Str toJson(ns1_Label* self);
Str toJson(Str* self);
Str toJson(Bool* self);
Str toJson(ns1_Shape* self);

template <class T>
Int size(Span<T>* self) {
    Int _sm_expr1;
    _sm_expr1 = self->len;
    return _sm_expr1;
}
template <class T>
T at(Span<T>* self, Int index) {
    T* _sm_base1;
    _sm_base1 = self->ptr;
    auto _sm_expr1 = _sm_base1[index];
    return _sm_expr1;
}
Char charAt(Span<Char>* self, Int index) {
    Char _sm_expr1;
    _sm_expr1 = at(self, index);
    return _sm_expr1;
}
Str substr(Span<Char>* self, Int from, Int count) {
    Int len, begin, take;
    Bool _sm_expr1;
    len = size(self);
    begin = from;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr1 = begin > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = len;
    L4:;
    take = len - begin;
    _sm_expr1 = count >= 0;
    if (_sm_expr1) goto L7;
    goto L6;
    L7:;
    _sm_expr1 = count < take;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    take = count;
    L6:;
    Str out;
    _sm_expr1 = take > 0;
    if (_sm_expr1) goto L8;
    goto L9;
    L8:;
    simse_str_setBytes(out, self->ptr, begin, take);
    L9:;
    return out;
}
Str toString(Span<Char>* self) {
    Int _sm_expr1;
    Str _sm_expr2;
    _sm_expr1 = size(self);
    _sm_expr2 = substr(self, 0, _sm_expr1);
    return _sm_expr2;
}
Int compareTo(Span<Char>* self, Span<Char> other) {
    Bool _sm_expr3, _sm_expr4, _sm_expr7;
    Int _sm_diff_2, _sm_expr8, diff;
    auto _sm_expr1 = self->len;
    auto _sm_expr2 = other.len;
    _sm_expr3 = _sm_expr1 <= _sm_expr2;
    if (_sm_expr3) goto L1;
    goto L2;
    L1:;
    _sm_diff_2 = simse_mem_compare(self->ptr, 0, other.ptr, 0, self->len);
    _sm_expr4 = _sm_diff_2 != 0;
    if (_sm_expr4) goto L3;
    goto L4;
    L3:;
    return _sm_diff_2;
    L4:;
    {
        auto _sm_expr5 = self->len;
        auto _sm_expr6 = other.len;
        _sm_expr7 = _sm_expr5 == _sm_expr6;
        if (_sm_expr7) goto L5;
        goto L6;
        L5:;
        return 0;
        L6:;
        _sm_expr8 = -1;
        return _sm_expr8;
    }
    L2:;
    diff = simse_mem_compare(self->ptr, 0, other.ptr, 0, other.len);
    _sm_expr3 = diff != 0;
    if (_sm_expr3) goto L7;
    goto L8;
    L7:;
    return diff;
    L8:;
    return 1;
}
Bool equals(Span<Char>* self, Span<Char> other) {
    Bool _sm_expr3;
    Int _sm_expr4;
    auto _sm_expr1 = self->len;
    auto _sm_expr2 = other.len;
    _sm_expr3 = _sm_expr1 != _sm_expr2;
    if (_sm_expr3) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    _sm_expr4 = simse_mem_compare(self->ptr, 0, other.ptr, 0, self->len);
    _sm_expr3 = _sm_expr4 == 0;
    return _sm_expr3;
}
Str plus(Span<Char>* self, Span<Char> other) {
    Str* _sm_base3;
    Bool _sm_expr2;
    Int at, _sm_expr4;
    Char* _sm_expr5;
    Str result;
    simse_str_setBytes(result, self->ptr, 0, self->len);
    auto _sm_expr1 = other.len;
    _sm_expr2 = _sm_expr1 > 0;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    at = simse_lenOf(result);
    {
        auto _sm_expr3 = other.len;
        _sm_expr4 = at + _sm_expr3;
        result.resize(_sm_expr4);
        _sm_base3 = &result;
        _sm_expr5 = simse_str_data(_sm_base3);
        simse_mem_copy(_sm_expr5, at, other.ptr, 0, other.len);
    }
    L2:;
    return result;
}
template <class T>
Bool simse_optHasValue(Opt<T>* self) {
    SmOptTypes _sm_base1;
    Bool _sm_expr1;
    _sm_base1 = SmOptTypes::Value;
    _sm_expr1 = isOfType(self, _sm_base1);
    return _sm_expr1;
}
template <class T>
T simse_optValue(Opt<T>* self) {
    T _sm_expr1;
    _sm_expr1 = self->Value;
    return _sm_expr1;
}
template <class T>
Bool simse_resHasValue(Res<T>* self) {
    SmResTypes _sm_base1;
    Bool _sm_expr1;
    _sm_base1 = SmResTypes::Value;
    _sm_expr1 = isOfType(self, _sm_base1);
    return _sm_expr1;
}
template <class T>
T simse_resValue(Res<T>* self) {
    T _sm_expr1;
    _sm_expr1 = self->Value;
    return _sm_expr1;
}
template <class T>
Str simse_resError(Res<T>* self) {
    Str _sm_expr1;
    _sm_expr1 = self->Error;
    return _sm_expr1;
}
template <class T>
Opt<T> simse_optSome(T value) {
    Opt<T> result;
    initByValue(simse_addressOf(result));
    setValue(simse_addressOf(result), value);
    return result;
}
template <class T>
Opt<T> simse_optNone() {
    Opt<T> result;
    initByValue(simse_addressOf(result));
    return result;
}
template <class T>
Res<T> simse_resOk(T value) {
    Res<T> result;
    initByValue(simse_addressOf(result));
    setValue(simse_addressOf(result), value);
    return result;
}
template <class T>
Res<T> simse_resErr(Str message) {
    Res<T> result;
    initByValue(simse_addressOf(result));
    setError(simse_addressOf(result), message);
    return result;
}
void initByValue(Str* self) {
}
Str substr(Str* self, Int start, Int len) {
    Str* _sm_base1;
    Int begin, _sm_expr2, count;
    Bool _sm_expr1;
    Char* _sm_expr8;
    begin = start;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr2 = simse_lenOf((*self));
    _sm_expr1 = begin > _sm_expr2;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = simse_lenOf((*self));
    L4:;
    _sm_expr2 = simse_lenOf((*self));
    count = _sm_expr2 - begin;
    _sm_expr1 = len >= 0;
    if (_sm_expr1) goto L7;
    goto L6;
    L7:;
    _sm_expr1 = len < count;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    count = len;
    L6:;
    Str out;
    _sm_expr1 = count > 0;
    if (_sm_expr1) goto L8;
    goto L9;
    L8:;
    _sm_base1 = self;
    _sm_expr8 = simse_str_data(_sm_base1);
    simse_str_setBytes(out, _sm_expr8, begin, count);
    L9:;
    return out;
}
// stress/json/src/main.kt
int main() {
    ns1_Point p, _sm_expr3;
    Str _sm_expr1, _sm_expr2, _sm_expr5;
    ns1_Label label, _sm_expr4;
    ns1_Shape shape;
    p = ns1_Point{1, 2};
    _sm_expr1 = toJson(simse_addressOf(p));
    simse_println((_sm_expr1), stdout);
    label = ns1_Label{__sm_stringTable[0], true};
    _sm_expr2 = toJson(simse_addressOf(label));
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = ns1_Point{3, 4};
    _sm_expr4 = ns1_Label{__sm_stringTable[4], false};
    shape = ns1_Shape{__sm_stringTable[8], _sm_expr3, _sm_expr4};
    _sm_expr5 = toJson(simse_addressOf(shape));
    simse_println((_sm_expr5), stdout);
    return 0;
}
// <generated>/kt.kt
Str jsonQuoted(Str value) {
    Str out;
    Int i, _sm_expr1;
    Bool _sm_expr2;
    Char ch;
    out = Str();
    simse_str_append(out, '"');
    i = 0;
    L1:;
    _sm_expr1 = simse_lenOf(value);
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    ch = simse_str_charAt(value, i);
    _sm_expr2 = ch == '"';
    if (_sm_expr2) goto L3;
    goto L4;
    L3:;
    simse_str_append(out, '\\');
    simse_str_append(out, '"');
    goto L17;
    L4:;
    _sm_expr2 = ch == '\\';
    if (_sm_expr2) goto L6;
    goto L7;
    L6:;
    simse_str_append(out, '\\');
    simse_str_append(out, '\\');
    goto L17;
    L7:;
    _sm_expr2 = ch == '\n';
    if (_sm_expr2) goto L9;
    goto L10;
    L9:;
    simse_str_append(out, '\\');
    simse_str_append(out, 'n');
    goto L17;
    L10:;
    _sm_expr2 = ch == '\r';
    if (_sm_expr2) goto L12;
    goto L13;
    L12:;
    simse_str_append(out, '\\');
    simse_str_append(out, 'r');
    goto L17;
    L13:;
    _sm_expr2 = ch == '\t';
    if (_sm_expr2) goto L15;
    goto L16;
    L15:;
    simse_str_append(out, '\\');
    simse_str_append(out, 't');
    goto L17;
    L16:;
    simse_str_append(out, ch);
    L17:;
    i = i + 1;
    goto L1;
    L2:;
    simse_str_append(out, '"');
    return out;
}
// <generated>/kt.kt
Str toJson(ns1_Point* self) {
    Int* _sm_base1, * _sm_base2;
    Str out, _sm_expr1, _sm_expr2;
    out = __sm_stringTable[12];
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[10]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base1 = simse_addressOf(self->x);
    _sm_expr1 = toJson(_sm_base1);
    simse_str_appendStr(out, _sm_expr1);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[11]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base2 = simse_addressOf(self->y);
    _sm_expr2 = toJson(_sm_base2);
    simse_str_appendStr(out, _sm_expr2);
    simse_str_append(out, '}');
    return out;
}
// <generated>/kt.kt
Str toJson(Int* self) {
    Str _sm_expr1;
    _sm_expr1 = simse_int_toString((*self));
    return _sm_expr1;
}
// <generated>/kt.kt
Str toJson(ns1_Label* self) {
    Str* _sm_base1;
    Bool* _sm_base2;
    Str out, _sm_expr1, _sm_expr2;
    out = __sm_stringTable[12];
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[6]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base1 = simse_addressOf(self->text);
    _sm_expr1 = toJson(_sm_base1);
    simse_str_appendStr(out, _sm_expr1);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[1]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base2 = simse_addressOf(self->flagged);
    _sm_expr2 = toJson(_sm_base2);
    simse_str_appendStr(out, _sm_expr2);
    simse_str_append(out, '}');
    return out;
}
// <generated>/kt.kt
Str toJson(Str* self) {
    Str _sm_expr1;
    _sm_expr1 = jsonQuoted((*self));
    return _sm_expr1;
}
// <generated>/kt.kt
Str toJson(Bool* self) {
    if ((*self)) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[7];
    L2:;
    return __sm_stringTable[3];
}
// <generated>/kt.kt
Str toJson(ns1_Shape* self) {
    Str* _sm_base1;
    ns1_Point* _sm_base2;
    ns1_Label* _sm_base3;
    Str out, _sm_expr1, _sm_expr2, _sm_expr3;
    out = __sm_stringTable[12];
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[5]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base1 = simse_addressOf(self->name);
    _sm_expr1 = toJson(_sm_base1);
    simse_str_appendStr(out, _sm_expr1);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[2]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base2 = simse_addressOf(self->corner);
    _sm_expr2 = toJson(_sm_base2);
    simse_str_appendStr(out, _sm_expr2);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[9]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base3 = simse_addressOf(self->tag);
    _sm_expr3 = toJson(_sm_base3);
    simse_str_appendStr(out, _sm_expr3);
    simse_str_append(out, '}');
    return out;
}

template <class T>
inline void simse_list_append(List<T>& self, const std::type_identity_t<T>& value) {
    self.push_back(value);
}

template <class T>
inline List<T> simse_listOf(const List<T>* values) {
    return *values;
}

template <class T>
inline void simse_list_removeAt(List<T>& self, Int index) {
    self.erase(self.begin() + index);
}

template <class T>
inline void simse_list_removeRange(List<T>& self, Int start, Int end) {
    self.erase(self.begin() + start, self.begin() + end);
}

template <class T>
inline Int simse_array_count(const Array<T>& self) {
    return self.count();
}

template <class T>
inline Array<T> simse_list_toArray(const List<T>& self) {
    const Int count = self.size();
    if (count <= 0) {
        return Array<T>();
    }
    Array<T> result(count);
    for (Int i = 0; i < count; i++) {
        result[i] = self[i];
    }
    return result;
}

template <class T>
inline List<T> simse_array_toList(const Array<T>& self) {
    List<T> result;
    const Int count = self.count();
    result.reserve(count);
    for (Int i = 0; i < count; i++) {
        result.push_back(self[i]);
    }
    return result;
}

template <class T>
inline Array<T> simse_arrayEmpty() {
    return Array<T>();
}

inline void simse_str_append(Str& self, Char value) {
    self.push_back(static_cast<char>(value));
}

inline void simse_str_appendStr(Str& self, const Str& value) {
    self.append(value);
}

inline void simse_str_appendStrPtr(Str& self, const Str* value) {
    if (value != nullptr) self.append(*value);
}

inline void simse_str_reserve(Str& self, Int count) {
    self.reserve((Str::size_type) count);
}

inline Str simse_int_toString(Int self) {
    return std::to_string(self);
}

inline Int simse_lenOf(const Str& self) {
    return self.size();
}

template <class T, int N>
inline Int simse_lenOf(const SmallVector<T, N>& self) {
    return self.size();
}

inline Char simse_str_charAt(const Str& self, Int index) {
    return (Char) self[index];
}

inline List<Str> simse_str_split(const Str& self, const Str& separator) {
    List<Str> parts;
    if (separator.empty()) {
        parts.push_back(self);
        return parts;
    }
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + separator.size();
    }
    return parts;
}

inline Int simse_count_char_in_str(const Str* self, char ch) {
    Int count = 0;
    const char* data = self->data();
    Int len = self->size();
    for (Int i = 0; i < len; i++) {
        if (data[i] == ch) {
            count++;
        }
    }
    return count;
}

inline List<Str> simse_str_split(const Str& self, Char separator) {
    List<Str> parts;
    parts.reserve(simse_count_char_in_str(&self, separator));
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + 1;
    }
    return parts;
}

inline Int simse_str_find(const Str& self, const Str& sub) {
    Int found = self.find(sub);
    return found == Str::npos ? -1 : found;
}

inline Int simse_str_lastIndexOf(const Str& self, const Str& sub) {
    Int found = self.rfind(sub);
    return found == Str::npos ? -1 : found;
}

inline Str simse_str_replace(const Str& self, const Str& from, const Str& to) {
    if (from.empty()) return self;
    Str result;
    Int pos = 0;
    while (true) {
        Int found = self.find(from, pos);
        if (found == Str::npos) {
            result.append(self, pos, Str::npos);
            break;
        }
        result.append(self, pos, found - pos);
        result += to;
        pos = found + from.size();
    }
    return result;
}

inline Opt<Int> simse_str_toInt(const Str& self) {
    if (self.empty()) return Opt<Int>();
    Int value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Int>();
    Opt<Int> result;
    result.setValue(value);
    return result;
}

inline Opt<Float64> simse_str_toFloat(const Str& self) {
    if (self.empty()) return Opt<Float64>();
    const char* begin = self.data();
    char* end = nullptr;
    errno = 0;
    const Float64 value = std::strtod(begin, &end);
    if (end != begin + self.size() || errno == ERANGE) return Opt<Float64>();
    Opt<Float64> result;
    result.setValue(value);
    return result;
}

inline void simse_str_initByValue(Str& self, const Str& value) {
    self = value;
}

template <class T>
inline Str simse_num_toString(const T& self) {
    return std::to_string(self);
}

inline Str simse_char_toString(Char self) {
    return std::to_string((int) self);
}

inline Str simse_bool_toString(Bool self) {
    return self ? "true" : "false";
}

template <class K, class V>
inline Dictionary<K, V> simse_dictionaryOf() {
    return Dictionary<K, V>();
}

template <class K, class V>
inline V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return self.valuePtr(key);
}

template <class K, class V>
inline Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    const V* found = simse_dict_getPtr(self, key);
    if (found == nullptr) return Opt<V>();
    Opt<V> result;
    result.setValue(*found);
    return result;
}

template <class K, class V>
inline Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return simse_dict_getPtr(self, key) != nullptr;
}

template <class K, class V>
inline void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                              const std::type_identity_t<V>& value) {
    self.insert_or_assign(key, value);
}

template <class K, class V>
inline void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    self.erase(key);
}

template <class K, class V>
inline Int simse_dict_size(const Dictionary<K, V>& self) {
    return (Int) self.size();
}

template <class K, class V>
inline List<K> simse_dict_keys(const Dictionary<K, V>& self) {
    List<K> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.first);
    return out;
}

template <class K, class V>
inline List<V> simse_dict_values(const Dictionary<K, V>& self) {
    List<V> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.second);
    return out;
}

template <class K, class V>
inline void simse_dict_clear(Dictionary<K, V>& self) {
    self.clear();
}

template <class T>
inline Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value) {
    for (const T& item : self) {
        if (item == value) return true;
    }
    return false;
}

template <class T, class F>
inline void simse_list_sort(List<T>& self, F less) {
    Func<Bool(T*, T*)> fn = less;
    std::sort(self.begin(), self.end(), [&fn](const T& a, const T& b) {
        return fn(const_cast<T*>(&a), const_cast<T*>(&b));
    });
}

template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; 
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, Span<Char>* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  
    Int length = 0; 
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = Span<Char>{bytes + at, length};
    }
}

Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

Int64 simse_nowNanos() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
}

inline SmString::SmString(const Span<Char>& view)
    : SmString(reinterpret_cast<const char*>(view.ptr), view.len) {
}
