// Generated by the Simse compiler. Do not edit.
#include "cppsrc/rtl/simse.hpp"
#include <type_traits>

// The string-literal pool's decoder (impl_specs/rtl-abi.md, "String literals: one
// table"): the emitter writes one pool of bytes plus two run-length encoded index
// series - where each entry starts and how long it is - and this expands them into the
// `StrView` per entry, once, before `main` runs. It was cppsrc/rtl/strtable.hpp.
//
// Six things are deliberate in the shape the emitter writes:
//
//  - **Both series are stored as "what to subtract from the previous value"**, with an
//    implicit 0 before the first entry: `value[i] = value[i-1] - series[i]`. The
//    literals are ordered longest first, so a length series descends slowly and a
//    *difference* of it is a small number - mostly 0 between the many literals of equal
//    length (85% of them on the compiler's own table).
//  - **Each series is run-length encoded**: its length first, then alternating blocks of
//    non-repeating values (a count, then that many values) and of runs (a count, then
//    that many `times, value` pairs), until the length is filled. The element type is a
//    template parameter because the emitter picks the width: `Int16` when every number
//    fits, `Int` otherwise.
//  - The pool is the literal texts themselves, adjacent, so the C++ compiler decodes
//    every escape and the emitter's decoding only has to agree about *how many bytes* an
//    escape costs. The emitted `static_assert` on the pool's `sizeof` is the check.
//  - The series are expanded into *stack* arrays in the initializer and dropped when it
//    returns: no heap, and the encoded statics are all the program carries.
//  - An entry is a 12-byte `StrView`, not the 32-byte owning `Str` the table used to
//    hold, and start-up allocates nothing for the literals.
//  - The pool is `const char` (a string literal, read-only) while `StrView` holds the
//    language's mutable `Char*`; the constness is cast away here, in the one place the
//    pool is touched, and nothing writes through it.

template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count);

#include <chrono>

// Time natives (the Simse surface is the prelude file cppsrc/rtl/rtl.kt). All three are
// monotonic clocks - never going backwards - since an arbitrary fixed point:
// `simse_nowMillis` for logging, and the finer `simse_nowMicros` / `simse_nowNanos` for
// the instrumented profiler (`cppsrc/profiling`, and the emitted `profileApp.measure(...)`
// of a `--profile` build; `--profile-nanos` picks the nanosecond clock). It was
// cppsrc/rtl/timeops.hpp, and its definitions were the last
// thing left in cppsrc/rtl/native.cpp - they are this section's now, so the clock is
// emitted into the program like any other prelude body and there is nothing to link.
// `emit: always`
// because the profiler's runtime is emitted by the *compiler* rather than named by
// the program: a `--profile` build needs these declarations whether or not the program
// ever asks for the time.
Int64 simse_nowMillis();
Int64 simse_nowMicros();
Int64 simse_nowNanos();

// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 13;
static const char __sm_stringPool[] =
    "a\"b\\c" "flagged" "corner" "false" "plain" "name" "text" "true" "box" "tag" "x" "y" "{" 
;
static const Int16 __sm_stringStarts[] = {13,3,0,-5,-2,1,2,1,2,0,1,1,2,0,4,1,0,2,0};
static const Int16 __sm_stringLens[] = {13,2,-5,-2,1,2,1,2,0,1,1,2,0,3,1,0,2,1,2,0};
static_assert(sizeof(__sm_stringPool) - 1 == 49, "the string pool and its length index disagree");
static StrView __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

// What a view's byte operations still need from C++ (specs/built-in-types.md, "Views").
// The byte work itself - `find`/`indexOf`, `startsWith`/`startsWithPtr`, `substr`/`toString`
// - is Simse now, in cppsrc/rtl/StrView.kt over the span and the intrinsics
// (cppsrc/rtl/intrinsics.kt). What remains here is the `Span` member passthroughs, which
// cannot be Simse without shadowing the member they call, and `spanOfStr`, whose two
// overloads are picked by C++ overload resolution at the desugar's site (Parser.kt's
// `parseWhen`) rather than by a declaration - so a declaration reaches this section, and a
// program that calls one pays for this text (`sourcegen/ResGen.kt`).
//
// `StrView` *is* a `Span<Char>`, so `self.len`, `self[i]` and `self.slice(...)` below are
// the span's own members (cppsrc/rtl/span.hpp) - and `at` is *not* an operation of its
// own: the span's member serves it (cppsrc/rtl/StrView.kt), as `atPtr` is the
// language's (cppsrc/rtl/Span.kt).
Int simse_strView_size(StrView self);
Bool simse_strView_isEmpty(StrView self);
StrView simse_strView_slice(StrView self, Int start);
StrView simse_strView_slice(StrView self, Int start, Int count);
Char simse_strView_charAt(StrView self, Int index);
StrView simse_spanOfStr(Str* text);
StrView simse_spanOfStr(StrView view);

#include <cstdint>
#include <type_traits>

// The List/Array/Str primitives behind the prelude (impl_specs/native-interop.md), moved
// out of cppsrc/rtl/listops.hpp. Index and range errors are unchecked, matching the
// language's no-exceptions policy: `removeAt`/`removeRange` with an out-of-range index is
// undefined behavior (specs/language-decisions.md).

// Appends `value` to the end of `self`. The value is a non-deduced context so a literal
// argument (e.g. a `const char[]`) converts to the element type instead of making `T`
// ambiguous.
template <class T>
void simse_list_append(List<T>& self, const std::type_identity_t<T>& value);

// The list literal's fallback (cppsrc/rtl/rtl.kt): the compiler turns
// `listOf<Str>("a", "b")` into the construction itself, so this runs only for a position
// with no destination slot.
template <class T>
List<T> simse_listOf(const List<T>* values);

template <class T>
void simse_list_removeAt(List<T>& self, Int index);
template <class T>
void simse_list_removeRange(List<T>& self, Int start, Int end);
template <class T>
Int simse_array_count(const Array<T>& self);
template <class T>
Array<T> simse_list_toArray(const List<T>& self);
template <class T>
List<T> simse_array_toList(const Array<T>& self);
template <class T>
Array<T> simse_arrayEmpty();

void simse_str_append(Str& self, Char value);
void simse_str_appendStr(Str& self, const Str& value);
void simse_str_appendStrPtr(Str& self, const Str* value);
void simse_str_reserve(Str& self, Int count);
Str simse_int_toString(Int self);

// `lenOf(x)`: one read-only length operation, declared `data` in the prelude
// (cppsrc/rtl/rtl.kt) so that a repeated call on an unchanged value is one call
// (cppsrc/linear/ReusePure.kt) and a borrow proof may call it (cppsrc/parser/BorrowParams.kt).
// `Str` and `List` are heavy values, so the receiver is taken by reference - a by-value
// parameter would copy one per call. The containers whose count a declaration already spells
// (`Array.count`, `Dictionary.size`, `StrView.size`) keep those declarations; this is the
// operation for the two the language cannot otherwise spell.
Int simse_lenOf(const Str& self);
template <class T, int N>
Int simse_lenOf(const SmallVector<T, N>& self);

#include <algorithm>
#include <type_traits>
#include <utility>

// The Dictionary operations and the extra List helpers behind the prelude
// (impl_specs/native-interop.md), moved out of cppsrc/rtl/dictops.hpp. The key/value
// parameters are non-deduced (`std::type_identity_t`) so that a literal argument (e.g. a
// `const char[]` key or an integer value) converts to the element type instead of making
// the template argument ambiguous.
//
// Errors are unchecked, matching the dictionary's own semantics and the language's
// no-exceptions policy: `get`/`has` on a missing key behave as documented, while `remove`
// of an absent key is a no-op.

// `dictionaryOf<K, V>()`: the empty-dictionary construction.
template <class K, class V>
Dictionary<K, V> simse_dictionaryOf();

// `d.getPtr(key)`: the value's place in the dictionary, or `null` when the key is
// absent - the read that copies nothing (`get` copies the value out, `has` is this with
// the pointer tested). The place is the dictionary's own storage, so it is valid until
// the next `insert`/`remove`/`clear` on that dictionary.
template <class K, class V>
V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.get(key)`: the value for `key`, or an empty `Opt` when absent.
template <class K, class V>
Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.has(key)`: whether `key` is present.
template <class K, class V>
Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.insert(key, value)`: insert or replace.
template <class K, class V>
void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                       const std::type_identity_t<V>& value);

// `d.remove(key)`: erase when present (a no-op otherwise).
template <class K, class V>
void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.size()`: the number of entries.
template <class K, class V>
Int simse_dict_size(const Dictionary<K, V>& self);

// `d.keys()`: the keys in the dictionary's iteration order (unspecified; sort for a
// deterministic order).
template <class K, class V>
List<K> simse_dict_keys(const Dictionary<K, V>& self);

// `d.values()`: the values in the dictionary's iteration order (unspecified).
template <class K, class V>
List<V> simse_dict_values(const Dictionary<K, V>& self);

// `d.clear()`: remove every entry.
template <class K, class V>
void simse_dict_clear(Dictionary<K, V>& self);

// `items.contains(value)`: linear membership test (`operator==` on elements).
template <class T>
Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value);

// `items.sort(less)`: in-place sort using the `(*T, *T) -> Bool` comparator. The comparator
// comes from a Simse lambda (a C++ lambda or Func), so it is a template parameter rather
// than a fixed type; it takes its two elements by pointer, so each is read where `std::sort`
// holds it instead of being copied into the comparison.
template <class T, class F>
void simse_list_sort(List<T>& self, F less);

#include <charconv>
#include <cstddef>
#include <system_error>

// The string, character, numeric-conversion and min/max operations behind the prelude
// (impl_specs/native-interop.md, specs/built-in-types.md), moved out of
// cppsrc/rtl/strops.hpp.
//
// `Str` is the inline `SmString` (smstring.hpp): every size, length and index here is the
// language's `Int` (`int32_t`), including `Str::npos`, which is `-1`. Index/range errors
// are unchecked where the underlying operation is unchecked; the `Opt`-returning
// conversions never throw.
//
// What is only a byte loop is Simse now (cppsrc/rtl/rtl.kt: `trim`, `substr`,
// `startsWith`/`endsWith`, case folding and the `Char` predicates); what stays is what
// reaches `SmString` internals (`charAt`, `find`, `lastIndexOf`, `split`, `replace`) or the
// standard library (`std::from_chars`, `std::to_string`).

// `Str.charAt(index)`: the byte at `index` (unchecked; no bounds test).
Char simse_str_charAt(const Str& self, Int index);

// `Str.split(separator)` splits on every occurrence. An empty separator returns the whole
// string as a single element. Two overloads: a separator string and a separator byte.
List<Str> simse_str_split(const Str& self, const Str& separator);
List<Str> simse_str_split(const Str& self, Char separator);

// `Str.find(sub)` returns the first index of `sub`, or -1 when absent (the language's
// spelling of C++ `npos`).
Int simse_str_find(const Str& self, const Str& sub);

// `Str.lastIndexOf(sub)` returns the last index of `sub`, or -1 when absent.
Int simse_str_lastIndexOf(const Str& self, const Str& sub);

// `Str.replace(from, to)` replaces every occurrence of `from` with `to`.
Str simse_str_replace(const Str& self, const Str& from, const Str& to);

// `Str.toInt()`/`Str.toFloat()` parse the whole string; failure (or a non-empty trailing
// remainder) yields `Opt.none()`. No exceptions: `std::from_chars` reports errors through
// its return value.
Opt<Int> simse_str_toInt(const Str& self);
Opt<Float64> simse_str_toFloat(const Str& self);

// `Str.initByValue(value)`/`Str.initByValue()`: the `initByValue` convention for `Str`
// (cppsrc/rtl/rtl.kt), setting the receiver in place.
void simse_str_initByValue(Str& self, const Str& value);
void simse_str_initByValueEmpty(Str& self);

// `Char` is a signed 8-bit integer; the checks are byte-range tests so they do not depend
// on the C locale. Space, tab, newline and carriage return count as space; form feed and
// vertical tab do not. They stay here because a body would emit a `Char* self` receiver (a
// `Char` is a scalar) while the call sites and the `CharPredicate` function values need the
// byte by value.
Bool simse_char_isDigit(Char self);
Bool simse_char_isAlpha(Char self);
Bool simse_char_isAlphaOrDigit(Char self);
Bool simse_char_isSpace(Char self);

// Numeric conversions. `Char` is an 8-bit integer, so it stringifies as a number.
template <class T>
Str simse_num_toString(const T& self);
Str simse_char_toString(Char self);
Str simse_bool_toString(Bool self);

#include <cstdio>

// `print` / `println` in C, not C++ streams. The language's formatting is its own (`fmtStr`), and
// a value is one `fwrite`/`fputs`, so a program that prints never pulls in <iostream> - and with
// it the standard streams' static construction and the locale facets that drag in. One overload
// per built-in `println` accepts, so a call spells the same whatever it prints; `bool` prints
// `true`/`false`, which is what the `std::boolalpha` the emitter used to write gave.
inline void simse_write(const Str& value, FILE* out) {
    std::fwrite(value.data(), 1, (std::size_t) value.size(), out);
}

inline void simse_write(StrView value, FILE* out) {
    std::fwrite(value.ptr, 1, (std::size_t) value.len, out);
}

inline void simse_write(bool value, FILE* out) {
    std::fputs(value ? "true" : "false", out);
}

inline void simse_write(char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(signed char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(unsigned char value, FILE* out) {
    std::fputc((int) value, out);
}

inline void simse_write(short value, FILE* out) {
    std::fprintf(out, "%d", (int) value);
}

inline void simse_write(int value, FILE* out) {
    std::fprintf(out, "%d", value);
}

inline void simse_write(long value, FILE* out) {
    std::fprintf(out, "%ld", value);
}

inline void simse_write(long long value, FILE* out) {
    std::fprintf(out, "%lld", value);
}

inline void simse_write(float value, FILE* out) {
    std::fprintf(out, "%g", (double) value);
}

inline void simse_write(double value, FILE* out) {
    std::fprintf(out, "%g", value);
}

template <class T>
inline void simse_print(const T& value, FILE* out) {
    simse_write(value, out);
}

template <class T>
inline void simse_println(const T& value, FILE* out) {
    simse_write(value, out);
    std::fputc('\n', out);
}

struct ns1_Point;
struct ns1_Label;
struct ns1_Shape;
// stress/json/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Point {
    Int x;
    Int y;
};
SIMSE_PACK_POP
// stress/json/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Label {
    Str text;
    Bool flagged;
};
SIMSE_PACK_POP
// stress/json/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Shape {
    Str name;
    ns1_Point corner;
    ns1_Label tag;
};
SIMSE_PACK_POP

Str substr(StrView* self, Int from, Int count);
Str toString(StrView* self);
Str substr(Str* self, Int start, Int len);
Str jsonQuoted(Str value);
Str toJson(ns1_Point* self);
Str toJson(Int* self);
Str toJson(ns1_Label* self);
Str toJson(Str* self);
Str toJson(Bool* self);
Str toJson(ns1_Shape* self);

Str substr(StrView* self, Int from, Int count) {
    Int len, begin, end, _sm_expr6;
    Bool _sm_expr1;
    len = simse_strView_size((*self));
    begin = from;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr1 = begin > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = len;
    L4:;
    end = begin + count;
    _sm_expr1 = count < 0;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    end = begin;
    L6:;
    _sm_expr1 = end > len;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    end = len;
    L8:;
    Str out;
    _sm_expr1 = end > begin;
    if (_sm_expr1) goto L9;
    goto L10;
    L9:;
    _sm_expr6 = end - begin;
    simse_str_setBytes(out, self->ptr, begin, _sm_expr6);
    L10:;
    return out;
}
Str toString(StrView* self) {
    Int _sm_expr1;
    Str _sm_expr2;
    _sm_expr1 = simse_strView_size((*self));
    _sm_expr2 = substr(self, 0, _sm_expr1);
    return _sm_expr2;
}
Str substr(Str* self, Int start, Int len) {
    Str* _sm_base1;
    Int begin, _sm_expr2, count;
    Bool _sm_expr1;
    Char* _sm_expr8;
    begin = start;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr2 = simse_lenOf((*self));
    _sm_expr1 = begin > _sm_expr2;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = simse_lenOf((*self));
    L4:;
    _sm_expr2 = simse_lenOf((*self));
    count = _sm_expr2 - begin;
    _sm_expr1 = len >= 0;
    if (_sm_expr1) goto L7;
    goto L6;
    L7:;
    _sm_expr1 = len < count;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    count = len;
    L6:;
    Str out;
    _sm_expr1 = count > 0;
    if (_sm_expr1) goto L8;
    goto L9;
    L8:;
    _sm_base1 = self;
    _sm_expr8 = simse_str_data(_sm_base1);
    simse_str_setBytes(out, _sm_expr8, begin, count);
    L9:;
    return out;
}
// stress/json/src/main.kt
int main() {
    ns1_Point p, _sm_expr3;
    Str _sm_expr1, _sm_expr2, _sm_expr5;
    ns1_Label label, _sm_expr4;
    ns1_Shape shape;
    p = ns1_Point{1, 2};
    _sm_expr1 = toJson(simse_addressOf(p));
    simse_println((_sm_expr1), stdout);
    label = ns1_Label{__sm_stringTable[0], true};
    _sm_expr2 = toJson(simse_addressOf(label));
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = ns1_Point{3, 4};
    _sm_expr4 = ns1_Label{__sm_stringTable[4], false};
    shape = ns1_Shape{__sm_stringTable[8], _sm_expr3, _sm_expr4};
    _sm_expr5 = toJson(simse_addressOf(shape));
    simse_println((_sm_expr5), stdout);
    return 0;
}
// <generated>/kt.kt
Str jsonQuoted(Str value) {
    Str out;
    Int i, _sm_expr1;
    Bool _sm_expr2;
    Char ch;
    out = Str();
    simse_str_append(out, '"');
    i = 0;
    L1:;
    _sm_expr1 = simse_lenOf(value);
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    ch = simse_str_charAt(value, i);
    _sm_expr2 = ch == '"';
    if (_sm_expr2) goto L3;
    goto L4;
    L3:;
    simse_str_append(out, '\\');
    simse_str_append(out, '"');
    goto L17;
    L4:;
    _sm_expr2 = ch == '\\';
    if (_sm_expr2) goto L6;
    goto L7;
    L6:;
    simse_str_append(out, '\\');
    simse_str_append(out, '\\');
    goto L17;
    L7:;
    _sm_expr2 = ch == '\n';
    if (_sm_expr2) goto L9;
    goto L10;
    L9:;
    simse_str_append(out, '\\');
    simse_str_append(out, 'n');
    goto L17;
    L10:;
    _sm_expr2 = ch == '\r';
    if (_sm_expr2) goto L12;
    goto L13;
    L12:;
    simse_str_append(out, '\\');
    simse_str_append(out, 'r');
    goto L17;
    L13:;
    _sm_expr2 = ch == '\t';
    if (_sm_expr2) goto L15;
    goto L16;
    L15:;
    simse_str_append(out, '\\');
    simse_str_append(out, 't');
    goto L17;
    L16:;
    simse_str_append(out, ch);
    L17:;
    i = i + 1;
    goto L1;
    L2:;
    simse_str_append(out, '"');
    return out;
}
// <generated>/kt.kt
Str toJson(ns1_Point* self) {
    Int* _sm_base1, * _sm_base2;
    Str out, _sm_expr1, _sm_expr2;
    out = __sm_stringTable[12];
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[10]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base1 = simse_addressOf(self->x);
    _sm_expr1 = toJson(_sm_base1);
    simse_str_appendStr(out, _sm_expr1);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[11]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base2 = simse_addressOf(self->y);
    _sm_expr2 = toJson(_sm_base2);
    simse_str_appendStr(out, _sm_expr2);
    simse_str_append(out, '}');
    return out;
}
// <generated>/kt.kt
Str toJson(Int* self) {
    Str _sm_expr1;
    _sm_expr1 = simse_int_toString((*self));
    return _sm_expr1;
}
// <generated>/kt.kt
Str toJson(ns1_Label* self) {
    Str* _sm_base1;
    Bool* _sm_base2;
    Str out, _sm_expr1, _sm_expr2;
    out = __sm_stringTable[12];
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[6]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base1 = simse_addressOf(self->text);
    _sm_expr1 = toJson(_sm_base1);
    simse_str_appendStr(out, _sm_expr1);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[1]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base2 = simse_addressOf(self->flagged);
    _sm_expr2 = toJson(_sm_base2);
    simse_str_appendStr(out, _sm_expr2);
    simse_str_append(out, '}');
    return out;
}
// <generated>/kt.kt
Str toJson(Str* self) {
    Str _sm_expr1;
    _sm_expr1 = jsonQuoted((*self));
    return _sm_expr1;
}
// <generated>/kt.kt
Str toJson(Bool* self) {
    if ((*self)) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[7];
    L2:;
    return __sm_stringTable[3];
}
// <generated>/kt.kt
Str toJson(ns1_Shape* self) {
    Str* _sm_base1;
    ns1_Point* _sm_base2;
    ns1_Label* _sm_base3;
    Str out, _sm_expr1, _sm_expr2, _sm_expr3;
    out = __sm_stringTable[12];
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[5]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base1 = simse_addressOf(self->name);
    _sm_expr1 = toJson(_sm_base1);
    simse_str_appendStr(out, _sm_expr1);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[2]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base2 = simse_addressOf(self->corner);
    _sm_expr2 = toJson(_sm_base2);
    simse_str_appendStr(out, _sm_expr2);
    simse_str_append(out, ',');
    simse_str_append(out, '"');
    simse_str_appendStr(out, __sm_stringTable[9]);
    simse_str_append(out, '"');
    simse_str_append(out, ':');
    _sm_base3 = simse_addressOf(self->tag);
    _sm_expr3 = toJson(_sm_base3);
    simse_str_appendStr(out, _sm_expr3);
    simse_str_append(out, '}');
    return out;
}

inline Int simse_strView_size(StrView self) {
    return self.len;
}

inline Bool simse_strView_isEmpty(StrView self) {
    return self.len <= 0;
}

// `view.slice(start)`: from `start` to the end (C# `Slice(int)`).
inline StrView simse_strView_slice(StrView self, Int start) {
    return self.slice(start);
}

// `view.slice(start, count)`: `count` bytes from `start` (C# `Slice(int, int)`).
inline StrView simse_strView_slice(StrView self, Int start, Int count) {
    return self.slice(start, count);
}

inline Char simse_strView_charAt(StrView self, Int index) {
    return self[index];
}

// `spanOfStr(text)`: a view over a string's bytes. It borrows the string - the string
// has to outlive the view - and does not copy it (`&text` would box a copy instead).
// `Str` is a `char` buffer on the C++ side and the language's `Char` is a signed byte,
// hence the cast.
inline StrView simse_spanOfStr(Str* text) {
    return StrView(reinterpret_cast<Char*>(text->data()), text->size());
}

// `spanOfStr(view)`: a `StrView` already is a view, so this overload is the identity. It is
// what lets the `when`-over-strings desugar (`Parser.kt`'s `parseWhen`) extract the subject
// with `spanOfStr` without knowing whether it is a `Str` or a `StrView` - the C++ overload
// resolution picks the borrowed view or the identity, and the tests compare against it.
inline StrView simse_spanOfStr(StrView view) {
    return view;
}

template <class T>
inline void simse_list_append(List<T>& self, const std::type_identity_t<T>& value) {
    self.push_back(value);
}

template <class T>
inline List<T> simse_listOf(const List<T>* values) {
    return *values;
}

// Removes the single element at `index`.
template <class T>
inline void simse_list_removeAt(List<T>& self, Int index) {
    self.erase(self.begin() + index);
}

// Removes the half-open range [start, end).
template <class T>
inline void simse_list_removeRange(List<T>& self, Int start, Int end) {
    self.erase(self.begin() + start, self.begin() + end);
}

// `Array<T>.count()`: the element count stored at the front of the block.
template <class T>
inline Int simse_array_count(const Array<T>& self) {
    return self.count();
}

// `List<T>.toArray()` (specs/built-in-types.md): copies the elements into one count-first
// block. Element copies are value copies, like every other copy in the language.
template <class T>
inline Array<T> simse_list_toArray(const List<T>& self) {
    const Int count = self.size();
    if (count <= 0) {
        return Array<T>();
    }
    Array<T> result(count);
    for (Int i = 0; i < count; i++) {
        result[i] = self[i];
    }
    return result;
}

// `Array<T>.toList()`: the growable copy, which is how an element is added to an array.
template <class T>
inline List<T> simse_array_toList(const Array<T>& self) {
    List<T> result;
    const Int count = self.count();
    result.reserve(count);
    for (Int i = 0; i < count; i++) {
        result.push_back(self[i]);
    }
    return result;
}

// `arrayEmpty<T>()`: the shared, zero-length array of `T` (no allocation).
template <class T>
inline Array<T> simse_arrayEmpty() {
    return Array<T>();
}

// `Str.append(ch)`: `Str` has no single-character append, so this is `push_back`.
inline void simse_str_append(Str& self, Char value) {
    self.push_back(static_cast<char>(value));
}

// `Str.appendStr(text)`: appends in place, so an emitter accumulates output without
// `out = out + text` rebuilding the whole buffer on every line (which is quadratic).
inline void simse_str_appendStr(Str& self, const Str& value) {
    self.append(value);
}

// `Str.appendStrPtr(text)`: the same append for a text the caller only *borrows*, so
// nothing is copied on the way.
inline void simse_str_appendStrPtr(Str& self, const Str* value) {
    if (value != nullptr) self.append(*value);
}

// `Str.reserve(count)`: grows the buffer once, so a run of appends writes the text once
// instead of copying the accumulated prefix at every growth step. A *hint*, not a length.
inline void simse_str_reserve(Str& self, Int count) {
    self.reserve((Str::size_type) count);
}

// `Int.toString()`: the scalar-to-inline-string conversion (specs/memory-model.md).
inline Str simse_int_toString(Int self) {
    return std::to_string(self);
}

inline Int simse_lenOf(const Str& self) {
    return self.size();
}

// `List<T>` is `SmallVector<T, 4>` (cppsrc/rtl/containers.hpp), so one overload serves every
// element type and inline capacity.
template <class T, int N>
inline Int simse_lenOf(const SmallVector<T, N>& self) {
    return self.size();
}

// `dictionaryOf<K, V>()`: `Dictionary<K, V>` is a value type, so this default-constructs
// one.
template <class K, class V>
inline Dictionary<K, V> simse_dictionaryOf() {
    return Dictionary<K, V>();
}

template <class K, class V>
inline V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return self.valuePtr(key);
}

template <class K, class V>
inline Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    const V* found = simse_dict_getPtr(self, key);
    if (found == nullptr) return Opt<V>::none();
    return Opt<V>::some(*found);
}

template <class K, class V>
inline Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return simse_dict_getPtr(self, key) != nullptr;
}

template <class K, class V>
inline void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                              const std::type_identity_t<V>& value) {
    self.insert_or_assign(key, value);
}

template <class K, class V>
inline void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    self.erase(key);
}

template <class K, class V>
inline Int simse_dict_size(const Dictionary<K, V>& self) {
    return (Int) self.size();
}

template <class K, class V>
inline List<K> simse_dict_keys(const Dictionary<K, V>& self) {
    List<K> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.first);
    return out;
}

template <class K, class V>
inline List<V> simse_dict_values(const Dictionary<K, V>& self) {
    List<V> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.second);
    return out;
}

template <class K, class V>
inline void simse_dict_clear(Dictionary<K, V>& self) {
    self.clear();
}

template <class T>
inline Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value) {
    for (const T& item : self) {
        if (item == value) return true;
    }
    return false;
}

template <class T, class F>
inline void simse_list_sort(List<T>& self, F less) {
    std::sort(self.begin(), self.end(), [&less](const T& a, const T& b) {
        return less(const_cast<T*>(&a), const_cast<T*>(&b));
    });
}

inline Char simse_str_charAt(const Str& self, Int index) {
    return (Char) self[index];
}

inline List<Str> simse_str_split(const Str& self, const Str& separator) {
    List<Str> parts;
    if (separator.empty()) {
        parts.push_back(self);
        return parts;
    }
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + separator.size();
    }
    return parts;
}

// How many bytes of `self` are `ch`: what the byte-separator split reserves up front.
inline Int simse_count_char_in_str(const Str* self, char ch) {
    Int count = 0;
    const char* data = self->data();
    Int len = self->size();
    for (Int i = 0; i < len; i++) {
        if (data[i] == ch) {
            count++;
        }
    }
    return count;
}

inline List<Str> simse_str_split(const Str& self, Char separator) {
    List<Str> parts;
    parts.reserve(simse_count_char_in_str(&self, separator));
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + 1;
    }
    return parts;
}

inline Int simse_str_find(const Str& self, const Str& sub) {
    Int found = self.find(sub);
    return found == Str::npos ? -1 : found;
}

inline Int simse_str_lastIndexOf(const Str& self, const Str& sub) {
    Int found = self.rfind(sub);
    return found == Str::npos ? -1 : found;
}

inline Str simse_str_replace(const Str& self, const Str& from, const Str& to) {
    if (from.empty()) return self;
    Str result;
    Int pos = 0;
    while (true) {
        Int found = self.find(from, pos);
        if (found == Str::npos) {
            result.append(self, pos, Str::npos);
            break;
        }
        result.append(self, pos, found - pos);
        result += to;
        pos = found + from.size();
    }
    return result;
}

inline Opt<Int> simse_str_toInt(const Str& self) {
    if (self.empty()) return Opt<Int>::none();
    Int value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Int>::none();
    return Opt<Int>::some(value);
}

inline Opt<Float64> simse_str_toFloat(const Str& self) {
    if (self.empty()) return Opt<Float64>::none();
    Float64 value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Float64>::none();
    return Opt<Float64>::some(value);
}

inline void simse_str_initByValue(Str& self, const Str& value) {
    self = value;
}

inline void simse_str_initByValueEmpty(Str& self) {
    self = Str();
}

// The shared space test, used by `simse_char_isSpace` (and, in Simse, by `Str.trim`).
inline Bool simse_str_isSpaceByte(Char ch) {
    return ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r';
}

inline Bool simse_char_isDigit(Char self) {
    return self >= '0' && self <= '9';
}

inline Bool simse_char_isAlpha(Char self) {
    return (self >= 'a' && self <= 'z') || (self >= 'A' && self <= 'Z');
}

inline Bool simse_char_isAlphaOrDigit(Char self) {
    return simse_char_isAlpha(self) || simse_char_isDigit(self);
}

inline Bool simse_char_isSpace(Char self) {
    return simse_str_isSpaceByte(self);
}

template <class T>
inline Str simse_num_toString(const T& self) {
    return std::to_string(self);
}

inline Str simse_char_toString(Char self) {
    return std::to_string((int) self);
}

inline Str simse_bool_toString(Bool self) {
    return self ? "true" : "false";
}

// Expands one run-length encoded series into `out`, which holds `count` values.
template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; // stream[0] is the series' own length
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

// Fills `table` from the pool and the two expanded series: an offset increment and a
// byte count per entry, both rebuilt by subtracting the stored value from the one before.
inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  // this entry's offset increment, rebuilt from the start series
    Int length = 0; // this entry's byte count, rebuilt from the length series
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = StrView(bytes + at, length);
    }
}

// The three monotonic clocks. `steady_clock` is the one clock the standard library
// promises cannot go backwards, which is what makes a duration between two readings
// meaningful (`impl_specs/profiling.md`).
Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

Int64 simse_nowNanos() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
}

// The `simse_write` overloads and the two printers are all inline in the forward block: nothing
// here.
