// CgProfile.kt
//
// The preamble every program carries and the `--profile` name tables. Extension methods
// on `Emitter` (Codegen.kt).

package codegen

import sema
import common
import linear
import optimizations
import profiling
import resources


fun Emitter.preludeText(): Unit {
    this.sections.appendText(`// Generated by the Simse compiler. Do not edit.
#include "src/rtl/simse.hpp"
#include <type_traits>

`)
}

// `--profile`: the instrumented profiler's runtime, which every emitted body measures into
// (impl_specs/profiling.md); nothing when it is off. A section of its own so `support` text
// can precede it.
fun Emitter.emitProfileText(): Unit {
    this.sections.appendText(profPreludeText())
}

// The dense index of a measured body's name (`--profile`): assigned the first time the
// body is written, so the runtime's `FunctionData` list is indexed by a constant.
fun Emitter.profIndexOf(name: *Str): Int {
    if (!profEnabled()) {
        return 0
    }
    val found: *Int = this.profNameIndex.getPtr(name)
    if (found != null) {
        return *found
    }
    val index: Int = this.profNames.size()
    this.profNames.append(this.prettySymbol(name))
    this.profNameIndex.insert(*name, index)
    return index
}

// A measured body's name as a reader can place it (`--profile`). The `nsN_` prefix the
// compiler assigns *is* its package, so `ns1_emitFunction` reads `codegen.emitFunction` -
// Simse's separator, not C++'s (`profDots` folds any `::` left). A lambda's measured body is
// the synthesized `<owner>_closure<N>` class whose `operator()` is the call, so it is named
// for what the reader wrote: `ns1_partTextProcessing_closure1::operator()` reads
// `strings.partTextProcessing.lambda1`. `rtl` and `main` are unprefixed and pass through.
// Only the profiler's table wants this spelling; the emitted symbols stay mangled.
fun Emitter.prettySymbol(name: *Str): Str {
    val closureAt: Int = name.indexOf("_closure")
    if (closureAt > 0) {
        val rest: Str = name.substr(closureAt + 8, name.size() - closureAt - 8)
        var digits: Str
        var d: Int = 0
        while (d < rest.size()) {
            val ch: Char = rest.charAt(d)
            if (ch < '0' || ch > '9') {
                break
            }
            digits.append(ch)
            d = d + 1
        }
        if (digits.size() > 0) {
            val packageNameText: Str = this.packageName(name.substr(0, closureAt))
            return `@packageNameText.lambda@digits`
        }
    }
    return this.packageName(name)
}

// A plain symbol with its `nsN_` package prefix spelled out (`ns1_emitFunction` is
// `codegen.emitFunction`); an unprefixed symbol (`main`, an `rtl` native) passes through.
fun Emitter.packageName(name: *Str): Str {
    val packages: List<Str> = this.nsPrefixes.keys()
    var i: Int = 0
    while (i < packages.size()) {
        val prefix: Str = this.nsPrefix(packages[i])
        if (prefix.size() > 0 && name.startsWith(prefix)) {
            return packages[i] + "." + name.substr(prefix.size(), name.size() - prefix.size())
        }
        i = i + 1
    }
    return *name
}

// The name table, written with the bodies (`--profile`): the last measured body is only
// named once every body is written. Empty when the flag is off.
fun Emitter.emitProfileNames(): Unit {
    this.sections.appendText(profNameTableText(*this.profNames))
}
