// Generated by the Simse compiler. Do not edit.
#include "src/rtl/simse.hpp"
#include <type_traits>


template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count);

#include <chrono>

Int64 simse_nowMillis();
Int64 simse_nowMicros();
Int64 simse_nowNanos();

// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 7;
static const char __sm_stringPool[] =
    "float" "none" "int" "d:" "L" "R" "" 
;
static const Int16 __sm_stringStarts[] = {7,2,0,-5,1,4,1,1,0};
static const Int16 __sm_stringLens[] = {7,1,-5,1,4,1,2,0,1};
static_assert(sizeof(__sm_stringPool) - 1 == 16, "the string pool and its length index disagree");
static StrView __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

template <class T>
Bool simse_opt_hasValue(const Opt<T>& self);

template <class T>
void simse_opt_initByValue(Opt<T>& self, const T& value);
template <class T>
void simse_opt_initByValueNone(Opt<T>& self);

template <class T>
void simse_res_initByValue(Res<T>& self, const T& value);

#include <cerrno>
#include <charconv>
#include <cstddef>
#include <cstdlib>
#include <system_error>


Char simse_str_charAt(const Str& self, Int index);

List<Str> simse_str_split(const Str& self, const Str& separator);
List<Str> simse_str_split(const Str& self, Char separator);

Int simse_str_find(const Str& self, const Str& sub);

Int simse_str_lastIndexOf(const Str& self, const Str& sub);

Str simse_str_replace(const Str& self, const Str& from, const Str& to);

Opt<Int> simse_str_toInt(const Str& self);
Opt<Float64> simse_str_toFloat(const Str& self);

void simse_str_initByValue(Str& self, const Str& value);

template <class T>
Str simse_num_toString(const T& self);
Str simse_char_toString(Char self);
Str simse_bool_toString(Bool self);

#include <bit>
#include <cstring>

Int simse_strCountDigits(Int64 value);
void simse_strAddInt(char* target, Int64 value, Int count);
StrView simse_strBoolView(Bool value);

#include <cstdio>

inline void simse_write(const Str& value, FILE* out) {
    std::fwrite(value.data(), 1, (std::size_t) value.size(), out);
}

inline void simse_write(StrView value, FILE* out) {
    std::fwrite(value.ptr, 1, (std::size_t) value.len, out);
}

inline void simse_write(bool value, FILE* out) {
    std::fputs(value ? "true" : "false", out);
}

inline void simse_write(char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(signed char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(unsigned char value, FILE* out) {
    std::fputc((int) value, out);
}

inline void simse_write(short value, FILE* out) {
    std::fprintf(out, "%d", (int) value);
}

inline void simse_write(int value, FILE* out) {
    std::fprintf(out, "%d", value);
}

inline void simse_write(long value, FILE* out) {
    std::fprintf(out, "%ld", value);
}

inline void simse_write(long long value, FILE* out) {
    std::fprintf(out, "%lld", value);
}

inline void simse_write(float value, FILE* out) {
    std::fprintf(out, "%g", (double) value);
}

inline void simse_write(double value, FILE* out) {
    std::fprintf(out, "%g", value);
}

template <class T>
inline void simse_print(const T& value, FILE* out) {
    simse_write(value, out);
}

template <class T>
inline void simse_println(const T& value, FILE* out) {
    simse_write(value, out);
    std::fputc('\n', out);
}

struct ns1_DoubleOrFloat;
struct ns1_SideOrSide;
struct ns1_Marker;
struct ns1_WithMethod;
// stress/unions/src/main.kt
enum class ns1_SmDoubleOrFloatTypes { None, IntValue, DoubleValue };
inline ns1_SmDoubleOrFloatTypes ns1_simse_SmDoubleOrFloatTypes_fromInt(Int value) { return (ns1_SmDoubleOrFloatTypes) value; }
// stress/unions/src/main.kt
SIMSE_PACK_PUSH
struct ns1_DoubleOrFloat {
    ns1_SmDoubleOrFloatTypes _type = ns1_SmDoubleOrFloatTypes::None;
    union {
        Int IntValue;
        Float64 DoubleValue;
    };
};
SIMSE_PACK_POP
inline Bool operator==(const ns1_DoubleOrFloat& self, ns1_SmDoubleOrFloatTypes tag) { return self._type == tag; }
inline Bool operator==(const ns1_DoubleOrFloat* self, ns1_SmDoubleOrFloatTypes tag) { return self->_type == tag; }
inline Bool operator!=(const ns1_DoubleOrFloat& self, ns1_SmDoubleOrFloatTypes tag) { return self._type != tag; }
inline Bool operator!=(const ns1_DoubleOrFloat* self, ns1_SmDoubleOrFloatTypes tag) { return self->_type != tag; }
inline ns1_SmDoubleOrFloatTypes ns1_getTypeOf(ns1_DoubleOrFloat* self) {
    return self->_type;
}
inline Bool ns1_isOfType(ns1_DoubleOrFloat* self, ns1_SmDoubleOrFloatTypes typeToCheck) {
    return self->_type == typeToCheck;
}
inline void ns1_setNone(ns1_DoubleOrFloat* self) {
    self->_type = ns1_SmDoubleOrFloatTypes::None;
}
inline void ns1_initByValue(ns1_DoubleOrFloat* self) {
    self->_type = ns1_SmDoubleOrFloatTypes::None;
}
inline void ns1_setIntValue(ns1_DoubleOrFloat* self, Int value) {
    self->_type = ns1_SmDoubleOrFloatTypes::IntValue;
    self->IntValue = value;
}
inline Opt<Int> ns1_getIntValue(ns1_DoubleOrFloat* self) {
    if (self->_type == ns1_SmDoubleOrFloatTypes::IntValue) {
        return Opt<Int>::some(self->IntValue);
    }
    return Opt<Int>();
}
inline void ns1_initByValue(ns1_DoubleOrFloat* self, Int value) {
    self->_type = ns1_SmDoubleOrFloatTypes::IntValue;
    self->IntValue = value;
}
inline void ns1_setDoubleValue(ns1_DoubleOrFloat* self, Float64 value) {
    self->_type = ns1_SmDoubleOrFloatTypes::DoubleValue;
    self->DoubleValue = value;
}
inline Opt<Float64> ns1_getDoubleValue(ns1_DoubleOrFloat* self) {
    if (self->_type == ns1_SmDoubleOrFloatTypes::DoubleValue) {
        return Opt<Float64>::some(self->DoubleValue);
    }
    return Opt<Float64>();
}
inline void ns1_initByValue(ns1_DoubleOrFloat* self, Float64 value) {
    self->_type = ns1_SmDoubleOrFloatTypes::DoubleValue;
    self->DoubleValue = value;
}
// stress/unions/src/main.kt
enum class ns1_Left { L };
inline ns1_Left ns1_simse_Left_fromInt(Int value) { return (ns1_Left) value; }
// stress/unions/src/main.kt
enum class ns1_Right { R };
inline ns1_Right ns1_simse_Right_fromInt(Int value) { return (ns1_Right) value; }
// stress/unions/src/main.kt
enum class ns1_SmSideOrSideTypes { None, L, R };
inline ns1_SmSideOrSideTypes ns1_simse_SmSideOrSideTypes_fromInt(Int value) { return (ns1_SmSideOrSideTypes) value; }
// stress/unions/src/main.kt
SIMSE_PACK_PUSH
struct ns1_SideOrSide {
    ns1_SmSideOrSideTypes _type = ns1_SmSideOrSideTypes::None;
    union {
        ns1_Left L;
        ns1_Right R;
    };
};
SIMSE_PACK_POP
inline Bool operator==(const ns1_SideOrSide& self, ns1_SmSideOrSideTypes tag) { return self._type == tag; }
inline Bool operator==(const ns1_SideOrSide* self, ns1_SmSideOrSideTypes tag) { return self->_type == tag; }
inline Bool operator!=(const ns1_SideOrSide& self, ns1_SmSideOrSideTypes tag) { return self._type != tag; }
inline Bool operator!=(const ns1_SideOrSide* self, ns1_SmSideOrSideTypes tag) { return self->_type != tag; }
inline ns1_SmSideOrSideTypes ns1_getTypeOf(ns1_SideOrSide* self) {
    return self->_type;
}
inline Bool ns1_isOfType(ns1_SideOrSide* self, ns1_SmSideOrSideTypes typeToCheck) {
    return self->_type == typeToCheck;
}
inline void ns1_setNone(ns1_SideOrSide* self) {
    self->_type = ns1_SmSideOrSideTypes::None;
}
inline void ns1_initByValue(ns1_SideOrSide* self) {
    self->_type = ns1_SmSideOrSideTypes::None;
}
inline void ns1_setL(ns1_SideOrSide* self, ns1_Left value) {
    self->_type = ns1_SmSideOrSideTypes::L;
    self->L = value;
}
inline Opt<ns1_Left> ns1_getL(ns1_SideOrSide* self) {
    if (self->_type == ns1_SmSideOrSideTypes::L) {
        return Opt<ns1_Left>::some(self->L);
    }
    return Opt<ns1_Left>();
}
inline void ns1_initByValue(ns1_SideOrSide* self, ns1_Left value) {
    self->_type = ns1_SmSideOrSideTypes::L;
    self->L = value;
}
inline void ns1_setR(ns1_SideOrSide* self, ns1_Right value) {
    self->_type = ns1_SmSideOrSideTypes::R;
    self->R = value;
}
inline Opt<ns1_Right> ns1_getR(ns1_SideOrSide* self) {
    if (self->_type == ns1_SmSideOrSideTypes::R) {
        return Opt<ns1_Right>::some(self->R);
    }
    return Opt<ns1_Right>();
}
inline void ns1_initByValue(ns1_SideOrSide* self, ns1_Right value) {
    self->_type = ns1_SmSideOrSideTypes::R;
    self->R = value;
}
// stress/unions/src/main.kt
enum class ns1_SmMarkerTypes { None };
inline ns1_SmMarkerTypes ns1_simse_SmMarkerTypes_fromInt(Int value) { return (ns1_SmMarkerTypes) value; }
// stress/unions/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Marker {
    ns1_SmMarkerTypes _type = ns1_SmMarkerTypes::None;
};
SIMSE_PACK_POP
inline Bool operator==(const ns1_Marker& self, ns1_SmMarkerTypes tag) { return self._type == tag; }
inline Bool operator==(const ns1_Marker* self, ns1_SmMarkerTypes tag) { return self->_type == tag; }
inline Bool operator!=(const ns1_Marker& self, ns1_SmMarkerTypes tag) { return self._type != tag; }
inline Bool operator!=(const ns1_Marker* self, ns1_SmMarkerTypes tag) { return self->_type != tag; }
inline ns1_SmMarkerTypes ns1_getTypeOf(ns1_Marker* self) {
    return self->_type;
}
inline Bool ns1_isOfType(ns1_Marker* self, ns1_SmMarkerTypes typeToCheck) {
    return self->_type == typeToCheck;
}
inline void ns1_setNone(ns1_Marker* self) {
    self->_type = ns1_SmMarkerTypes::None;
}
inline void ns1_initByValue(ns1_Marker* self) {
    self->_type = ns1_SmMarkerTypes::None;
}
// stress/unions/src/main.kt
enum class ns1_SmWithMethodTypes { None, I };
inline ns1_SmWithMethodTypes ns1_simse_SmWithMethodTypes_fromInt(Int value) { return (ns1_SmWithMethodTypes) value; }
// stress/unions/src/main.kt
SIMSE_PACK_PUSH
struct ns1_WithMethod {
    ns1_SmWithMethodTypes _type = ns1_SmWithMethodTypes::None;
    union {
        Int I;
    };
};
SIMSE_PACK_POP
inline Bool operator==(const ns1_WithMethod& self, ns1_SmWithMethodTypes tag) { return self._type == tag; }
inline Bool operator==(const ns1_WithMethod* self, ns1_SmWithMethodTypes tag) { return self->_type == tag; }
inline Bool operator!=(const ns1_WithMethod& self, ns1_SmWithMethodTypes tag) { return self._type != tag; }
inline Bool operator!=(const ns1_WithMethod* self, ns1_SmWithMethodTypes tag) { return self->_type != tag; }
inline ns1_SmWithMethodTypes ns1_getTypeOf(ns1_WithMethod* self) {
    return self->_type;
}
inline Bool ns1_isOfType(ns1_WithMethod* self, ns1_SmWithMethodTypes typeToCheck) {
    return self->_type == typeToCheck;
}
inline void ns1_setNone(ns1_WithMethod* self) {
    self->_type = ns1_SmWithMethodTypes::None;
}
inline void ns1_initByValue(ns1_WithMethod* self) {
    self->_type = ns1_SmWithMethodTypes::None;
}
inline void ns1_setI(ns1_WithMethod* self, Int value) {
    self->_type = ns1_SmWithMethodTypes::I;
    self->I = value;
}
inline Opt<Int> ns1_getI(ns1_WithMethod* self) {
    if (self->_type == ns1_SmWithMethodTypes::I) {
        return Opt<Int>::some(self->I);
    }
    return Opt<Int>();
}
inline void ns1_initByValue(ns1_WithMethod* self, Int value) {
    self->_type = ns1_SmWithMethodTypes::I;
    self->I = value;
}

void initByValue(Str* self);
Int ns1_doubled(ns1_WithMethod* self);
Str ns1_label(ns1_DoubleOrFloat* u);
Str ns1_tagged(ns1_DoubleOrFloat* u);
Str ns1_labelSide(ns1_SideOrSide s);
Str ns1_describe(ns1_DoubleOrFloat* self);
Int ns1_partUnionClass();
Int ns1_partConstructionReturn();
ns1_DoubleOrFloat ns1_make();
ns1_DoubleOrFloat ns1_makeParen();

void initByValue(Str* self) {
}
// stress/unions/src/main.kt
Int ns1_doubled(ns1_WithMethod* self) {
    Int _sm_expr1, _sm_expr2;
    _sm_expr1 = self->I;
    _sm_expr2 = _sm_expr1 * 2;
    return _sm_expr2;
}
// stress/unions/src/main.kt
Str ns1_label(ns1_DoubleOrFloat* u) {
    Str out;
    ns1_SmDoubleOrFloatTypes _sm_expr1;
    Bool _sm_expr2;
    out = __sm_stringTable[6];
    _sm_expr1 = ns1_SmDoubleOrFloatTypes::IntValue;
    _sm_expr2 = u == _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    out = __sm_stringTable[2];
    goto L6;
    L2:;
    _sm_expr1 = ns1_SmDoubleOrFloatTypes::DoubleValue;
    _sm_expr2 = u == _sm_expr1;
    if (_sm_expr2) goto L4;
    goto L5;
    L4:;
    out = __sm_stringTable[0];
    goto L6;
    L5:;
    out = __sm_stringTable[1];
    L6:;
    return out;
}
// stress/unions/src/main.kt
Str ns1_tagged(ns1_DoubleOrFloat* u) {
    Str out;
    ns1_SmDoubleOrFloatTypes _sm_expr1;
    Bool _sm_expr2;
    out = __sm_stringTable[6];
    _sm_expr1 = ns1_SmDoubleOrFloatTypes::None;
    _sm_expr2 = u == _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    out = __sm_stringTable[1];
    goto L8;
    L2:;
    _sm_expr1 = ns1_SmDoubleOrFloatTypes::IntValue;
    _sm_expr2 = u == _sm_expr1;
    if (_sm_expr2) goto L4;
    goto L5;
    L4:;
    out = __sm_stringTable[2];
    goto L8;
    L5:;
    _sm_expr1 = ns1_SmDoubleOrFloatTypes::DoubleValue;
    _sm_expr2 = u == _sm_expr1;
    if (_sm_expr2) goto L7;
    goto L8;
    L7:;
    out = __sm_stringTable[0];
    L8:;
    return out;
}
// stress/unions/src/main.kt
Str ns1_labelSide(ns1_SideOrSide s) {
    Str out;
    ns1_SmSideOrSideTypes _sm_when3, _sm_expr1;
    Bool _sm_expr2;
    out = __sm_stringTable[6];
    _sm_when3 = ns1_getTypeOf(simse_addressOf(s));
    _sm_expr1 = ns1_SmSideOrSideTypes::L;
    _sm_expr2 = _sm_when3 == _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    out = __sm_stringTable[4];
    goto L6;
    L2:;
    _sm_expr1 = ns1_SmSideOrSideTypes::R;
    _sm_expr2 = _sm_when3 == _sm_expr1;
    if (_sm_expr2) goto L4;
    goto L5;
    L4:;
    out = __sm_stringTable[5];
    goto L6;
    L5:;
    out = __sm_stringTable[1];
    L6:;
    return out;
}
// stress/unions/src/main.kt
Str ns1_describe(ns1_DoubleOrFloat* self) {
    char* __sm_catP;
    ns1_DoubleOrFloat* _sm_base1;
    Str _sm_expr1, _sm_expr2;
    _sm_base1 = self;
    _sm_expr1 = ns1_label(_sm_base1);
    _sm_expr2.resize(2 + _sm_expr1.size());
    __sm_catP = _sm_expr2.data();
    std::memcpy(__sm_catP, "d:", 2);
    __sm_catP = __sm_catP + 2;
    std::memcpy(__sm_catP, _sm_expr1.data(), _sm_expr1.size());
    return _sm_expr2;
}
// stress/unions/src/main.kt
Int ns1_partUnionClass() {
    ns1_SmDoubleOrFloatTypes _sm_base1, _sm_base3, _sm_expr2, _sm_expr3, _sm_expr12, _sm_expr14,
        _sm_expr16;
    ns1_DoubleOrFloat* _sm_base2, * _sm_base4, * _sm_base5, * _sm_base6, * _sm_base7, * _sm_base10,
        * _sm_base11, * _sm_base12;
    Int _sm_base8, _sm_base9, _sm_expr8, five, _sm_expr31, _sm_expr32;
    ns1_Left _sm_base13;
    ns1_SmSideOrSideTypes _sm_base14;
    ns1_Right _sm_base15;
    ns1_SmMarkerTypes _sm_base16;
    Bool _sm_expr1, _sm_expr4, _sm_expr6, _sm_expr10, _sm_expr11, _sm_expr13, _sm_expr15, _sm_expr17,
        _sm_expr21, _sm_expr28, _sm_expr30;
    Opt<Int> _sm_expr5, i;
    Str _sm_expr7, _sm_expr18, _sm_expr19, _sm_expr20, _sm_expr23, _sm_expr24, _sm_expr25, _sm_expr26,
        _sm_expr27, _sm_expr29;
    Opt<Float64> _sm_expr9, d;
    Float64 _sm_expr22;
    ns1_DoubleOrFloat a;
    ns1_initByValue(simse_addressOf(a));
    _sm_base1 = ns1_SmDoubleOrFloatTypes::None;
    _sm_expr1 = ns1_isOfType(simse_addressOf(a), _sm_base1);
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = ns1_getTypeOf(simse_addressOf(a));
    _sm_expr3 = ns1_SmDoubleOrFloatTypes::None;
    _sm_expr4 = _sm_expr2 == _sm_expr3;
    simse_println((_sm_expr4), stdout);
    _sm_expr5 = ns1_getIntValue(simse_addressOf(a));
    _sm_expr6 = simse_opt_hasValue(_sm_expr5);
    simse_println((_sm_expr6), stdout);
    _sm_base2 = &a;
    _sm_expr7 = ns1_tagged(_sm_base2);
    simse_println((_sm_expr7), stdout);
    ns1_setIntValue(simse_addressOf(a), 5);
    i = ns1_getIntValue(simse_addressOf(a));
    _sm_expr8 = i.value();
    simse_println((_sm_expr8), stdout);
    _sm_expr9 = ns1_getDoubleValue(simse_addressOf(a));
    _sm_expr10 = simse_opt_hasValue(_sm_expr9);
    simse_println((_sm_expr10), stdout);
    _sm_base3 = ns1_SmDoubleOrFloatTypes::IntValue;
    _sm_expr11 = ns1_isOfType(simse_addressOf(a), _sm_base3);
    simse_println((_sm_expr11), stdout);
    _sm_expr12 = ns1_SmDoubleOrFloatTypes::IntValue;
    _sm_expr13 = a == _sm_expr12;
    simse_println((_sm_expr13), stdout);
    _sm_expr14 = ns1_SmDoubleOrFloatTypes::DoubleValue;
    _sm_expr15 = a != _sm_expr14;
    simse_println((_sm_expr15), stdout);
    _sm_expr16 = ns1_SmDoubleOrFloatTypes::IntValue;
    _sm_expr17 = a == _sm_expr16;
    simse_println((_sm_expr17), stdout);
    _sm_base4 = &a;
    _sm_expr18 = ns1_label(_sm_base4);
    simse_println((_sm_expr18), stdout);
    _sm_base5 = &a;
    _sm_expr19 = ns1_tagged(_sm_base5);
    simse_println((_sm_expr19), stdout);
    _sm_expr20 = ns1_describe(simse_addressOf(a));
    simse_println((_sm_expr20), stdout);
    ns1_DoubleOrFloat b;
    ns1_initByValue(simse_addressOf(b), 2.5);
    d = ns1_getDoubleValue(simse_addressOf(b));
    _sm_expr21 = simse_opt_hasValue(d);
    simse_println((_sm_expr21), stdout);
    _sm_expr22 = d.value();
    simse_println((_sm_expr22), stdout);
    _sm_base6 = &b;
    _sm_expr23 = ns1_label(_sm_base6);
    simse_println((_sm_expr23), stdout);
    five = 5;
    ns1_DoubleOrFloat c;
    ns1_initByValue(simse_addressOf(c), five);
    _sm_base7 = &c;
    _sm_expr24 = ns1_label(_sm_base7);
    simse_println((_sm_expr24), stdout);
    _sm_base8 = c.IntValue;
    simse_println((_sm_base8), stdout);
    c.IntValue = 11;
    _sm_base9 = c.IntValue;
    simse_println((_sm_base9), stdout);
    _sm_base10 = &c;
    _sm_expr25 = ns1_label(_sm_base10);
    simse_println((_sm_expr25), stdout);
    ns1_setNone(simse_addressOf(c));
    _sm_base11 = &c;
    _sm_expr26 = ns1_label(_sm_base11);
    simse_println((_sm_expr26), stdout);
    _sm_base12 = &c;
    _sm_expr27 = ns1_tagged(_sm_base12);
    simse_println((_sm_expr27), stdout);
    ns1_SideOrSide s;
    _sm_base13 = ns1_Left::L;
    ns1_initByValue(simse_addressOf(s), _sm_base13);
    _sm_base14 = ns1_SmSideOrSideTypes::L;
    _sm_expr28 = ns1_isOfType(simse_addressOf(s), _sm_base14);
    simse_println((_sm_expr28), stdout);
    _sm_base15 = ns1_Right::R;
    ns1_setR(simse_addressOf(s), _sm_base15);
    _sm_expr29 = ns1_labelSide(s);
    simse_println((_sm_expr29), stdout);
    ns1_Marker m;
    ns1_initByValue(simse_addressOf(m));
    _sm_base16 = ns1_SmMarkerTypes::None;
    _sm_expr30 = ns1_isOfType(simse_addressOf(m), _sm_base16);
    simse_println((_sm_expr30), stdout);
    ns1_WithMethod w;
    ns1_initByValue(simse_addressOf(w), 4);
    _sm_expr31 = ns1_doubled(simse_addressOf(w));
    simse_println((_sm_expr31), stdout);
    w.I = 6;
    _sm_expr32 = ns1_doubled(simse_addressOf(w));
    simse_println((_sm_expr32), stdout);
    return 0;
}
// stress/unions/src/main.kt
Int ns1_partConstructionReturn() {
    ns1_DoubleOrFloat* _sm_base1, * _sm_base2;
    ns1_DoubleOrFloat _sm_expr1, _sm_expr3;
    Str _sm_expr2, _sm_expr4;
    _sm_expr1 = ns1_make();
    _sm_base1 = &_sm_expr1;
    _sm_expr2 = ns1_label(_sm_base1);
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = ns1_makeParen();
    _sm_base2 = &_sm_expr3;
    _sm_expr4 = ns1_label(_sm_base2);
    simse_println((_sm_expr4), stdout);
    return 0;
}
// stress/unions/src/main.kt
ns1_DoubleOrFloat ns1_make() {
    Int v;
    v = 7;
    ns1_DoubleOrFloat _sm_expr1;
    ns1_initByValue(simse_addressOf(_sm_expr1), v);
    return _sm_expr1;
}
// stress/unions/src/main.kt
ns1_DoubleOrFloat ns1_makeParen() {
    Int v;
    v = 8;
    ns1_DoubleOrFloat _sm_ctor1;
    ns1_initByValue(simse_addressOf(_sm_ctor1), v);
    return _sm_ctor1;
}
// stress/unions/src/main.kt
int main() {
    ns1_partUnionClass();
    ns1_partConstructionReturn();
    return 0;
}

template <class T>
inline Bool simse_opt_hasValue(const Opt<T>& self) {
    return self.hasValue();
}

template <class T>
inline void simse_opt_initByValue(Opt<T>& self, const T& value) { self = Opt<T>::some(value); }
template <class T>
inline void simse_opt_initByValueNone(Opt<T>& self) { self = Opt<T>(); }
template <class T>
inline void simse_res_initByValue(Res<T>& self, const T& value) { self = Res<T>::ok(value); }

inline Char simse_str_charAt(const Str& self, Int index) {
    return (Char) self[index];
}

inline List<Str> simse_str_split(const Str& self, const Str& separator) {
    List<Str> parts;
    if (separator.empty()) {
        parts.push_back(self);
        return parts;
    }
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + separator.size();
    }
    return parts;
}

inline Int simse_count_char_in_str(const Str* self, char ch) {
    Int count = 0;
    const char* data = self->data();
    Int len = self->size();
    for (Int i = 0; i < len; i++) {
        if (data[i] == ch) {
            count++;
        }
    }
    return count;
}

inline List<Str> simse_str_split(const Str& self, Char separator) {
    List<Str> parts;
    parts.reserve(simse_count_char_in_str(&self, separator));
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + 1;
    }
    return parts;
}

inline Int simse_str_find(const Str& self, const Str& sub) {
    Int found = self.find(sub);
    return found == Str::npos ? -1 : found;
}

inline Int simse_str_lastIndexOf(const Str& self, const Str& sub) {
    Int found = self.rfind(sub);
    return found == Str::npos ? -1 : found;
}

inline Str simse_str_replace(const Str& self, const Str& from, const Str& to) {
    if (from.empty()) return self;
    Str result;
    Int pos = 0;
    while (true) {
        Int found = self.find(from, pos);
        if (found == Str::npos) {
            result.append(self, pos, Str::npos);
            break;
        }
        result.append(self, pos, found - pos);
        result += to;
        pos = found + from.size();
    }
    return result;
}

inline Opt<Int> simse_str_toInt(const Str& self) {
    if (self.empty()) return Opt<Int>::none();
    Int value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Int>::none();
    return Opt<Int>::some(value);
}

inline Opt<Float64> simse_str_toFloat(const Str& self) {
    if (self.empty()) return Opt<Float64>::none();
    const char* begin = self.data();
    char* end = nullptr;
    errno = 0;
    const Float64 value = std::strtod(begin, &end);
    if (end != begin + self.size() || errno == ERANGE) return Opt<Float64>::none();
    return Opt<Float64>::some(value);
}

inline void simse_str_initByValue(Str& self, const Str& value) {
    self = value;
}

template <class T>
inline Str simse_num_toString(const T& self) {
    return std::to_string(self);
}

inline Str simse_char_toString(Char self) {
    return std::to_string((int) self);
}

inline Str simse_bool_toString(Bool self) {
    return self ? "true" : "false";
}

static const unsigned long long smStrDigitPow10[20] = {
    1ull, 10ull, 100ull, 1000ull, 10000ull, 100000ull, 1000000ull, 10000000ull,
    100000000ull, 1000000000ull, 10000000000ull, 100000000000ull, 1000000000000ull,
    10000000000000ull, 100000000000000ull, 1000000000000000ull, 10000000000000000ull,
    100000000000000000ull, 1000000000000000000ull, 10000000000000000000ull
};

inline Int simse_strCountDigits(Int64 value) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (magnitude < 10ull) {
        return value < 0 ? 2 : 1;
    }
    Int bits = (Int) std::bit_width(magnitude);
    Int guess = (Int) (((unsigned int) bits * 1233u) >> 12);
    Int digits = guess + (magnitude >= smStrDigitPow10[guess] ? 1 : 0);
    return digits + (value < 0 ? 1 : 0);
}

struct SmStrDigitPairTable {
    char text[200];
    constexpr SmStrDigitPairTable() : text() {
        for (Int i = 0; i < 100; i = i + 1) {
            text[i * 2] = (char) ('0' + i / 10);
            text[i * 2 + 1] = (char) ('0' + i % 10);
        }
    }
};

static constexpr SmStrDigitPairTable smStrDigitPairs{};

inline void simse_strAddInt(char* target, Int64 value, Int count) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (value < 0) {
        target[0] = '-';
        count = count - 1;
        target = target + 1;
    }
    while (count >= 2) {
        unsigned int pair = (unsigned int) (magnitude % 100ull);
        magnitude /= 100ull;
        count = count - 2;
        target[count] = smStrDigitPairs.text[pair * 2];
        target[count + 1] = smStrDigitPairs.text[pair * 2 + 1];
    }
    if (count == 1) {
        target[0] = (char) ('0' + (Int) magnitude);
    }
}

inline StrView simse_strBoolView(Bool value) {
    static Char texts[2][6] = {"true", "false"};
    static Int lens[2] = {4, 5};
    Int at = value ? 0 : 1;
    return StrView(texts[at], lens[at]);
}

template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; 
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  
    Int length = 0; 
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = StrView(bytes + at, length);
    }
}

Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

Int64 simse_nowNanos() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
}
