// Generated by the Simse compiler. Do not edit.
#include "src/rtl/simse.hpp"
#include <type_traits>


template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count);

#include <chrono>

Int64 simse_nowMillis();
Int64 simse_nowMicros();
Int64 simse_nowNanos();

// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 97;
static const char __sm_stringPool[] =
    "the quick brown fox jumps over the lazy dog the extraordinary fox" "a literal well past the twenty-three byte inline capacity of Str" "line one\nline \"two\" with \\ back\n\ttabbed" "line one\nline \"two\" with \\ back\n	tabbed" "He said \"hi\" and left \\ right" "first @\nsecond @" "  Hello,World  " "@ who and @2" "empty-or-bar" "relational" "say \"hi\"" "a@ b and " "equality" "line one" "_sm_@_@" "bitwise" "hello @" "matched" "a=@b=@" "a=|b=|" "letter" "x|y\n@" "Hello" "Simse" "World" "a\\nb" "alpha" "a|b=@" "b=|=|" "c=@:@" "empty" "other" "plain" "shift" "world" " -> " "@who" "HEAD" "a\nb" "beta" "head" "pair" " ~ " "(@)" "@ |" "THE" "a=|" "abc" "cat" "fox" "n=@" "run" "s=@" "the" "two" "v=|" "w=@" "x=@" "zzz" "|@|" "|x|" "!=" "<<" "<=" "==" ">=" "@!" "@@" "\t" "aa" "ab" "bb" "no" "zz" "||" " " "!" "&" "," "-" "<" "=" ">" "?" "@" "Z" "[" "]" "^" "a" "l" "p" "q" "t" "x" "|" "" 
;
static const Int16 __sm_stringStarts[] = {97,10,0,-65,1,25,0,10,13,1,3,0,1,2,2,4,-1,1,0,1,1,3,0,1,1,1,2,0,1,1,1,3,0,2,1,-1,1,8,0,1,1,1,2,0,2,1,-1,1,2,0,1,1,1,18,0,1,1,1,6,0,2,1,-1,1,5,0,1,1,1,20,0};
static const Int16 __sm_stringLens[] = {97,9,-65,1,25,0,10,13,1,3,0,1,2,2,4,-1,1,0,1,1,3,0,1,1,1,2,0,1,1,1,3,0,2,1,-1,1,8,0,1,1,1,2,0,2,1,-1,1,2,0,1,1,1,18,0,1,1,1,6,0,2,1,-1,1,5,0,1,1,1,20,0,1,1};
static_assert(sizeof(__sm_stringPool) - 1 == 581, "the string pool and its length index disagree");
static StrView __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

template <class T>
Span<T> simse_spanOf(List<T>* items);
template <class T>
Span<T> simse_spanOf(Array<T>* items);

StrView simse_spanOfStr(Str* text);
StrView simse_spanOfStr(StrView view);

#include <cstdint>
#include <type_traits>


template <class T>
void simse_list_append(List<T>& self, const std::type_identity_t<T>& value);

template <class T>
List<T> simse_listOf(const List<T>* values);

template <class T>
void simse_list_removeAt(List<T>& self, Int index);
template <class T>
void simse_list_removeRange(List<T>& self, Int start, Int end);
template <class T>
Int simse_array_count(const Array<T>& self);
template <class T>
Array<T> simse_list_toArray(const List<T>& self);
template <class T>
List<T> simse_array_toList(const Array<T>& self);
template <class T>
Array<T> simse_arrayEmpty();

void simse_str_append(Str& self, Char value);
void simse_str_appendStr(Str& self, const Str& value);
void simse_str_appendStrPtr(Str& self, const Str* value);
void simse_str_reserve(Str& self, Int count);
Str simse_int_toString(Int self);

#include <algorithm>
#include <type_traits>
#include <utility>


template <class K, class V>
Dictionary<K, V> simse_dictionaryOf();

template <class K, class V>
V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                       const std::type_identity_t<V>& value);

template <class K, class V>
void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key);

template <class K, class V>
Int simse_dict_size(const Dictionary<K, V>& self);

template <class K, class V>
List<K> simse_dict_keys(const Dictionary<K, V>& self);

template <class K, class V>
List<V> simse_dict_values(const Dictionary<K, V>& self);

template <class K, class V>
void simse_dict_clear(Dictionary<K, V>& self);

template <class T>
Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value);

template <class T, class F>
void simse_list_sort(List<T>& self, F less);

Int simse_lenOf(const Str& self);
template <class T, int N>
Int simse_lenOf(const SmallVector<T, N>& self);

#include <cerrno>
#include <charconv>
#include <cstddef>
#include <cstdlib>
#include <system_error>


Char simse_str_charAt(const Str& self, Int index);

List<Str> simse_str_split(const Str& self, const Str& separator);
List<Str> simse_str_split(const Str& self, Char separator);

Int simse_str_find(const Str& self, const Str& sub);

Int simse_str_lastIndexOf(const Str& self, const Str& sub);

Str simse_str_replace(const Str& self, const Str& from, const Str& to);

Opt<Int> simse_str_toInt(const Str& self);
Opt<Float64> simse_str_toFloat(const Str& self);

void simse_str_initByValue(Str& self, const Str& value);

template <class T>
Str simse_num_toString(const T& self);
Str simse_char_toString(Char self);
Str simse_bool_toString(Bool self);

#include <bit>
#include <cstring>

Int simse_strCountDigits(Int64 value);
void simse_strAddInt(char* target, Int64 value, Int count);
StrView simse_strBoolView(Bool value);

#include <cstdio>

inline void simse_write(const Str& value, FILE* out) {
    std::fwrite(value.data(), 1, (std::size_t) value.size(), out);
}

inline void simse_write(StrView value, FILE* out) {
    std::fwrite(value.ptr, 1, (std::size_t) value.len, out);
}

inline void simse_write(bool value, FILE* out) {
    std::fputs(value ? "true" : "false", out);
}

inline void simse_write(char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(signed char value, FILE* out) {
    std::fputc((int) (unsigned char) value, out);
}

inline void simse_write(unsigned char value, FILE* out) {
    std::fputc((int) value, out);
}

inline void simse_write(short value, FILE* out) {
    std::fprintf(out, "%d", (int) value);
}

inline void simse_write(int value, FILE* out) {
    std::fprintf(out, "%d", value);
}

inline void simse_write(long value, FILE* out) {
    std::fprintf(out, "%ld", value);
}

inline void simse_write(long long value, FILE* out) {
    std::fprintf(out, "%lld", value);
}

inline void simse_write(float value, FILE* out) {
    std::fprintf(out, "%g", (double) value);
}

inline void simse_write(double value, FILE* out) {
    std::fprintf(out, "%g", value);
}

template <class T>
inline void simse_print(const T& value, FILE* out) {
    simse_write(value, out);
}

template <class T>
inline void simse_println(const T& value, FILE* out) {
    simse_write(value, out);
    std::fputc('\n', out);
}

template <class T>
struct Opt;
template <class T>
struct Res;
struct ns1_Tag;
// src/rtl
enum class SmOptTypes { None, Value };
inline SmOptTypes simse_SmOptTypes_fromInt(Int value) { return (SmOptTypes) value; }
// src/rtl
SIMSE_PACK_PUSH
template <Bool SmManaged, class T> struct SmOptStorage;
template <class T> struct SmOptStorage<false, T> {
    SmOptTypes _type = SmOptTypes::None;
    union {
        T Value;
    };
    SmOptStorage() {}
    void setValue(T value) {
        _type = SmOptTypes::Value;
        Value = std::move(value);
    }
    void setNone() {
        _type = SmOptTypes::None;
    }
};
template <class T> struct SmOptStorage<true, T> {
    SmOptTypes _type = SmOptTypes::None;
    union {
        T Value;
    };
    SmOptStorage() {}
    SmOptStorage(const SmOptStorage& other) { this->copyFrom(other); }
    SmOptStorage(SmOptStorage&& other) noexcept { this->moveFrom(other); }
    ~SmOptStorage() { this->destroyActive(); }
    SmOptStorage& operator=(const SmOptStorage& other) {
        if (this != &other) {
            this->destroyActive();
            this->copyFrom(other);
        }
        return *this;
    }
    SmOptStorage& operator=(SmOptStorage&& other) noexcept {
        if (this != &other) {
            this->destroyActive();
            this->moveFrom(other);
        }
        return *this;
    }
    void destroyActive() {
        switch (this->_type) {
            case SmOptTypes::Value: simse_destroy(this->Value); break;
            default: break;
        }
        this->_type = SmOptTypes::None;
    }
    void copyFrom(const SmOptStorage& other) {
        switch (other._type) {
            case SmOptTypes::Value: ::new ((void *) &this->Value) T(other.Value); this->_type = SmOptTypes::Value; break;
            default: break;
        }
    }
    void moveFrom(SmOptStorage& other) {
        switch (other._type) {
            case SmOptTypes::Value: ::new ((void *) &this->Value) T(std::move(other.Value)); this->_type = SmOptTypes::Value; break;
            default: break;
        }
    }
    void setValue(T value) {
        if (_type == SmOptTypes::Value) {
            Value = std::move(value);
            return;
        }
        this->destroyActive();
        _type = SmOptTypes::Value;
        ::new ((void *) &Value) T(std::move(value));
    }
    void setNone() {
        this->destroyActive();
    }
};
template <class T>
struct Opt : SmOptStorage<SmUnionManaged<T>, T> {
};
SIMSE_PACK_POP
template <class T>
inline Bool operator==(const Opt<T>& self, SmOptTypes tag) { return self._type == tag; }
template <class T>
inline Bool operator==(const Opt<T>* self, SmOptTypes tag) { return self->_type == tag; }
template <class T>
inline Bool operator!=(const Opt<T>& self, SmOptTypes tag) { return self._type != tag; }
template <class T>
inline Bool operator!=(const Opt<T>* self, SmOptTypes tag) { return self->_type != tag; }
template <class T>
inline SmOptTypes getTypeOf(Opt<T>* self) {
    return self->_type;
}
template <class T>
inline Bool isOfType(Opt<T>* self, SmOptTypes typeToCheck) {
    return self->_type == typeToCheck;
}
template <class T>
inline void setNone(Opt<T>* self) {
    self->setNone();
}
template <class T>
inline void initByValue(Opt<T>* self) {
    self->setNone();
}
template <class T>
inline void setValue(Opt<T>* self, T value) {
    self->setValue(std::move(value));
}
template <class T>
inline Opt<T> getValue(Opt<T>* self) {
    if (self->_type == SmOptTypes::Value) {
        Opt<T> result;
        result.setValue(self->Value);
        return result;
    }
    return Opt<T>();
}
template <class T>
inline void initByValue(Opt<T>* self, T value) {
    self->setValue(std::move(value));
}
// src/rtl
enum class SmResTypes { None, Value, Error };
inline SmResTypes simse_SmResTypes_fromInt(Int value) { return (SmResTypes) value; }
// src/rtl
SIMSE_PACK_PUSH
template <Bool SmManaged, class T> struct SmResStorage;
template <class T> struct SmResStorage<false, T> {
    SmResTypes _type = SmResTypes::None;
    union {
        T Value;
        Str Error;
    };
    SmResStorage() {}
    void setValue(T value) {
        _type = SmResTypes::Value;
        Value = std::move(value);
    }
    void setError(Str value) {
        _type = SmResTypes::Error;
        Error = std::move(value);
    }
    void setNone() {
        _type = SmResTypes::None;
    }
};
template <class T> struct SmResStorage<true, T> {
    SmResTypes _type = SmResTypes::None;
    union {
        T Value;
        Str Error;
    };
    SmResStorage() {}
    SmResStorage(const SmResStorage& other) { this->copyFrom(other); }
    SmResStorage(SmResStorage&& other) noexcept { this->moveFrom(other); }
    ~SmResStorage() { this->destroyActive(); }
    SmResStorage& operator=(const SmResStorage& other) {
        if (this != &other) {
            this->destroyActive();
            this->copyFrom(other);
        }
        return *this;
    }
    SmResStorage& operator=(SmResStorage&& other) noexcept {
        if (this != &other) {
            this->destroyActive();
            this->moveFrom(other);
        }
        return *this;
    }
    void destroyActive() {
        switch (this->_type) {
            case SmResTypes::Value: simse_destroy(this->Value); break;
            case SmResTypes::Error: simse_destroy(this->Error); break;
            default: break;
        }
        this->_type = SmResTypes::None;
    }
    void copyFrom(const SmResStorage& other) {
        switch (other._type) {
            case SmResTypes::Value: ::new ((void *) &this->Value) T(other.Value); this->_type = SmResTypes::Value; break;
            case SmResTypes::Error: ::new ((void *) &this->Error) Str(other.Error); this->_type = SmResTypes::Error; break;
            default: break;
        }
    }
    void moveFrom(SmResStorage& other) {
        switch (other._type) {
            case SmResTypes::Value: ::new ((void *) &this->Value) T(std::move(other.Value)); this->_type = SmResTypes::Value; break;
            case SmResTypes::Error: ::new ((void *) &this->Error) Str(std::move(other.Error)); this->_type = SmResTypes::Error; break;
            default: break;
        }
    }
    void setValue(T value) {
        if (_type == SmResTypes::Value) {
            Value = std::move(value);
            return;
        }
        this->destroyActive();
        _type = SmResTypes::Value;
        ::new ((void *) &Value) T(std::move(value));
    }
    void setError(Str value) {
        if (_type == SmResTypes::Error) {
            Error = std::move(value);
            return;
        }
        this->destroyActive();
        _type = SmResTypes::Error;
        ::new ((void *) &Error) Str(std::move(value));
    }
    void setNone() {
        this->destroyActive();
    }
};
template <class T>
struct Res : SmResStorage<SmUnionManaged<T, Str>, T> {
};
SIMSE_PACK_POP
template <class T>
inline Bool operator==(const Res<T>& self, SmResTypes tag) { return self._type == tag; }
template <class T>
inline Bool operator==(const Res<T>* self, SmResTypes tag) { return self->_type == tag; }
template <class T>
inline Bool operator!=(const Res<T>& self, SmResTypes tag) { return self._type != tag; }
template <class T>
inline Bool operator!=(const Res<T>* self, SmResTypes tag) { return self->_type != tag; }
template <class T>
inline SmResTypes getTypeOf(Res<T>* self) {
    return self->_type;
}
template <class T>
inline Bool isOfType(Res<T>* self, SmResTypes typeToCheck) {
    return self->_type == typeToCheck;
}
template <class T>
inline void setNone(Res<T>* self) {
    self->setNone();
}
template <class T>
inline void initByValue(Res<T>* self) {
    self->setNone();
}
template <class T>
inline void setValue(Res<T>* self, T value) {
    self->setValue(std::move(value));
}
template <class T>
inline Opt<T> getValue(Res<T>* self) {
    if (self->_type == SmResTypes::Value) {
        Opt<T> result;
        result.setValue(self->Value);
        return result;
    }
    return Opt<T>();
}
template <class T>
inline void initByValue(Res<T>* self, T value) {
    self->setValue(std::move(value));
}
template <class T>
inline void setError(Res<T>* self, Str value) {
    self->setError(std::move(value));
}
template <class T>
inline Opt<Str> getError(Res<T>* self) {
    if (self->_type == SmResTypes::Error) {
        Opt<Str> result;
        result.setValue(self->Error);
        return result;
    }
    return Opt<Str>();
}
template <class T>
requires (!std::is_same_v<Str, T>)
inline void initByValue(Res<T>* self, Str value) {
    self->setError(std::move(value));
}
// stress/strings/src/main.kt
SIMSE_PACK_PUSH
struct ns1_Tag {
    Str name;
    Int count;
};
SIMSE_PACK_POP

template <class T>
T get(Span<T>* self, Int index);
template <class T>
void set(Span<T>* self, Int index, T value);
Char charAt(StrView* self, Int index);
Bool startsWith(StrView* self, Str* text);
Int find(StrView* self, Str sub);
Int indexOf(StrView* self, Str* sub);
Str substr(StrView* self, Int from, Int count);
Str toString(StrView* self);
Int compareTo(StrView* self, StrView other);
Bool equals(StrView* self, StrView other);
Str plus(StrView* self, StrView other);
template <class T>
Bool simse_optHasValue(Opt<T>* self);
template <class T>
T simse_optValue(Opt<T>* self);
template <class T>
Bool simse_resHasValue(Res<T>* self);
template <class T>
T simse_resValue(Res<T>* self);
template <class T>
Str simse_resError(Res<T>* self);
template <class T>
Opt<T> simse_optSome(T value);
template <class T>
Opt<T> simse_optNone();
template <class T>
Res<T> simse_resOk(T value);
template <class T>
Res<T> simse_resErr(Str message);
template <class T>
struct Span_iterValues_yieldable {
    Int branch{};
    T current{};
    Span<T>* _sm_self{};
    Int i{};
    Int len{};
};

template <class T>
Bool advance(Span_iterValues_yieldable<T>* self) {
    Bool _sm_base1, _sm_base3, _sm_expr1;
    Int _sm_base2, _sm_base4, _sm_base5, _sm_base7, _sm_base8, _sm_base10, _sm_base11, _sm_base12;
    Span<T>* _sm_base6, * _sm_base9;
    T _sm_expr2;
    _sm_base2 = self->branch;
    _sm_base1 = _sm_base2 == -1;
    if (_sm_base1) goto L2;
    _sm_base4 = self->branch;
    _sm_base3 = _sm_base4 == 1;
    if (_sm_base3) goto LY1;
    self->i = 0;
    _sm_base6 = self->_sm_self;
    _sm_base5 = _sm_base6->size();
    self->len = _sm_base5;
    L1:;
    _sm_base7 = self->i;
    _sm_base8 = self->len;
    _sm_expr1 = _sm_base7 < _sm_base8;
    if (!(_sm_expr1)) goto L2;
    _sm_base9 = self->_sm_self;
    _sm_base10 = self->i;
    _sm_expr2 = get(_sm_base9, _sm_base10);
    self->current = _sm_expr2;
    self->branch = 1;
    return true;
    LY1:;
    _sm_base12 = self->i;
    _sm_base11 = _sm_base12 + 1;
    self->i = _sm_base11;
    goto L1;
    L2:;
    self->branch = -1;
    return false;
}

template <class T>
Span_iterValues_yieldable<T> iterValues(Span<T>* self);
Bool compareLessThan(Str* left, Str* right);
void initByValue(Str* self);
Str fmtStr(StrView fmt, List<Str>* items);
Str fmtStrWith(Char separator, StrView templateText, List<Str>* items);
Str substr(Str* self, Int start, Int len);
Bool startsWith(Str* self, Str* prefix);
Bool endsWith(Str* self, Str* suffix);
Str trim(Str* self);
Str toUpper(Str* self);
Str toLower(Str* self);
Bool isEmpty(Str* self);
Bool isSpace(Char* self);
Int ns1_partStrIsEmpty();
Int ns1_partStringEscapes();
Int ns1_partStrings();
Int ns1_partTextProcessing();
Str ns1_pair(Str* a, Str* b);
Int ns1_partConcat();
Int ns1_partRawStrings();
Str ns1_classify(Str* op);
Str ns1_classifyPtr(Str* op);
Str ns1_viewKind(StrView v);
Str ns1_fixed(Str* op);
Int ns1_partWhenStrings();

template <class T>
T get(Span<T>* self, Int index) {
    T* _sm_base1;
    _sm_base1 = self->ptr;
    auto _sm_expr1 = _sm_base1[index];
    return _sm_expr1;
}
template <class T>
void set(Span<T>* self, Int index, T value) {
    T* _sm_base1;
    _sm_base1 = self->ptr;
    _sm_base1[index] = value;
}
Char charAt(StrView* self, Int index) {
    Char _sm_expr1;
    _sm_expr1 = self->at(index);
    return _sm_expr1;
}
Bool startsWith(StrView* self, Str* text) {
    Int count, compareResult;
    Bool _sm_expr1;
    Char* _sm_expr2;
    count = simse_lenOf((*text));
    auto thisLen = self->len;
    _sm_expr1 = count > thisLen;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    _sm_expr2 = simse_str_data(text);
    compareResult = simse_mem_compare(self->ptr, 0, _sm_expr2, 0, count);
    _sm_expr1 = compareResult == 0;
    return _sm_expr1;
}
Int find(StrView* self, Str sub) {
    Int needle, len, _sm_expr3, i, j, _sm_expr7;
    Bool _sm_expr1, _sm_expr10;
    Char _sm_expr9;
    needle = simse_lenOf(sub);
    _sm_expr1 = needle == 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return 0;
    L2:;
    len = self->size();
    _sm_expr1 = needle > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    _sm_expr3 = -1;
    return _sm_expr3;
    L4:;
    i = 0;
    L5:;
    _sm_expr3 = i + needle;
    _sm_expr1 = _sm_expr3 <= len;
    if (!(_sm_expr1)) goto L6;
    j = 0;
    L7:;
    _sm_expr1 = j < needle;
    if (_sm_expr1) goto L10;
    goto L8;
    L10:;
    _sm_expr7 = i + j;
    {
        auto _sm_expr8 = self->ptr[_sm_expr7];
        _sm_expr9 = simse_str_charAt(sub, j);
        _sm_expr10 = _sm_expr8 == _sm_expr9;
        if (_sm_expr10) goto L9;
        goto L8;
        L9:;
        j = j + 1;
        goto L7;
    }
    L8:;
    _sm_expr1 = j == needle;
    if (_sm_expr1) goto L11;
    goto L12;
    L11:;
    return i;
    L12:;
    i = i + 1;
    goto L5;
    L6:;
    _sm_expr3 = -1;
    return _sm_expr3;
}
Int indexOf(StrView* self, Str* sub) {
    Str _sm_base1;
    Int _sm_expr1;
    _sm_base1 = *(sub);
    _sm_expr1 = find(self, _sm_base1);
    return _sm_expr1;
}
Str substr(StrView* self, Int from, Int count) {
    Int len, begin, end, _sm_expr6;
    Bool _sm_expr1;
    len = self->size();
    begin = from;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr1 = begin > len;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = len;
    L4:;
    end = begin + count;
    _sm_expr1 = count < 0;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    end = begin;
    L6:;
    _sm_expr1 = end > len;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    end = len;
    L8:;
    Str out;
    _sm_expr1 = end > begin;
    if (_sm_expr1) goto L9;
    goto L10;
    L9:;
    _sm_expr6 = end - begin;
    simse_str_setBytes(out, self->ptr, begin, _sm_expr6);
    L10:;
    return out;
}
Str toString(StrView* self) {
    Int _sm_expr1;
    Str _sm_expr2;
    _sm_expr1 = self->size();
    _sm_expr2 = substr(self, 0, _sm_expr1);
    return _sm_expr2;
}
Int compareTo(StrView* self, StrView other) {
    Bool _sm_expr3, _sm_expr4, _sm_expr7;
    Int _sm_diff_2, _sm_expr8, diff;
    auto _sm_expr1 = self->len;
    auto _sm_expr2 = other.len;
    _sm_expr3 = _sm_expr1 <= _sm_expr2;
    if (_sm_expr3) goto L1;
    goto L2;
    L1:;
    _sm_diff_2 = simse_mem_compare(self->ptr, 0, other.ptr, 0, self->len);
    _sm_expr4 = _sm_diff_2 != 0;
    if (_sm_expr4) goto L3;
    goto L4;
    L3:;
    return _sm_diff_2;
    L4:;
    {
        auto _sm_expr5 = self->len;
        auto _sm_expr6 = other.len;
        _sm_expr7 = _sm_expr5 == _sm_expr6;
        if (_sm_expr7) goto L5;
        goto L6;
        L5:;
        return 0;
        L6:;
        _sm_expr8 = -1;
        return _sm_expr8;
    }
    L2:;
    diff = simse_mem_compare(self->ptr, 0, other.ptr, 0, other.len);
    _sm_expr3 = diff != 0;
    if (_sm_expr3) goto L7;
    goto L8;
    L7:;
    return diff;
    L8:;
    return 1;
}
Bool equals(StrView* self, StrView other) {
    Bool _sm_expr3;
    Int _sm_expr4;
    auto _sm_expr1 = self->len;
    auto _sm_expr2 = other.len;
    _sm_expr3 = _sm_expr1 != _sm_expr2;
    if (_sm_expr3) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    _sm_expr4 = simse_mem_compare(self->ptr, 0, other.ptr, 0, self->len);
    _sm_expr3 = _sm_expr4 == 0;
    return _sm_expr3;
}
Str plus(StrView* self, StrView other) {
    Str* _sm_base3;
    Bool _sm_expr2;
    Int at, _sm_expr4;
    Char* _sm_expr5;
    Str result;
    simse_str_setBytes(result, self->ptr, 0, self->len);
    auto _sm_expr1 = other.len;
    _sm_expr2 = _sm_expr1 > 0;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    at = simse_lenOf(result);
    {
        auto _sm_expr3 = other.len;
        _sm_expr4 = at + _sm_expr3;
        result.resize(_sm_expr4);
        _sm_base3 = &result;
        _sm_expr5 = simse_str_data(_sm_base3);
        simse_mem_copy(_sm_expr5, at, other.ptr, 0, other.len);
    }
    L2:;
    return result;
}
template <class T>
Bool simse_optHasValue(Opt<T>* self) {
    SmOptTypes _sm_base1;
    Bool _sm_expr1;
    _sm_base1 = SmOptTypes::Value;
    _sm_expr1 = isOfType(self, _sm_base1);
    return _sm_expr1;
}
template <class T>
T simse_optValue(Opt<T>* self) {
    T _sm_expr1;
    _sm_expr1 = self->Value;
    return _sm_expr1;
}
template <class T>
Bool simse_resHasValue(Res<T>* self) {
    SmResTypes _sm_base1;
    Bool _sm_expr1;
    _sm_base1 = SmResTypes::Value;
    _sm_expr1 = isOfType(self, _sm_base1);
    return _sm_expr1;
}
template <class T>
T simse_resValue(Res<T>* self) {
    T _sm_expr1;
    _sm_expr1 = self->Value;
    return _sm_expr1;
}
template <class T>
Str simse_resError(Res<T>* self) {
    Str _sm_expr1;
    _sm_expr1 = self->Error;
    return _sm_expr1;
}
template <class T>
Opt<T> simse_optSome(T value) {
    Opt<T> result;
    initByValue(simse_addressOf(result));
    setValue(simse_addressOf(result), value);
    return result;
}
template <class T>
Opt<T> simse_optNone() {
    Opt<T> result;
    initByValue(simse_addressOf(result));
    return result;
}
template <class T>
Res<T> simse_resOk(T value) {
    Res<T> result;
    initByValue(simse_addressOf(result));
    setValue(simse_addressOf(result), value);
    return result;
}
template <class T>
Res<T> simse_resErr(Str message) {
    Res<T> result;
    initByValue(simse_addressOf(result));
    setError(simse_addressOf(result), message);
    return result;
}
template <class T>
Span_iterValues_yieldable<T> iterValues(Span<T>* self) {
    Span_iterValues_yieldable<T> machine{};
    machine._sm_self = self;
    machine.branch = 0;
    return machine;
}
Bool compareLessThan(Str* left, Str* right) {
    StrView _sm_expr1, _sm_expr2;
    Bool _sm_expr3;
    _sm_expr1 = simse_spanOfStr(left);
    _sm_expr2 = simse_spanOfStr(right);
    _sm_expr3 = (compareTo(simse_addressOf(_sm_expr1), _sm_expr2) < 0);
    return _sm_expr3;
}
void initByValue(Str* self) {
}
Str fmtStr(StrView fmt, List<Str>* items) {
    Str _sm_base2, out;
    Bool _sm_expr1;
    Int points, i, _sm_expr2, _sm_expr8, used;
    Char _sm_expr4, ch;
    _sm_expr1 = items == nullptr;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return fmt;
    L2:;
    points = 0;
    i = 0;
    L3:;
    _sm_expr2 = fmt.size();
    _sm_expr1 = i < _sm_expr2;
    if (!(_sm_expr1)) goto L4;
    _sm_expr4 = charAt(simse_addressOf(fmt), i);
    _sm_expr1 = _sm_expr4 == '|';
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    points = points + 1;
    L6:;
    i = i + 1;
    goto L3;
    L4:;
    _sm_expr2 = simse_lenOf((*items));
    _sm_expr1 = points != _sm_expr2;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    return fmt;
    L8:;
    out = __sm_stringTable[96];
    _sm_expr8 = fmt.size();
    simse_str_reserve(out, _sm_expr8);
    used = 0;
    i = 0;
    L9:;
    _sm_expr2 = fmt.size();
    _sm_expr1 = i < _sm_expr2;
    if (!(_sm_expr1)) goto L10;
    ch = charAt(simse_addressOf(fmt), i);
    _sm_expr1 = ch == '|';
    if (_sm_expr1) goto L11;
    goto L12;
    L11:;
    _sm_base2 = (*items)[used];
    simse_str_appendStr(out, _sm_base2);
    used = used + 1;
    goto L13;
    L12:;
    simse_str_append(out, ch);
    L13:;
    i = i + 1;
    goto L9;
    L10:;
    return out;
}
Str fmtStrWith(Char separator, StrView templateText, List<Str>* items) {
    Str _sm_base2, out;
    Bool _sm_expr1;
    Int points, i, _sm_expr2, _sm_expr8, used;
    Char _sm_expr4, ch;
    _sm_expr1 = items == nullptr;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return templateText;
    L2:;
    points = 0;
    i = 0;
    L3:;
    _sm_expr2 = templateText.size();
    _sm_expr1 = i < _sm_expr2;
    if (!(_sm_expr1)) goto L4;
    _sm_expr4 = charAt(simse_addressOf(templateText), i);
    _sm_expr1 = _sm_expr4 == separator;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    points = points + 1;
    L6:;
    i = i + 1;
    goto L3;
    L4:;
    _sm_expr2 = simse_lenOf((*items));
    _sm_expr1 = points != _sm_expr2;
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    return templateText;
    L8:;
    out = __sm_stringTable[96];
    _sm_expr8 = templateText.size();
    simse_str_reserve(out, _sm_expr8);
    used = 0;
    i = 0;
    L9:;
    _sm_expr2 = templateText.size();
    _sm_expr1 = i < _sm_expr2;
    if (!(_sm_expr1)) goto L10;
    ch = charAt(simse_addressOf(templateText), i);
    _sm_expr1 = ch == separator;
    if (_sm_expr1) goto L11;
    goto L12;
    L11:;
    _sm_base2 = (*items)[used];
    simse_str_appendStr(out, _sm_base2);
    used = used + 1;
    goto L13;
    L12:;
    simse_str_append(out, ch);
    L13:;
    i = i + 1;
    goto L9;
    L10:;
    return out;
}
Str substr(Str* self, Int start, Int len) {
    Str* _sm_base1;
    Int begin, _sm_expr2, count;
    Bool _sm_expr1;
    Char* _sm_expr8;
    begin = start;
    _sm_expr1 = begin < 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    begin = 0;
    L2:;
    _sm_expr2 = simse_lenOf((*self));
    _sm_expr1 = begin > _sm_expr2;
    if (_sm_expr1) goto L3;
    goto L4;
    L3:;
    begin = simse_lenOf((*self));
    L4:;
    _sm_expr2 = simse_lenOf((*self));
    count = _sm_expr2 - begin;
    _sm_expr1 = len >= 0;
    if (_sm_expr1) goto L7;
    goto L6;
    L7:;
    _sm_expr1 = len < count;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    count = len;
    L6:;
    Str out;
    _sm_expr1 = count > 0;
    if (_sm_expr1) goto L8;
    goto L9;
    L8:;
    _sm_base1 = self;
    _sm_expr8 = simse_str_data(_sm_base1);
    simse_str_setBytes(out, _sm_expr8, begin, count);
    L9:;
    return out;
}
Bool startsWith(Str* self, Str* prefix) {
    Int count, _sm_expr1, i;
    Bool _sm_expr2;
    Char _sm_expr4, _sm_expr5;
    count = simse_lenOf((*prefix));
    _sm_expr1 = simse_lenOf((*self));
    _sm_expr2 = count > _sm_expr1;
    if (_sm_expr2) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    i = 0;
    L3:;
    _sm_expr2 = i < count;
    if (!(_sm_expr2)) goto L4;
    _sm_expr4 = simse_str_charAt((*self), i);
    _sm_expr5 = simse_str_charAt((*prefix), i);
    _sm_expr2 = _sm_expr4 != _sm_expr5;
    if (_sm_expr2) goto L5;
    goto L6;
    L5:;
    return false;
    L6:;
    i = i + 1;
    goto L3;
    L4:;
    return true;
}
Bool endsWith(Str* self, Str* suffix) {
    Int count, len, i, _sm_expr3, _sm_expr4;
    Bool _sm_expr1;
    Char _sm_expr5, _sm_expr6;
    count = simse_lenOf((*suffix));
    len = simse_lenOf((*self));
    _sm_expr1 = count > len;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return false;
    L2:;
    i = 0;
    L3:;
    _sm_expr1 = i < count;
    if (!(_sm_expr1)) goto L4;
    _sm_expr3 = len - count;
    _sm_expr4 = _sm_expr3 + i;
    _sm_expr5 = simse_str_charAt((*self), _sm_expr4);
    _sm_expr6 = simse_str_charAt((*suffix), i);
    _sm_expr1 = _sm_expr5 != _sm_expr6;
    if (_sm_expr1) goto L5;
    goto L6;
    L5:;
    return false;
    L6:;
    i = i + 1;
    goto L3;
    L4:;
    return true;
}
Str trim(Str* self) {
    Str* _sm_base1;
    Int begin, end, _sm_expr5, _sm_expr10;
    Bool _sm_expr1, _sm_expr3;
    Char ch, _sm_ch_2;
    Char* _sm_expr9;
    begin = 0;
    end = simse_lenOf((*self));
    L1:;
    _sm_expr1 = begin < end;
    if (!(_sm_expr1)) goto L2;
    ch = simse_str_charAt((*self), begin);
    _sm_expr1 = isSpace(simse_addressOf(ch));
    _sm_expr3 = !_sm_expr1;
    if (_sm_expr3) goto L2;
    begin = begin + 1;
    goto L1;
    L2:;
    _sm_expr1 = end > begin;
    if (!(_sm_expr1)) goto L6;
    _sm_expr5 = end - 1;
    _sm_ch_2 = simse_str_charAt((*self), _sm_expr5);
    _sm_expr1 = isSpace(simse_addressOf(_sm_ch_2));
    _sm_expr3 = !_sm_expr1;
    if (_sm_expr3) goto L6;
    end = end - 1;
    goto L2;
    L6:;
    Str out;
    _sm_expr1 = end > begin;
    if (_sm_expr1) goto L9;
    goto L10;
    L9:;
    _sm_base1 = self;
    _sm_expr9 = simse_str_data(_sm_base1);
    _sm_expr10 = end - begin;
    simse_str_setBytes(out, _sm_expr9, begin, _sm_expr10);
    L10:;
    return out;
}
Str toUpper(Str* self) {
    Int _sm_expr1, i, _sm_expr2;
    Bool _sm_expr3;
    Char ch;
    Str out;
    _sm_expr1 = simse_lenOf((*self));
    simse_str_reserve(out, _sm_expr1);
    i = 0;
    L1:;
    _sm_expr2 = simse_lenOf((*self));
    _sm_expr3 = i < _sm_expr2;
    if (!(_sm_expr3)) goto L2;
    ch = simse_str_charAt((*self), i);
    _sm_expr3 = ch >= 'a';
    if (_sm_expr3) goto L5;
    goto L4;
    L5:;
    _sm_expr3 = ch <= 'z';
    if (_sm_expr3) goto L3;
    goto L4;
    L3:;
    ch = ch - 32;
    L4:;
    simse_str_append(out, ch);
    i = i + 1;
    goto L1;
    L2:;
    return out;
}
Str toLower(Str* self) {
    Int _sm_expr1, i, _sm_expr2;
    Bool _sm_expr3;
    Char ch;
    Str out;
    _sm_expr1 = simse_lenOf((*self));
    simse_str_reserve(out, _sm_expr1);
    i = 0;
    L1:;
    _sm_expr2 = simse_lenOf((*self));
    _sm_expr3 = i < _sm_expr2;
    if (!(_sm_expr3)) goto L2;
    ch = simse_str_charAt((*self), i);
    _sm_expr3 = ch >= 'A';
    if (_sm_expr3) goto L5;
    goto L4;
    L5:;
    _sm_expr3 = ch <= 'Z';
    if (_sm_expr3) goto L3;
    goto L4;
    L3:;
    ch = ch + 32;
    L4:;
    simse_str_append(out, ch);
    i = i + 1;
    goto L1;
    L2:;
    return out;
}
Bool isEmpty(Str* self) {
    Int _sm_expr1;
    Bool _sm_expr2;
    _sm_expr1 = simse_lenOf((*self));
    _sm_expr2 = _sm_expr1 == 0;
    return _sm_expr2;
}
Bool isSpace(Char* self) {
    Char _sm_base1, _sm_base2, _sm_base3, _sm_base4;
    Bool _sm_expr2, _sm_expr1;
    _sm_base1 = ((*self));
    _sm_expr2 = _sm_base1 == ' ';
    _sm_expr1 = _sm_expr2;
    if (_sm_expr1) goto _sm_sc1;
    _sm_base2 = ((*self));
    _sm_expr2 = _sm_base2 == '\t';
    _sm_expr1 = _sm_expr2;
    if (_sm_expr1) goto _sm_sc1;
    _sm_base3 = ((*self));
    _sm_expr2 = _sm_base3 == '\n';
    _sm_expr1 = _sm_expr2;
    if (_sm_expr1) goto _sm_sc1;
    _sm_base4 = ((*self));
    _sm_expr2 = _sm_base4 == '\r';
    _sm_expr1 = _sm_expr2;
    _sm_sc1:;
    return _sm_expr1;
}
// stress/strings/src/main.kt
Int ns1_partStrIsEmpty() {
    Str _sm_base1, _sm_base2, _sm_base3;
    Bool _sm_expr1, _sm_expr2, _sm_expr3;
    _sm_base1 = __sm_stringTable[96];
    _sm_expr1 = isEmpty(simse_addressOf(_sm_base1));
    simse_println((_sm_expr1), stdout);
    _sm_base2 = __sm_stringTable[94];
    _sm_expr2 = isEmpty(simse_addressOf(_sm_base2));
    simse_println((_sm_expr2), stdout);
    _sm_base3 = __sm_stringTable[96];
    _sm_expr3 = isEmpty(simse_addressOf(_sm_base3));
    if (_sm_expr3) goto L1;
    goto L2;
    L1:;
    simse_println((__sm_stringTable[30]), stdout);
    L2:;
    return 0;
}
// stress/strings/src/main.kt
Int ns1_partStringEscapes() {
    Str newline, escaped, quote, tab, empty, longText;
    Int _sm_expr1, _sm_expr2, _sm_expr3, _sm_expr4, _sm_expr5, _sm_expr6;
    newline = __sm_stringTable[38];
    escaped = __sm_stringTable[25];
    quote = __sm_stringTable[10];
    tab = __sm_stringTable[68];
    empty = __sm_stringTable[96];
    longText = __sm_stringTable[1];
    _sm_expr1 = simse_lenOf(newline);
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = simse_lenOf(escaped);
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = simse_lenOf(quote);
    simse_println((_sm_expr3), stdout);
    _sm_expr4 = simse_lenOf(tab);
    simse_println((_sm_expr4), stdout);
    _sm_expr5 = simse_lenOf(empty);
    simse_println((_sm_expr5), stdout);
    simse_println((quote), stdout);
    simse_println((escaped), stdout);
    _sm_expr6 = simse_lenOf(longText);
    simse_println((_sm_expr6), stdout);
    simse_println((__sm_stringTable[89]), stdout);
    simse_println((__sm_stringTable[70]), stdout);
    simse_println((__sm_stringTable[47]), stdout);
    return 0;
}
// stress/strings/src/main.kt
Int ns1_partStrings() {
    Str _sm_base1, _sm_base2, _sm_base4, _sm_base6, raw, text, _sm_expr1, _sm_expr2, _sm_expr12,
        _sm_expr15;
    Str* _sm_base3, * _sm_base5;
    Bool _sm_expr3, _sm_expr5, _sm_expr13, _sm_expr14;
    Int _sm_expr6, _sm_expr7, _sm_expr9, _sm_expr10, _sm_expr11;
    List<Str> parts;
    Char _sm_expr8;
    raw = __sm_stringTable[6];
    text = trim(simse_addressOf(raw));
    simse_println((text), stdout);
    _sm_expr1 = toUpper(simse_addressOf(text));
    simse_println((_sm_expr1), stdout);
    _sm_expr2 = toLower(simse_addressOf(text));
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = isEmpty(simse_addressOf(text));
    simse_println((_sm_expr3), stdout);
    Str _sm_expr4;
    initByValue(simse_addressOf(_sm_expr4));
    _sm_expr5 = isEmpty(simse_addressOf(_sm_expr4));
    simse_println((_sm_expr5), stdout);
    _sm_expr6 = simse_lenOf(text);
    simse_println((_sm_expr6), stdout);
    parts = simse_str_split(text, __sm_stringTable[78]);
    _sm_expr7 = simse_lenOf(parts);
    simse_println((_sm_expr7), stdout);
    _sm_base1 = parts[0];
    simse_println((_sm_base1), stdout);
    _sm_base2 = parts[1];
    simse_println((_sm_base2), stdout);
    _sm_expr8 = simse_str_charAt(text, 0);
    simse_println((_sm_expr8), stdout);
    _sm_expr9 = simse_str_find(text, __sm_stringTable[24]);
    simse_println((_sm_expr9), stdout);
    _sm_expr10 = simse_str_find(text, __sm_stringTable[58]);
    simse_println((_sm_expr10), stdout);
    _sm_expr11 = simse_str_lastIndexOf(text, __sm_stringTable[90]);
    simse_println((_sm_expr11), stdout);
    _sm_expr12 = substr(simse_addressOf(text), 6, 5);
    simse_println((_sm_expr12), stdout);
    _sm_base4 = __sm_stringTable[22];
    _sm_base3 = &_sm_base4;
    _sm_expr13 = startsWith(simse_addressOf(text), _sm_base3);
    simse_println((_sm_expr13), stdout);
    _sm_base6 = __sm_stringTable[24];
    _sm_base5 = &_sm_base6;
    _sm_expr14 = endsWith(simse_addressOf(text), _sm_base5);
    simse_println((_sm_expr14), stdout);
    _sm_expr15 = simse_str_replace(text, __sm_stringTable[24], __sm_stringTable[23]);
    simse_println((_sm_expr15), stdout);
    return 0;
}
// stress/strings/src/main.kt
Int ns1_partTextProcessing() {
    Str* _sm_base2, * _sm_base3, * _sm_base5;
    Str _sm_base4, _sm_base6, text, word, longest, shout, _sm_expr19;
    List<Str> words, keys;
    Dictionary<Str, Int> counts;
    Int i, _sm_expr1, _sm_expr5, _sm_expr6, _sm_expr7, _sm_expr9, _sm_expr11, k, _sm_expr16;
    Bool _sm_expr2, _sm_expr12, _sm_expr18, _sm_expr20;
    Opt<Int> seen, _sm_expr8, _sm_expr10;
    text = __sm_stringTable[0];
    words = simse_str_split(text, __sm_stringTable[75]);
    counts = simse_dictionaryOf<Str, Int>();
    i = 0;
    L1:;
    _sm_expr1 = simse_lenOf(words);
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    word = words[i];
    seen = simse_dict_get(counts, word);
    _sm_expr2 = simse_optHasValue(simse_addressOf(seen));
    if (_sm_expr2) goto L3;
    goto L4;
    L3:;
    _sm_expr1 = simse_optValue(simse_addressOf(seen));
    _sm_expr5 = _sm_expr1 + 1;
    simse_dict_insert(counts, word, _sm_expr5);
    goto L5;
    L4:;
    simse_dict_insert(counts, word, 1);
    L5:;
    i = i + 1;
    goto L1;
    L2:;
    _sm_expr6 = simse_lenOf(words);
    simse_println((_sm_expr6), stdout);
    _sm_expr7 = simse_dict_size(counts);
    simse_println((_sm_expr7), stdout);
    _sm_expr8 = simse_dict_get(counts, __sm_stringTable[53]);
    _sm_expr9 = simse_optValue(simse_addressOf(_sm_expr8));
    simse_println((_sm_expr9), stdout);
    _sm_expr10 = simse_dict_get(counts, __sm_stringTable[49]);
    _sm_expr11 = simse_optValue(simse_addressOf(_sm_expr10));
    simse_println((_sm_expr11), stdout);
    _sm_expr12 = simse_dict_has(counts, __sm_stringTable[48]);
    simse_println((_sm_expr12), stdout);
    longest = __sm_stringTable[96];
    keys = simse_dict_keys(counts);
    simse_list_sort(keys, compareLessThan);
    k = 0;
    L6:;
    _sm_expr1 = simse_lenOf(keys);
    _sm_expr2 = k < _sm_expr1;
    if (!(_sm_expr2)) goto L7;
    _sm_base2 = simse_addressOf(keys[k]);
    _sm_expr1 = simse_lenOf((*_sm_base2));
    _sm_expr16 = simse_lenOf(longest);
    _sm_expr2 = _sm_expr1 > _sm_expr16;
    if (_sm_expr2) goto L8;
    goto L9;
    L8:;
    longest = keys[k];
    L9:;
    k = k + 1;
    goto L6;
    L7:;
    simse_println((longest), stdout);
    shout = toUpper(simse_addressOf(text));
    _sm_base4 = __sm_stringTable[45];
    _sm_base3 = &_sm_base4;
    _sm_expr18 = startsWith(simse_addressOf(shout), _sm_base3);
    simse_println((_sm_expr18), stdout);
    _sm_expr19 = simse_str_replace(text, __sm_stringTable[49], __sm_stringTable[48]);
    _sm_base6 = __sm_stringTable[48];
    _sm_base5 = &_sm_base6;
    _sm_expr20 = endsWith(simse_addressOf(_sm_expr19), _sm_base5);
    simse_println((_sm_expr20), stdout);
    return 0;
}
// stress/strings/src/main.kt
Str ns1_pair(Str* a, Str* b) {
    char* __sm_catP;
    Str _sm_base1, _sm_base2, _sm_expr1, _sm_expr2;
    _sm_base1 = *(a);
    _sm_expr1.resize(1 + _sm_base1.size());
    __sm_catP = _sm_expr1.data();
    std::memcpy(__sm_catP, _sm_base1.data(), _sm_base1.size());
    __sm_catP = __sm_catP + _sm_base1.size();
    *__sm_catP = (char) ('-');
    _sm_base2 = *(b);
    _sm_expr2.resize(_sm_expr1.size() + _sm_base2.size());
    __sm_catP = _sm_expr2.data();
    std::memcpy(__sm_catP, _sm_expr1.data(), _sm_expr1.size());
    __sm_catP = __sm_catP + _sm_expr1.size();
    std::memcpy(__sm_catP, _sm_base2.data(), _sm_base2.size());
    return _sm_expr2;
}
// stress/strings/src/main.kt
Int ns1_partConcat() {
    char* __sm_catP;
    Int __sm_catAt;
    Int __sm_catC0;
    Str* _sm_base1, * _sm_base3, * _sm_base5, * _sm_base6;
    Str _sm_base2, _sm_base4, a, b, _sm_expr2, _sm_expr3, _sm_expr5, _sm_expr6, _sm_expr7, _sm_expr8,
        _sm_expr9, _sm_expr10, _sm_expr12, _sm_expr13, acc, _sm_expr17, _sm_expr18, _sm_expr19, _sm_expr20,
        _sm_expr21, _sm_expr23, _sm_expr24, bare, _sm_expr25, _sm_expr26, _sm_expr27, _sm_expr28, _sm_expr29,
        _sm_expr30, _sm_expr31, _sm_expr32, _sm_expr33, _sm_expr34;
    Int* _sm_base7;
    List<Str> _sm_base16, _sm_base18, _sm_base31, _sm_base33, _sm_base35;
    List<Str>* _sm_base17, * _sm_base19, * _sm_base32, * _sm_base34, * _sm_base36;
    Int _sm_base29;
    ns1_Tag tag;
    StrView format, withFormat;
    Char withSep;
    a = __sm_stringTable[26];
    b = __sm_stringTable[39];
    _sm_expr2.resize(1 + a.size() + b.size());
    __sm_catP = _sm_expr2.data();
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    std::memcpy(__sm_catP, b.data(), b.size());
    __sm_catP = __sm_catP + b.size();
    *__sm_catP = (char) ('!');
    simse_println((_sm_expr2), stdout);
    _sm_expr3.resize(1 + a.size());
    __sm_catP = _sm_expr3.data();
    *__sm_catP = (char) ('x');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, a.data(), a.size());
    simse_println((_sm_expr3), stdout);
    _sm_expr5.resize(1 + a.size() + b.size());
    __sm_catP = _sm_expr5.data();
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    *__sm_catP = (char) (':');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, b.data(), b.size());
    simse_println((_sm_expr5), stdout);
    _sm_base2 = __sm_stringTable[91];
    _sm_base1 = &_sm_base2;
    _sm_base4 = __sm_stringTable[92];
    _sm_base3 = &_sm_base4;
    _sm_expr6 = ns1_pair(_sm_base1, _sm_base3);
    _sm_expr7.resize(a.size() + _sm_expr6.size());
    __sm_catP = _sm_expr7.data();
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    std::memcpy(__sm_catP, _sm_expr6.data(), _sm_expr6.size());
    simse_println((_sm_expr7), stdout);
    _sm_base5 = &a;
    _sm_base6 = &b;
    _sm_expr8 = ns1_pair(_sm_base5, _sm_base6);
    simse_println((_sm_expr8), stdout);
    tag = ns1_Tag{__sm_stringTable[93], 3};
    _sm_expr9 = tag.name;
    _sm_expr10.resize(1 + _sm_expr9.size());
    __sm_catP = _sm_expr10.data();
    std::memcpy(__sm_catP, _sm_expr9.data(), _sm_expr9.size());
    __sm_catP = __sm_catP + _sm_expr9.size();
    *__sm_catP = (char) ('=');
    _sm_base7 = simse_addressOf(tag.count);
    __sm_catC0 = simse_strCountDigits((*_sm_base7));
    _sm_expr12.resize(_sm_expr10.size() + __sm_catC0);
    __sm_catP = _sm_expr12.data();
    std::memcpy(__sm_catP, _sm_expr10.data(), _sm_expr10.size());
    __sm_catP = __sm_catP + _sm_expr10.size();
    simse_strAddInt(__sm_catP, (*_sm_base7), __sm_catC0);
    simse_println((_sm_expr12), stdout);
    _sm_expr13.resize(4);
    __sm_catP = _sm_expr13.data();
    std::memcpy(__sm_catP, "aa", 2);
    __sm_catP = __sm_catP + 2;
    std::memcpy(__sm_catP, "bb", 2);
    simse_println((_sm_expr13), stdout);
    acc = __sm_stringTable[51];
    __sm_catAt = acc.size();
    acc.resize(__sm_catAt + 1 + a.size() + b.size());
    __sm_catP = acc.data() + __sm_catAt;
    *__sm_catP = (char) ('-');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    std::memcpy(__sm_catP, b.data(), b.size());
    simse_println((acc), stdout);
    _sm_expr17.resize(2 + acc.size());
    __sm_catP = _sm_expr17.data();
    *__sm_catP = (char) ('[');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, acc.data(), acc.size());
    __sm_catP = __sm_catP + acc.size();
    *__sm_catP = (char) (']');
    simse_println((_sm_expr17), stdout);
    _sm_expr18.resize(5);
    __sm_catP = _sm_expr18.data();
    std::memcpy(__sm_catP, "plain", 5);
    simse_println((_sm_expr18), stdout);
    _sm_expr19.resize(2 + a.size());
    __sm_catP = _sm_expr19.data();
    std::memcpy(__sm_catP, "a=", 2);
    __sm_catP = __sm_catP + 2;
    std::memcpy(__sm_catP, a.data(), a.size());
    simse_println((_sm_expr19), stdout);
    _sm_expr20.resize(1 + a.size() + b.size());
    __sm_catP = _sm_expr20.data();
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    *__sm_catP = (char) ('x');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, b.data(), b.size());
    simse_println((_sm_expr20), stdout);
    _sm_expr21.resize(3 + a.size() + b.size());
    __sm_catP = _sm_expr21.data();
    std::memcpy(__sm_catP, "b=", 2);
    __sm_catP = __sm_catP + 2;
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    *__sm_catP = (char) ('=');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, b.data(), b.size());
    simse_println((_sm_expr21), stdout);
    _sm_expr23.resize(a.size());
    __sm_catP = _sm_expr23.data();
    std::memcpy(__sm_catP, a.data(), a.size());
    simse_println((_sm_expr23), stdout);
    _sm_expr24.resize(0);
    simse_println((_sm_expr24), stdout);
    bare = __sm_stringTable[85];
    __sm_catAt = bare.size();
    bare.resize(__sm_catAt + 0);
    simse_println((bare), stdout);
    format = __sm_stringTable[55];
    _sm_base16 = List<Str>{a};
    _sm_base17 = &_sm_base16;
    _sm_expr25 = fmtStr(format, _sm_base17);
    simse_println((_sm_expr25), stdout);
    _sm_base18 = List<Str>{a};
    _sm_base19 = &_sm_base18;
    _sm_expr26 = fmtStr(__sm_stringTable[19], _sm_base19);
    simse_println((_sm_expr26), stdout);
    _sm_expr27.resize(2 + a.size());
    __sm_catP = _sm_expr27.data();
    std::memcpy(__sm_catP, "x=", 2);
    __sm_catP = __sm_catP + 2;
    std::memcpy(__sm_catP, a.data(), a.size());
    simse_println((_sm_expr27), stdout);
    _sm_expr28.resize(2 + a.size());
    __sm_catP = _sm_expr28.data();
    *__sm_catP = (char) ('|');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    *__sm_catP = (char) ('|');
    simse_println((_sm_expr28), stdout);
    _sm_expr29.resize(3 + a.size() + b.size());
    __sm_catP = _sm_expr29.data();
    std::memcpy(__sm_catP, "c=", 2);
    __sm_catP = __sm_catP + 2;
    std::memcpy(__sm_catP, a.data(), a.size());
    __sm_catP = __sm_catP + a.size();
    *__sm_catP = (char) (':');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, b.data(), b.size());
    simse_println((_sm_expr29), stdout);
    _sm_expr30.resize(5);
    __sm_catP = _sm_expr30.data();
    std::memcpy(__sm_catP, "plain", 5);
    simse_println((_sm_expr30), stdout);
    _sm_base29 = tag.count;
    __sm_catC0 = simse_strCountDigits(_sm_base29);
    _sm_expr31.resize(2 + __sm_catC0);
    __sm_catP = _sm_expr31.data();
    std::memcpy(__sm_catP, "n=", 2);
    __sm_catP = __sm_catP + 2;
    simse_strAddInt(__sm_catP, _sm_base29, __sm_catC0);
    simse_println((_sm_expr31), stdout);
    withFormat = __sm_stringTable[56];
    _sm_base31 = List<Str>{a};
    _sm_base32 = &_sm_base31;
    _sm_expr32 = fmtStrWith('@', withFormat, _sm_base32);
    simse_println((_sm_expr32), stdout);
    withSep = '@';
    _sm_base33 = List<Str>{a};
    _sm_base34 = &_sm_base33;
    _sm_expr33 = fmtStrWith(withSep, __sm_stringTable[52], _sm_base34);
    simse_println((_sm_expr33), stdout);
    _sm_base35 = List<Str>{a};
    _sm_base36 = &_sm_base35;
    _sm_expr34 = fmtStrWith('@', __sm_stringTable[18], _sm_base36);
    simse_println((_sm_expr34), stdout);
    return 0;
}
// stress/strings/src/main.kt
Int ns1_partRawStrings() {
    char* __sm_catP;
    Int __sm_catC0;
    Str* _sm_base1, * _sm_base2, * _sm_base4;
    Str _sm_base3, text, empty, quoted, who, _sm_expr10, _sm_expr11, _sm_expr12, _sm_expr13, _sm_expr14,
        _sm_expr15, _sm_expr16, _sm_expr17, _sm_expr18, _sm_expr20, multi, piped, plain;
    List<Str> _sm_base25, _sm_base27;
    List<Str>* _sm_base26, * _sm_base28;
    Int _sm_expr1, _sm_expr2, _sm_when1_n, _sm_expr9, n;
    Bool _sm_expr3, _sm_expr5, _sm_expr6, _sm_expr7;
    StrView _sm_expr4, _sm_when1_v;
    text = __sm_stringTable[3];
    _sm_expr1 = simse_lenOf(text);
    simse_println((_sm_expr1), stdout);
    simse_println((text), stdout);
    empty = __sm_stringTable[96];
    _sm_expr2 = simse_lenOf(empty);
    simse_println((_sm_expr2), stdout);
    _sm_expr3 = isEmpty(simse_addressOf(empty));
    simse_println((_sm_expr3), stdout);
    _sm_base1 = &text;
    _sm_expr4 = simse_spanOfStr(_sm_base1);
    _sm_expr5 = equals(simse_addressOf(_sm_expr4), __sm_stringTable[2]);
    simse_println((_sm_expr5), stdout);
    _sm_base3 = __sm_stringTable[13];
    _sm_base2 = &_sm_base3;
    _sm_expr6 = startsWith(simse_addressOf(text), _sm_base2);
    simse_println((_sm_expr6), stdout);
    _sm_base4 = &text;
    _sm_when1_v = simse_spanOfStr(_sm_base4);
    _sm_when1_n = _sm_when1_v.size();
    _sm_expr7 = _sm_when1_n == 39;
    if (_sm_expr7) goto L3;
    goto L2;
    L3:;
    _sm_expr7 = equals(simse_addressOf(_sm_when1_v), __sm_stringTable[3]);
    if (_sm_expr7) goto L1;
    goto L2;
    L1:;
    simse_println((__sm_stringTable[17]), stdout);
    goto L4;
    L2:;
    simse_println((__sm_stringTable[72]), stdout);
    L4:;
    quoted = __sm_stringTable[4];
    _sm_expr9 = simse_lenOf(quoted);
    simse_println((_sm_expr9), stdout);
    simse_println((quoted), stdout);
    who = __sm_stringTable[34];
    n = 42;
    _sm_expr10.resize(6 + who.size());
    __sm_catP = _sm_expr10.data();
    std::memcpy(__sm_catP, "hello ", 6);
    __sm_catP = __sm_catP + 6;
    std::memcpy(__sm_catP, who.data(), who.size());
    simse_println((_sm_expr10), stdout);
    _sm_expr11.resize(1 + who.size());
    __sm_catP = _sm_expr11.data();
    std::memcpy(__sm_catP, who.data(), who.size());
    __sm_catP = __sm_catP + who.size();
    *__sm_catP = (char) ('!');
    simse_println((_sm_expr11), stdout);
    _sm_expr12.resize(who.size() + who.size());
    __sm_catP = _sm_expr12.data();
    std::memcpy(__sm_catP, who.data(), who.size());
    __sm_catP = __sm_catP + who.size();
    std::memcpy(__sm_catP, who.data(), who.size());
    simse_println((_sm_expr12), stdout);
    __sm_catC0 = simse_strCountDigits(n);
    _sm_expr13.resize(2 + __sm_catC0);
    __sm_catP = _sm_expr13.data();
    std::memcpy(__sm_catP, "n=", 2);
    __sm_catP = __sm_catP + 2;
    simse_strAddInt(__sm_catP, n, __sm_catC0);
    simse_println((_sm_expr13), stdout);
    simse_println((__sm_stringTable[7]), stdout);
    simse_println((__sm_stringTable[84]), stdout);
    _sm_expr14.resize(4 + who.size());
    __sm_catP = _sm_expr14.data();
    std::memcpy(__sm_catP, "a|b=", 4);
    __sm_catP = __sm_catP + 4;
    std::memcpy(__sm_catP, who.data(), who.size());
    simse_println((_sm_expr14), stdout);
    _sm_expr15.resize(2 + who.size());
    __sm_catP = _sm_expr15.data();
    *__sm_catP = (char) ('|');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, who.data(), who.size());
    __sm_catP = __sm_catP + who.size();
    *__sm_catP = (char) ('|');
    simse_println((_sm_expr15), stdout);
    __sm_catC0 = simse_strCountDigits(n);
    _sm_expr16.resize(5 + who.size() + __sm_catC0);
    __sm_catP = _sm_expr16.data();
    std::memcpy(__sm_catP, "_sm_", 4);
    __sm_catP = __sm_catP + 4;
    std::memcpy(__sm_catP, who.data(), who.size());
    __sm_catP = __sm_catP + who.size();
    *__sm_catP = (char) ('_');
    __sm_catP = __sm_catP + 1;
    simse_strAddInt(__sm_catP, n, __sm_catC0);
    simse_println((_sm_expr16), stdout);
    __sm_catC0 = simse_strCountDigits(n);
    _sm_expr17.resize(who.size() + __sm_catC0);
    __sm_catP = _sm_expr17.data();
    std::memcpy(__sm_catP, who.data(), who.size());
    __sm_catP = __sm_catP + who.size();
    simse_strAddInt(__sm_catP, n, __sm_catC0);
    simse_println((_sm_expr17), stdout);
    _sm_expr18.resize(2 + who.size());
    __sm_catP = _sm_expr18.data();
    *__sm_catP = (char) ('(');
    __sm_catP = __sm_catP + 1;
    std::memcpy(__sm_catP, who.data(), who.size());
    __sm_catP = __sm_catP + who.size();
    *__sm_catP = (char) (')');
    simse_println((_sm_expr18), stdout);
    _sm_expr20.resize(11 + who.size());
    __sm_catP = _sm_expr20.data();
    std::memcpy(__sm_catP, "a@ b and ", 9);
    __sm_catP = __sm_catP + 9;
    std::memcpy(__sm_catP, who.data(), who.size());
    __sm_catP = __sm_catP + who.size();
    std::memcpy(__sm_catP, " |", 2);
    simse_println((_sm_expr20), stdout);
    _sm_base25 = List<Str>{who, who};
    _sm_base26 = &_sm_base25;
    multi = fmtStrWith('@', __sm_stringTable[5], _sm_base26);
    simse_println((multi), stdout);
    _sm_base27 = List<Str>{who};
    _sm_base28 = &_sm_base27;
    piped = fmtStrWith('@', __sm_stringTable[21], _sm_base28);
    simse_println((piped), stdout);
    plain = __sm_stringTable[36];
    simse_println((plain), stdout);
    return 0;
}
// stress/strings/src/main.kt
Str ns1_classify(Str* op) {
    StrView _sm_when2_v;
    Int _sm_when2_n;
    Bool _sm_expr1;
    Char _sm_expr3;
    _sm_when2_v = simse_spanOfStr(op);
    _sm_when2_n = _sm_when2_v.size();
    _sm_expr1 = _sm_when2_n == 0;
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[30];
    L2:;
    _sm_expr1 = _sm_when2_n == 1;
    if (_sm_expr1) goto L8;
    goto L7;
    L8:;
    _sm_expr3 = get(simse_addressOf(_sm_when2_v), 0);
    _sm_expr1 = _sm_expr3 == '|';
    if (_sm_expr1) goto L4;
    L7:;
    _sm_expr1 = _sm_when2_n == 1;
    if (_sm_expr1) goto L9;
    goto L6;
    L9:;
    _sm_expr3 = get(simse_addressOf(_sm_when2_v), 0);
    _sm_expr1 = _sm_expr3 == '^';
    if (_sm_expr1) goto L4;
    L6:;
    _sm_expr1 = _sm_when2_n == 1;
    if (_sm_expr1) goto L10;
    goto L5;
    L10:;
    _sm_expr3 = get(simse_addressOf(_sm_when2_v), 0);
    _sm_expr1 = _sm_expr3 == '&';
    if (_sm_expr1) goto L4;
    goto L5;
    L4:;
    return __sm_stringTable[15];
    L5:;
    _sm_expr1 = _sm_when2_n == 2;
    if (_sm_expr1) goto L15;
    goto L14;
    L15:;
    _sm_expr1 = equals(simse_addressOf(_sm_when2_v), __sm_stringTable[64]);
    if (_sm_expr1) goto L12;
    L14:;
    _sm_expr1 = _sm_when2_n == 2;
    if (_sm_expr1) goto L16;
    goto L13;
    L16:;
    _sm_expr1 = equals(simse_addressOf(_sm_when2_v), __sm_stringTable[61]);
    if (_sm_expr1) goto L12;
    goto L13;
    L12:;
    return __sm_stringTable[12];
    L13:;
    _sm_expr1 = _sm_when2_n == 1;
    if (_sm_expr1) goto L23;
    goto L22;
    L23:;
    _sm_expr3 = get(simse_addressOf(_sm_when2_v), 0);
    _sm_expr1 = _sm_expr3 == '<';
    if (_sm_expr1) goto L18;
    L22:;
    _sm_expr1 = _sm_when2_n == 1;
    if (_sm_expr1) goto L24;
    goto L21;
    L24:;
    _sm_expr3 = get(simse_addressOf(_sm_when2_v), 0);
    _sm_expr1 = _sm_expr3 == '>';
    if (_sm_expr1) goto L18;
    L21:;
    _sm_expr1 = _sm_when2_n == 2;
    if (_sm_expr1) goto L25;
    goto L20;
    L25:;
    _sm_expr1 = equals(simse_addressOf(_sm_when2_v), __sm_stringTable[63]);
    if (_sm_expr1) goto L18;
    L20:;
    _sm_expr1 = _sm_when2_n == 2;
    if (_sm_expr1) goto L26;
    goto L19;
    L26:;
    _sm_expr1 = equals(simse_addressOf(_sm_when2_v), __sm_stringTable[65]);
    if (_sm_expr1) goto L18;
    goto L19;
    L18:;
    return __sm_stringTable[9];
    L19:;
    _sm_expr1 = _sm_when2_n == 2;
    if (_sm_expr1) goto L30;
    goto L29;
    L30:;
    _sm_expr1 = equals(simse_addressOf(_sm_when2_v), __sm_stringTable[62]);
    if (_sm_expr1) goto L28;
    goto L29;
    L28:;
    return __sm_stringTable[33];
    L29:;
    return __sm_stringTable[31];
}
// stress/strings/src/main.kt
Str ns1_classifyPtr(Str* op) {
    Str* _sm_base1;
    StrView _sm_when3_v;
    Int _sm_when3_n;
    Bool _sm_expr1;
    Char _sm_expr3;
    _sm_base1 = op;
    _sm_when3_v = simse_spanOfStr(_sm_base1);
    _sm_when3_n = _sm_when3_v.size();
    _sm_expr1 = _sm_when3_n == 0;
    if (_sm_expr1) goto L1;
    _sm_expr1 = _sm_when3_n == 1;
    if (_sm_expr1) goto L4;
    goto L2;
    L4:;
    _sm_expr3 = get(simse_addressOf(_sm_when3_v), 0);
    _sm_expr1 = _sm_expr3 == '|';
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[8];
    L2:;
    _sm_expr1 = _sm_when3_n == 2;
    if (_sm_expr1) goto L9;
    goto L8;
    L9:;
    _sm_expr1 = equals(simse_addressOf(_sm_when3_v), __sm_stringTable[64]);
    if (_sm_expr1) goto L6;
    L8:;
    _sm_expr1 = _sm_when3_n == 2;
    if (_sm_expr1) goto L10;
    goto L7;
    L10:;
    _sm_expr1 = equals(simse_addressOf(_sm_when3_v), __sm_stringTable[70]);
    if (_sm_expr1) goto L6;
    goto L7;
    L6:;
    return __sm_stringTable[54];
    L7:;
    return __sm_stringTable[31];
}
// stress/strings/src/main.kt
Str ns1_viewKind(StrView v) {
    StrView _sm_when4_v;
    Int _sm_when4_n;
    Bool _sm_expr1;
    Char _sm_expr2;
    _sm_when4_v = simse_spanOfStr(v);
    _sm_when4_n = _sm_when4_v.size();
    _sm_expr1 = _sm_when4_n == 1;
    if (_sm_expr1) goto L4;
    goto L3;
    L4:;
    _sm_expr2 = get(simse_addressOf(_sm_when4_v), 0);
    _sm_expr1 = _sm_expr2 == 'a';
    if (_sm_expr1) goto L1;
    L3:;
    _sm_expr1 = _sm_when4_n == 1;
    if (_sm_expr1) goto L5;
    goto L2;
    L5:;
    _sm_expr2 = get(simse_addressOf(_sm_when4_v), 0);
    _sm_expr1 = _sm_expr2 == 'b';
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[20];
    L2:;
    _sm_expr1 = _sm_when4_n == 2;
    if (_sm_expr1) goto L9;
    goto L8;
    L9:;
    _sm_expr1 = equals(simse_addressOf(_sm_when4_v), __sm_stringTable[70]);
    if (_sm_expr1) goto L7;
    goto L8;
    L7:;
    return __sm_stringTable[41];
    L8:;
    return __sm_stringTable[83];
}
// stress/strings/src/main.kt
Str ns1_fixed(Str* op) {
    Str _sm_base1;
    Bool _sm_expr1;
    _sm_base1 = *(op);
    _sm_expr1 = equals(simse_addressOf(simse_spanOfStr(simse_addressOf(_sm_base1))), __sm_stringTable[40]);
    if (_sm_expr1) goto L1;
    goto L2;
    L1:;
    return __sm_stringTable[37];
    L2:;
    return __sm_stringTable[31];
}
// stress/strings/src/main.kt
Int ns1_partWhenStrings() {
    char* __sm_catP;
    List<Str>* _sm_base1, * _sm_base3;
    Str* _sm_base2, * _sm_base4, * _sm_base5, * _sm_base7;
    Str _sm_base6, _sm_base8, op, _sm_expr3, _sm_expr4, _sm_expr5, _sm_expr8, _sm_expr10, _sm_expr11,
        _sm_expr12, word, _sm_expr18, _sm_expr22;
    List<Str> ops, words;
    Span<Str> _sm_expr1, _sm_expr13;
    Span_iterValues_yieldable<Str> _sm_for6, _sm_for7;
    Bool _sm_expr2;
    Ref<Str> _sm_expr16;
    ops = List<Str>{__sm_stringTable[96], __sm_stringTable[95], __sm_stringTable[88], __sm_stringTable[77], __sm_stringTable[64], __sm_stringTable[61], __sm_stringTable[80], __sm_stringTable[82], __sm_stringTable[63], __sm_stringTable[65], __sm_stringTable[62], __sm_stringTable[73], __sm_stringTable[74]};
    _sm_base1 = &ops;
    _sm_expr1 = simse_spanOf(_sm_base1);
    _sm_for6 = iterValues(simse_addressOf(_sm_expr1));
    L1:;
    _sm_expr2 = advance(&_sm_for6);
    if (!(_sm_expr2)) goto L2;
    op = _sm_for6.current;
    _sm_expr3.resize(4 + op.size());
    __sm_catP = _sm_expr3.data();
    std::memcpy(__sm_catP, op.data(), op.size());
    __sm_catP = __sm_catP + op.size();
    std::memcpy(__sm_catP, " -> ", 4);
    _sm_base2 = &op;
    _sm_expr4 = ns1_classify(_sm_base2);
    _sm_expr5.resize(_sm_expr3.size() + _sm_expr4.size());
    __sm_catP = _sm_expr5.data();
    std::memcpy(__sm_catP, _sm_expr3.data(), _sm_expr3.size());
    __sm_catP = __sm_catP + _sm_expr3.size();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    simse_println((_sm_expr5), stdout);
    goto L1;
    L2:;
    _sm_expr3 = ns1_viewKind(__sm_stringTable[89]);
    _sm_expr4.resize(1 + _sm_expr3.size());
    __sm_catP = _sm_expr4.data();
    std::memcpy(__sm_catP, _sm_expr3.data(), _sm_expr3.size());
    __sm_catP = __sm_catP + _sm_expr3.size();
    *__sm_catP = (char) (' ');
    _sm_expr8 = ns1_viewKind(__sm_stringTable[70]);
    _sm_expr10.resize(1 + _sm_expr4.size() + _sm_expr8.size());
    __sm_catP = _sm_expr10.data();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    __sm_catP = __sm_catP + _sm_expr4.size();
    std::memcpy(__sm_catP, _sm_expr8.data(), _sm_expr8.size());
    __sm_catP = __sm_catP + _sm_expr8.size();
    *__sm_catP = (char) (' ');
    _sm_expr11 = ns1_viewKind(__sm_stringTable[47]);
    _sm_expr12.resize(_sm_expr10.size() + _sm_expr11.size());
    __sm_catP = _sm_expr12.data();
    std::memcpy(__sm_catP, _sm_expr10.data(), _sm_expr10.size());
    __sm_catP = __sm_catP + _sm_expr10.size();
    std::memcpy(__sm_catP, _sm_expr11.data(), _sm_expr11.size());
    simse_println((_sm_expr12), stdout);
    words = List<Str>{__sm_stringTable[96], __sm_stringTable[95], __sm_stringTable[70], __sm_stringTable[73]};
    _sm_base3 = &words;
    _sm_expr13 = simse_spanOf(_sm_base3);
    _sm_for7 = iterValues(simse_addressOf(_sm_expr13));
    L3:;
    _sm_expr2 = advance(&_sm_for7);
    if (!(_sm_expr2)) goto L4;
    word = _sm_for7.current;
    _sm_expr3.resize(3 + word.size());
    __sm_catP = _sm_expr3.data();
    std::memcpy(__sm_catP, word.data(), word.size());
    __sm_catP = __sm_catP + word.size();
    std::memcpy(__sm_catP, " ~ ", 3);
    _sm_expr16 = makeRef<std::remove_cvref_t<decltype((word))>>(word);
    _sm_base4 = (_sm_expr16).get();
    _sm_expr4 = ns1_classifyPtr(_sm_base4);
    _sm_expr18.resize(_sm_expr3.size() + _sm_expr4.size());
    __sm_catP = _sm_expr18.data();
    std::memcpy(__sm_catP, _sm_expr3.data(), _sm_expr3.size());
    __sm_catP = __sm_catP + _sm_expr3.size();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    simse_println((_sm_expr18), stdout);
    goto L3;
    L4:;
    _sm_base6 = __sm_stringTable[40];
    _sm_base5 = &_sm_base6;
    _sm_expr3 = ns1_fixed(_sm_base5);
    _sm_expr4.resize(1 + _sm_expr3.size());
    __sm_catP = _sm_expr4.data();
    std::memcpy(__sm_catP, _sm_expr3.data(), _sm_expr3.size());
    __sm_catP = __sm_catP + _sm_expr3.size();
    *__sm_catP = (char) (' ');
    _sm_base8 = __sm_stringTable[31];
    _sm_base7 = &_sm_base8;
    _sm_expr8 = ns1_fixed(_sm_base7);
    _sm_expr22.resize(_sm_expr4.size() + _sm_expr8.size());
    __sm_catP = _sm_expr22.data();
    std::memcpy(__sm_catP, _sm_expr4.data(), _sm_expr4.size());
    __sm_catP = __sm_catP + _sm_expr4.size();
    std::memcpy(__sm_catP, _sm_expr8.data(), _sm_expr8.size());
    simse_println((_sm_expr22), stdout);
    return 0;
}
// stress/strings/src/main.kt
int main() {
    ns1_partStrIsEmpty();
    ns1_partStringEscapes();
    ns1_partStrings();
    ns1_partTextProcessing();
    ns1_partConcat();
    ns1_partRawStrings();
    ns1_partWhenStrings();
    return 0;
}

template <class T>
inline Span<T> simse_spanOf(List<T>* items) {
    return Span<T>(items->data(), items->size());
}

template <class T>
inline Span<T> simse_spanOf(Array<T>* items) {
    const Int count = items->count();
    return Span<T>(count > 0 ? &(*items)[0] : nullptr, count);
}

inline StrView simse_spanOfStr(Str* text) {
    return StrView(reinterpret_cast<Char*>(text->data()), text->size());
}

inline StrView simse_spanOfStr(StrView view) {
    return view;
}

template <class T>
inline void simse_list_append(List<T>& self, const std::type_identity_t<T>& value) {
    self.push_back(value);
}

template <class T>
inline List<T> simse_listOf(const List<T>* values) {
    return *values;
}

template <class T>
inline void simse_list_removeAt(List<T>& self, Int index) {
    self.erase(self.begin() + index);
}

template <class T>
inline void simse_list_removeRange(List<T>& self, Int start, Int end) {
    self.erase(self.begin() + start, self.begin() + end);
}

template <class T>
inline Int simse_array_count(const Array<T>& self) {
    return self.count();
}

template <class T>
inline Array<T> simse_list_toArray(const List<T>& self) {
    const Int count = self.size();
    if (count <= 0) {
        return Array<T>();
    }
    Array<T> result(count);
    for (Int i = 0; i < count; i++) {
        result[i] = self[i];
    }
    return result;
}

template <class T>
inline List<T> simse_array_toList(const Array<T>& self) {
    List<T> result;
    const Int count = self.count();
    result.reserve(count);
    for (Int i = 0; i < count; i++) {
        result.push_back(self[i]);
    }
    return result;
}

template <class T>
inline Array<T> simse_arrayEmpty() {
    return Array<T>();
}

inline void simse_str_append(Str& self, Char value) {
    self.push_back(static_cast<char>(value));
}

inline void simse_str_appendStr(Str& self, const Str& value) {
    self.append(value);
}

inline void simse_str_appendStrPtr(Str& self, const Str* value) {
    if (value != nullptr) self.append(*value);
}

inline void simse_str_reserve(Str& self, Int count) {
    self.reserve((Str::size_type) count);
}

inline Str simse_int_toString(Int self) {
    return std::to_string(self);
}

template <class K, class V>
inline Dictionary<K, V> simse_dictionaryOf() {
    return Dictionary<K, V>();
}

template <class K, class V>
inline V* simse_dict_getPtr(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return self.valuePtr(key);
}

template <class K, class V>
inline Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    const V* found = simse_dict_getPtr(self, key);
    if (found == nullptr) return Opt<V>();
    Opt<V> result;
    result.setValue(*found);
    return result;
}

template <class K, class V>
inline Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return simse_dict_getPtr(self, key) != nullptr;
}

template <class K, class V>
inline void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                              const std::type_identity_t<V>& value) {
    self.insert_or_assign(key, value);
}

template <class K, class V>
inline void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    self.erase(key);
}

template <class K, class V>
inline Int simse_dict_size(const Dictionary<K, V>& self) {
    return (Int) self.size();
}

template <class K, class V>
inline List<K> simse_dict_keys(const Dictionary<K, V>& self) {
    List<K> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.first);
    return out;
}

template <class K, class V>
inline List<V> simse_dict_values(const Dictionary<K, V>& self) {
    List<V> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.second);
    return out;
}

template <class K, class V>
inline void simse_dict_clear(Dictionary<K, V>& self) {
    self.clear();
}

template <class T>
inline Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value) {
    for (const T& item : self) {
        if (item == value) return true;
    }
    return false;
}

template <class T, class F>
inline void simse_list_sort(List<T>& self, F less) {
    Func<Bool(T*, T*)> fn = less;
    std::sort(self.begin(), self.end(), [&fn](const T& a, const T& b) {
        return fn(const_cast<T*>(&a), const_cast<T*>(&b));
    });
}

inline Int simse_lenOf(const Str& self) {
    return self.size();
}

template <class T, int N>
inline Int simse_lenOf(const SmallVector<T, N>& self) {
    return self.size();
}

inline Char simse_str_charAt(const Str& self, Int index) {
    return (Char) self[index];
}

inline List<Str> simse_str_split(const Str& self, const Str& separator) {
    List<Str> parts;
    if (separator.empty()) {
        parts.push_back(self);
        return parts;
    }
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + separator.size();
    }
    return parts;
}

inline Int simse_count_char_in_str(const Str* self, char ch) {
    Int count = 0;
    const char* data = self->data();
    Int len = self->size();
    for (Int i = 0; i < len; i++) {
        if (data[i] == ch) {
            count++;
        }
    }
    return count;
}

inline List<Str> simse_str_split(const Str& self, Char separator) {
    List<Str> parts;
    parts.reserve(simse_count_char_in_str(&self, separator));
    Int pos = 0;
    while (true) {
        Int found = self.find(separator, pos);
        if (found == Str::npos) {
            parts.push_back(self.substr(pos));
            break;
        }
        parts.push_back(self.substr(pos, found - pos));
        pos = found + 1;
    }
    return parts;
}

inline Int simse_str_find(const Str& self, const Str& sub) {
    Int found = self.find(sub);
    return found == Str::npos ? -1 : found;
}

inline Int simse_str_lastIndexOf(const Str& self, const Str& sub) {
    Int found = self.rfind(sub);
    return found == Str::npos ? -1 : found;
}

inline Str simse_str_replace(const Str& self, const Str& from, const Str& to) {
    if (from.empty()) return self;
    Str result;
    Int pos = 0;
    while (true) {
        Int found = self.find(from, pos);
        if (found == Str::npos) {
            result.append(self, pos, Str::npos);
            break;
        }
        result.append(self, pos, found - pos);
        result += to;
        pos = found + from.size();
    }
    return result;
}

inline Opt<Int> simse_str_toInt(const Str& self) {
    if (self.empty()) return Opt<Int>();
    Int value = 0;
    const char* begin = self.data();
    const char* end = begin + self.size();
    std::from_chars_result parsed = std::from_chars(begin, end, value);
    if (parsed.ec != std::errc() || parsed.ptr != end) return Opt<Int>();
    Opt<Int> result;
    result.setValue(value);
    return result;
}

inline Opt<Float64> simse_str_toFloat(const Str& self) {
    if (self.empty()) return Opt<Float64>();
    const char* begin = self.data();
    char* end = nullptr;
    errno = 0;
    const Float64 value = std::strtod(begin, &end);
    if (end != begin + self.size() || errno == ERANGE) return Opt<Float64>();
    Opt<Float64> result;
    result.setValue(value);
    return result;
}

inline void simse_str_initByValue(Str& self, const Str& value) {
    self = value;
}

template <class T>
inline Str simse_num_toString(const T& self) {
    return std::to_string(self);
}

inline Str simse_char_toString(Char self) {
    return std::to_string((int) self);
}

inline Str simse_bool_toString(Bool self) {
    return self ? "true" : "false";
}

static const unsigned long long smStrDigitPow10[20] = {
    1ull, 10ull, 100ull, 1000ull, 10000ull, 100000ull, 1000000ull, 10000000ull,
    100000000ull, 1000000000ull, 10000000000ull, 100000000000ull, 1000000000000ull,
    10000000000000ull, 100000000000000ull, 1000000000000000ull, 10000000000000000ull,
    100000000000000000ull, 1000000000000000000ull, 10000000000000000000ull
};

inline Int simse_strCountDigits(Int64 value) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (magnitude < 10ull) {
        return value < 0 ? 2 : 1;
    }
    Int bits = (Int) std::bit_width(magnitude);
    Int guess = (Int) (((unsigned int) bits * 1233u) >> 12);
    Int digits = guess + (magnitude >= smStrDigitPow10[guess] ? 1 : 0);
    return digits + (value < 0 ? 1 : 0);
}

struct SmStrDigitPairTable {
    char text[200];
    constexpr SmStrDigitPairTable() : text() {
        for (Int i = 0; i < 100; i = i + 1) {
            text[i * 2] = (char) ('0' + i / 10);
            text[i * 2 + 1] = (char) ('0' + i % 10);
        }
    }
};

static constexpr SmStrDigitPairTable smStrDigitPairs{};

inline void simse_strAddInt(char* target, Int64 value, Int count) {
    unsigned long long magnitude =
        value < 0 ? 0ull - (unsigned long long) value : (unsigned long long) value;
    if (value < 0) {
        target[0] = '-';
        count = count - 1;
        target = target + 1;
    }
    while (count >= 2) {
        unsigned int pair = (unsigned int) (magnitude % 100ull);
        magnitude /= 100ull;
        count = count - 2;
        target[count] = smStrDigitPairs.text[pair * 2];
        target[count + 1] = smStrDigitPairs.text[pair * 2 + 1];
    }
    if (count == 1) {
        target[0] = (char) ('0' + (Int) magnitude);
    }
}

inline StrView simse_strBoolView(Bool value) {
    static Char texts[2][6] = {"true", "false"};
    static Int lens[2] = {4, 5};
    Int at = value ? 0 : 1;
    return StrView(texts[at], lens[at]);
}

template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; 
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  
    Int length = 0; 
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = StrView(bytes + at, length);
    }
}

Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

Int64 simse_nowNanos() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::nanoseconds>(now).count();
}
