// Generated by the Simse compiler. Do not edit.
#include "cppsrc/rtl/simse.hpp"
#include <iostream>
#include <type_traits>

// The program's string literals: one pool, and two run-length encoded index
// series (offsets as deltas, then lengths), each as what to subtract from the
// previous value; strtable.hpp has the stream format.
static const Int __sm_stringCount = 5;
static const char __sm_stringPool[] =
    "negative" "parsed" "a" "b" "c" 
;
static const Int16 __sm_stringStarts[] = {5,5,0,-8,2,5,0};
static const Int16 __sm_stringLens[] = {5,3,-8,2,5,1,2,0};
static_assert(sizeof(__sm_stringPool) - 1 == 17, "the string pool and its length index disagree");
static StrView __sm_stringTable[__sm_stringCount];
static struct __SmStringTableInitType {
    __SmStringTableInitType() {
        Int starts[__sm_stringCount];
        Int lens[__sm_stringCount];
        simse_strTableExpand(__sm_stringStarts, starts, __sm_stringCount);
        simse_strTableExpand(__sm_stringLens, lens, __sm_stringCount);
        simse_strTableDecode(__sm_stringPool, starts, lens, __sm_stringTable,
            __sm_stringCount);
    }
} __sm_stringTableInit;

Opt<Int> ns1_pick(Int i);
Res<Str> ns1_parse(Int n);
Str ns1_describe(Int n);
Int ns1_countUntil(List<Str> names, Int limit);
// stress/flat-blocks/src/main.kt:12
Opt<Int> ns1_pick(Int i) {
    Bool _sm_expr1;
    Opt<Int> _sm_expr2;
    Bool _sm_expr3;
    Opt<Int> _sm_expr4;
    Opt<Int> _sm_expr5;
    _sm_expr1 = i < 0;
    if (!(_sm_expr1)) goto L2;
    _sm_expr2 = Opt<Int>::none();
    return _sm_expr2;
    L2:;
    _sm_expr3 = i >= 10;
    if (!(_sm_expr3)) goto L4;
    _sm_expr4 = Opt<Int>::none();
    return _sm_expr4;
    L4:;
    _sm_expr5 = Opt<Int>::some(i);
    return _sm_expr5;
}
// stress/flat-blocks/src/main.kt:22
Res<Str> ns1_parse(Int n) {
    Bool _sm_expr1;
    Res<Str> _sm_expr2;
    Res<Str> _sm_expr3;
    _sm_expr1 = n < 0;
    if (!(_sm_expr1)) goto L2;
    _sm_expr2 = Res<Str>::err(__sm_stringTable[0]);
    return _sm_expr2;
    L2:;
    _sm_expr3 = Res<Str>::ok(__sm_stringTable[1]);
    return _sm_expr3;
}
// stress/flat-blocks/src/main.kt:29
Str ns1_describe(Int n) {
    Res<Str> r;
    Bool _sm_expr1;
    Bool _sm_expr2;
    Str _sm_expr3;
    Str _sm_expr4;
    r = ns1_parse(n);
    _sm_expr1 = r.isOk();
    _sm_expr2 = !_sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr3 = r.Error;
    return _sm_expr3;
    L2:;
    _sm_expr4 = r.Value;
    return _sm_expr4;
}
// stress/flat-blocks/src/main.kt:37
Int ns1_countUntil(List<Str> names, Int limit) {
    Int i;
    Int _sm_expr1;
    Bool _sm_expr2;
    Bool _sm_expr3;
    Int _sm_expr4;
    i = 0;
    L1:;
    _sm_expr1 = names.size();
    _sm_expr2 = i < _sm_expr1;
    if (!(_sm_expr2)) goto L2;
    _sm_expr3 = i >= limit;
    if (!(_sm_expr3)) goto L4;
    return i;
    L4:;
    i = i + 1;
    goto L1;
    L2:;
    _sm_expr4 = names.size();
    return _sm_expr4;
}
// stress/flat-blocks/src/main.kt:48
int main() {
    Opt<Int> _sm_expr1;
    Int _sm_expr2;
    Int _sm_expr3;
    Opt<Int> _sm_expr4;
    Bool _sm_expr5;
    Str _sm_expr6;
    Int _sm_expr7;
    Str _sm_expr8;
    List<Str> names;
    Int _sm_expr9;
    _sm_expr1 = ns1_pick(3);
    _sm_expr2 = _sm_expr1.value();
    std::cout << std::boolalpha << (_sm_expr2) << std::endl;
    _sm_expr3 = -1;
    _sm_expr4 = ns1_pick(_sm_expr3);
    _sm_expr5 = _sm_expr4.hasValue();
    std::cout << std::boolalpha << (_sm_expr5) << std::endl;
    _sm_expr6 = ns1_describe(2);
    std::cout << std::boolalpha << (_sm_expr6) << std::endl;
    _sm_expr7 = -2;
    _sm_expr8 = ns1_describe(_sm_expr7);
    std::cout << std::boolalpha << (_sm_expr8) << std::endl;
    names = List<Str>();
    simse_list_append(names, __sm_stringTable[2]);
    simse_list_append(names, __sm_stringTable[3]);
    simse_list_append(names, __sm_stringTable[4]);
    _sm_expr9 = ns1_countUntil(names, 2);
    std::cout << std::boolalpha << (_sm_expr9) << std::endl;
    return 0;
}
