// Generated by the Simse compiler. Do not edit.
#include "cppsrc/rtl/simse.hpp"
#include <iostream>
#include <type_traits>

// The string-literal pool's decoder (impl_specs/rtl-abi.md, "String literals: one
// table"): the emitter writes one pool of bytes plus two run-length encoded index
// series - where each entry starts and how long it is - and this expands them into the
// `StrView` per entry, once, before `main` runs. It was cppsrc/rtl/strtable.hpp.
//
// Six things are deliberate in the shape the emitter writes:
//
//  - **Both series are stored as "what to subtract from the previous value"**, with an
//    implicit 0 before the first entry: `value[i] = value[i-1] - series[i]`. The
//    literals are ordered longest first, so a length series descends slowly and a
//    *difference* of it is a small number - mostly 0 between the many literals of equal
//    length (85% of them on the compiler's own table).
//  - **Each series is run-length encoded**: its length first, then alternating blocks of
//    non-repeating values (a count, then that many values) and of runs (a count, then
//    that many `times, value` pairs), until the length is filled. The element type is a
//    template parameter because the emitter picks the width: `Int16` when every number
//    fits, `Int` otherwise.
//  - The pool is the literal texts themselves, adjacent, so the C++ compiler decodes
//    every escape and the emitter's decoding only has to agree about *how many bytes* an
//    escape costs. The emitted `static_assert` on the pool's `sizeof` is the check.
//  - The series are expanded into *stack* arrays in the initializer and dropped when it
//    returns: no heap, and the encoded statics are all the program carries.
//  - An entry is a 12-byte `StrView`, not the 32-byte owning `Str` the table used to
//    hold, and start-up allocates nothing for the literals.
//  - The pool is `const char` (a string literal, read-only) while `StrView` holds the
//    language's mutable `Char*`; the constness is cast away here, in the one place the
//    pool is touched, and nothing writes through it.

template <class T>
void simse_strTableExpand(const T* stream, Int* out, Int count);
void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count);

#include <chrono>

// Time natives (the Simse surface is the prelude file cppsrc/rtl/rtl.kt). Both are
// monotonic clocks - never going backwards - since an arbitrary fixed point:
// `simse_nowMillis` for logging, the finer `simse_nowMicros` for the instrumented
// profiler (`cppsrc/profiling`, and the emitted `profileApp.measure(...)` of a
// `--profile` build). It was cppsrc/rtl/timeops.hpp, and its definitions were the last
// thing left in cppsrc/rtl/native.cpp - they are this section's now, so the clock is
// emitted into the program like any other prelude body and there is nothing to link.
// `emit: always`
// because the profiler's runtime is emitted by the *compiler* rather than named by
// the program: a `--profile` build needs these two declarations whether or not the program
// ever asks for the time.
Int64 simse_nowMillis();
Int64 simse_nowMicros();

// `spanOf(items)`: a span over a list's elements, generated (`cppsrc/rtl/_res.md`).
template <class T>
Span<T> simse_spanOf(List<T>* items);

// The operations a view is read through (specs/built-in-types.md, "Views"; the
// declarations are cppsrc/rtl/StrView.kt). The *type* and the *literal interop* stay in
// cppsrc/rtl/strview.hpp: `using StrView = Span<Char>`, the comparison operators, `+`,
// `<<` and the `Str` conversions are reached by C++ overload resolution at a literal
// site rather than by a prelude declaration, so no declaration could reach a section for
// them - while these eleven are named, one symbol each, and a program that calls one
// pays for this text (`sourcegen/ResGen.kt`).
//
// `StrView` *is* a `Span<Char>`, so `self.len`, `self[i]` and `self.slice(...)` below are
// the span's own members (cppsrc/rtl/span.hpp) - and `at` is *not* an operation of its
// own: the span's member serves it (`cppsrc/rtl/StrView.kt`), as `atPtr` is the
// language's (cppsrc/rtl/Span.kt).
Int simse_strView_size(StrView self);
Bool simse_strView_isEmpty(StrView self);
StrView simse_strView_slice(StrView self, Int start);
StrView simse_strView_slice(StrView self, Int start, Int count);
Char simse_strView_charAt(StrView self, Int index);
Bool simse_strView_startsWith(StrView self, const Str& text);
Bool simse_strView_startsWithPtr(StrView self, const Str* text, Int length);
Int simse_strView_find(StrView self, const Str& sub);
Int simse_strView_indexOf(StrView self, const Str& sub);
Str simse_strView_substr(StrView self, Int from, Int count);
Str simse_strView_toString(StrView self);
StrView simse_spanOfStr(Str* text);

#include <cstdint>
#include <type_traits>

// The List/Array/Str primitives behind the prelude (impl_specs/native-interop.md), moved
// out of cppsrc/rtl/listops.hpp. Index and range errors are unchecked, matching the
// language's no-exceptions policy: `removeAt`/`removeRange` with an out-of-range index is
// undefined behavior (specs/language-decisions.md).

// Appends `value` to the end of `self`. The value is a non-deduced context so a literal
// argument (e.g. a `const char[]`) converts to the element type instead of making `T`
// ambiguous.
template <class T>
void simse_list_append(List<T>& self, const std::type_identity_t<T>& value);

// The list literal's fallback (cppsrc/rtl/rtl.kt): the compiler turns
// `listOf<Str>("a", "b")` into the construction itself, so this runs only for a position
// with no destination slot.
template <class T>
List<T> simse_listOf(const List<T>* values);

template <class T>
void simse_list_removeAt(List<T>& self, Int index);
template <class T>
void simse_list_removeRange(List<T>& self, Int start, Int end);
template <class T>
Int simse_array_count(const Array<T>& self);
template <class T>
Array<T> simse_list_toArray(const List<T>& self);
template <class T>
List<T> simse_array_toList(const Array<T>& self);
template <class T>
Array<T> simse_arrayEmpty();

void simse_str_append(Str& self, Char value);
void simse_str_appendStr(Str& self, const Str& value);
void simse_str_appendStrPtr(Str& self, const Str* value);
void simse_str_reserve(Str& self, Int count);
Str simse_int_toString(Int self);

#include <algorithm>
#include <type_traits>
#include <utility>

// The Dictionary operations and the extra List helpers behind the prelude
// (impl_specs/native-interop.md), moved out of cppsrc/rtl/dictops.hpp. The key/value
// parameters are non-deduced (`std::type_identity_t`) so that a literal argument (e.g. a
// `const char[]` key or an integer value) converts to the element type instead of making
// the template argument ambiguous.
//
// Errors are unchecked, matching the dictionary's own semantics and the language's
// no-exceptions policy: `get`/`has` on a missing key behave as documented, while `remove`
// of an absent key is a no-op.

// `dictionaryOf<K, V>()`: the empty-dictionary construction.
template <class K, class V>
Dictionary<K, V> simse_dictionaryOf();

// `d.get(key)`: the value for `key`, or an empty `Opt` when absent.
template <class K, class V>
Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.has(key)`: whether `key` is present.
template <class K, class V>
Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.insert(key, value)`: insert or replace.
template <class K, class V>
void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                       const std::type_identity_t<V>& value);

// `d.remove(key)`: erase when present (a no-op otherwise).
template <class K, class V>
void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key);

// `d.size()`: the number of entries.
template <class K, class V>
Int simse_dict_size(const Dictionary<K, V>& self);

// `d.keys()`: the keys in the dictionary's iteration order (unspecified; sort for a
// deterministic order).
template <class K, class V>
List<K> simse_dict_keys(const Dictionary<K, V>& self);

// `d.values()`: the values in the dictionary's iteration order (unspecified).
template <class K, class V>
List<V> simse_dict_values(const Dictionary<K, V>& self);

// `d.clear()`: remove every entry.
template <class K, class V>
void simse_dict_clear(Dictionary<K, V>& self);

// `items.contains(value)`: linear membership test (`operator==` on elements).
template <class T>
Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value);

// `items.sort(less)`: in-place sort using the `(T, T) -> Bool` comparator. The comparator
// comes from a Simse lambda (a C++ lambda or Func), so it is a template parameter rather
// than a fixed type.
template <class T, class F>
void simse_list_sort(List<T>& self, F less);

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <system_error>

// The platform's filesystem/IO operations (impl_specs/native-interop.md). They were
// cppsrc/rtl/native.cpp - the repository's one hand-written translation unit beside the
// published bootstrap - so building a program meant compiling *and linking* a second file,
// and a build that left it out failed in the linker rather than in the compiler. The bodies
// are this section's now: a program that reaches one of these symbols has the prototype and
// the definition emitted into its own translation unit, which is what makes
// `cppsrc/simse_bootstrap.cpp` buildable on its own.
//
// `emit: always`, for the reason `timeops` is: a *program* may name any of these symbols
// with a declaration of its own - `native("simse_native_readFile") fun readFile(...)`, which
// is `native-interop.md`'s example and `stress/native-read-file`'s - and then no `res`
// declaration reaches this section for it to be found by (`sourcegen/ResGen.kt`). The
// platform's C++ is the runtime's FFI, so like a linked runtime it is there for every
// program; what a program pays for it is about 4 KB of text, the same code the linker used
// to place whether or not the program called it.
//
// The Simse surface is the prelude file cppsrc/rtl/fs.kt, plus `readFile` in
// cppsrc/common/common.kt (a normal module of the compiler). The prototypes used to live in
// cppsrc/rtl/fs.hpp and cppsrc/rtl/filestream.hpp, which is why those headers are gone - a
// section carries its own declaration half in `forward`.

Str simse_native_readFile(const Str& path);
List<Str> simse_listFiles(const Str& dir, const Str& ext);
List<Str> simse_listFilesDirect(const Str& dir, const Str& ext);
Bool simse_writeFile(const Str& path, const Str& content);
Str simse_pathCanonical(const Str& path);
Bool simse_pathIsDirectory(const Str& path);
Bool simse_pathExists(const Str& path);
void simse_eprintln(const Str& text);
FileStream* simse_fileStream_open(const Str& path);

// stress/smgen-res-collision/src/main.kt:17
int main() {
    List<Int>* _sm_base1;
    List<Int>* _sm_base2;
    List<Int> items;
    Span<Int> real;
    Span<Int> empty;
    Int _sm_expr1;
    Int _sm_expr2;
    items = List<Int>();
    simse_list_append(items, 3);
    _sm_base1 = &items;
    real = simse_spanOf(_sm_base1);
    _sm_base2 = &items;
    empty = simse_spanOf(_sm_base2);
    _sm_expr1 = real.size();
    std::cout << std::boolalpha << (_sm_expr1) << std::endl;
    _sm_expr2 = empty.size();
    std::cout << std::boolalpha << (_sm_expr2) << std::endl;
    return 0;
}

// The collision fixture (the `spanOfEmpty` section of cppsrc/rtl/_res.md): the same
// symbol as `spanOf`, so whichever declaration the emitter reaches last wins.
template <class T>
inline Span<T> simse_spanOf(List<T>* items) {
    return Span<T>(nullptr, -1);
}

inline Int simse_strView_size(StrView self) {
    return self.len;
}

inline Bool simse_strView_isEmpty(StrView self) {
    return self.len <= 0;
}

// `view.slice(start)`: from `start` to the end (C# `Slice(int)`).
inline StrView simse_strView_slice(StrView self, Int start) {
    return self.slice(start);
}

// `view.slice(start, count)`: `count` bytes from `start` (C# `Slice(int, int)`).
inline StrView simse_strView_slice(StrView self, Int start, Int count) {
    return self.slice(start, count);
}

inline Char simse_strView_charAt(StrView self, Int index) {
    return self[index];
}

// True when the view begins with `text`.
inline Bool simse_strView_startsWith(StrView self, const Str& text) {
    const Int count = text.size();
    if (count > self.len) return false;
    for (Int i = 0; i < count; i++) {
        if ((char) self[i] != text[i]) return false;
    }
    return true;
}

// `startsWithPtr(text, length)`: the same comparison against text this view does not
// own, reached by raw pointer and with its length already known. `startsWith` would
// copy the `Str` first, which is what a table lookup cannot afford; the first byte is
// the caller's cheap test, this does the rest.
inline Bool simse_strView_startsWithPtr(StrView self, const Str* text, Int length) {
    if (length > self.len) return false;
    for (Int i = 1; i < length; i++) {
        if ((char) self[i] != (*text)[i]) return false;
    }
    return true;
}

// `find(sub)`: the index of the first occurrence of `sub` in the bytes, or -1. The
// bytes are compared in place: nothing is copied.
inline Int simse_strView_find(StrView self, const Str& sub) {
    const Int needle = sub.size();
    if (needle == 0) return 0;
    if (needle > self.len) return -1;
    for (Int i = 0; i + needle <= self.len; i++) {
        Int j = 0;
        while (j < needle && (char) self[i + j] == sub[j]) j++;
        if (j == needle) return i;
    }
    return -1;
}

// `indexOf` is the other spelling of `find`.
inline Int simse_strView_indexOf(StrView self, const Str& sub) {
    return simse_strView_find(self, sub);
}

// The owned copy of `count` bytes from `from`, with `from` clamped to [0, size] and
// `count` allowed to run to the end, like `Str.substr`.
inline Str simse_strView_substr(StrView self, Int from, Int count) {
    const Int len = self.len;
    Int begin = from < 0 ? 0 : from;
    if (begin > len) begin = len;
    Int end = count < 0 ? begin : begin + count;
    if (end > len) end = len;
    Str result;
    if (end > begin) {
        result.resize(end - begin);
        std::memcpy(result.data(), self.ptr + begin, (std::size_t) (end - begin));
    }
    return result;
}

// The owned copy of the whole view, as a `Str` (the language's `toString()`
// convention, like `Int.toString()`).
inline Str simse_strView_toString(StrView self) {
    return simse_strView_substr(self, 0, self.len);
}

// `spanOfStr(text)`: a view over a string's bytes. It borrows the string - the string
// has to outlive the view - and does not copy it (`&text` would box a copy instead).
// `Str` is a `char` buffer on the C++ side and the language's `Char` is a signed byte,
// hence the cast.
inline StrView simse_spanOfStr(Str* text) {
    return StrView(reinterpret_cast<Char*>(text->data()), text->size());
}

template <class T>
inline void simse_list_append(List<T>& self, const std::type_identity_t<T>& value) {
    self.push_back(value);
}

template <class T>
inline List<T> simse_listOf(const List<T>* values) {
    return *values;
}

// Removes the single element at `index`.
template <class T>
inline void simse_list_removeAt(List<T>& self, Int index) {
    self.erase(self.begin() + index);
}

// Removes the half-open range [start, end).
template <class T>
inline void simse_list_removeRange(List<T>& self, Int start, Int end) {
    self.erase(self.begin() + start, self.begin() + end);
}

// `Array<T>.count()`: the element count stored at the front of the block.
template <class T>
inline Int simse_array_count(const Array<T>& self) {
    return self.count();
}

// `List<T>.toArray()` (specs/built-in-types.md): copies the elements into one count-first
// block. Element copies are value copies, like every other copy in the language.
template <class T>
inline Array<T> simse_list_toArray(const List<T>& self) {
    const Int count = self.size();
    if (count <= 0) {
        return Array<T>();
    }
    Array<T> result(count);
    for (Int i = 0; i < count; i++) {
        result[i] = self[i];
    }
    return result;
}

// `Array<T>.toList()`: the growable copy, which is how an element is added to an array.
template <class T>
inline List<T> simse_array_toList(const Array<T>& self) {
    List<T> result;
    const Int count = self.count();
    result.reserve(count);
    for (Int i = 0; i < count; i++) {
        result.push_back(self[i]);
    }
    return result;
}

// `arrayEmpty<T>()`: the shared, zero-length array of `T` (no allocation).
template <class T>
inline Array<T> simse_arrayEmpty() {
    return Array<T>();
}

// `Str.append(ch)`: `Str` has no single-character append, so this is `push_back`.
inline void simse_str_append(Str& self, Char value) {
    self.push_back(static_cast<char>(value));
}

// `Str.appendStr(text)`: appends in place, so an emitter accumulates output without
// `out = out + text` rebuilding the whole buffer on every line (which is quadratic).
inline void simse_str_appendStr(Str& self, const Str& value) {
    self.append(value);
}

// `Str.appendStrPtr(text)`: the same append for a text the caller only *borrows*, so
// nothing is copied on the way.
inline void simse_str_appendStrPtr(Str& self, const Str* value) {
    if (value != nullptr) self.append(*value);
}

// `Str.reserve(count)`: grows the buffer once, so a run of appends writes the text once
// instead of copying the accumulated prefix at every growth step. A *hint*, not a length.
inline void simse_str_reserve(Str& self, Int count) {
    self.reserve((Str::size_type) count);
}

// `Int.toString()`: the scalar-to-inline-string conversion (specs/memory-model.md).
inline Str simse_int_toString(Int self) {
    return std::to_string(self);
}

// `dictionaryOf<K, V>()`: `Dictionary<K, V>` is a value type, so this default-constructs
// one.
template <class K, class V>
inline Dictionary<K, V> simse_dictionaryOf() {
    return Dictionary<K, V>();
}

template <class K, class V>
inline Opt<V> simse_dict_get(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    auto it = self.find(key);
    if (it == self.end()) return Opt<V>::none();
    return Opt<V>::some(it->second);
}

template <class K, class V>
inline Bool simse_dict_has(const Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    return self.find(key) != self.end();
}

template <class K, class V>
inline void simse_dict_insert(Dictionary<K, V>& self, const std::type_identity_t<K>& key,
                              const std::type_identity_t<V>& value) {
    self.insert_or_assign(key, value);
}

template <class K, class V>
inline void simse_dict_remove(Dictionary<K, V>& self, const std::type_identity_t<K>& key) {
    self.erase(key);
}

template <class K, class V>
inline Int simse_dict_size(const Dictionary<K, V>& self) {
    return (Int) self.size();
}

template <class K, class V>
inline List<K> simse_dict_keys(const Dictionary<K, V>& self) {
    List<K> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.first);
    return out;
}

template <class K, class V>
inline List<V> simse_dict_values(const Dictionary<K, V>& self) {
    List<V> out;
    out.reserve((Int) self.size());
    for (const auto& entry : self) out.push_back(entry.second);
    return out;
}

template <class K, class V>
inline void simse_dict_clear(Dictionary<K, V>& self) {
    self.clear();
}

template <class T>
inline Bool simse_list_contains(const List<T>& self, const std::type_identity_t<T>& value) {
    for (const T& item : self) {
        if (item == value) return true;
    }
    return false;
}

template <class T, class F>
inline void simse_list_sort(List<T>& self, F less) {
    std::sort(self.begin(), self.end(), less);
}

// Expands one run-length encoded series into `out`, which holds `count` values.
template <class T>
inline void simse_strTableExpand(const T* stream, Int* out, Int count) {
    Int at = 0;
    Int cursor = 1; // stream[0] is the series' own length
    while (at < count) {
        const Int literals = (Int) stream[cursor++];
        for (Int i = 0; i < literals && at < count; i++) out[at++] = (Int) stream[cursor++];
        if (at >= count) break;
        const Int runs = (Int) stream[cursor++];
        for (Int i = 0; i < runs && at < count; i++) {
            const Int times = (Int) stream[cursor++];
            const Int value = (Int) stream[cursor++];
            for (Int j = 0; j < times && at < count; j++) out[at++] = value;
        }
    }
}

// Fills `table` from the pool and the two expanded series: an offset increment and a
// byte count per entry, both rebuilt by subtracting the stored value from the one before.
inline void simse_strTableDecode(const char* pool, const Int* starts, const Int* lengths, StrView* table, Int count) {
    Char* bytes = const_cast<Char*>(reinterpret_cast<const Char*>(pool));
    Int delta = 0;  // this entry's offset increment, rebuilt from the start series
    Int length = 0; // this entry's byte count, rebuilt from the length series
    Int at = 0;
    for (Int i = 0; i < count; i++) {
        delta -= starts[i];
        length -= lengths[i];
        at += delta;
        table[i] = StrView(bytes + at, length);
    }
}

// The two monotonic clocks. `steady_clock` is the one clock the standard library
// promises cannot go backwards, which is what makes a duration between two readings
// meaningful (`impl_specs/profiling.md`).
Int64 simse_nowMillis() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
}

Int64 simse_nowMicros() {
    const auto now = std::chrono::steady_clock::now().time_since_epoch();
    return (Int64) std::chrono::duration_cast<std::chrono::microseconds>(now).count();
}

// The whole file as bytes; empty when it cannot be read.
Str simse_native_readFile(const Str& path) {
    Str result;
    FILE* file = fopen(path.c_str(), "rb");
    if (file == nullptr) return result;
    fseek(file, 0, SEEK_END);
    const int fileSize = ftell(file);
    fseek(file, 0, SEEK_SET);
    result.resize(fileSize);
    fread(result.data(), 1, fileSize, file);
    fclose(file);
    return result;
}

// Every `ext`-suffixed file under `dir`, recursively, sorted; empty when `dir` is not a
// directory. The one place the "generic separators" rule is applied, so a scanned path
// matches the same path given explicitly (e.g. `--root cppsrc` vs an explicit input
// file): this and the compiler's own dedup key both read these strings.
List<Str> simse_listFiles(const Str& dir, const Str& ext) {
    List<Str> matchingFiles;

    // The standard filesystem API works in std::string; the language works in Str
    // (`simse_toStdString` is a no-op copy when Str is std::string).
    const std::string dirText = simse_toStdString(dir);
    const std::string wantedExt = simse_toStdString(ext);

    if (!std::filesystem::exists(dirText) || !std::filesystem::is_directory(dirText)) {
        return matchingFiles;
    }
    for (const auto& entry: std::filesystem::recursive_directory_iterator(dirText)) {
        if (entry.is_regular_file() && entry.path().extension() == wantedExt) {
            matchingFiles.push_back(simse_fromStdString(entry.path().generic_string()));
        }
    }
    std::sort(matchingFiles.begin(), matchingFiles.end());
    return matchingFiles;
}

// The non-recursive form, for `import a.b.c` directory resolution.
List<Str> simse_listFilesDirect(const Str& dir, const Str& ext) {
    List<Str> files;
    std::error_code ec;
    if (!std::filesystem::is_directory(simse_toStdString(dir), ec)) {
        return files;
    }
    for (const auto& entry: std::filesystem::directory_iterator(simse_toStdString(dir), ec)) {
        if (entry.is_regular_file() && entry.path().extension() == simse_toStdString(ext)) {
            files.push_back(simse_fromStdString(entry.path().generic_string()));
        }
    }
    std::sort(files.begin(), files.end());
    return files;
}

Bool simse_writeFile(const Str& path, const Str& content) {
    FILE* out = fopen(path.c_str(), "wb");
    if (out == nullptr) {
        return false;
    }
    fwrite(content.data(), 1, content.length(), out);
    fclose(out);
    return true;
}

Str simse_pathCanonical(const Str& path) {
    std::error_code ec;
    std::filesystem::path canonical = std::filesystem::weakly_canonical(
            std::filesystem::path(simse_toStdString(path)), ec);
    return ec ? path : simse_fromStdString(canonical.string());
}

Bool simse_pathIsDirectory(const Str& path) {
    std::error_code ec;
    return std::filesystem::is_directory(simse_toStdString(path), ec);
}

Bool simse_pathExists(const Str& path) {
    std::error_code ec;
    return std::filesystem::exists(simse_toStdString(path), ec);
}

void simse_eprintln(const Str& text) {
    fprintf(stderr, "%s\n", text.c_str());
}

// The stream's own operations (`readLine`, `readLineInto`, `readLineView`, `fileSize`,
// `close`) are the `filestream` section below: the emitter calls a handle's methods as
// members, and the struct that declares them is cppsrc/rtl/filestream.hpp. Only the
// constructor-like `open` lives here, as a free function.
FileStream* simse_fileStream_open(const Str& path) {
    auto* stream = new FileStream();
    stream->file.open(simse_toStdString(path), std::ios::binary);
    if (!stream->file.is_open()) {
        delete stream;
        return nullptr;
    }
    stream->chunk.resize(256 * 1024);
    std::error_code ec;
    const std::uintmax_t size = std::filesystem::file_size(simse_toStdString(path), ec);
    stream->size = ec ? 0 : (Int64) size;
    return stream;
}
